### ISSUE TITLE
Proposal: Animation directives

### ISSUE THREAD

**Issue by LarsDenBakker** [lit/lit#1017]
Managing animations efficiently can be quite tricky if you want to avoid race conditions. I've been working on some `lit-html` directives which make it possible to manage animations declaratively. 

I think this would be a powerful addition to lit-html, is this something that would be interesting to add to the main repository or should it be distributed somewhere separately?

**Comment by justinfagnani** [comment]
I would be very interesting in having built-in animation/motion directives. Agreed that managing state/DOM transitions correctly is tricky and directives can help there.

cc @rictic who looked into this a little while back.

**Comment by hyperpress** [comment]
I actually ran into this issue recently and I think it would be great to add as a directive with little cost.

**Comment by Stradivario** [comment]
I have managed to deal with animations using `anime` library using declarative approach with WebComponent instead of directive.

https://rxdi.github.io/ui-kit/animation

Source code:
https://github.com/rxdi/ui-kit/tree/master/src/animation


Usage:

```html
<rx-animation>
    <div style="transform: translateX(-100%);">Item 1</div>
    <div style="transform: translateX(-100%);">Item 2</div>
</rx-animation>
```

With options

```html
<rx-animation .options=${({ stagger }) => ({
    delay: stagger(200),
    translateX: 0,
    easing: 'spring(1, 80, 10, 0)'
})}>
    <div style="transform: translateX(-100%);">Item 1</div>
    <div style="transform: translateX(-100%);">Item 2</div>
</rx-animation>
```

Regards!

**Comment by sorvell** [comment]
Closing now that we have https://github.com/lit/lit/tree/main/packages/labs/motion. If changes/additions should be made to that package, please file more specific issues.
