### ISSUE TITLE
Feature RQ: Support for MutationObserver & ResizeObserver

### ISSUE THREAD

**Issue by hokiedsp** [lit/lit#1165]
I've been using lit-html for a couple months now and truly love its concept. But I encountered awkwardness using it with [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) & [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) (likely extendable to other Web API Observers).

Could lit-html add a support for them?

If there isn't already a plan for their support, I have a proposal for it (a straightforward extension of event listeners):

# Add observers

Templates can also include declarative Web API observers. An observer looks like an attribute binding, but with a prefix character (`#` maybe?) followed by an observer name. 

```
// template definition
const myTemplate = () => html`<div 
    #ResizeObserver = ${resizeObserver} 
    #MutationObserver = ${mutationObserver}
  ></div>`;
```

The observer can be either a plain observer instance, or an object with `observer` and `options` property:

```
const resizeObserver = new ResizeObserver(resizeHandler);
const mutationObserver = {
   observer: new MutationObserver(mutationHandler), 
   options: {attributes: true, childList: true};
};
```

Underneath, the observer name is purely used for bookkeeping, and when an observer is changed, `disconnect()` the previous & `observe()` with the new.

All the Web API observers (both existing & proposed) appear to follow the same syntax, so I think this declaration syntax should work. What do you think?

**Comment by kevinpschaaf** [comment]
This is pretty trivial to do using lit-html's [directive API](https://lit-html.polymer-project.org/guide/creating-directives).

Here's an example pretty close to what you were proposing: https://stackblitz.com/edit/lit-mo-directive?file=index.js

For now I'll keep this issue open  to consider a little more whether this might be something we want to add as a first-class directive or part type, but for now this should unblock you.

**Comment by hokiedsp** [comment]
That's pretty cool! Thank you for putting together the example. I haven't looked into directive yet, so definitely a good place for me to get my feet wet.

Having this feature built-in would be useful so I hope others will chime in for their support!

Thanks again.

**Comment by justinfagnani** [comment]
We recently added an observers package to lit-labs: https://github.com/lit/lit/tree/main/packages/labs/observers

Does that address the needs here?
