### ISSUE TITLE
[lit-html] Clarify behavior of classMap

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#1278]
The test for classMap say that dynamic classes can not override and remove static classes, but this is only true on the first render. Subsequent renders will remove static classes. This is clearly broken, but what is the right behavior? To allow overriding or not? If we're going to change this, 2.0 is the time.

**Comment by sorvell** [comment]
I think the most important thing is that `classMap` can remove the classes it previously set. I don't think the behavior when you have a conflict between a static class and a classMap class is important. We should just add docs that you shouldn't do that.

**Comment by justinfagnani** [comment]
We can't change this behavior w/o potentially breaking people though, so I do want to settle on what we want, even if we recommend against class clashes like this.
