### ISSUE TITLE
Add TypeScript npm tags?

### ISSUE THREAD

**Issue by jablko** [lit/lit#1363]
Would you be willing to add the following npm tags to lit-html: `ts3.2`, `ts3.3`, `ts3.4`, `ts3.5`, `ts3.6`, `ts3.7`, `ts3.8`, `ts3.9`, `ts4.0`, `ts4.1`?

[@types/storybook__polymer](https://www.npmjs.com/package/@types/storybook__polymer) (well, [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47646)) supports TypeScript 3.2, but it (and other types) transitively depends on lit-html, the `@latest` version of which [doesn't](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47676/checks?check_run_id=1125616263).
- I think I could add a [peer dependency](https://docs.npmjs.com/files/package.json#peerdependencies) on lit-html < 1.2, but this seems wrong since it does work with the `@latest` version, you just need TypeScript >= 3.4.
- I could set the [minimum TypeScript version](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-33-or-above) of @types/storybook__polymer (and other types) to 3.4, but that seems wrong because they do support TypeScript 3.2, you just need the previous version of lit-html, and doing so would only be right until such time as lit-html dropped TypeScript 3.4 support.

Or, DefinitelyTyped [provides `ts3.2`, etc. npm tags](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-31-and-earlier) so people can request compatible previous-versions of types with e.g. `npm install --tag ts3.2 @types/storybook__polymer`. If lit-html provided the npm tags above, then this mechanism would also retrieve the latest compatible dependencies (lit-html < 1.2 with `--tag ts3.2` and `@latest` with `--tag ts3.4` or without), instead of facing either new lit-html releases altering older types' minimum TypeScript version, or older types needing to enforce the versions of their transitive dependencies.

**Comment by justinfagnani** [comment]
I'm lacking some context here. We publish standard ES2017 to npm. The TypeScript files are only published to use in source maps - other than that it shouldn't be noticeable that the project is written in TypeScript.

So what do the tags do here? Why are they necessary? Will they need to be updated every time we publish to npm?

I'm also not familiar with `@storybook/polymer`. Is it still maintained? Following the repository link from npmjs.com gives me a 404. The repo now has a `web-components` package. That has a peer dependency on lit-html, which should probably be just a normal dependency. I can't see why bumping the version of the lit-html dependency would be a problem - Storybook should be able to use the latest version with no problems.

**Comment by jablko** [comment]
I'm new here but it looks like people consuming the TypeScript files with older versions of the compiler [isn't a new problem](https://github.com/Polymer/lit-element/issues/935#issuecomment-601313642), and was previously addressed by [introducing downlevel-dts](https://github.com/Polymer/lit-element/issues/935#issuecomment-601313642)? DefinitelyTyped is affected because @types/storybook__polymer [uses the `TemplateResult` and `SVGTemplateResult` types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/35d9a313065eb02b63d265dcea3a0e73d55c108b/types/storybook__polymer/index.d.ts#L14) from lit-element, and I think the newer @storybook/web-components [does the same thing](https://github.com/storybookjs/storybook/blob/77ddfe075ebb853d0d6a5fc74fb909de642cc63a/app/web-components/src/client/preview/types.ts#L2).

The tags are the DefinitelyTyped [mechanism for installing previous versions](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-31-and-earlier), so a user doing `npm install --tag ts3.2 @types/storybook__polymer` expects to get a previous version that supports TypeScript 3.2 if the latest version doesn't. By adding them to lit-html they'll get a previous version of that too, so the combined result works with 3.2.

lit-html ships a `ts3.4` directory to support 3.4, the tags are analogous but identify a previous version rather than being shipped inside `@latest`. Ideally they'd be updated every time there's a new release, so the `ts3.4`+ tags all match `@latest`.

I see what you mean about @storybook/polymer being deprecated and superseded by @storybook/web-components, maybe we can just excise @types/storybook__polymer. On the other hand it is [still receiving critical bug fixes](https://github.com/storybook-eol/polymer#readme), and the npm tags would benefit any other packages consuming lit-html types.

**Comment by kevinpschaaf** [comment]
Closing due to age. Please reopen if the latest releases still pose an issue.
