### ISSUE TITLE
[ssr] Improve integration test infrastructure

### ISSUE THREAD

**Issue by kevinpschaaf** [lit/lit#1378]
# Description
Task to improve the integration test infrastructure used in lit-ssr:

* [ ] Consider whether web-test-runner can be used on the client instead of mocha
* [ ] Consider adding suites to break up tests
* [ ] Consider allowing the `basic_test` runner to run multiple files-worth of tests

**Comment by aomarks** [comment]
Closing for now, though we could potentially take advantage of https://github.com/lit/lit/issues/2351 in our own tests.
