### ISSUE TITLE
[lit-ssr] Implement full list of built-in reflecting attributes

### ISSUE THREAD

**Issue by kevinpschaaf** [lit/lit#1380]
## Description
The `reflected-attributes.ts` module in `lit-ssr` currently has a placeholder/stub list of reflecting attributes, which should be built out based on the full DOM IDL.

## Acceptance criteria
Tests committed and passing for built-in reflecting attributes

**Comment by nicolejadeyee** [comment]
@kevinpschaaf to add PR and close

**Comment by kevinpschaaf** [comment]
Done in https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/reflected-attributes.ts.
