### ISSUE TITLE
[lit-html] Review browser test matrix

### ISSUE THREAD

**Issue by abdonrd** [lit/lit#1404]
Now this issue is closed:

https://github.com/Polymer/lit-html/blob/677d5feb15ffce15c21b0b7f6264749fa8a74698/packages/tests/web-test-runner.config.js#L27-L40

Issue link: https://github.com/modernweb-dev/web/issues/472

**Comment by web-padawan** [comment]
In case if you need to test on iOS Simulators, please check https://github.com/modernweb-dev/web/issues/788

That issue proposes a solution to use legacy JWP capabilities for those browsers that don't work with W3C capabilities.

**Comment by kevinpschaaf** [comment]
Our current browser test matrix looks like this:
```js
const browserPresets = {
  // Default set of Playwright browsers to test when running locally.
  local: ['chromium', 'firefox', 'webkit'],

  // Browsers to test during automated continuous integration.
  //
  // https://saucelabs.com/platform/supported-browsers-devices
  // https://wiki.saucelabs.com/display/DOCS/Platform+Configurator
  //
  // Many browser configurations don't yet work with @web/test-runner-saucelabs.
  // See https://github.com/modernweb-dev/web/issues/472.
  sauce: [
    'sauce:Windows 10/Firefox@68', // Current ESR
    'sauce:Windows 10/Chrome@latest-3',
    'sauce:macOS 10.15/Safari@latest',
    // "sauce:Windows 10/MicrosoftEdge@18", // Browser start timeout
    'sauce:Windows 7/Internet Explorer@11', // Browser start timeout
  ],
};
```

Seems like the only thing to review is whether we can re-enable Edge testing.

**Comment by justinfagnani** [comment]
I think our matrix is good until our next browser support update. We don't support legacy Edge anymore, just the Chromium-based Edge.
