### ISSUE TITLE
[labs/task] Refine API of Task

### ISSUE THREAD

**Issue by sorvell** [lit/lit#1499]
## Description
There are some API rough edges in AsyncTask that may change. Noting them here for discussion and so that users are aware.

- [x] Currently the `value` and `error` properties are cleared when a task becomes pending. It might be useful to keep these around until the task completes. Additionally, if a task errors, perhaps the previous value should be retained?
- [ ] It would be nice to be able to abort a task. The platform provides an [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) for this which could be integrated into `AsyncTask`.
- [x] There's not a good way to be informed when a task completes. There is an update, but if you want code external to the update to know, it must be done manually, for example by vending a promise for the task completion.
- [ ] Tasks are triggered in `updated`. This means that an element must render 2x to see its pending state (meaning a common pattern to set a property that's a dep and await updateComplete will not render a pending state), and it also means there's currently a dev mode warning when using `AsyncTask`.

## Acceptance criteria
Refine API and land changes.

**Comment by sorvell** [comment]
Per suggestion from @kevinpschaaf: to avoid timing issues with changing deps and the element lifecycle, it may make sense to alternatively or additively be able to trigger the task (here via `update`), e.g.

```
render() {
  const dep1 = computeDep1(this.value1, this.value2);
  const dep2 = computeDep2(this.value3, this.value4);
  this.asyncTask.update([dep1, dep2]);
  return html`
    <div>${this.asyncTask.render({
      pending() { return html`please wait...`
      complete(value) { return html`${value}`}
    });
  `
}
```

**Comment by justinfagnani** [comment]
All of these issues have been addressed except whether to run the task from `hostUpdated` or `hostUpdate`.

**Comment by justinfagnani** [comment]
I opened https://github.com/lit/lit/issues/4003 to track timing. Closing this issue now.
