### ISSUE TITLE
[lit-starter-*] Move starter kits to use open-wc analyzer

### ISSUE THREAD

**Issue by kevinpschaaf** [lit/lit#1573]
## Description
The custom-elements.json generated for the sample element in `lit-starter-ts`/`js` includes property entries for properties from the `ReactiveElement` base class:

```json
        {
          "name": "renderRoot",
          "description": "Node or ShadowRoot into which element DOM should be rendered. Defaults\nto an open shadowRoot.",
          "type": "HTMLElement | ShadowRoot"
        },
        {
          "name": "isUpdatePending",
          "type": "boolean"
        },
        {
          "name": "hasUpdated",
          "type": "boolean"
        },
        {
          "name": "updateComplete",
          "description": "Returns a Promise that resolves when the element has completed updating.\nThe Promise value is a boolean that is `true` if the element completed the\nupdate without triggering another update. The Promise result is `false` if\na property was set inside `updated()`. If the Promise is rejected, an\nexception was thrown during the update.\n\nTo await additional asynchronous work, override the `getUpdateComplete`\nmethod. For example, it is sometimes useful to await a rendered element\nbefore fulfilling this Promise. To do this, first await\n`super.getUpdateComplete()`, then any subsequent state.",
          "type": "Promise<boolean>"
        }
```

Not sure if these are expected. These are all technically `public` properties on the base class, but ideally they would not be included.

## Acceptance criteria
Investigate and either fix or open issue on lit-analyzer.

**Comment by justinfagnani** [comment]
We should switch the starter kits to Open WC's analyzer.

**Comment by kevinpschaaf** [comment]
Since the manifest being generated no longer follows the latest custom-elements-manifest.json spec, we resolved to upgrade the starter kits to the open-wc analyzer: https://custom-elements-manifest.open-wc.org/analyzer/getting-started/. The 11ty docs generation in the starter kit ingests the manifest, so that will need to be updated also.

**Comment by kevinpschaaf** [comment]
Done in https://github.com/lit/lit/pull/2117.
