### ISSUE TITLE
[lit-next] Create labs package that includes Flip directive

### ISSUE THREAD

**Issue by sorvell** [lit/lit#1585]
## Description
Create a labs package, perhaps called "motion" that includes the FLIP directive. 

WIP branch: https://github.com/Polymer/lit-html/tree/lit-next-flip

## Acceptance criteria
Land PR with new package

**Comment by justinfagnani** [comment]
I'd love to add the SpringController from here: https://stackblitz.com/edit/lit-element-goo?file=src%2Fspring-controller.js
