### ISSUE TITLE
until() prevent flickering best practice

### ISSUE THREAD

**Issue by MichaelPeter** [lit/lit#1617]
## Description
I am building a autocomplete-component and on every character typed by the user, a request is sent to the server getting the best autocomplete options.
Now while the options are loading a Lade /Loading text should be shown
till the resultset arrives. The best solution for this seemed until()

Here the loading:

![grafik](https://user-images.githubusercontent.com/4217002/108050642-2d031680-704a-11eb-994b-14a8428add57.png)

Now when the list is loaded it should be shown:

![grafik](https://user-images.githubusercontent.com/4217002/108050741-4e640280-704a-11eb-8f0c-bba521c96377.png)

Now - "sadly" - the server responds within 10-20 millseconds. So the dropdown flickers since it always switches between loading and showing the resultset.

What is the best solution to prevent this flickering? Could there be a option in until which shows the placeholder text only after 100 milliseconds? 

My first idea was should I make before the request promise a promise which shows nothing at all for 100 milliseconds?

Greetings
Michael

**Comment by lkraav** [comment]
Best practice is to debounce requests to server at minimum 250ms after user has stopped typing.

It's a bad idea to query server on every character typed. User should be able to quickly type more characters to get a better initial match, here debounce helps.

**Comment by MichaelPeter** [comment]
Hello Ikraav,

I understand where you are coming from, also from a server performance standpoint.

But this is an inhouse application with limited users and server performance is not the issue here, also the query is extremly fast.

Waiting 250 milliseconds till the user stops typing would take out the snappiness of the application.
Also users type register numbers. For example R100DE for the german register when the user has typed
R100, he wants to immidatly see suggestions for R100DE, R100US, R100EN.
So just slowing down the autocomplete would be not the solution.
would take out the snappiness of the application.

**Comment by lkraav** [comment]
> But this is an inhouse application with limited users and server performance is not the issue here, also the query is extremly fast.

And yet here we are talking about flickering.

> Waiting 250 milliseconds till the user stops typing would take out the snappiness of the application.

Display a progress indicator immediately - that doesn't mean you actually have to send the query.

Snappiness at 250ms is fine - tried and tested on multiple applications.

**Comment by elycruz** [comment]
@MichaelPeter What @lkraav says is correct - In a version of this component that I built (for a private app library) my default timeout is set at 1 second (it allows users to type out something closer to what they're looking for without having the dropdown interrupt their attention from what their actually interested in).  Look at twitter and/or googles search feature(s).

**Comment by elycruz** [comment]
@MichaelPeter Also if you have a fixed list of search results you can download the whole list before the application is at ready state and also it sounds like your component logic is not accommodating/keeping the dropdown area of the component open - I would investigate the logic behind when the dropdown opens/closes (also) for a fix to the flicker issue.

**Comment by sorvell** [comment]
Closing due to age and based on the discussion and recommendations above. Please feel free to re-open if there's something specific that still needs explanation. Thanks!.
