### ISSUE TITLE
[styleMap directive]: Allow undefined type 

### ISSUE THREAD

**Issue by matthias-ccri** [lit/lit#1618]
# Description
Cannot use styleMap with values whose types include `undefined`.

![image](https://user-images.githubusercontent.com/18034092/108086830-cdeed300-7044-11eb-891f-14892ae3b5bf.png)

# Steps to Reproduce

1. Write this code

```ts
import {html, render} from 'lit-html';

declare const color: string | undefined;
render(html`<div style=${styleMap({color})}></div>`, document.body);
```

2. See this output...
(See error below)

## Live Reproduction Link
https://codesandbox.io/s/lit-html-starter-forked-xzi43?file=/src/index.ts

## Expected Results
`styleMap` should be declarative, i.e. determining the styles of an element. If `undefined` or `null` are passed, the styles should be cleared. It's unclear whether [the spec for CSSStyleDeclaration.setProperty](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-setproperty) treats `''` and `null` differently, but in any case, the DOM APIs may be imperative, but `styleMap` should be declarative.

Irrespective of the type error, undefined does work perfectly fine.

## Actual Results
TS Error
```
Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)
style-map.d.ts(16, 5): The expected type comes from this index signature.
```

## Browsers Affected
N/A --- typescript

Related PR: https://github.com/Polymer/lit-html/pull/1616

**Comment by matthias-ccri** [comment]
I may be wrong about this. There is a use case where a user would want style to be applied additively — default styles.

Consider an element with a _default width_, set by CSS. It may add a `width` property to allow a user to override the width. In this case, the `width` being `undefined` doesn't mean "clear the width style", it means "retain the default style".

In CSS, there are values like `inherit`, `initial`, and `unset`, but none of these mean "ignore this style rule and use the next-closest rule". The only way is to not add the style at all.

In order to accomplish this (if styleMap were declarative in the way I first suggested), the cleanest way would be something like this, which is still ugly:
```
const {width} = this;
html`
  <style>
  .divStyles { width: 123 }
  </style>
  <div class="divStyles"
      style=${{
        ...(width ? {width} : {})
      }}
  ></div>
`
```

**Comment by AndrewJakubowicz** [comment]
Hi @matthias-ccri,

Sorry for the delay. Giving you a status update to see if resolves your case.
https://github.com/lit/lit/pull/1665 has been merged, which means in lit-html version 2 this is solved.

Your example with updated lit-html version: https://codesandbox.io/s/lit-html-starter-forked-ly7xd?file=/src/index.ts

Would this solve your use case temporarily?
Thank you!

**Comment by matthias-ccri** [comment]
@AndrewJakubowicz yes, it looks like that solves it. Thanks!
