### ISSUE TITLE
[lit-element] [lit-next] Issue with textarea exposing a property 

### ISSUE THREAD

**Issue by mrin9** [lit/lit#1717]
# Description
When I expose a property using `<textarea>` content,  the behavior is weird

# Lit versions
`lit: "2.0.0-pre.2"`

# Steps to Reproduce
- create a lit-element with a property (lets call it `name`)
- show this property using textarea
  ```
  <textarea> ${this.name} </textarea>
  ```
- now use this property in any other elements attribute 
  ```
  <div data-name="${this.name}"> </div>
  ```

## Live Reproduction Link
https://stackblitz.com/edit/lit-html-next-s3zjyy

## Expected Results
should render and not throw a console error

## Actual Results
do not render and throw a console error

## Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
> Not tested in other browser, but seems it will be the same case with others too

> In case it matters, it works with `lit-element - 2.4.0`

**Comment by sorvell** [comment]
Putting a part inside a `textarea` like this is not well supported. It's much better to make a property binding to the `.textContent` property of the `textarea`.

However, this should definitely not break subsequent parts like this. We'll work on a fix.

**Comment by justinfagnani** [comment]
We should add a dev mode warning for this. While you can put a binding in a `<textarea>` if the user updates the text it'll break the binding.
