### ISSUE TITLE
[lit/reactive-element] Decorators expect to be set to properties of "string | undefined" preventing Symbol()

### ISSUE THREAD

**Issue by Westbrook** [lit/lit#1789]
With `lit@2.0` I am no longer able to do the following without a Typescript error:

```
import { LitElement } from 'lit';
import { queryAssignedNodes } from 'lit/decorators.js';

const propertyKeySymbol = Symbol('propertyKey');

export class MyEl extends LitElement {
  @queryAssignedNodes('', true)
  private [propertyKeySymbol]!: NodeListOf<HTMLElement>;
}
```

This produces a:
```
error TS2345: Argument of type 'unique symbol' is not assignable to parameter of type 'string | undefined'.
```

It seems the change is here: https://github.com/lit/lit/blob/25e7a3186efa692ffeafa7e0d254ff3c3e9c9955/packages/reactive-element/src/decorators/base.ts#L73

Whereas previously this mapped to the following type:
```
declare type PropertyKey = string | number | symbol;
```

If this seems like an acceptable change, I'd be happy to structure a PR. Please let me know if you have an alternative implementation that would avoid this.

**Comment by justinfagnani** [comment]
Seems like just an oversight on our part. A PR would be great. A test for Symbol-keyed properties would be great too :)
