### ISSUE TITLE
Add official lint support via ESLint Plugin for better DX

### ISSUE THREAD

**Issue by codecycletechnologies** [lit/lit#1797]
## Description

**Who wants the functionality**
Lit developers need it from day one to work effectively with lit. 

**What it is they want**
Officially supported ESLint Plugin for lit.

**Why they want it**
To code confidently, to code with less errors, to save time

**Functional description of task/subtask**

**Code lint is always first priority for better and error free DX.
If eslint plugin can solve lint issue for both JS & TS then why cant we make it officially supported for lit?
Its 20% efforts and making 80% positive impact for developer experience.**

These are few tools for VS code and typescript which support lint for lit.
[https://github.com/web-padawan/awesome-lit#litelement-extensions](https://github.com/web-padawan/awesome-lit#litelement-extensions) (check tools also for eslint plugin)
[https://github.com/Microsoft/typescript-lit-html-plugin](https://github.com/Microsoft/typescript-lit-html-plugin)

**Pros**
- Lint rules needs to be supported officially so developers can have more trust for lit.
- Lint rules will be included in every version release of lit so DX will not be broken.
- It will help developers to start with lit once it will be added in lit website that this is officially supported and maintained by lit team.

**Existing Solution**
- Right now diff people putting efforts in diff repos in github to solve linting problem for lit, but its not centralised efforts so its not worth.
- Code in diff repos are outdated and cant keep up with new releases by lit.

## Acceptance criteria
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.
- New repo or sub project in lit labs for this
- Docs added into lit website for this.

**Comment by codecycletechnologies** [comment]
@justinfagnani @straversi Kindly share your views. Thanks

**Comment by justinfagnani** [comment]
Please see https://www.npmjs.com/package/eslint-plugin-lit which is also listed on our development docs: https://lit.dev/docs/tools/development/#ide-plugins

**Comment by justinfagnani** [comment]
I made some edits to the development docs to make this a little more clear: https://github.com/lit/lit.dev/pull/340

**Comment by beingminimal** [comment]
@justinfagnani this all are not officially supported and not updated also with lit new releases.
can we ask this repo owner to move repo in lit organisation? and make efforts centralise to make it official which will help to keep lint updated with all lit releases.
Awaiting your response.

**Comment by codecycletechnologies** [comment]
@justinfagnani this all are not officially supported and not updated also with lit new releases.
can we ask this repo owner to move repo in lit organisation? and make efforts centralise to make it official which will help to keep lint updated with all lit releases.
Awaiting your response.

**Comment by justinfagnani** [comment]
@codecycletechnologies it's not really possible for our team to maintain all the useful tools in the Lit ecosystem. We tried this when we used HTML Imports and it was not sustainable. We're very happy that others in the community have been able to write extensions for standard JS tooling that support Lit. This has worked out much better.

I'm sure @43081j is already thinking about Lit 2 support in `eslint-plugin-lit`. Please consider that we just released the first release candidate, so it's early and there could be an update before our stable release.

It's possible that we adopt some tools into our monorepo or org, but only if the tool maintainer was interested in that too. We don't see a lot of upside in forking valuable community projects. @43081j might have thoughts, but that's probably something to discuss in an issue here: https://github.com/43081j/eslint-plugin-lit

**Comment by codecycletechnologies** [comment]
@justinfagnani I was thinking same which you suggested in 3rd paragraph. i will create issue there and will explain things and its importance if required then i will request you to join conversation in future, is it fine?
And thanks for positive response & support.

**Comment by 43081j** [comment]
i'm still very actively maintaining at least the eslint plugin and, when possible, contributing to the analyzer/vs code plugin fwiw.

i'll work on a lit 2 PR to it this weekend for sure

**Comment by codecycletechnologies** [comment]
@43081j i am really happy and thankful for your efforts for lit community and developers.
But please think once for this issue. https://github.com/43081j/eslint-plugin-lit/issues/83
it will be really helpful for developers in long running.
Awaiting your response. thanks
