### ISSUE TITLE
[all] Tag 2.0.0 pre-releases git tags

### ISSUE THREAD

**Issue by simi** [lit/lit#1798]
:wave: as mentioned on slack, it would be handy to get all releases to NPM being tagged in git by git tags as well. Currently there is no 2.x git tag, but it seems on NPM there are at least 3 2.x (pre/rc) versions.

![lit](https://user-images.githubusercontent.com/193936/115726691-3e86d880-a383-11eb-9e59-8ad81c6c9ca7.png)

**Comment by kevinpschaaf** [comment]
We'll do this consistently going forward. As of yesterday's release, all published packages are being released: https://github.com/lit/lit/tags
