### ISSUE TITLE
Enable github discussions feature for all lit org repos to help dev community

### ISSUE THREAD

**Issue by codecycletechnologies** [lit/lit#1803]
## Description

- Who wants the functionality
   - Developers
- What it is they want
   - Enable github discussions for better developer community communication https://docs.github.com/en/discussions
- Why they want it
   - To avoid issues which are not that much relevant and to make things more clear before filling issue 
- Functional description of task/subtask
By enabling github discussion developers can interact more easily and clearly.

**Pros**
- It will help to create more clear issues and we can save time through discussion
- New developers can search and find solutions from it
- It can be act as officially supported forum for it
- It will be like developers helping in official way for developers so they don't need to find solution on other websites.

Here is the few samples that diff community already using it.
https://docs.github.com/en/discussions

## Acceptance criteria
Enable it and adds category into it like announcement, general, etc
Add discussion info in project's main readme file also so new developers can connect faster.
What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.

**Comment by codecycletechnologies** [comment]
@aomarks kindly share your views, thanks.

**Comment by sorvell** [comment]
Closing since discussions are enabled now for the main lit repo. Thanks for the suggestion.
