### ISSUE TITLE
[lit/reactive-element] Make using adoptingStyleSheets opt-in

### ISSUE THREAD

**Issue by web-padawan** [lit/lit#1811]
# Description

Currently, the `ReactiveElement` base class [adopts styles](https://github.com/lit/lit/blob/e0c6e2c928ea5e50fae2b75f8c56ef4f2f47ad84/packages/reactive-element/src/reactive-element.ts#L778-L781) using the `adoptedStyleSheets` if possible.
This means that in Chromium-based browsers this is the default option:

https://github.com/lit/lit/blob/e0c6e2c928ea5e50fae2b75f8c56ef4f2f47ad84/packages/reactive-element/src/css-tag.ts#L119-L123

While this was mentioned as a positive improvement in terms of performance, there are still some [objections](https://github.com/WICG/construct-stylesheets/issues/45#issuecomment-826397124) related to `adoptedStyleSheets`  API and it looks like there is no consensus yet on how to proceed with this API.

That said, the fact that [API already has some usage](https://github.com/WICG/construct-stylesheets/issues/45#issuecomment-577781329) - which is probably because of LitElement - was mentioned in the issue linked above, and such statements could introduce unnecessary pressure with regards to the standardisation process.

Previously it was possible to use `UpdatingElement` which didn't include any code related to adopting stylesheets.
However, starting with Lit 2.0 that class is removed in favor of `ReactiveElement` which **does** handle the styles.

## Expected Results

I'm wondering if there could be some way to opt-out from using `adoptedStyleSheets` when using Lit, like a flag?
It would make even more sense to make this API not enabled by default but **make it opt-in** instead.

The main benefit of this would be to ensure Lit defaults to a standard based Shadow DOM in all the browsers.

## Actual Results

Currently it is only possible to opt out from `adoptedStyleSheets` by using a workaround:

```js
delete document.prototype.adoptedStyleSheets;
```

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by hsablonniere** [comment]
I'm in favor of this while the standardisation process is still in progress.

**Comment by justinfagnani** [comment]
Our intention is to mostly abstract away how styles are actually applied and just do the right thing for each environment we're in. Is there a problem that using `adoptedStyleSheets` is causing? If you just don't want to support this feature in Chrome because it shipped before other browsers, then disabling globally seems like the right approach.

**Comment by web-padawan** [comment]
IMHO, there are the following problems here (although most of Lit users probably wouldn't care about those):

1. `adoptedStyleSheets` is still an experimental feature (at least until the consensus is reached).
2. Lit-based components work differently in Chrome and Firefox / Safari because using this feature.
3. It isn't possible to opt-out for Lit only, while keeping it available for any third-party components.

I would suggest to make the following change in order to address all of those concerns:

```ts
export const adoptStyles = (
  renderRoot: ShadowRoot,
  styles: CSSResultFlatArray,
  experimentalAdoptedStyleSheets = true
) => {
  if (supportsAdoptingStyleSheets && experimentalAdoptedStyleSheets) {
    (renderRoot as ShadowRoot).adoptedStyleSheets = styles.map((s) =>
      s instanceof CSSStyleSheet ? s : s.styleSheet!
    );
  }
```

The `experimentalAdoptedStyleSheets` flag would make it possible for `ReactiveElement` extensions to disable using constructable stylesheets, as it was possible with `UpdatingElement`, while keeping the rest of the logic intact.

There is one more check inside the [`getCompatibleStyle`](https://github.com/lit/lit/blob/198d5d583fb45b7788eee217fcaa8361aa4ac085/packages/reactive-element/src/css-tag.ts#L140) which could be a bit harder to update, but it appears that this helper does not enforce using `adoptedStyleSheets`, so it's not directly related to the concerns listed above.

**Comment by sorvell** [comment]
Your reason #1 seems to be in tension with #2 and #3. Defeating `adoptedStyles` globally satisfies #1 and #2. It's unclear why #3 specifically is important, especially if you're concerned about #1 and #2. 

We're also hopeful that the feature will land in all browsers soon.

**Comment by pthomasius** [comment]
> Our intention is to mostly abstract away how styles are actually applied and just do the right thing for each environment we're in. Is there a problem that using `adoptedStyleSheets` is causing? If you just don't want to support this feature in Chrome because it shipped before other browsers, then disabling globally seems like the right approach.

I'm working on an app that moves htmlelements between documents (windows) and litElements loose their styles once moved to new doc as the adoptedStyleSheets get removed. Calling adoptStyles() again fails with global error that adoptedstylesheets cannot be shared between documents.
Is there a recomended way of handling this?

**Comment by web-padawan** [comment]
@pthomasius Technically, `adoptedCallback()` might be the right place for handling such cases.
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions

IIRC moving nodes across documents has this limitation, and it's not specific to `adoptedStyleSheets` only.
Here is a similar issue about Scoped Custom Element Registries proposal: https://github.com/WICG/webcomponents/issues/907

I'm afraid this might be considered an edge case by the Lit tea though.

**Comment by pthomasius** [comment]
Yes been trying to re-apply in the adoptedCallback by creating a new CSSStyleSheet from the lit styles property and applying to renderRoot, but looks like I will have to resort to imported stylesheets rather then constructed ones. Or maybe construct from CSS import modules rather then the lit styles property. 

Thank you for the links and info.

**Comment by justinfagnani** [comment]
@pthomasius can you open a new issue for that?

**Comment by web-padawan** [comment]
I agree it's better to discuss the above problem separately.
