### ISSUE TITLE
[@lit-labs/react] ReactControllerHost._updated() not called after 2 kicks

### ISSUE THREAD

**Issue by Vac1911** [lit/lit#1815]
# Description
The ReactControllerHost class does not update its self more than 2 times.
@ajmchambers was attempting to produce use the mouse position controller example as a hook in a react component, but the react component is only updating the coordinates once.

Doing some debugging I found this is because after the second kick, ReactControllerHost._updated() is not called. This leaves ReactControllerHost._updatePending set permanently to true, which means all calls to ReactControllerHost.requestUpdate() will fail. (See "Actual Results" section for my log output).

# Steps to Reproduce

1. Start with the usage code provided in [readme](https://github.com/lit/lit/tree/main/packages/labs/react#usage-1). (I changed the name of the react component)

```js
import * as React from 'react';
import {useController} from '@lit-labs/react/use-controller.js';
import {MouseController} from '@example/mouse-controller';

// Write a React hook function:
const useMouse = () => {
  // Use useController to create and store a controller instance:
  const controller = useController(React, (host) => new MouseController(host));
  // return the controller: return controller;
  // or return a custom object for a more React-idiomatic API:
  return controller.position;
};

// Now use the new hook in a React component:
const MousePositionComponent = (props) => {
  const mousePosition = useMouse();
  return (
    <pre>
      x: {mousePosition.x}
      y: {mousePosition.y}
    </pre>
  );
};

export default MousePositionComponent;
```

2. Create a controller such as the following:

```js
export class MouseController {
  host;
  pos = { x: 0, y: 0 };

  _onMouseMove = ({ clientX, clientY }) => {
    this.pos = { x: clientX, y: clientY };
    this.host.requestUpdate();
  };

  constructor(host) {
    this.host = host;
    host.addController(this);
  }

  hostConnected() {
    window.addEventListener("mousemove", this._onMouseMove);
  }

  hostDisconnected() {
    window.removeEventListener("mousemove", this._onMouseMove);
  }
}

```
3. Render it like so:
```jsx
import { StrictMode } from "react";
import ReactDOM from "react-dom";
import MousePositionReact from "./react/MousePosition";

const rootElement = document.getElementById("root");
ReactDOM.render(
  <StrictMode>
    <MousePositionReact />
  </StrictMode>,
  rootElement
);
```
4. Move the mouse and watch it update twice and stop.

## Reproduction Link
Original issue from @ajmchambers:
https://codesandbox.io/s/confident-jackson-l5kl1?file=/src/react/MousePosition.js

My recreation with console logging:
https://codesandbox.io/s/lucid-dust-nq56g?file=/src/react/useController.ts:604-623

Additional recreation with different event:
https://codesandbox.io/s/lingering-smoke-57s1y?file=/src/ClickController.js

## Expected Results
The mouse position keeps updating while the mouse is moved, and every time the component updates, ReactControllerHost._updated() would be called.

## Actual Results
The react component does not update more than 2 times, and ReactControllerHost._updated() stops being called after a couple updates.

Logging output from my reproduction with debugging:
- "request update" - [ReactControllerHost.requestUpdate() before checking _updatePending property. ](https://github.com/lit/lit/blob/e0c6e2c928ea5e50fae2b75f8c56ef4f2f47ad84/packages/labs/react/src/use-controller.ts#L59)
- "starting kick" - [ReactControllerHost.requestUpdate() right before updating _kick. ](https://github.com/lit/lit/blob/e0c6e2c928ea5e50fae2b75f8c56ef4f2f47ad84/packages/labs/react/src/use-controller.ts#L61)
- "update resolved" - [ReactControllerHost._updated() after where the _updatePending proprerty is turned back to false. ](https://github.com/lit/lit/blob/e0c6e2c928ea5e50fae2b75f8c56ef4f2f47ad84/packages/labs/react/src/use-controller.ts#L89)
- "component update" - inside the React component, immedietly before the return statement.

![image](https://user-images.githubusercontent.com/45333542/116280205-73fe3e00-a756-11eb-8c21-e3ff6f7a8ebb.png)

**Comment by ajmchambers** [comment]
Looking at this myself, I think changing this [line](https://github.com/lit/lit/blob/main/packages/labs/react/src/use-controller.ts#L62):

```typescript
requestUpdate(): void {
  if (!this._updatePending) {
    this._updatePending = true;
    // Trigger a React update by updating some state
    microtask.then(() => this._kick(this._kickCount + 1));
  }
}
```

To this, seems to work correctly for me:

```typescript
requestUpdate(): void {
  if (!this._updatePending) {
    this._updatePending = true;
    // Trigger a React update by updating some state
    microtask.then(() => {
      this._kickCount++;
      this._kick(this._kickCount);
    }
  }
}
```

**Comment by Vac1911** [comment]
This worked for me (you forgot a parenthesis):
```
microtask.then(() => {
  this._kickCount++;
  this._kick(this._kickCount);
});
```
I'm pretty sure what that's doing is setting the state 2 times, but I have no idea why that's fixing it. Since that's updating it twice at the same time in the life cycle, believe the component only updates once, and that's the result i got with testing it.
<hr/>

> By default, effects run after every completed render, but you can choose to fire them only when certain values have changed.

Someone correct my if I am wrong but [react effects](https://reactjs.org/docs/hooks-reference.html#useeffect) are basically just functions that are run after an update (specifically after an update + render) (also the second param can be used to limit the calls when a specific state variable is updated).

So [this line](https://github.com/lit/lit/blob/17580adeed8d3ebdc783c0938bb7ae24908c414f/packages/labs/react/src/use-controller.ts#L141) basically says "after component does an update and renders, call: host._updated()". In my earlier reproduction with logging, it shows the component does am update without _updated called.

**This is completely untested but It's possible:**
The state wasn't actually being set but not actually changed by this._kick(this._kickCount + 1). In the internal reactjs logic: it looks for a value in state to change, in order to que the firing of an effect, instead of actually just firing it after every render, like it should. That would cause the component to update/render but not fire [this effect].(https://github.com/lit/lit/blob/17580adeed8d3ebdc783c0938bb7ae24908c414f/packages/labs/react/src/use-controller.ts#L141)

**Comment by ajmchambers** [comment]
Yea maybe the reason it only updated the first 2 times was because kick was given the values: 0 -> 1 -> 1 -> 1 -> 1
So the first update was the inital load with tick at 0, then second at 1, then it kept being set to 1 no it wasn't considered a change:

0 // _kickCount = 0, initial value, render component
1 // _kickCount + 1, update component
1 // _kickCount + 1, no change
1 // _kickCount + 1, no change
1 // _kickCount + 1, no change
... and so on

**Comment by Vac1911** [comment]
Yeah, printing the value of `this_.kickCount`, before the kick:
```
// Trigger a React update by updating some state
window.debug("starting kick", this._kickCount);
microtask.then(() => this._kick(this._kickCount + 1));
```
Outputs 0 both times that ReactControllerHost._updated() is normally reached. With some more looking into, I found that the `useController` method is called every time the component updates which contains `const [kickCount, kick] = useState(0);`, with and without [this change](https://github.com/lit/lit/issues/1815#issuecomment-827787671) (unsure if relevant).

With logging, the suggested change does show the kick count incrementing, so it seems that the `_kick()` method is not updating the `_kickCount` property.

**Comment by ajmchambers** [comment]
Yea think the flow kinda makes sense to me now:

```typescript
// useController
const [kickCount, kick] = useState(0);

...

const host = new ReactControllerHost<C>(kickCount, kick); // kickCount is 0, kick is the setState to update the useState

...

// ReactControllerHost
private _kickCount: number;
// A function to trigger an update of the React component
private _kick: (k: number) => void;

constructor(kickCount: number, kick: (k: number) => void) {
  this._kickCount = kickCount; // stored initial value of 0
  this._kick = kick; // stored setState function from the original useState
  this._updateCompletePromise = new Promise((res, _rej) => {
    this._resolveUpdate = res;
  });
}

...

microtask.then(() => {
  this._kickCount++; // increments the stored _kickCount on the ReactControllerHost 
  this._kick(this._kickCount); // passes the new value along to update the state in the useController, which should cause a rerender
});
```

**Comment by Vac1911** [comment]
>Yea think the flow kinda makes sense to me now
At this point thou, why not use a random string or the current time stamp, that way we can just get rid of _kickCount?

**Comment by ajmchambers** [comment]
I'll try and put together a pull request, though windows doesn't seem to like the lit monorepo - and wsl ubuntu is not liking playwright... so ill need to dig out the old mac I reckon

**Comment by Vac1911** [comment]
I can throw up a pull request quick, dont worry about it
