### ISSUE TITLE
TemplateResult is not exported by 'lit'

### ISSUE THREAD

**Issue by samanime** [lit/lit#1821]
# Description

The documentation indicates that TemplateResult should be exported by 'lit': https://lit.dev/docs/api/templates/#TemplateResult

It however is not.

I need it to be able to determine if an object is the result of `html`, with `obj instanceof TemplateResult`. I could check if it has `_$litType$ === 1`, but that wouldn't be very future safe. 

If there is a reason we don't want TemplateResult to be exported, I'd recommend we create an `isHtml()` or `isTemplateResult()` helper.

Using the current version: 2.0.0-rc.1

# Steps to Reproduce

```
import { TemplateResult } from 'lit';

console.log(TemplateResult); // should not be undefined, but is.
```

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-5n9b25

## Expected Results

TemplateResult should exist.

## Actual Results

TemplateResult is undefined and/or an error about "no named export TemplateResult" is given.

## Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari 11
- [X] Safari 10
- [X] IE 11

**Comment by justinfagnani** [comment]
`TemplateResult` is only an interface. There's no object to export. There is an `isTemplateResult()` helper in `directive-helpers.js`: https://lit.dev/docs/api/custom-directives/#isTemplateResult
