### ISSUE TITLE
[labs/react] Children have wrong type when "DOM" library is present in tsconfig.json

### ISSUE THREAD

**Issue by swissmanu** [lit/lit#1826]
# Description

When the `dom` library is part of the `libs` configuration of `tsconfig.json`, a React component created using `createComponent` exposes a wrong type for the components `children` prop, resulting in an error:

```
components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'HTMLCollection | (HTMLCollection & string) | (HTMLCollection & number) | (HTMLCollection & false) | (HTMLCollection & true) | (HTMLCollection & ReactElement<...>) | (HTMLCollection & ReactNodeArray) | (HTMLCollection & ReactPortal) | undefined'.ts(2747)
```

This can be fixed be removing `dom`. Though, this might not be always the wanted solution.

# Steps to Reproduce

1. Add `dom` to the compiler option `lib` in `tsconfig.json`:

```json
{
    "compilerOptions": {
        "lib": [
            "dom"
        ],
        // ...
    }
}
```

2. Create a React component based on a `LitElement` Web Component:

```ts
import { createComponent } from "@lit-labs/react";
import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";
import React from "react";

@customElement("my-component")
export class MyComponent extends LitElement {
  render() {
    return html` <div><slot></slot></div> `;
  }
}

export const MyComponentReact = createComponent(
  React,
  "my-component",
  MyComponent
);
```

3. Use the component:

```ts
export default function App() {
  return (
    <div className="App">
      <MyComponentReact>
        Start editing to see some magic happen!
      </MyComponentReact>
    </div>
  );
}
```

4. Problem:

<img width="963" alt="image" src="https://user-images.githubusercontent.com/170832/116655786-f02d9700-a98b-11eb-9240-1d2ee7adbf44.png">

5. To resolve the problem momentarily, remove `dom` from the libraries in `tsconfig.json`

## Live Reproduction Link

https://codesandbox.io/s/strange-shadow-ryi9h

(I could not use your stackblitz template, since `tsconfig.json` cannot be modified there)

## Expected Results

The type for the `children` prop is `children?: React.ReactNode`, no matter if `dom` is part of the imported libraries or not.

## Actual Results

```
components don't accept text as child elements. Text in JSX has the type 'string', but the expected type of 'children' is 'HTMLCollection | (HTMLCollection & string) | (HTMLCollection & number) | (HTMLCollection & false) | (HTMLCollection & true) | (HTMLCollection & ReactElement<...>) | (HTMLCollection & ReactNodeArray) | (HTMLCollection & ReactPortal) | undefined'.ts(2747)
```

## Browsers Affected

This issue is not related to a specific browser.

## Further Notes

Interestingly, the type of the imported wrapper component looks as expected, but as soon as it is used within JSX, things go crazy.

<img width="751" alt="image" src="https://user-images.githubusercontent.com/170832/116688436-fdac4680-a9b6-11eb-936f-f6b5d277b394.png">

**Comment by justinfagnani** [comment]
This was a little tricky for figure out - by adding the "dom" library it defined the actually properties of HTMLElement, which include `children`. `ParentNode.children` is an `HTMLCollection` and so TypeScript was intersecting that with React's types and requiring that `children` also be an `HTMLCollection`.

Fixed it by omitting `children` from the instance type before passing that type to `React.PropsWithChildren`.

**Comment by swissmanu** [comment]
Very cool you could figure it out @justinfagnani ❤️ I tried to find a solution myself this afternoon.. Without any success, yet. I planned to have another look with a fresh mind tomorrow, but thats obviously not necessary anymore. ☺️

Thanks a lot! Have a great weekend 🙌
