### ISSUE TITLE
[labs/motion] `flip-controller.js` is missing in the npm release

### ISSUE THREAD

**Issue by alangdm** [lit/lit#1827]
# Description

While trying to use `@lit-labs/motion` in a JS project, I noticed that I was getting the following error:

```
GET http://localhost:8000/node_modules/@lit-labs/motion/flip-controller.js net::ERR_ABORTED 404 (Not Found)
```

After looking at the node_modules folder, I noticed that while the other TS files have their counterpart JS files, `flip-controller` seems to be absent

https://unpkg.com/browse/@lit-labs/motion@1.0.0-rc.1/

# Steps to Reproduce

1. Install  `@lit-labs/motion` from npm
2. Import it like this
```js
import { flip } from '@lit-labs/motion';
```
3. The above-mentioned error occurs

**Comment by mabry1985** [comment]
This seems to be a duplicate of, or similar to, [#1796](https://github.com/lit/lit/issues/1796)

**Comment by Vac1911** [comment]
> This seems to be a duplicate of, or similar to, [#1796](https://github.com/lit/lit/issues/1796)

I believe it is caused by the same issue, however this is reporting that the critical fix has should added to the npm package (I'm not 100% sure how npm releases work).

**Comment by Vac1911** [comment]
Temporary work around (until the fix is in the npm release)

**Comment by Vac1911** [comment]
Temporary work around _(please note: this is **really** bad practice.)_

Put [this file](https://gist.github.com/Vac1911/0d26b268ca38651cd53562a6f4bd618f) into your `node_modules/@lit-labs/motion` folder. Make sure that the file is named `flip-controller.js`

For those wondering: the code in that gist was made by recompiling lit while I was working on an unrelated issue.

**Comment by alangdm** [comment]
It seems rc2 fixed this issue so I'll close this, thanks a lot!
