### ISSUE TITLE
Subclassing a mixin class that accesses `observedAttributes` throws

### ISSUE THREAD

**Issue by bennypowers** [lit/lit#1835]
# Description

# Steps to Reproduce

```ts
import {html, css, LitElement} from 'lit';
import {property, customElement} from 'lit/decorators.js';

type Constructor<T = {}> = { new (...args:any[]): T }

function XAMixin<B extends Constructor<
  HTMLElement & {
    attributeChangedCallback?(name: string, oldVal: string, newVal: string): void;
  }> & {
  observedAttributes?: string[]
}>(superclass: B) {
  abstract class ApolloElement extends superclass {
    static documentType: 'document'|'query'|'mutation'|'subscription' = 'document';

    static get observedAttributes(): string[] {
      return [
        ...superclass.observedAttributes ?? [],
        'x-a',
      ];
    }

    declare xA?: string;

    constructor(...a: any[]) { super(...a); }

    attributeChangedCallback(name: string, oldVal: string, newVal: string): void {
      if (!superclass.observedAttributes?.includes?.(name)) {
        switch (name) {
          case 'x-a':
            if (this.xA !== newVal)
              this.xA = newVal;
            break;
          default:
            break;
        }
      }
      super.attributeChangedCallback?.(name, oldVal, newVal);
    }
  }

  return ApolloElement;
}

@customElement('x-a-lit-super')
class XALitSuper extends LitElement {
  @property({ reflect: true, attribute: 'x-a' }) xA = '';
}

@customElement('x-a-lit-mixed')
class XALitMixed extends XAMixin(LitElement) {
  @property({ reflect: true, attribute: 'x-a' }) xA = '';
}

@customElement('x-b-lit-super')
class XBLitSuper extends LitElement {
  @property({ reflect: true, attribute: 'x-b' }) xB = '';
}

@customElement('x-b-lit-mixed')
class XBLitMixed extends XAMixin(LitElement) {
  @property({ reflect: true, attribute: 'x-b' }) xB = '';
}
```

```html
<p>x-a-lit-super</p>
<x-a-lit-super x-a="z" x-b="y"></x-a-lit-super>
 
<p>x-b-lit-super</p>
<x-b-lit-super x-a="z" x-b="y"></x-b-lit-super>

<p>x-a-lit-mixed</p>
<x-a-lit-mixed x-a="z" x-b="y"></x-a-lit-mixed>
 
<p>x-b-lit-mixed</p>
<x-b-lit-mixed x-a="z" x-b="y"></x-b-lit-mixed>
```

2. error:
```
Uncaught TypeError: can't access property "forEach", this.elementProperties is undefined
    get observedAttributes https://cdn.skypack.dev/-/@lit/reactive-element@v1.0.0-pre.3-oqcORhgB4WWZaoegW9ly/dist=es2020,mode=imports/optimized/@lit/reactive-element.js:49
    get observedAttributes https://playground.lit.dev/playground-projects/3m6nrno/simple-greeting.js:15
    n https://cdn.skypack.dev/-/@lit/reactive-element@v1.0.0-pre.3-oqcORhgB4WWZaoegW9ly/dist=es2020,mode=imports/optimized/@lit/reactive-element/decorators/custom-element.js:6
    n https://cdn.skypack.dev/-/@lit/reactive-element@v1.0.0-pre.3-oqcORhgB4WWZaoegW9ly/dist=es2020,mode=imports/optimized/@lit/reactive-element/decorators/custom-element.js:6
    __decorate https://playground.lit.dev/playground-projects/3m6nrno/simple-greeting.js:4
    <anonymous> https://playground.lit.dev/playground-projects/3m6nrno/simple-greeting.js:58
```

## Live Reproduction Link

[reproduction playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7cHJvcGVydHksIGN1c3RvbUVsZW1lbnR9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxudHlwZSBDb25zdHJ1Y3RvcjxUID0ge30-ID0geyBuZXcgKC4uLmFyZ3M6YW55W10pOiBUIH1cblxuZnVuY3Rpb24gWEFNaXhpbjxCIGV4dGVuZHMgQ29uc3RydWN0b3I8XG4gIEhUTUxFbGVtZW50ICYge1xuICAgIGF0dHJpYnV0ZUNoYW5nZWRDYWxsYmFjaz8obmFtZTogc3RyaW5nLCBvbGRWYWw6IHN0cmluZywgbmV3VmFsOiBzdHJpbmcpOiB2b2lkO1xuICB9PiAmIHtcbiAgb2JzZXJ2ZWRBdHRyaWJ1dGVzPzogc3RyaW5nW11cbn0-KHN1cGVyY2xhc3M6IEIpIHtcbiAgYWJzdHJhY3QgY2xhc3MgQXBvbGxvRWxlbWVudCBleHRlbmRzIHN1cGVyY2xhc3Mge1xuICAgIHN0YXRpYyBkb2N1bWVudFR5cGU6ICdkb2N1bWVudCd8J3F1ZXJ5J3wnbXV0YXRpb24nfCdzdWJzY3JpcHRpb24nID0gJ2RvY3VtZW50JztcblxuICAgIHN0YXRpYyBnZXQgb2JzZXJ2ZWRBdHRyaWJ1dGVzKCk6IHN0cmluZ1tdIHtcbiAgICAgIHJldHVybiBbXG4gICAgICAgIC4uLnN1cGVyY2xhc3Mub2JzZXJ2ZWRBdHRyaWJ1dGVzID8_IFtdLFxuICAgICAgICAneC1hJyxcbiAgICAgIF07XG4gICAgfVxuXG4gICAgZGVjbGFyZSB4QT86IHN0cmluZztcblxuICAgIGNvbnN0cnVjdG9yKC4uLmE6IGFueVtdKSB7IHN1cGVyKC4uLmEpOyB9XG5cbiAgICBhdHRyaWJ1dGVDaGFuZ2VkQ2FsbGJhY2sobmFtZTogc3RyaW5nLCBvbGRWYWw6IHN0cmluZywgbmV3VmFsOiBzdHJpbmcpOiB2b2lkIHtcbiAgICAgIGlmICghc3VwZXJjbGFzcy5vYnNlcnZlZEF0dHJpYnV0ZXM_LmluY2x1ZGVzPy4obmFtZSkpIHtcbiAgICAgICAgc3dpdGNoIChuYW1lKSB7XG4gICAgICAgICAgY2FzZSAneC1hJzpcbiAgICAgICAgICAgIGlmICh0aGlzLnhBICE9PSBuZXdWYWwpXG4gICAgICAgICAgICAgIHRoaXMueEEgPSBuZXdWYWw7XG4gICAgICAgICAgICBicmVhaztcbiAgICAgICAgICBkZWZhdWx0OlxuICAgICAgICAgICAgYnJlYWs7XG4gICAgICAgIH1cbiAgICAgIH1cbiAgICAgIHN1cGVyLmF0dHJpYnV0ZUNoYW5nZWRDYWxsYmFjaz8uKG5hbWUsIG9sZFZhbCwgbmV3VmFsKTtcbiAgICB9XG4gIH1cblxuICByZXR1cm4gQXBvbGxvRWxlbWVudDtcbn1cblxuZXhwb3J0IGNsYXNzIFhBVmFuaWxsYVN1cGVyIGV4dGVuZHMgSFRNTEVsZW1lbnQge1xuICBzdGF0aWMgb2JzZXJ2ZWRBdHRyaWJ1dGVzID0gWyd4LWEnLCAneC1iJ107XG4gIFxuICBnZXQgeEEoKSB7XG4gICAgcmV0dXJuIHRoaXMudGV4dENvbnRlbnQ7XG4gIH1cbiAgXG4gIHNldCB4QSh2YWw6IHN0cmluZykge1xuICAgIHRoaXMudGV4dENvbnRlbnQgPSB2YWw7XG4gIH1cbiAgXG4gIGF0dHJpYnV0ZUNoYW5nZWRDYWxsYmFjayhuYW1lOiBzdHJpbmcsIG9sZFZhbDogc3RyaW5nLCBuZXdWYWw6IHN0cmluZykge1xuICAgIGlmIChuYW1lID09PSAneC1hJyAmJiB0aGlzLnhBICE9PSBuZXdWYWwpIHtcbiAgICAgICAgdGhpcy54QSA9IG5ld1ZhbDtcbiAgICB9XG4gIH1cbn1cblxuZXhwb3J0IGNsYXNzIFhCVmFuaWxsYVN1cGVyIGV4dGVuZHMgSFRNTEVsZW1lbnQge1xuICBzdGF0aWMgb2JzZXJ2ZWRBdHRyaWJ1dGVzID0gWyd4LWInXTtcbiAgXG4gIGdldCB4QigpIHtcbiAgICByZXR1cm4gdGhpcy50ZXh0Q29udGVudDtcbiAgfVxuICBcbiAgc2V0IHhCKHZhbDogc3RyaW5nKSB7XG4gICAgdGhpcy50ZXh0Q29udGVudCA9IHZhbDtcbiAgfVxuICBcbiAgYXR0cmlidXRlQ2hhbmdlZENhbGxiYWNrKG5hbWU6IHN0cmluZywgb2xkVmFsOiBzdHJpbmcsIG5ld1ZhbDogc3RyaW5nKSB7XG4gICAgaWYgKG5hbWUgPT09ICd4LWInICYmIHRoaXMueEIgIT09IG5ld1ZhbCkge1xuICAgICAgICB0aGlzLnhCID0gbmV3VmFsO1xuICAgIH1cbiAgfVxufVxuXG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3gtYS12YW5pbGxhLXN1cGVyJywgWEFWYW5pbGxhU3VwZXIpO1xuXG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3gtYi12YW5pbGxhLXN1cGVyJywgWEJWYW5pbGxhU3VwZXIpO1xuXG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3gtYS12YW5pbGxhLW1peGVkJywgWEFNaXhpbihYQVZhbmlsbGFTdXBlcikpO1xuXG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3gtYi12YW5pbGxhLW1peGVkJywgWEFNaXhpbihYQlZhbmlsbGFTdXBlcikpO1xuXG5AY3VzdG9tRWxlbWVudCgneC1hLWxpdC1zdXBlcicpXG5jbGFzcyBYQUxpdFN1cGVyIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBwcm9wZXJ0eSh7IHJlZmxlY3Q6IHRydWUsIGF0dHJpYnV0ZTogJ3gtYScgfSkgeEEgPSAnJztcbn1cblxuQGN1c3RvbUVsZW1lbnQoJ3gtYS1saXQtbWl4ZWQnKVxuY2xhc3MgWEFMaXRNaXhlZCBleHRlbmRzIFhBTWl4aW4oTGl0RWxlbWVudCkge1xuICBAcHJvcGVydHkoeyByZWZsZWN0OiB0cnVlLCBhdHRyaWJ1dGU6ICd4LWEnIH0pIHhBID0gJyc7XG59XG5cbkBjdXN0b21FbGVtZW50KCd4LWItbGl0LXN1cGVyJylcbmNsYXNzIFhCTGl0U3VwZXIgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgQHByb3BlcnR5KHsgcmVmbGVjdDogdHJ1ZSwgYXR0cmlidXRlOiAneC1iJyB9KSB4QiA9ICcnO1xufVxuXG5AY3VzdG9tRWxlbWVudCgneC1iLWxpdC1taXhlZCcpXG5jbGFzcyBYQkxpdE1peGVkIGV4dGVuZHMgWEFNaXhpbihMaXRFbGVtZW50KSB7XG4gIEBwcm9wZXJ0eSh7IHJlZmxlY3Q6IHRydWUsIGF0dHJpYnV0ZTogJ3gtYicgfSkgeEIgPSAnJztcbn0ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHA-eC1hLXZhbmlsbGEtc3VwZXI8L3A-XG4gIDx4LWEtdmFuaWxsYS1zdXBlciB4LWE9XCJ6XCIgeC1iPVwieVwiPjwveC1hLXZhbmlsbGEtc3VwZXI-XG4gICBcbiAgPHA-eC1iLXZhbmlsbGEtc3VwZXI8L3A-XG4gIDx4LWItdmFuaWxsYS1zdXBlciB4LWE9XCJ6XCIgeC1iPVwieVwiPjwveC1iLXZhbmlsbGEtc3VwZXI-XG4gIFxuICA8cD54LWEtdmFuaWxsYS1taXhlZDwvcD5cbiAgPHgtYS12YW5pbGxhLW1peGVkIHgtYT1cInpcIiB4LWI9XCJ5XCI-PC94LWEtdmFuaWxsYS1taXhlZD5cbiAgIFxuICA8cD54LWItdmFuaWxsYS1taXhlZDwvcD5cbiAgPHgtYi12YW5pbGxhLW1peGVkIHgtYT1cInpcIiB4LWI9XCJ5XCI-PC94LWItdmFuaWxsYS1taXhlZD5cbiAgXG4gIDxwPngtYS1saXQtc3VwZXI8L3A-XG4gIDx4LWEtbGl0LXN1cGVyIHgtYT1cInpcIiB4LWI9XCJ5XCI-PC94LWEtbGl0LXN1cGVyPlxuICAgXG4gIDxwPngtYi1saXQtc3VwZXI8L3A-XG4gIDx4LWItbGl0LXN1cGVyIHgtYT1cInpcIiB4LWI9XCJ5XCI-PC94LWItbGl0LXN1cGVyPlxuICBcbiAgPHA-eC1hLWxpdC1taXhlZDwvcD5cbiAgPHgtYS1saXQtbWl4ZWQgeC1hPVwielwiIHgtYj1cInlcIj48L3gtYS1saXQtbWl4ZWQ-XG4gICBcbiAgPHA-eC1iLWxpdC1taXhlZDwvcD5cbiAgPHgtYi1saXQtbWl4ZWQgeC1hPVwielwiIHgtYj1cInlcIj48L3gtYi1saXQtbWl4ZWQ-XG48L2JvZHk-XG4ifV0)

## Expected Results

subclassing with a class that defines observedAttributes with decorator preserves decorator behaviour

## Actual Results

Error

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by 43081j** [comment]
This is because of `this` binding.

```ts
class Base {
  static foo() {
    console.log(this);
  }
}
```

`Base.foo()` will log out `Base`, but `super.foo()` in a subclass will log the subclass.

IMO we should add defensive code or throw a useful error in these cases when someone has lost `this` by accident, rather than using non-null assertions and assuming it'll always be right.

**Comment by kevinpschaaf** [comment]
`ReactiveElement` has `finalized=true` by default, but has no `elementProperties`, which is what makes calling `LitElement.observedAttributes` unsafe. I think we didn't anticipate calling an unsubclassed LitElement's observedAttributes directly, but the mixin use case here is valid, so we'll get that fixed.

**Comment by sorvell** [comment]
We're going to fix the exception here so that calling `LitElement|ReactiveElement.bservedAttributes` does not throw.

However, it's important to point out that the mixin should use `super.observedAttributes` and not directly use the passed in base class, e.g. `superclass.observedAttributes` (and likewise `super.constructor.observedAttributes`). The difference is what `this` is when in the super getter for `observedAttributes`. It's in `observedAttributes` that `ReactiveElement` crawls through the `properties` objects and creates reactive properties. Therefore it's important that the `this` be the extending subclass where `properties` is defined rather than the superclass itself. You won't hit this issue when using the decorator which directly calls `createProperty`, only when using `static properties`. Consider:

```
class XALitMixed extends XAMixin(LitElement) {
  static properties = { prop: {}};
}
```

If the base class getter is called directly (e.g. `superclass.observedAttributes`) then `prop` will not be a reactive property. However, if `super.observedAttributes` is used, then `prop` will be a reactive property. It's also fine to directly call `finalize()` in the `observedAttributes` implementation to ensure `properties` become reactive.

Hope that makes sense.

**Comment by bennypowers** [comment]
It does, I updated the code in apollo-elements which 'inspired' this issue to use `super.` and it actually works better than before with fewer bytes, the prototype chain just doin' it's thing.

Thanks for the speedy resolution; it was interesting watching it come together.
