### ISSUE TITLE
Who publishes lit to npm?

### ISSUE THREAD

**Issue by philkunz** [lit/lit#1838]
Why is there not only one single Google maintained service account that publishes to npm?
I look on npm and find a user named "rictic" with no bio and no verifiable status quo having published the last version of lit.

The only developer I can really attribute to lit is @justinfagnani , the rest of the contributors I simply don't know. I'd expect the package to be either published by him or some Google Service Account that is some sorts of verifiable in a quick and painless manner.

**Comment by justinfagnani** [comment]
We maintain control on npm exactly who has permissions to publish the package, and we require 2-factor authentication to publish. Many other packages give team members permission to publish. Is that causing a problem?

**Comment by philkunz** [comment]
@justinfagnani Given that lit is used in highly sensitive contexts, and potentially has access to data from passwords to health data shown on websites, I'd rather take the approach of typescript or angular: Proper CI/CD and requiring more than one set of eyes to merge stuff into a release candidate. Also it is confusing to see some unknown person for "lit" as publisher in contrast to you as publisher of "lit-element". In other words: Why risk the attack vector of 5 systems, if you can reduce it to one? Also, if your system is compromised, two factor doesn't really help much.

**Comment by justinfagnani** [comment]
@philkunz Angular does seem to use a few group accounts for publishing, but TypeScript uses personal accounts like we do.

I don't think the group account gives any more security. We would rely on our password sharing mechanisms on our side, rather than access control on the npm side.

**Comment by philkunz** [comment]
Still, also for typescript, publishing happens from typescript-bot account. Its true, that they have given unnecessary access to multiple developers though. 
Anyway, I'm going to close this issue as it seems not to be a priority right now.
