### ISSUE TITLE
The type of an event is not propagated to the listener

### ISSUE THREAD

**Issue by Kokujou** [lit/lit#1839]
# Description

I'm currently using LitHtml in Javascript, getting some type safety with JSDoc. 
When i dispatch an event it's properly detected and provides auto complete to me, but when i now add an arrow notation like this:

`<custom-element @custom-event="${(e)=>console.log(e)}"></custom-element>`

then the e-property has implicitly the any-type. i'm just working with javascript and JSDoc but probably TypeScipt has the same problem, if it is like that. 

the problem is severe, because whenever i just want to pass the custom-event detail to a function and treat it as a simple output, then i always have to manually specify the type of the event. 

I have no idea if this is the right place to state this issue, i hope someone can help me, knows a workaround or can even fix this issue. 

# Steps to Reproduce

1. create any component which dispatches and type of event

2. subscribe tot his event using this code

`<custom-element @custom-event="${(e)=>console.log(e)}"></custom-element>`

the event parameter e will have implicitly the any-type and no type autocomplete or error-checks are enabled

## Expected Results

e should be for native Events of type Event, (KeyboardEvent, ...) or CustomEvent<DetailType> for custom events

## Actual Results

e is of type any

## Browsers Affected

it is no browser-related issue

**Comment by web-padawan** [comment]
Here is the related feature request in `lit-analyzer`: https://github.com/runem/lit-analyzer/issues/143

**Comment by justinfagnani** [comment]
Closing here since it's a lit-analyzer feature.
