### ISSUE TITLE
[all] Registry error when lit element project build with webpack

### ISSUE THREAD

**Issue by bchekuri** [lit/lit#1847]
Use-case: Web component A, B using web component C. Using Webpack we are building two different bundles for web component A and B so that other teams can use A and B independently. 

When we are loading both the bundles into same webpage we are getting registry error for web component C as both A and B bundles are trying execute "customElements.define".

Is there a way we can add some check as below, so that we don't cause the registry error.

if (!customElements.get("test-component")) {
  customElements.define(
    "test-component,
    TestComponent
  );
}

Or is there any other quick suggestions to fix it.

**Comment by justinfagnani** [comment]
Can Webpack not create a shared chunk of the code common to A and B?

**Comment by justinfagnani** [comment]
btw, the code you wrote will work, but you'd still be loading the element definition and all of Lit multiple times. A shared chunk would be much better.

**Comment by bchekuri** [comment]
Thank you @justinfagnani  We will create the shared chunk.

**Comment by kevinpschaaf** [comment]
Closing as shared chunk is the recommended solution.
