### ISSUE TITLE
[reactive-element] ReactiveControllerHost#requestUpdate should have optional args

### ISSUE THREAD

**Issue by bennypowers** [lit/lit#1851]
# Description

https://github.com/lit/lit/blob/0ba0ab472fd8294d604b5ce8bc89569b8c8828bd/packages/reactive-element/src/reactive-controller.ts#L27

`ReactiveControllerHost#requestUpdate` has no arguments, it should take some optional arguments, even `...args: any[]`

# Steps to Reproduce

```ts
import {ReactiveController, ReactiveControllerHost} from 'lit';

class Controller implements ReactiveController {
  constructor(public host: ReactiveControllerHost, private propertyKey: string) {
    this.host.requestUpdate(propertyKey);
  }
  hostConnected() {}
  hostDisconnected() {}
}
```

> TypeScript: Expected 0 arguments, but got 1.

## Live Reproduction Link

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge1JlYWN0aXZlQ29udHJvbGxlciwgUmVhY3RpdmVDb250cm9sbGVySG9zdH0gZnJvbSAnbGl0JztcblxuY2xhc3MgQ29udHJvbGxlciBpbXBsZW1lbnRzIFJlYWN0aXZlQ29udHJvbGxlciB7XG4gIGNvbnN0cnVjdG9yKHB1YmxpYyBob3N0OiBSZWFjdGl2ZUNvbnRyb2xsZXJIb3N0LCBwcml2YXRlIHByb3BlcnR5S2V5OiBzdHJpbmcpIHtcbiAgICB0aGlzLmhvc3QucmVxdWVzdFVwZGF0ZShwcm9wZXJ0eUtleSk7XG4gIH1cbiAgaG9zdENvbm5lY3RlZCgpIHt9XG4gIGhvc3REaXNjb25uZWN0ZWQoKSB7fVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn1d

## Expected Results

No TS error

## Actual Results

> TypeScript: Expected 0 arguments, but got 1.

## Browsers Affected

N/A (type side only)

**Comment by justinfagnani** [comment]
`ReactiveControllerHost#requestUpdate()` is defined to take no arguments: https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-controller.ts#L27

**Comment by bennypowers** [comment]
those are good suggestions, thanks

> requestUpdate() has no arguments because not all hosts could handle those arguments in a reasonable way (not all hosts will have named properties to update)

the current situation though actively prohibits hosts from having any params to `requestUpdate` whatsoever, which is weird because `LitElement#requestUpdate` has params, so users expecting to be able to `this.host.requestUpdate(propertyKey)` won't be able to. Whereas if you allow `...args: any[]` than it's really up to the user to decide.

**Comment by justinfagnani** [comment]
You can type the host as `LitElement` or `ReactiveElement` if you need access to that specific API, but other hosts like for React or Angular won't have anything to do with with the arguments.

**Comment by bennypowers** [comment]
Here's an example of the kinds of issues I'm running in to:

```ts
export class ApolloElement<D extends I.MaybeTDN = I.MaybeTDN, V = I.MaybeVariables<D>>
  extends FASTElement implements ReactiveControllerHost {
  readyToReceiveDocument = false;
  
  $apolloController = new ApolloBehavior(this)
  
  addController(controller: ReactiveController & Behavior): void {
    this.$fastController.addBehaviors([controller]);
  }

  removeController(controller: ReactiveController & Behavior): void {
    this.$fastController.removeBehaviors([controller])
  }

  requestUpdate(name, oldValue): void {
    Observable.notify(this, name);
  }
}
```

> TypeScript: Property 'requestUpdate' in type 'ApolloElement<D, V>' is not assignable to the same property in base type 'ReactiveControllerHost'. Type '(name: any, oldValue: any) => void' is not assignable to type '() => void'.

In this case, I'm the one defining the host API, but the narrow types on `ReactiveControllerHost` prevent that.

Same if I 

```ts
interface ApolloControllerHost extends ReactiveControllerHost {
  requestUpdate(name: string, oldValue: unknown): void
}
```

**Comment by bennypowers** [comment]
Why do I want to do it this way and not with one of your suggestions above?

Because FAST's reactivity model encourages me to move in this direction.

**Comment by justinfagnani** [comment]
This just seems like a different API from ReactiveControllerHost. If you need to pass arguments that plain hosts wouldn't know what to do with, I think you need to extend the ReactiveControllerHost interface and add a new API, exactly like you have done with ApolloControllerHost.

Updating the base interface with `requestUpdate(...args: any[])` doesn't help because one host could interpret `...args: any[]` as `name: string, oldValue: unknown` and another host differently so calls like `requestUpdate(name, oldValue)` could cause errors in another host. We would have to defined some actual contract for `requestUpdate()`, but I wouldn't be comfortable with that being `(name, oldValue)` because there's no requirement that a controller has a name, or a single name, or a value or a single value.

I think the best approach here might be a FAST-specific adapter that stores a name to use:

```ts
class FastControllerHost<T, C extends ReactiveController> implements ReactiveControllerHost {
  fastHost: FASTElement;
  name: string;
  previousValue: T;
  controller: C;
  getValue: (controller: C) => T;
  controllers: Array<ReactiveController>;

  constructor(
      fastHost: FASTElement,
      name: string,
      createController: (host: ReactiveControllerHost) => C,
      getValue: (controller: C) => T) {
    this.fastHost = fastHost;
    this.name = name;
    this.controller = createController(this);
    this.getValue = getValue;
    
    // TODO: Listen to the FASTElement lifecycle and call:
    //   this.controllers.forEach((c) => c.hostUpdate())
    //   this.controllers.forEach((c) => c.hostUpdated())
    //   this.controllers.forEach((c) => c.hostConnected())
    //   this.controllers.forEach((c) => c.hostDisconnected())
  }

  addController(controller: ReactiveController): void {
    controllers.push(controller);
  }

  removeController(controller: ReactiveController & Behavior): void {
    this.controllers.splice(this.controllers.indexOf(controller) >>> 0, 1);
  }

  get updateComplete() {
    // does FAST have a similar Promise? If not, simulate it
  }

  requestUpdate(): void {
    const value = this.getValue(this.controller);
    Observable.notify(host, previousValue);
    this.previousValue = value;
  }
}
const connectController = <T, C extends ReactiveController>(
      fastHost: FASTElement,
      name: string,
      createController: (host: ReactiveControllerHost) => ReactiveController,
      getValue: (controller: C) => T) => new FastControllerHost<T>(fastHost, name, createController, getValue)

class MyElement extends FASTElement {
  private fooController = connectController(this, 'hostFoo', (host) => new FooController(host), (c) => c.foo);
}
```

This is very similar to our `useController()` adapter for React with the addition of a name and previous value.

**Comment by bennypowers** [comment]
Sometimes the solution sits there right in front of your eyes for weeks.

I solved my instigating issue by (ready for this?) making the `name` and `oldValue` params to my `BaseClass extends ReactiveElement` optional. For the want of two `?` I wrestled with the compiler 🤷
