### ISSUE TITLE
[lit-element] Investigate possible startup performance regression

### ISSUE THREAD

**Issue by e111077** [lit/lit#1855]
## Description

Script bootup time is seemingly slower in Lit 2 than Lit 1 in the js-framework-benchmark [public benchmarks](https://rawgit.com/krausest/js-framework-benchmark/master/webdriver-ts-results/table.html). Everything else seems to be a progression but this one consistently returns as a regression.

Implementation can be found [here](https://github.com/krausest/js-framework-benchmark/tree/master/frameworks/keyed/lit).

| BEFORE | AFTER |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/5981958/117346781-1310ed00-ae5d-11eb-9263-52670685e99d.png) | ![image](https://user-images.githubusercontent.com/5981958/117346855-2c199e00-ae5d-11eb-867f-c6201521c382.png) |

We should:

* determine whether this is an actual regression
* determine whether this is an issue with the benchmark

## Acceptance criteria

We can reproduce these results and set action items to fix either our code or the benchmark

**Comment by zandaqo** [comment]
Not too familiar with the benchmark, but I can't help noticing that Lit 2 implementation [loads](https://github.com/krausest/js-framework-benchmark/blob/d82527f42e08168ac2f9052e3adc1423f55e812e/frameworks/keyed/lit/index.html#L7) webcomponents polyfill from the network unlike lit-html (and all other frameworks I checked) that only load local scripts.

**Comment by e111077** [comment]
FWIW, looking at the git blame, the previous implementation of the benchmark also loaded the polyfill

**Comment by justinfagnani** [comment]
ah, I think both should not load the polyfill for this benchmark.

**Comment by AndrewJakubowicz** [comment]
I'm not able to close this issue -- but I think we can close it.

[Updated results here](https://krausest.github.io/js-framework-benchmark/current.html)

And screenshot for ease. Removing the polyfill has improved the other startup metrics.

![image](https://user-images.githubusercontent.com/15080861/119238517-938b4b00-baf7-11eb-8321-8f38f83a6ae1.png)
