### ISSUE TITLE
[lit-html] Provide a PropertyPart type

### ISSUE THREAD

**Issue by e111077** [lit/lit#1863]
## Description

- Who wants the functionality
  - People who write directives
- What it is they want
	- A PropertyPart type
- Why they want it
	- PartInfo has a PartInfo.PROPERTY entry
	- Semantically it doesn't make sense that the types don't export a PropertyPart even if it's an alias of AttributePart
- Functional description of task/subtask
	- `export type PropertyPart = AttributePart`

## Acceptance criteria

A `PropertyPart` is importable from `lit-html/directive.js`

**Comment by justinfagnani** [comment]
This was fixed a while back.
