### ISSUE TITLE
TypeScript declarations missing from npm (@lit-labs/motion)

### ISSUE THREAD

**Issue by hersing** [lit/lit#1866]
There are no `d.ts` files when installing `@lit-labs/motion` from `npm` making `TypeScript` pretty mad.
Should be an easy fix in your package.json or tsconfig, hope to be able to play with it soon 😊 
<img width="395" alt="Skærmbillede 2021-05-08 kl  21 19 54" src="https://user-images.githubusercontent.com/6490650/117550907-2aa9ca80-b043-11eb-892c-b7600af230bb.png">

**Comment by kevinpschaaf** [comment]
Should be fixed by https://github.com/lit/lit/pull/2186.
