### ISSUE TITLE
[reactive-element] Add a dev-mode properties object for easy inspection

### ISSUE THREAD

**Issue by e111077** [lit/lit#1875]
## Description

- Who wants the functionality
  - people debugging lit in dev mode
- What it is they want
  - A way to easily see the values of reactive properties
- Why they want it
  - Chrome prop inspector mixes HTMLElement's native properties with those of the reactive properties and it's hard to fish them out as they are alphabetical
- Functional description of task/subtask
  - in Lit dev mode perhaps add a `this.__dev__.reactiveProps` that has an object that mirrors the reactive props

## Acceptance criteria

A dev mode feature has been made that acknowledges the DX of inspecting reactive properties in some way or form.

**Comment by e111077** [comment]
this is super low pri. Just a nicety

**Comment by justinfagnani** [comment]
I think we're unlikely to get to something like this and should lobby DevTools to show properties by prototype again, or make a DevTools extension again.
