### ISSUE TITLE
[localize] XLIFF serializer should update instead of replace

### ISSUE THREAD

**Issue by aomarks** [lit/lit#1879]
When we write out XLIFF XML files after extraction, we always generate a completely fresh XML document from our internal data model.

However, this means any extra XLIFF nodes/attributes that may have been added to the document by the translation process (e.g. `state="needs-translation"`) but that isn't part of our internal data model will be lost.

So, when there is an existing XLIFF document, we should update it rather than replace it to preserve these external changes.

**Comment by enqueue** [comment]
I could try and give this one a go, if that is OK for you. Do you have any hints or remarks before I try myself at a PR? This is what I have in mind:

1. In or around [XliffFormatter.encodeLocale](https://github.com/lit/lit/blob/0260a15e2087d2b1ea8f5072663a637cedd186d9/packages/localize-tools/src/formatters/xliff.ts#L195) try to load existing file (again...), build a map by `trans-unit` id attributes.
2. If file does not exist, initialize new document with basic elements (will be written later).
3. For each name
* Get or create `trans-unit` for name.
* `Translation` exists for name? Get or create `target` in `trans-unit`, add/replace element content with `translation`. Option 1: Always create `target` element without content or with source content. Option 2: Do not alter element content when `target` state is one of _x_, _y_,...
* `desc` exists for name? Get or create `note` in `trans-unit`, add/replace element content with `desc`. Do _not_ remove obsolete `note` elements.
4. Delete each `trans-unit` that has an `id` that does not correspond with a `name` in our set of messages, i.e. remove obsolete translations.

**Comment by aomarks** [comment]
Hi @enqueue! A PR for this would be great if you wanted to take a shot! Your proposal sounds about right to me. Basically I think if there's no existing XML file we should do what we do already, but if there is an existing XML file we should preserve it as much as possible, and only mutate the specific nodes that changing.
