### ISSUE TITLE
[lit-html] Precompiling Templates

### ISSUE THREAD

**Issue by jridgewell** [lit/lit#189]
Related to https://github.com/PolymerLabs/lit-html/issues/187, I'm opening this so we can discuss how to precompile templates.

The general idea is how do we take creating a `Template` instance out of the first-render load time. Ie, make this [new](https://github.com/PolymerLabs/lit-html/blob/1eb0baf/src/lit-html.ts#L55) disappear, taking [all of this](https://github.com/PolymerLabs/lit-html/blob/1eb0baf/src/lit-html.ts#L184-L347) (163 lines of very slow code!) out of the first render.

I think we can manage to precompile these in a build step, making a file instantiate `Templates` with the correct `TemplateStringsArray` and already instantiated `TemplatePart`s  (with the correct indexes). We might need to expose the `templateCache` externally.

**Comment by RayBenefield** [comment]
👍 

This would be awesome for what I'm working on as well. I've been using https://www.npmjs.com/package/es6-template-strings as an intermediary to setup a templating system with individual files as templates loaded in instead of baked into the JS files to enable designers similar to templating engines in full stack frameworks like Django/Laravel/Rails, using raw ES6. Something that takes a stringified form of an ES6 template would be huge in cutting that out of my pipeline.

**Comment by jridgewell** [comment]
So what I'm imagining is:

```js
// templates/hello-world.js
import { html } from 'lit-html';

export function hello(name) {
  return html`<div>
    ${name}
  </div>`;
}
```

Would be transformed into:
```js
import { html, templateCache, Template } from 'lit-html';

const template = new Template([], false);

function precompiled(array, values) {
  template.element.innerHTML = interpolate(array, values);
  template.parts = [
    new TemplatePart('node', 2),
  ];
  templateCache.put(array, template);
};
precompiled`<div>
    ${<!--marker-->}
  </div>`;

export function hello(name) {
  return html`<div>
    ${name}
  </div>`;
}
```

Maybe even:

```js
import { Template, TemplateResult } from 'lit-html';

// Imagine if Template's constructor was split into a separate method
// and instead was simple.
const template = new Template();

const strings = [`<div>
    `, `
  </div>`];
template.element.innerHTML = interpolate(strings, ['<!--marker-->']);
template.parts = [
  new TemplatePart('node', 2),
];

export function hello(name) {
  return new TemplateResult(template, [name]);
}
```

**Comment by lukechu10** [comment]
Has there been any progress on this? The last message was over 2 years ago!

**Comment by justinfagnani** [comment]
@lukechu10 Nothing so far. We would have updated the issue if something was happening here. Do you need this feature for some reason?

**Comment by lukechu10** [comment]
One advantage this would bring is that we can strip out all the tabs in the template to minify it without any external tools.

**Comment by vicb** [comment]
@justinfagnani 
- do you think that this could give an interesting perf boost (by not having to parse html at runtime) ? 
- do you anticipate any road blocks ?

**Comment by justinfagnani** [comment]
We have a new `CompiledTemplateResult` type with tests for hand-compiled templates, and a prototype transform. There is a very nice first-render performance boost from compilation. We'll continue to work on the transform.

**Comment by vicb** [comment]
I saw that in next, great job 👍

**Comment by DemiusAcademius** [comment]
Do you have any plans for compile templates at build time in the future?

**Comment by justinfagnani** [comment]
Closing as completed. We have a `@lit-labs/compiler` package await initial release now!
