### ISSUE TITLE
[reactive-element] Revert css`` return type to CSSResult

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#1894]
We have a few too many users accessing `cssText` on the result of the `css` tag. The change to returning CSSResultGroup was intended to prevent TypeScript from narrowing the type of `static styles` and make subclassing easier, but this might not be panning out how we intended. It seems more pragmatic to roll back this change for now.

In the future we may want to deprecate `.cssText` and prepare for a time when `css` can return a CSSStyleSheet directly.

**Comment by sorvell** [comment]
Let's add to the docs that users can explicitly type `static styles: CSSResultGroup = ...` so that the type does not auto-narrow and subclassers can then still use either an array or single style.
