### ISSUE TITLE
My disable button won't re-enable

### ISSUE THREAD

**Issue by elvinckoay** [lit/lit#1895]
![image](https://user-images.githubusercontent.com/13036974/118180324-3ef71a00-b3eb-11eb-854b-e455d68c1e35.png)

![image](https://user-images.githubusercontent.com/13036974/118180206-22f37880-b3eb-11eb-9f3c-75e70abffd0f.png)

I got something like this going on. I am unsure why my button stays disabled

**Comment by aomarks** [comment]
If the button has the `disabled` attribute set, then a `click` event won't be dispatched on it.

**Comment by matheus-garcia** [comment]
> If the button has the `disabled` attribute set, then a `click` event won't be dispatched on it.

Hello Alexander, I have that EXACTLY problem right now, I have a custom button component that is **disabled**, but **(click)** event still fires on clicking, don't know exactly what to do to fix that.

**Comment by sorvell** [comment]
Closing based on @aomarks's explanation. Please open a new issue if there's any remaining problem. Thanks!
