### ISSUE TITLE
[localize] error in generated templates with multiple placeholder

### ISSUE THREAD

**Issue by jlesquembre** [lit/lit#1896]
# Description

Generated files (with `lit-localize extract/build`) are mixing the placeholders in the template

# Steps to Reproduce

1. Given this template:

```ts
  render() {
    return msg(html`
      <h1>Hello, ${this.name} ${this.surname}!</h1>
      <div>Current language: ${this.lang}</div>
      <button @click=${this._toogleLang} part="button">Toogle language</button>
      <slot></slot>
    `);
```
[source](https://github.com/jlesquembre/lit-element-localize-issue/blob/4121a6805e69d00ada87a73e95df6ad94490cda5/src/my-element.ts#L43-L49)

2. Those files are generated:
 
```xml
  <source>
      <ph id="0">&lt;h1></ph>Hello, <ph id="1">${this.name} ${this.surname}</ph>!<ph id="2">&lt;/h1>
      &lt;div></ph>Current language: <ph id="3">${this.lang}&lt;/div>
      &lt;button @click="${this._toogleLang}" part="button"></ph>Toogle language<ph id="4">&lt;/button>
      &lt;slot>&lt;/slot>
    </ph></source>
```
[source](https://github.com/jlesquembre/lit-element-localize-issue/blob/4121a6805e69d00ada87a73e95df6ad94490cda5/xliff/es.xlf#L6-L11)

```ts
    export const templates = {
      'hee42ce2388b5d52a': html`
      <h1>Hola, ${1} ${1}!</h1>
      <div>Idioma: ${3}</div>
      <button @click="${3}" part="button">Cambiar idioma</button>
      <slot></slot>
    `,
```
[source](https://github.com/jlesquembre/lit-element-localize-issue/blob/4121a6805e69d00ada87a73e95df6ad94490cda5/src/locales/es.ts#L11-L17)

Full code is here: https://github.com/jlesquembre/lit-element-localize-issue (I took [lit-element-starter-ts](https://github.com/PolymerLabs/lit-element-starter-ts) as a starting point)

You can run `npm run i18n:extract` and `npm run i18n:build` to regenerate the locale files, and `npm run build`, `npm run serve` to serve the site at http://localhost:8000/dev

## Expected Results

I expect to see `Hola John Doe!` if I select the `es` locale.

## Actual Results

I see `Hola Doe Doe!`

## Browsers Affected

I only tested it with Chrome, but I guess all browsers are affected

**Comment by aomarks** [comment]
Thanks for the report! Reproduced and identified the bug, should have a fix later today.

**Comment by aomarks** [comment]
Will be fixed once https://github.com/lit/lit/issues/1896 lands and published (hopefully in next day or two).

**Comment by jlesquembre** [comment]
thanks, @aomarks ! I'll test again once is published

**Comment by aomarks** [comment]
Hi @jlesquembre the fix is published as `@lit/localize@0.3.3`

**Comment by jlesquembre** [comment]
Thanks @aomarks. 
I think you should do a new release for `@lit/localize` too. With the latest npm version, `lit-localize` fails with the error `Cannot find module '..../@lit/localize/internal/id-generation.js'`.
But thanks a lot for the quick fix :)

**Comment by aomarks** [comment]
> Thanks @aomarks.
> I think you should do a new release for `@lit/localize` too. With the latest npm version, `lit-localize` CLI fails with the error `Cannot find module '..../@lit/localize/internal/id-generation.js'`.
> But thanks a lot for the quick fix :)

Oops good point, there was a refactoring I forgot to account for. New releases are out.

**Comment by jlesquembre** [comment]
Thanks @aomarks , I just did some tests, and all looks good :+1:
