### ISSUE TITLE
asynchrounous cleanup logic (via update cycle) after disconnectedCallback

### ISSUE THREAD

**Issue by tlouisse** [lit/lit#1901]
# Description

In lit v1, it was possible to execute cleanup logic in the `updated` callback

# Steps to Reproduce

```js
import { html, LitElement } from 'https://jspm.dev/lit'; 

export class CleanupOnDisconnect extends LitElement {
  static properties = {
    cleanup: String,
  }

  render() {
    return html`<button @click="${this._disconnectMe}">disconnect me</button>`;
  }

  _disconnectMe() {
    this.parentNode.removeChild(this);
  }

  disconnectedCallback() {
    super.disconnectedCallback();

    alert("disconnected callback");
    // This should trigger alert below
    this.cleanup = 'disconnect';
  }

  updated(changedProperties) {
    super.updated(changedProperties);
    alert("updated callback");

    if (changedProperties.has('cleanup')) {
      alert('here I would cleanup');
    }
  }
}

customElements.define("cleanup-on-disconnect", CleanupOnDisconnect);
```

2. See this output...

https://webcomponents.dev/edit/5azQOVGqRu230uejg5Tc/src/index.js

## Expected Results

When pressing the button: in lit v1, I would see the alert with text 'updated callback', followed by 'here I would cleanup'.

## Actual Results

In lit v2, I don't see any of those, because the `updated` callback is not executed anymore. 

Question is if this is on purpose and cleanup logic should be performed synchronously?
It would be convenient (especially for more generic logic) if  one update cycle would be performed after disconnected.

**Comment by justinfagnani** [comment]
This is an intended breaking change: the update lifecycle now only runs while connected. This was necessary to implement disconnectable async directive correctly.

Our recommendation is to do cleanup work in `disconnectedCallback()`. If you also need to do some cleanup while connected, I would factor the cleanup into a separate method and call it from both `disconnectedCallback()` and `update()`.

I'm also curious if a reactive property is the best way to trigger a cleanup, vs a method like `this.cleanup()`.

**Comment by tlouisse** [comment]
Ok, thanks for the feedback!

A concrete use case where we need it (we probably have more similar examples): 
- we have a form field that can have an array of node references for aria-describedby and aria-labelledby (via methode `addToAriaLabel()` that will be called multiple times within one update cycle
- when the array of node references changes, it needs to rearrange them based on DOM order and some other criterua. For performance reasons, we only want to do the rearrangement once (and after that reflection to aria-labelledby happens)

On disconnect, we need to remove all node references that the form field doesn't 'own':
- we synchronously update the array in disconnectedCallback, but the async ordering + attr reflection won't happen anymore.

Summarized: we batch multiple requests for performance.

Would it maybe be possible to access the pending changedProperties in disconnectedCallback?
Smth like this pseudo code:

```js
disconnectedCallback() {
  // get scheduled changedProperties and call update / updated ?
  super.disconnectedCallback();
}
```

**Comment by justinfagnani** [comment]
I wouldn't recommend calling `update()` directly as that could mess up the state of any async directives. That's why we don't do that internally.

Why does the field need to update its ordering when disconnected, if it has cleared out references to the labeledby nodes?

One option here might be to do your own batching. The core technique we use in ReactiveElement is fairly straightforward:

```ts
class MyElement extends LitElement {
  private _reorderLabelsPending = false;
  
  async addToAriaLabel(n: Node) {
    this._storeLabel(n);
    if (this._reorderLabelsPending) {
      return;
    }
    this._reorderLabelsPending = true;
    await 0;
    this._reorderLabelsPending = false;
    this._doLabelReordering();
  }
}
```

**Comment by tlouisse** [comment]
The ordering would most likely not be affected when removing in this particular case indeed, but it would be nice to have a generic strategy for similar cases :)

Your example will help with finding such a strategy. Thanks for your help 👍
