### ISSUE TITLE
A way to extract component properties in Typescript

### ISSUE THREAD

**Issue by yannbf** [lit/lit#1902]
Hey 👋  Thanks for this awesome project!

At Storybook we provide types for frameworks that we support, and we have a type `Story` which looks a bit like this:

```ts
type Story<Args> {
  args: Args
 // other properties
}
```

supposedly a button type that has two properties `{ label: string; primary: boolean }`, one could use the type like this:

```ts
const template: Story<{ label: string; primary: boolean }>;
template.args = {
  // will autocomplete and validate label and primary properties
}
```

When using Storybook with lit, I was hoping that it would be possible to automatically extract properties from a `LitElement` instance, the ones defined via `@property` decorator, so that this would be possible:

```ts
class MyButton extends LitElement {
  @property({ type: String }) label: string
  // ...
}

const template: Story<MyButton>;
template.args = {
  // will autocomplete and validate label and primary properties
}
```

Is there any available mechanism for this already? Or plans to implement as such? 
Thank you!

**Comment by Westbrook** [comment]
In the context of Storybook, it would be great if a "lit" version (if such a thing were needed) were to follow in the footsteps of the "web components" version and support this sort of data via a [Custom Elements Manifest](https://github.com/webcomponents/custom-elements-manifest), this being the next version of the `custom-elements.json` file that the "web components" version of Storybook already supports. This would allow developers leveraging this version (or the next version of a "web components" general version of Storybook) to be able to surface attributes, properties, events, css custom properties, etc. no matter what technology (be it `lit` or something else) with which they developed the custom elements found in their project. This would further allow then to focus making the right technical decisions to ensure those custom elements best support the use cases they mean to solve for without feeling the need to split up their project or short change specific parts of their project in support of the Storybook build they leveraged in ways that were not beneficial to their teams and their consumers.

**Comment by justinfagnani** [comment]
Tools really shouldn't consider `@property` to be that special. Relevant properties on an element could be plain class fields, getters and setters, or provided with the static properties block.

I think the element type itself is the best type to use, since reflecting properties like `id`, `tabIndex`, `className` could be observed and used by an element, but if including all of HTMLElement is to much for your tastes, you can omit those properties, like:

```ts
class MyElement extends HTMLElement {
  foo?: number;
}

type MyElementOnly = Omit<MyElement, keyof HTMLElement>;
const template: Story<MyElementOnly>;
```

**Comment by nicolejadeyee** [comment]
Hi @yannbf, closing this issue. please re-open if you are still facing this.
