### ISSUE TITLE
[lit-html] Use `WeakRef` + `FinalizationRegistry` to implement repeat directive

### ISSUE THREAD

**Issue by mantou132** [lit/lit#1905]
We can use the key value to accurately find the updated content without using defective algorithms.

**Comment by justinfagnani** [comment]
WeakRef is not polyfillable and not available in IE11. Like Proxy, it's not something that we can use until we completely drop IE11 support.

**Comment by sorvell** [comment]
Closing based on previous comment.

**Comment by jrencz** [comment]
I just bumped into this one looking for answer if lit uses `FinalizationRegistry` and since 3.0 dropped IE11 support maybe this idea should be revisited?

**Comment by justinfagnani** [comment]
@jrencz Yes, we could potentially use WeakRef now, depending on other niche browser support.

I don't think this issue put forward a reason to do so, however.
