### ISSUE TITLE
Applying styles to all instances of an element after instantiation.

### ISSUE THREAD

**Issue by tmstn** [lit/lit#1913]
I have the following custom event handler where `flyout` is the lit element class definition. The new styles are successfully attached to the static array but the styles are not applied to the existing `flyout` elements or newly created `flyout` elements..

```typescript
app.events.add(eventType.settingsloaded, () => {
  const settings = app.settings.getSync();
  if (settings === undefined) {
    return;
  }
  flyout.styles.push(css`
    .header {
      background-color: ${unsafeCSS(settings.widget_background_color)};
      color: ${unsafeCSS(settings.widget_foreground_color)};
    }
  `);
});
```

**Comment by sorvell** [comment]
This is a bit uncharted territory and it's made a bit harder by inconsistent support for the underlying `adoptedStylesheets` feature on Shadow DOM.

Here's [an example](https://lit.dev/playground/#project=W3sibmFtZSI6Im15LWVsZW1lbnQudHMiLCJjb250ZW50IjoiaW1wb3J0IHtMaXRFbGVtZW50LCBodG1sLCBjc3MsIGFkb3B0U3R5bGVzLCBDU1NSZXN1bHR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbmNvbnN0IHN0eWxlZEVsZW1lbnRzOiBXZWFrTWFwPHR5cGVvZiBMaXRFbGVtZW50LCBTZXQ8TGl0RWxlbWVudD4-ID0gbmV3IE1hcCgpO1xuY29uc3QgdHJhY2tFbGVtZW50ID0gKGVsOiBMaXRFbGVtZW50KSA9PiB7XG4gIGNvbnN0IGN0b3IgPSBlbC5jb25zdHJ1Y3RvciBhcyB0eXBlb2YgTGl0RWxlbWVudDtcbiAgbGV0IGVscyA9IHN0eWxlZEVsZW1lbnRzLmdldChjdG9yKTtcbiAgaWYgKGVscyA9PT0gdW5kZWZpbmVkKSB7XG4gICAgc3R5bGVkRWxlbWVudHMuc2V0KGN0b3IsIChlbHMgPSBuZXcgU2V0KCkpKTtcbiAgfVxuICBlbHMuYWRkKGVsKTtcbn1cbmNvbnN0IGFkZFN0eWxlc1RvQWxsRWxlbWVudHMgPSAoZWw6IExpdEVsZW1lbnQsIHN0eWxlOiBDU1NSZXN1bHQpID0-IHtcbiAgLy8gYWRkIHN0eWxlIHRvIHN1YnNlcXVlbnRseSBjcmVhdGVkIGVsZW1lbnRzIG9mIHRoaXMgdHlwZS5cbiAgY29uc3QgY3RvciA9IChlbC5jb25zdHJ1Y3RvciBhcyB0eXBlb2YgTGl0RWxlbWVudCk7XG4gIGN0b3IuZWxlbWVudFN0eWxlcy5wdXNoKHN0eWxlKTtcbiAgLy8gQWRkIHN0eWxlcyB0byBhbGwgZXhpc3RpbmcgZWxlbWVudHMgb2YgdHlwZVxuICAvLyBOb3RlOiB3aXRoIHBsYXRmb3JtIHN1cHBvcnQgZm9yIGBhZG9wdGVkU3R5bGVzaGVldHNgLCB5b3UgY291bGQgc2ltcGx5XG4gIC8vIG1vZGlneSBvbmUgb2YgdGhlIHN0eWxlcyBpbiBgYWRvcHRlZFN0eWxlc2hlZXRzYCBhbmQgaXQgd291bGQgYmUgY2hhbmdlZFxuICAvLyBpbiBhbGwgaW5zdGFuY2VzLlxuICBjb25zdCBlbHMgPSBzdHlsZWRFbGVtZW50cy5nZXQoZWwuY29uc3RydWN0b3IgYXMgdHlwZW9mIExpdEVsZW1lbnQpO1xuICBmb3IgKGxldCBlIG9mIGVscykge1xuICAgIGFkb3B0U3R5bGVzKGUucmVuZGVyUm9vdCBhcyBTaGFkb3dSb290LCBjdG9yLmVsZW1lbnRTdHlsZXMpO1xuICB9XG59XG5cbmNvbnN0IGdldENvbG9yVmFsdWUgPSAoKSA9PiBNYXRoLnRydW5jKE1hdGgucmFuZG9tKCkgKiAyNTUpO1xuXG5AY3VzdG9tRWxlbWVudChcIm15LWVsZW1lbnRcIilcbmV4cG9ydCBjbGFzcyBNeUVsZW1lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgLy8gU3R5bGVzIGFyZSBzY29wZWQgdG8gdGhpcyBlbGVtZW50OiB0aGV5IHdvbid0IGNvbmZsaWN0IHdpdGggc3R5bGVzXG4gIC8vIG9uIHRoZSBtYWluIHBhZ2Ugb3IgaW4gb3RoZXIgY29tcG9uZW50cy4gU3R5bGluZyBBUEkgY2FuIGJlIGV4cG9zZWRcbiAgLy8gdmlhIENTUyBjdXN0b20gcHJvcGVydGllcy5cbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICA6aG9zdCB7XG4gICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgICBwYWRkaW5nOiAxMHB4O1xuICAgICAgYmFja2dyb3VuZDogbGlnaHRncmF5O1xuICAgIH1cbiAgICAucGxhbmV0IHtcbiAgICAgIGNvbG9yOiB2YXIoLS1wbGFuZXQtY29sb3IsIGJsdWUpO1xuICAgIH1cbiAgYDtcblxuXG4gIC8vIERlZmluZSByZWFjdGl2ZSBwcm9wZXJ0aWVzLS11cGRhdGluZyBhIHJlYWN0aXZlIHByb3BlcnR5IGNhdXNlc1xuICAvLyB0aGUgY29tcG9uZW50IHRvIHVwZGF0ZS5cbiAgQHByb3BlcnR5KCkgZ3JlZXRpbmcgPSBcIkhlbGxvXCI7XG4gIEBwcm9wZXJ0eSgpIHBsYW5ldCA9IFwiV29ybGRcIjtcbiAgXG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKCk7XG4gICAgdHJhY2tFbGVtZW50KHRoaXMpO1xuICB9XG5cbiAgLy8gVGhlIHJlbmRlcigpIG1ldGhvZCBpcyBjYWxsZWQgYW55IHRpbWUgcmVhY3RpdmUgcHJvcGVydGllcyBjaGFuZ2UuXG4gIC8vIFJldHVybiBIVE1MIGluIGEgc3RyaW5nIHRlbXBsYXRlIGxpdGVyYWwgdGFnZ2VkIHdpdGggdGhlIGBodG1sYFxuICAvLyB0YWcgZnVuY3Rpb24gdG8gZGVzY3JpYmUgdGhlIGNvbXBvbmVudCdzIGludGVybmFsIERPTS5cbiAgLy8gRXhwcmVzc2lvbnMgY2FuIHNldCBhdHRyaWJ1dGUgdmFsdWVzLCBwcm9lcHJ0eSB2YWx1ZXMsIGV2ZW50IGhhbmRsZXJzLFxuICAvLyBhbmQgY2hpbGQgbm9kZXMvdGV4dC5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPHNwYW4gQGNsaWNrPSR7dGhpcy50b2dnbGVQbGFuZXR9XG4gICAgICAgID48c3BhbiBjbGFzcz1cImdyZWV0aW5nXCI-JHt0aGlzLmdyZWV0aW5nfTwvc3Bhbj5cbiAgICAgICAgPHNwYW4gY2xhc3M9XCJwbGFuZXRcIj4ke3RoaXMucGxhbmV0fTwvc3Bhbj5cbiAgICAgIDwvc3Bhbj5cbiAgICBgO1xuICB9XG5cbiAgLy8gRXZlbnQgaGFuZGxlcnMgY2FuIHVwZGF0ZSB0aGUgc3RhdGUgb2YgQHByb3BlcnRpZXMgb24gdGhlIGVsZW1lbnRcbiAgLy8gaW5zdGFuY2UsIGNhdXNpbmcgaXQgdG8gcmUtcmVuZGVyXG4gIHRvZ2dsZVBsYW5ldCgpIHtcbiAgICB0aGlzLnBsYW5ldCA9IHRoaXMucGxhbmV0ID09PSBcIldvcmxkXCIgPyBcIk1hcnNcIiA6IFwiV29ybGRcIjtcbiAgICB0aGlzLmFkZFN0eWxlcygpO1xuICB9XG4gIFxuICBhZGRTdHlsZXMoKSB7XG4gICAgY29uc3Qgc3R5bGUgPSBjc3NgLmdyZWV0aW5nIHtcbiAgICAgIGNvbG9yOiByZ2IoJHtnZXRDb2xvclZhbHVlKCl9LCBcbiAgICAgICR7Z2V0Q29sb3JWYWx1ZSgpfSxcbiAgICAgICR7Z2V0Q29sb3JWYWx1ZSgpfSk7XG4gICAgfWAgYXMgQ1NTUmVzdWx0O1xuICAgIGFkZFN0eWxlc1RvQWxsRWxlbWVudHModGhpcywgc3R5bGUpO1xuICAgIGNvbnN0IGUgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KHRoaXMubG9jYWxOYW1lKTtcbiAgICB0aGlzLnBhcmVudE5vZGUuYXBwZW5kQ2hpbGQoZSk7XG4gIH1cbiAgICBcbn0ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbXktZWxlbWVudC5qc1wiPjwvc2NyaXB0PlxuICA8c3R5bGU-XG4gICAgLm1hcnMge1xuICAgICAgLS1wbGFuZXQtY29sb3I6IHJlZDtcbiAgICB9XG4gIDwvc3R5bGU-XG48L2hlYWQ-XG48Ym9keT5cbiAgPG15LWVsZW1lbnQ-PC9teS1lbGVtZW50PlxuPC9ib2R5PlxuIn1d) that shows you you can do something like this.

The interesting bits:
* The `static styles` property is processed once via `finalizeStyles` and becomes the `static elementStyles` property. So if you want to dynamically change the styles that new elements use, you can modify `static elementStyles`.
* To alter styles for an existing element, you can import `adoptStyles` and call `adoptStyles(this.shadowRoot, this.constructor.elementStyles)` after modifying `static elementStyles`.
* This will alter the existing instance and any subsequently created instances, however, it will not style any previously created instances. With consistent browser support (or a proper polyfill) for `adoptedStylesheets`, you could modify one of the styles in the `adoptedStylesheets` array and it would auto-apply to any existing instances; however, only Chrome currently support this and we do not have a proper polyfill. Instead the example implements some basic element tracking to accomplish something similar.

Note, the example just adds a new style with a random color on every click. This is just a sample and not a great way to do something like this.

Hope that helps.

**Comment by tmstn** [comment]
Thanks so much, that helps a lot!
