### ISSUE TITLE
Decorators + class fields do not work in certain babel setups

### ISSUE THREAD

**Issue by e111077** [lit/lit#1914]
# Description

In certain babel environments such as the default ones for snowpack's lit template and codesandbox's React setup, the `@property` and `@state` decorators break when supplied an initial value.

This becomes a problem in codesandbox where it's difficult to adjust the babel config.

In Snowpack, even our recommended babel setup doesn't work

# Steps to Reproduce

## Snowpack

1. set up a snowpack TS setup
2. create a TS component with a public property
3. change the public property on the element
4. observe it not change

example: glitch link [here](go [here](https://glitch.com/edit/#!/auspicious-handsomely-scabiosa?path=public%2Findex.html%3A1%3A0)) click the button to reverse text

## Codesandbox

1. set up a React TS setup
2. Crete a TS component with a public property
3. change the public property on the element
4. observe it not change

example: codesandbox link [here](https://codesandbox.io/s/modern-platform-4ecxu?file=/src/App.tsx) click the button to reverse text

## Expected Results

`requestUpdate` should be called on property set

## Actual Results

`requestUpdate` is not called on property set because babel is setting the class members with Object.defineProperty

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by sorvell** [comment]
Here's a [working Glitch example](https://glitch.com/edit/#!/peat-valley-coral?path=src%2Findex.ts%3A5%3A42).

It's important to use these Babel settings:

```
"plugins": [
    ["@babel/plugin-transform-typescript", {"allowDeclareFields": true}],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", {"loose": true}]
  ]
 ```

In addition, a class field cannot be used when using `static properties`.

**Comment by e111077** [comment]
> In addition, a class field cannot be used when using `static properties`.

Why's that? Transform doesn't like it?

**Comment by sorvell** [comment]
Babel is pretty opaque but just doesn't support it. It's documented: https://lit.dev/docs/components/decorators/#avoiding-issues-with-class-fields

**Comment by kevinpschaaf** [comment]
@e111077 is this still an issue even with the recommended babel setup? Is there work we can/should do on this?
