### ISSUE TITLE
Entire attribute content is cleared if any value in an `AttributePart` is `nothing`

### ISSUE THREAD

**Issue by bicknellr** [lit/lit#1921]
# Description

lit-html: `2.0.0-rc.3`
lit-element: `3.0.0-rc.2`

If any of the potentially many expressions used to render an `AttributePart` is `nothing`, then the attribute is removed entirely. This is true both when there is additional string content for the attribute written directly in the template and when there are multiple expressions used in a single attribute, some of which are a non-`nothing` value.

# Steps to Reproduce

1. Write this code

```ts
import {html, render, nothing} from 'lit';

render(html`
  <style>
    [attr~=abc] {
      color: red;
    }
  </style>
  <div attr="abc ${nothing}">
    This text should be red.
  </div>
  <div attr="${"abc"} ${nothing}">
    This text should also be red.
  </div>
`, document.body);
```

2. See this output...

All of the text is rendered with the initial color.

## Live Reproduction Link

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIHJlbmRlciwgbm90aGluZ30gZnJvbSAnbGl0JztcblxucmVuZGVyKGh0bWxgXG4gIDxzdHlsZT5cbiAgICBbYXR0cn49YWJjXSB7XG4gICAgICBjb2xvcjogcmVkO1xuICAgIH1cbiAgPC9zdHlsZT5cbiAgPGRpdiBhdHRyPVwiYWJjICR7bm90aGluZ31cIj5cbiAgICBUaGlzIHRleHQgc2hvdWxkIGJlIHJlZC5cbiAgPC9kaXY-XG4gIDxkaXYgYXR0cj1cIiR7XCJhYmNcIn0gJHtub3RoaW5nfVwiPlxuICAgIFRoaXMgdGV4dCBzaG91bGQgYWxzbyBiZSByZWQuXG4gIDwvZGl2PlxuYCwgZG9jdW1lbnQuYm9keSk7In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifV0

## Expected Results

The text is red.

## Actual Results

The text is not red.

**Comment by justinfagnani** [comment]
This was an intentional change to make `ifDefined()` declarative and SSR'able.

**Comment by justinfagnani** [comment]
This is unfortunately not listed in lit-html minor breaking changes: https://lit.dev/docs/releases/upgrade/#lit-html We should fix that

**Comment by justinfagnani** [comment]
Closing as WAI, even though we need to document this.
