### ISSUE TITLE
Allow Javascript users to invoke decorators

### ISSUE THREAD

**Issue by sorvell** [lit/lit#1924]
## Description

Users who want a tool-free experience using Lit currently do not have a good way to use decorators. Eventually, when decorators are platform supported, this issue will be resolved, but in the meantime, these users cannot take advantage of decorators. While it is possible to manually invoke a decorator, the syntax is awkward: `property({type: Boolean})(MyClass.prototype, 'foo')`.

Perhaps `static properties` could be extended to support using decorators to address this.

## Acceptance criteria
Design and implement a solution.

**Comment by justinfagnani** [comment]
Since we document all the vanilla JS equivalents of the decorators, I'm inclined to say that we don't build a way to invoke the decorators outside of decorator syntax. I'd keep the usage pattern we have now and aim for convergence when standard decorators land in JS.
