### ISSUE TITLE
Uncaught TypeError: this.L.has is not a function

### ISSUE THREAD

**Issue by herberthobregon** [lit/lit#1925]
# Description

If I define L property gets this.L.has is not a function

# Steps to Reproduce

1. Write this code

```ts
import {html, LitElement} from 'lit';
class MyElement extends LitElement {
	@property({ type: Array }) L: number[] = [];
}
window.customElements.define('x-el', MyElement);
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-abwsxa

## Expected Results

use L as property, in lit-element@2 I can use it. If is a reserve property of lit, you should a **_ or #**

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
Thanks for the issue! This is an oversight is our renaming code where we do correctly prefix private class fields, and we also have a set of "stable" names that need to be the same across versions, but we don't correctly prefix class fields that also need to be stable.

We need to fix this before stable release.
