### ISSUE TITLE
[labs/ssr] Option to omit `<!--lit-part-->` comments

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [lit/lit#1928]
Hi, I'm evaluating the new SSR capability, and its suitability for replacing `lit-html-server` for various tasks. I'm running a simple test:

```ts
import { render } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js"
import { html } from "lit"

const view = (name: string) => html`<h1>Hello, ${name}</h1>`

const ssrResult = render(view("Tim"))

for (const chunk of ssrResult) {
  console.log(chunk)
}
```

And getting output like:

```html
<!--lit-part iTZS7SiW4tA=-->
<h1>Hello, 
<!--lit-part-->
Tim
<!--/lit-part-->
</h1>
<!--/lit-part-->
```

So far so good. I imagine that the `lit-part` comments are useful for rehydrating server-side rendered templates on the client - which I guess is your main use-case. But I'm also considering other templating uses, such as:

* static site generation
* data-driven HTML email generation
* typical old-school server side app rendering plain HTML templates
* cloud functions providing pre-rendered, non-JS page widgets
* etc...

Now I guess I can add a stage to my tasks to parse out those comments, but I'm just wondering if these are valid use cases for lit-labs/ssr, and if so whether an extra rendering option (perhaps included in the `renderInfo` parameter to render) could indicate that they are not needed and leave them out?

**Comment by kevinpschaaf** [comment]
Yeah, I think we could probably add a render option to omit the hydration markers. 

Thanks for the feature request.

**Comment by tstewart-klaudhaus** [comment]
That's great to hear, thanks.

**Comment by markcellus** [comment]
I'm using lit-ssr to render more than just bits of the HTML page, so this issue is a little more critical for my use case.

For my project, I'd like to render the HTML document bits like `<!DOCTYPE html>`, `<html lang="en">`, etc. But these get rendered with surrounding `lit-part` markers, which prevents the HTML page from showing correctly in the browser. 

Is there a suggested workaround we could use until this is handled in the package? Thanks for any information!

**Comment by aomarks** [comment]
> I'm using lit-ssr to render more than just bits of the HTML page, so this issue is a little more critical for my use case.
> 
> For my project, I'd like to render the HTML document bits like `<!DOCTYPE html>`, `<html lang="en">`, etc. But these get rendered with surrounding `lit-part` markers, which prevents the HTML page from showing correctly in the browser.
> 
> Is there a suggested workaround we could use until this is handled in the package? Thanks for any information!

In @lit-labs/eleventy-plugin-lit we have a hacky workaround to just remove the outer comments with a regexp: https://github.com/lit/lit/blob/b12e8d93fb4a45b1a16e37716ac6e0a684d5e220/packages/labs/eleventy-plugin-lit/src/index.ts#L240 Might be good enough in the short term?

**Comment by markcellus** [comment]
Thanks! I just opted to use [decomment](https://www.npmjs.com/package/decomment) package since I actually want to get rid of _all_ HTML comments in output instead of just lit's markers. Worked like a charm!

**Comment by justinfagnani** [comment]
I hope to take a look at this soon. We need to figure out how exactly this would be exposed API-wise.

Some of the use-cases we're aware of include server-only templates for creating a page shell, with server/client templates nesting within. For that I think we'll need a separate template tag and/or brand for its TemplateResult to tell the SSR renderer to omit comments.

**Comment by rictic** [comment]
Check out the new server-only templates, which address this use case!
https://github.com/lit/lit/tree/main/packages/labs/ssr#server-only-templates
