### ISSUE TITLE
Inherit link/button styles from outside the shadow dom 

### ISSUE THREAD

**Issue by tmstn** [lit/lit#1931]
I have a component that renders either a link or a button that when clicked, displays a popup.

It would be useful if the link and button inherits the styling from higher up the DOM, outside of the component, so the link or button automatically uses the same styles as the page it is being added to.

Is this possible or does this go against the very idea of encapsulation and web components?

**Comment by davidhicks980** [comment]
Yes this is possible! You can do this in a few ways. First, you can write a property called createRenderRoot within your component, and return this: 
```
class LightDom extends LitElement {
  render() {
    return html`
      <p>This template renders without shadow DOM.</p>
    `;
  }
  createRenderRoot() {
  /**
   * Render template without shadow DOM. Note that shadow DOM features like
   * encapsulated CSS and slots are unavailable.
   */
    return this;
  }
}
```
(Note that I stole this example from the lit website)

However, as you can see, you loose the ability to use slots and encapsulated css, which is not _cool_

An alternative method would be to import static css from outside the component, as 
you can see here: https://lit.dev/docs/components/styles/#sharing-styles

However, that requires defining a css template, which is a pain to keep doing. What I would do is use css inheritance: https://lit.dev/docs/components/styles/#inheritance

What this means is that certain css properties, include all css custom variables, make it past the shadowdom. This makes it easy to change certain parts of your custom element easily. You can even assign variables to your individual component and interface with an exterior variable to maintain encapsulation. For example:

```
<style>
:root{
--link-bg: red
}
body{
--link-decoration: underline
}
custom-component {
--custom-link-decoration: var(--link-decoration)
}
</style>

<body>
  <custom-component class="is-pressed"></custom-component>
</body

<script>
....in CustomComponent that extends LitElement...
static get styles(){
return css`
:host{
--custom-element-link-color: blue
--custom-element-link-size: 24pt

}
:host(.is-pressed), :host(:hovered){
--custom-element-link-size: 56pt
}
a {
color: var(--custom-link-element-color) // should be blue
text-decoration: var(--custom-link-decoration) //should be underline
background-color: var(--link-bg) // should be red
font-size: var(--custom-element-link-size, 24pt) // should be 56pt when hovered or pressed, 24pt when not hovered
}

}`
```

Heads up, I didn't test that code so there may be an error! The basic premise is that anything you can do with custom variables outside of your element you can do within your element, so it makes them ideal for styling your component. My preferred pattern is having variables specific to your component that you assign to external variables, as shown with the --custom-link-decoration variable. LMK if I made any mistakes and hopefully I can help clarify!

Good luck!
David

**Comment by tmstn** [comment]
Thanks so much, this helps a lot.
