### ISSUE TITLE
Update packages to current versions

### ISSUE THREAD

**Issue by GrooveCS** [lit/lit#1932]
## Description

It took time to update all of the packages to the current versions. 

- **Who wants the functionality**: _I do, and the greater community._ 
- **What it is they want**: _To be able to develop web components with the current versions of supporting packages_
_The community wants it: To verify the packages are current and support at least ES2019, address security issues, and reduce the number of known issues._ 
- **Functional description of task/subtask**: _Took the time to run npm-check-updates to identify packages that should be updated._ 

## Acceptance criteria

What the card must do to accept it as complete. Acceptance Criteria must be concrete or measurable.

1. To run the automated test for each monorepo to verify no issues introduced.
2. Create pull request Feature/update npm packages to current versions #1933 to associate with this issue #1932

**Comment by sorvell** [comment]
Thanks for the issue. In general, we bump dependencies when necessary for the underlying code. We will, however, likely bump to current versions before the Lit 2 general release. Thanks for the PR.
