### ISSUE TITLE
getHTML is not a function

### ISSUE THREAD

**Issue by xiki808** [lit/lit#1934]
# Description

I'm getting a getHTML function does not exist error when calling this function on a templateResult

# Steps to Reproduce

1. Write this code

```js
import { LitElement, html, css } from 'lit';

export class MyClass extends LitElement {

  render() {
    const myelement = document.selectQuery('#myelement');
    myelement.insertAdjacentHTML('afterbegin', this._newElement().getHTML());
  }

  _newElement() {
    return html`<div>hello</div>`;
  }
}

window.customElements.define('test-element', MyClass);
```

## Expected Results

Returns the html string from the function `_newElement()` when calling `getHtml()` on it.

**Comment by justinfagnani** [comment]
This isn't a proper use of the TemplateResult API. In lit-html 1 `getHTML()` returns the prepared HTML for a _template_, which is intended to be cloned and processed by lit-html internally. In lit-html 2.0 we've removed that method and moved all template processing into `render()`.

**Comment by xiki808** [comment]
Ok, thank you for letting me know! I can use a normal string instead, was just wondering if there is any other proper way.
