### ISSUE TITLE
[lit-html] Lit parser for WebComponentDesigner

### ISSUE THREAD

**Issue by jogibear9988** [lit/lit#1944]
I'm working on a Designer Framework for Webcomponents: https://github.com/node-projects/web-component-designer

I'm currently workin on a Bindings Parser for "Polymer 3" Bindings, as we in our company still have some polymer3 components, and we have our own BasicWebcomponent (https://github.com/node-projects/base-custom-webcomponent) as a replacement.
 
But now I'm thinkin of adding LIT Template support. But as LIT Templates can contain very complex Javascript Code, I'm thinkin of would it make sense to include a Template parser for LIT? Do most of the elments only use simple Propertys in "${}" tags?

What would be the best way to do this? Does there already exist a Parser wich I could use?
I thought of using https://github.com/node-projects/node-html-parser and modify it so it also returns "bindings" from a template string. And if the Template is too complex,  it would fail.

But would this realy make sense? In LIT the "render" could be really complex, and often it can consist of more then one html´´ expression.

Any suggestions, thoughts, ...

**Comment by jogibear9988** [comment]
I think a template like:

     html`<h1>Hello ${name}</h1>`

could work, but something like:

     html`${this.userName
    ? html`Welcome ${this.userName}`
    : html`Please log in <button>Login</button>`
    }`

would already be to much

**Comment by justinfagnani** [comment]
lit-html template can contain arbitrary code. So any template parser has to be a combination of JavaScript/TypeScript parser and HTML parser for the content of the template literals. There are projects that do similar things, like lit-analyzer and web-component-analyzer. You might want to take a look there.

**Comment by jogibear9988** [comment]
I know they could contain any arbitary code, but I don't think a designer would make sense for any arbitary code. 
I only think, at a first step, only simple scenarios, where i only populate some small parts would be possible and usefull

**Comment by justinfagnani** [comment]
Yeah, you'll have to decide how complex of templates to support. At the limit, with dynamically chosen sub-templates, you won't be able to statically know what templates might be rendered. We do have systems at Google that support only a statically knowable subset of Lit templates, which we compile to [Closure Templates](https://github.com/google/closure-templates). We limit statements within render() to const variable declarations, require a single return statement of a template result, only support a few directives, and so on.

**Comment by jogibear9988** [comment]
I'll try what I can support. At first I will parse the JS Code, search for the template and parse the parts I could :-)

**Comment by justinfagnani** [comment]
I don't think we have anything actionable we can do here any time soon, so closing to clean up issues. Eventually we could offer some support based on code we have in lit-html and SSR.

**Comment by jogibear9988** [comment]
No problem. If I've questions I'll ask.
Problem is, I like to use esprima for Javascript parsing, but for this at first I need to work on ES2022 class members support :-)

**Comment by jogibear9988** [comment]
When I've finished this https://github.com/node-projects/esprima-next/pull/11 I'll get back to this
