### ISSUE TITLE
Should `ReactiveElement.getPropertyOptions` be public?

### ISSUE THREAD

**Issue by bennypowers** [lit/lit#1945]
In writing Apollo Elements I've had opportunity to do some hacking into `ReactiveElement`'s lifecycle. Specifically, I wrote a TypeScript decorator which forwards fields from a controller to the host and vice-versa.

```ts
function defineOnReactiveElement<T extends ReactiveElement & ApolloControllerHost>(
  proto: T,
  name: string & keyof T,
  opts: DefineOptions
): void {
  // Run our property effects
  defineOnHTMLElement(proto, name, {
    ...opts,
    // In addition to any user-defined side-effects,
    // also notify the ReactiveElement lifecycle
    onSet(this: T, x: unknown) {
      const old = this[name];
      opts?.onSet?.call?.(this, x);
      this.requestUpdate(name, old);
    },
  });
  // And also run ReactiveElement's property effects
  const Class = proto.constructor as typeof ReactiveElement;
  // @ts-expect-error: i know it's protected
  Class.createProperty(name, Class.getPropertyOptions(name));
}
```

In doing so, I end up calling `createProperty` (which is public) with `getPropertyOptions` (which is protected). In order to lubricate this workflow for TypeScript users, should `getPropertyOptions` be public?

**Comment by sorvell** [comment]
That sounds reasonable. Feel free to submit a PR for this.

**Comment by justinfagnani** [comment]
I think in the longer term I'd like to encourage people to use multiple decorators together, including possibly us separating out some of the responsibility of `@property()` into `@attribute()`:

```ts
class X extends LitElement {
  @attribute('foo-bar')
  @property()
  foo: string;
}
```

So even though for no I agree with @sorvell, I wonder if you could have a decorator which is meant to be used with `@property()`?

**Comment by bennypowers** [comment]
You mean like this?
```ts
  /**
   * If true, perform a query refetch if the query result is marked as being partial,
   * and the returned data is reset to an empty Object by the Apollo Client QueryManager
   * (due to a cache miss).
   *
   * The default value is false for backwards-compatibility's sake,
   * but should be changed to true for most use-cases.
   *
   * @summary Set to retry any partial query results.
   */
  @controlled({ path: 'options' })
  @property({ type: Boolean, attribute: 'partial-refetch' })
  partialRefetch?: boolean;
```

https://github.com/apollo-elements/apollo-elements/blob/dcccc4ca778378ad3f0b4823011680f7bbada8c8/packages/lit-apollo/apollo-query.ts#L117-L129

**Comment by justinfagnani** [comment]
@bennypowers yes. Are you trying to consolidate that decorator to make `@property()` not necessary?

My main concerns are around us having to keep public APIs that we might be able to optimize away over time, and static analysis that understands `@property()` but not other decorators. I don't generally want tools to assume `@property()` is special, since getters can be reactive, but right now `@property()` is a convenient way to know the property-attribute association.

**Comment by bennypowers** [comment]
> Are you trying to consolidate that decorator to make @property() not necessary?

No, I just want to lose the `@ts-expect-error`. I want composable decorators, too.
