### ISSUE TITLE
[lit-html] Error thrown when hydration contains a `<link>`

### ISSUE THREAD

**Issue by shakyShane** [lit/lit#1947]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `lit-html@2.0.0-rc.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/lit-html/development/experimental-hydrate.js b/node_modules/lit-html/development/experimental-hydrate.js
index f484f0f..42c6266 100644
--- a/node_modules/lit-html/development/experimental-hydrate.js
+++ b/node_modules/lit-html/development/experimental-hydrate.js
@@ -84,7 +84,7 @@ export const hydrate = (rootValue, container, options = {}) => {
             createAttributeParts(marker, stack, options);
             // Remove `defer-hydration` attribute, if any
             const parent = marker.parentElement;
-            if (parent.hasAttribute('defer-hydration')) {
+            if (parent?.hasAttribute('defer-hydration')) {
                 parent.removeAttribute('defer-hydration');
             }
         }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Leaving this here as a WIP, I am putting together a re-producing example, but the basic gist is that a render method like this throws an error because of the above

```ts
render() {
  return html`
    <link rel="stylesheet" href="tailwind.css" />
    <a href="/" class="underline">Home</a>
  `
}
```

**Comment by justinfagnani** [comment]
A full repro would be great. I'm a little perplexed how a marker could be left without a parentElement here, any different from any other top-level marker created by render(). The only markers without parents should have a shadow root as parent, and we should hit that in every Lit element. It'll be interesting to see if/why `<link>` triggers this.

**Comment by justinfagnani** [comment]
@shakyShane and updates here?

**Comment by shakyShane** [comment]
Hi @justinfagnani let me close this for now, and I'll re-open with further information once I get back to the CSS part of my project :)
