### ISSUE TITLE
[lit-html] Lit 2 event part parsing is less robust to errors than previous version

### ISSUE THREAD

**Issue by sorvell** [lit/lit#1949]
# Description

Malformed parts parse differently from how they did in previous versions. This is easiest to see (and may be limited to) event parts.

Examples:

* no leading quote: `foo=${'hi'}"`
* extra curly bracket: `foo=${'hi'}}`

# Steps to Reproduce

1. Write incorrect lit parts as described above
2. See that parts do not function as expected.

## Live Reproduction Link

[Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBAcHJvcGVydHkoKVxuICBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxwIEBjbGljaz0ke3RoaXMuY2xpY2tIYW5kbGVyfVwiPkNsaWNrIG1lISAodW5iYWxhbmNlZCB0cmFpbGluZyBxdW90ZSk8L3A-XG4gICAgICAgIDxwIEBjbGljaz0ke3RoaXMuY2xpY2tIYW5kbGVyfX0-Q2xpY2sgbWUhICh1bnF1b3RlZCBleHRyYSBjdXJseSBicmFjZSBhdCBlbmQpPC9wPlxuICAgICAgICA8cCBAY2xpY2s9XCIke3RoaXMuY2xpY2tIYW5kbGVyfX1cIj5DbGljayBtZSEgKHF1b3RlZCBleHRyYSBjdXJseSBicmFjZSBhdCBlbmQpPC9wPlxuICAgICAgICA8cCBAY2xpY2s9JHt0aGlzLmNsaWNrSGFuZGxlcn19XCI-Q2xpY2sgbWUhICh1bmJhbGFuY2VkIHRyYWlsaW5nIHF1b3RlLCBleHRyYSBjdXJseSBicmFjZSBhdCBlbmQpPC9wPlxuICAgIGA7XG4gICAgICAgIFxuICB9XG4gIFxuICBjbGlja0hhbmRsZXIoZSkge1xuICAgIGUudGFyZ2V0LnRleHRDb250ZW50ID0gJ2NsaWNrZWQhJztcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifV0) showing non-working event parts 

## Expected Results

Same [playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgY3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC1lbGVtZW50QDIuNC4wJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8cCBAY2xpY2s9JHt0aGlzLmNsaWNrSGFuZGxlcn1cIj5DbGljayBtZSEgKHVuYmFsYW5jZWQgdHJhaWxpbmcgcXVvdGUpPC9wPlxuICAgICAgICA8cCBAY2xpY2s9JHt0aGlzLmNsaWNrSGFuZGxlcn19PkNsaWNrIG1lISAodW5xdW90ZWQgZXh0cmEgY3VybHkgYnJhY2UgYXQgZW5kKTwvcD5cbiAgICAgICAgPHAgQGNsaWNrPVwiJHt0aGlzLmNsaWNrSGFuZGxlcn19XCI-Q2xpY2sgbWUhIChxdW90ZWQgZXh0cmEgY3VybHkgYnJhY2UgYXQgZW5kKTwvcD5cbiAgICAgICAgPHAgQGNsaWNrPSR7dGhpcy5jbGlja0hhbmRsZXJ9fVwiPkNsaWNrIG1lISAodW5iYWxhbmNlZCB0cmFpbGluZyBxdW90ZSwgZXh0cmEgY3VybHkgYnJhY2UgYXQgZW5kKTwvcD5cbiAgICBgO1xuICAgICAgICBcbiAgfVxuICBcbiAgY2xpY2tIYW5kbGVyKGUpIHtcbiAgICBlLnRhcmdldC50ZXh0Q29udGVudCA9ICdjbGlja2VkISc7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn1d) using previous version.

**Comment by kevinpschaaf** [comment]
I debugged this a bit more and it's not actually in the _parsing_ per se, its in the part update handling:

https://github.com/lit/lit/blob/c8fe1d4c4a8b1c9acdd5331129ae3641c51d9904/packages/lit-html/src/lit-html.ts#L849-L857

Because an `EventPart` that has extra strings will have a non-undefined `strings` field, it will take the `setValue(valuesArray, part, index)` fork in update; however, `EventPart`'s `setValue` implementation does not handle receiving an array. In Lit 1, the static strings had no bearing on the `EventPart` (although in Lit 1 we'd totally break if there were more than 1 expression in event position).

We can match the Lit 1 behavior by changing this line:
https://github.com/lit/lit/blob/c8fe1d4c4a8b1c9acdd5331129ae3641c51d9904/packages/lit-html/src/lit-html.ts#L1420-L1421

to:

```ts
    newListener = 
      resolveDirective(this, Array.isArray(newListener) ? newListener[0] : newListener, directiveParent, 0) ?? nothing;<br class="Apple-interchange-newline">
```

**Comment by sorvell** [comment]
Closing in favor of https://github.com/lit/lit/issues/2045.
