### ISSUE TITLE
Forced to use `.js` extension when importing from typescript

### ISSUE THREAD

**Issue by jpzwarte** [lit/lit#1951]
Currently you have to add the `.js` extension if you are importing a decorator:

```js
import { property } from 'lit/decorators.js';
```

Even when in typescript!

This can be "fixed" by adding 

```
    "./decorators": {
      "default": "./decorators.js"
    },
```

to the `exports` section of `package.json`.

@justinfagnani is that something you would consider?

**Comment by justinfagnani** [comment]
Using the .js extension means that import maps for lit only have to have entries for the package mains. If we allowed extension-less imports, import maps would have to have an entry for every entrypoint - and we have quite a few - which would make them large to download for apps and harder to hand write.

**Comment by jpzwarte** [comment]
Thanks, closing the issue.
