### ISSUE TITLE
[reactive-element] Support for customized build-in elements

### ISSUE THREAD

**Issue by Sebosek** [lit/lit#1952]
Hi,

I've tried to find the answer in the documentation, but without any luck, so I guess, it's not supported right now; however I would like to know if there is any plan to support [Customized build-in elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#customized_built-in_elements)?
Also, please consider mentioning it any part of the documentation.
Thanks!

**Comment by justinfagnani** [comment]
There's no plan to support them as of now. With Safari not supporting them we don't want to encourage developers to make elements that would require a polyfill to support all browsers.
