### ISSUE TITLE
Greek symbols result in "SyntaxError: Unexpected identifier 'i'"

### ISSUE THREAD

**Issue by jsantell** [lit/lit#1958]
# Description

The `Σ`, `Π`, etc. variable names in the codebase fails in mysterious ways when `<meta charset="utf8">` is not explicitly set. Browsers seem to default to this if not defined, but not the case in Safari Webviews.

For example, `self.Σi = 1` is interpreted as `self.Î i = 1`, causing `"SyntaxError: Unexpected identifier 'i'"`. Setting an explicit charset in the HTML page fixes the issue. A potential fix, other than removing the `Σ` symbols and similar, may be to not suffix (e.g. `Σi`, `Σo`), as the resulting space between the characters is what causes the issue. In other words, `self.Σ = 1` does not generate a syntax error.

![Screen Shot 2021-06-14 at 5 18 32 PM](https://user-images.githubusercontent.com/641267/121976431-a977de80-cd38-11eb-9f91-628a00e0896f.png)

It was unexpected to debug this, as only a few ways of importing scripts generate sufficient line information in Safari tooling (and seems to inconsistently reflect charset state in tools, rendering as either `Σ` or `Î`) as well as loading up unminified builds, and not expecting internal variable names to affect the runtime.

# Steps to Reproduce

* Run this from a WKWebview: `<script>self.Σi = 1</script>`

<img width="734" alt="Screen Shot 2021-06-14 at 5 44 45 PM" src="https://user-images.githubusercontent.com/641267/121976440-ada3fc00-cd38-11eb-8167-0093d48bf019.png">

## Expected Results

No error.

## Actual Results

`"SyntaxError: Unexpected identifier 'i'"`.

## Browsers Affected

- [x] Safari WKWebview with no explicit charset: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)"`.

**Comment by justinfagnani** [comment]
Wow, this is disappointing. I didn't know that the HTML document's encoding affected script sources, but it looks like if the script tag doesn't have a `charset` attribute and it doesn't have a BOM and the UA doesn't detect UTF-8 in another way, then the script falls back to the document's encoding.

We could try to require that either tools emit a BOM or documents/script tags specify the charset, but this might be a bit too much of a speed bump compared to other libraries. I wonder what Angular does, since they use a similar unicode prefixing scheme in Ivy?

**Comment by jridgewell** [comment]
External scripts can use `Content-Type: text/javascript; charset=utf-8` to set the charset. Or, lit could output ASCII-safe files (but still namespaced) via `\uXXXX` escaping:

```js
self.Σi = 1;
// \u03a3 is equivalent to Σ
assert.equal(self.\u03a3i, 1)
```

As long as you stick to the lower UTF planes, `\uXXXX` escapes are safe back to ES5 (the newer `\u{XXXXXX}` form is only ES6+).

**Comment by jridgewell** [comment]
Checked https://angular.io/default-src_app_custom-elements_code_code_component_ts-src_app_custom-elements_code_code_module_ts-es2017.eef8056e5a8d35c7b381.js, they're using unicode escapes.
