### ISSUE TITLE
My button component is disabled, but still fires (click) events.

### ISSUE THREAD

**Issue by matheusrgarcia** [lit/lit#1973]
# Description

I have a custom button component that fires click events even when it is **disabled**.

# Steps to Reproduce

1. Write this code

```ts
import { LitElement, html, property, customElement, query, svg } from 'lit-element';

import Style from "./james-button.scss";

@customElement("james-button")
export class JamesButton extends LitElement {
  @property({ type: Boolean })
  private disabled = false;

  @property({ type: Boolean })
  private busy = false;

  @property()
  private color: "highlight" | "success" | "translucide" | undefined;

  @property()
  private hover: "orange" | "purple" | "red" | undefined;

  @property()
  private size: 'very-big' | 'big' | 'medium' | 'small' | 'very-small' | undefined;

  @property()
  private border: 'all' | 'error' | 'gray' | 'orange' | 'purple' | 'highlight' | undefined;

  @property()
  private icon: any;

  @query("button")
  private button: any;

  @query("#svg")
  private svg: any;

  static get styles() {
    return [Style];
  }

  render() {
    return html`
    <button class="btn ${this.disabled ? 'btn-disabled' : ''} ${this.busy ? 'btn-busy' : ''}"
    type="button"
    ?disabled=${this.disabled}>
    ${this.icon ? svg`<div class="btn-icon" id="svg"></div>
    ` : null }
      <slot></slot>
    </button>
    `;
  }

  updated() {
    this.validateClassToButton();
    if (this.icon) {
      this.svg.innerHTML = this.icon;
    }
  }

  /**
   * Add one o more class to element <button> with structure ".btn-${typeOfStyle}-${variant}"
   * @param typeOfStyle Name of variation
   * @param variantOfStyle Variation mode
   */
  private addClassToButton(typeOfStyle: string, variantOfStyle: string): void {
    const classes = this.button.classList.toString();
    const type = new RegExp(typeOfStyle);

    if (type.test(classes)) {
      const classesMatched = classes.match(type);
      const classToRemove = classesMatched.input
        .split(" ")
        .filter((item: any) => {
          return item.includes(typeOfStyle);
        })[0];
      this.button.classList.remove(classToRemove);
    }

    if (/ /.test(variantOfStyle)) {
      // Check if has multiple variants for one style type
      variantOfStyle.split(" ").forEach((variant) => {
        this.button.classList.add(`btn-${typeOfStyle}-${variant}`);
      });
    } else {
      this.button.classList.add(`btn-${typeOfStyle}-${variantOfStyle}`);
    }
  }

  /**
   * Get all params valid and send class variations to addClassToButton
   */
  private validateClassToButton(): void {
    if (this.color) {
      this.addClassToButton("color", this.color);
    }

    if (this.hover) {
      this.addClassToButton("hover", this.hover);
    }

    if (this.size) {
      this.addClassToButton("size", this.size);
    }

    if (this.border) {
      this.addClassToButton("border", this.border);
    }
  }
}

```

## Expected Results

While using this custom element, when the button is disabled, click events shouldn't fire

## Actual Results

Disabled button still fires click events

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Opera

**Comment by justinfagnani** [comment]
Do you have an online reproduction we can try? This simple version shows that a boolean binding to `disabled` does work: https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ29uLW9mZicpXG5leHBvcnQgY2xhc3MgT25PZmZFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgQHByb3BlcnR5KClcbiAgX29uID0gZmFsc2U7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLm9uQ2xpY2t9ID9kaXNhYmxlZD0ke3RoaXMuX29ufT5PbjwvYnV0dG9uPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLm9uQ2xpY2t9ID9kaXNhYmxlZD0keyF0aGlzLl9vbn0-T2ZmPC9idXR0b24-XG4gICAgYDtcbiAgfVxuICBcbiAgb25DbGljaygpIHtcbiAgICB0aGlzLl9vbiA9ICF0aGlzLl9vbjtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxvbi1vZmY-PC9vbi1vZmY-XG48L2JvZHk-XG4ifV0

**Comment by sosa-vaadin** [comment]
I tried to reproduce your error without success. I was disabled the button, both by the private property defined in the class and by using the `disabled` HTML property. I used `addEventListener('click', listenerFun)` to listen to click events and, as expected when disabled, no click event was being fired.

In another note, the `disabled` property is `private` so I couldn't really change it from outside the component class without having the TypeScript compiler complain about it.

**Comment by sosa-vaadin** [comment]
> I wonder if the issue here is that they were listening to click events on the host element, which can still fire even if the internal button was disabled e.g. in this [playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ29uLW9mZicpXG5leHBvcnQgY2xhc3MgT25PZmZFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgQHByb3BlcnR5KClcbiAgX29uID0gZmFsc2U7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLm9uQ2xpY2t9ID9kaXNhYmxlZD0ke3RoaXMuX29ufT5PbjwvYnV0dG9uPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLm9uQ2xpY2t9ID9kaXNhYmxlZD0keyF0aGlzLl9vbn0-T2ZmPC9idXR0b24-XG4gICAgYDtcbiAgfVxuICBcbiAgb25DbGljaygpIHtcbiAgICB0aGlzLl9vbiA9ICF0aGlzLl9vbjtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxvbi1vZmY-PC9vbi1vZmY-XG48L2JvZHk-XG5cbjxzY3JpcHQ-XG4gIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJvbi1vZmZcIikuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsIGUgPT4gY29uc29sZS5sb2coXCJjbGljayBvbiBob3N0IVwiKSlcbjwvc2NyaXB0PiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMC1yYy4yXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjAtcmMuMlwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjAtcmMuMlwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjAtcmMuM1wiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

Even then, clicking the disabled button does not fire a click event on the host. Only clicking outside the disabled button (but  still inside the host) does.

**Comment by WickyNilliams** [comment]
Yeah, that's what i observed too. But css can complicate things - I have seen people do things like add `pointer-events: none` to disabled buttons, which would allow it to propagate up. See [here](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ29uLW9mZicpXG5leHBvcnQgY2xhc3MgT25PZmZFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgQHByb3BlcnR5KClcbiAgX29uID0gZmFsc2U7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGJ1dHRvbiBzdHlsZT0ke3RoaXMuX29uID8gXCJwb2ludGVyLWV2ZW50czogbm9uZVwiIDogXCJcIn0gQGNsaWNrPSR7dGhpcy5vbkNsaWNrfSA_ZGlzYWJsZWQ9JHt0aGlzLl9vbn0-T248L2J1dHRvbj5cbiAgICAgIDxidXR0b24gc3R5bGU9JHshdGhpcy5fb24gPyBcInBvaW50ZXItZXZlbnRzOiBub25lXCIgOiBcIlwifSBAY2xpY2s9JHt0aGlzLm9uQ2xpY2t9ID9kaXNhYmxlZD0keyF0aGlzLl9vbn0-T2ZmPC9idXR0b24-XG4gICAgYDtcbiAgfVxuICBcbiAgb25DbGljaygpIHtcbiAgICB0aGlzLl9vbiA9ICF0aGlzLl9vbjtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxvbi1vZmY-PC9vbi1vZmY-XG48L2JvZHk-XG5cbjxzY3JpcHQ-XG4gIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCJvbi1vZmZcIikuYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsIGUgPT4gY29uc29sZS5sb2coXCJjbGljayBvbiBob3N0IVwiKSlcbjwvc2NyaXB0PiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMC1yYy4yXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjAtcmMuMlwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjAtcmMuMlwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjAtcmMuM1wiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

But it's basically impossible to tell without the full code and/or a reduced test case from the OP

**Comment by sorvell** [comment]
Closing based on the discussion here. If there's a remaining specific issue, please post a reproduction, ideally using the [lit.dev/playground](https://lit.dev/playground/). Thanks!

**Comment by sorvell** [comment]
Closing based on the discussion here. If there's a remaining specific issue, please post a reproduction, ideally using the [lit.dev/playground](https://lit.dev/playground/). Thanks!
