### ISSUE TITLE
CreateRef doesn't match types of element

### ISSUE THREAD

**Issue by davidbwaters** [lit/lit#1974]
# Description

I'm new to typescript, but have used Lit (older versions) for a while.  I get a type error with the returned reference using createRef with lit-element.  The code below in VS should reproduce.  When trying to se the 'style' or use the ref when HTMLElement is expected, it doesn't have the correct properties.  The Ref definition looks like it should inherit them, but IDK enough about TS to debug..  

# Steps to Reproduce

1. Write this code

```ts
import {
  LitElement,
  html,
  css
} from 'lit';

import {
  customElement
} from 'lit/decorators.js';

import {
  ref,
  createRef
} from 'lit/directives/ref.js';

declare global {
  interface HTMLElementTagNameMap {
    'c-intro': Intro,
  }
  
}

@customElement('c-intro')

export class Intro extends LitElement {


  introEl = createRef<HTMLDivElement>()

  async introSetup() {

    this.introEl.style.position = 'fixed'

  }

  render() {
    return html`
      <div class='c-intro' ${ref(this.introEl)}></div>
      </div>
    `
  }
}

```

## Expected Results

Type should match reference element

## Actual Results

`Property 'style' does not exist on type 'Ref<HTMLDivElement>'.ts`

**Comment by AndrewJakubowicz** [comment]
Thanks for the issue!

From the [Lit documentation on Ref](https://lit.dev/docs/templates/directives/#ref), _"After rendering, the Ref's `value` property will be set to the element"_.
To fix the error in your provided code, access the `value` property to get the element in the ref, i.e:

```this.introEl.value.style.position = 'fixed'```

[Here's a playground with the fix.](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge1xuICBMaXRFbGVtZW50LFxuICBodG1sLFxuICBjc3Ncbn0gZnJvbSAnbGl0JztcblxuaW1wb3J0IHtcbiAgY3VzdG9tRWxlbWVudFxufSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbmltcG9ydCB7XG4gIHJlZixcbiAgY3JlYXRlUmVmXG59IGZyb20gJ2xpdC9kaXJlY3RpdmVzL3JlZi5qcyc7XG5cbmRlY2xhcmUgZ2xvYmFsIHtcbiAgaW50ZXJmYWNlIEhUTUxFbGVtZW50VGFnTmFtZU1hcCB7XG4gICAgJ2MtaW50cm8nOiBJbnRybyxcbiAgfVxuICBcbn1cblxuQGN1c3RvbUVsZW1lbnQoJ2MtaW50cm8nKVxuXG5leHBvcnQgY2xhc3MgSW50cm8gZXh0ZW5kcyBMaXRFbGVtZW50IHtcblxuXG4gIGludHJvRWwgPSBjcmVhdGVSZWY8SFRNTERpdkVsZW1lbnQ-KClcblxuICBhc3luYyBpbnRyb1NldHVwKCkge1xuICAgIHRoaXMuaW50cm9FbC52YWx1ZS5zdHlsZS5wb3NpdGlvbiA9ICdmaXhlZCdcbiAgfVxuICBcbiAgZmlyc3RVcGRhdGVkICgpIHtcbiAgICB0aGlzLmludHJvU2V0dXAoKVxuICB9XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGRpdiBjbGFzcz0nYy1pbnRybycgJHtyZWYodGhpcy5pbnRyb0VsKX0-PC9kaXY-XG4gICAgYFxuICB9XG59In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxjLWludHJvPjwvYy1pbnRybz5cbjwvYm9keT5cbiJ9XQ)

The playground renders the html:

```
<div class="c-intro" style="position: fixed;"></div>
```


Please let me know if the error persists or if I can help in any other way!
Thanks!

**Comment by davidbwaters** [comment]
Thanks for the quick reply, I got it now.  Loving the new Lit so far.
