### ISSUE TITLE
Add javascript examples to docs

### ISSUE THREAD

**Issue by davidbwaters** [lit/lit#1976]
I assume this is planned, maybe consider the priority of this.  Since Lit has become the go-to lib for people who want JS components and want to use the platform and less compilation, forcing TypeScript to be able to follow the docs seems like a turnoff for potential users and could hinder adoption.  This issue is not to debate the merits of TS.

I was in that group and am finally learning TypeScript, which I'm happy about and intended to, but it's not exactly an enjoyable process haha. It definitely adds to the learning curve, especially for people learning web dev.  Also, those who already know TS are more likely to already have a preferred component system, like React or Angular. 

I don't even necessarily think it should be heavily favored in the docs.  Obviously it eases compilation and debugging and that should be made clear, but a lot of people choose Lit because they want to use the platform and if you're fresh from learning the basics of JS/CSS/HTML, it's a barrier.  If these users try Lit, they will clearly see from a glance at the TS examples the advantages of writing components like this.  

Plus, TS isn't like SASS where you can just change the extension and expect it to work without adding tweaks and types somewhere in your code.  You'll probably be greeted with a slightly overwhelming number of errors that don't prevent code from working, like enabling a linter for the first time.  If you want to learn components and add a few dynamic web components to a static site, which is where things are trending now, adopting TS is a lot.

edit:  I didn't mean to add that Focus to the issue label, idk how to change this.

**Comment by aomarks** [comment]
Thanks for the issue! This is being worked on actively, we're going to add a toggle to all of the examples that will switch from TypeScript to JavaScript -- and it will remember your preference across pages.

We're going to support this using an automated transform from TypeScript to idiomatic JavaScript, see https://github.com/lit/lit/pull/1919.

Closing because we're tracking at https://github.com/lit/lit.dev/issues/332

**Comment by davidbwaters** [comment]
Awesome, thanks.  I searched to see if this was already an issue, but missed that one.  Maybe add `javascript` or `docs` to the title others don't miss it.
