### ISSUE TITLE
Quote type matters for converting properties with type Object | Array that contain strings.

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit#1984]
# Description

When passing attributes in from HTML using the default `Object | Array` converters, my expectation was that the quote type between `'` and `"` wouldn't matter.  This matters when you are trying to pass in an object or array of strings.

Depending on quote type the object or array attribute can parse into `undefined`.

# Steps to Reproduce

1. Write this code

```ts
import {html, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';

@customElement('simple-greeting')
export class SimpleGreeting extends LitElement {
  @property({type: Array})
  arrayStrExample = [];

  render() {
    return html`result: ${this.arrayStrExample}`
  }
}
```

And then try to use this component with the html:

```html
<simple-greeting arrayStrExample="['a', 'b']"></simple-greeting>
<simple-greeting arrayStrExample='["a", "b"]'></simple-greeting>
```

2. See this output rendered

```
result:
result: ab
```

## Live Reproduction Link

[Live example in Lit Playground from code above.](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBwcm9wZXJ0eSh7dHlwZTogQXJyYXl9KVxuICBhcnJheVN0ckV4YW1wbGUgPSBbXTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgcmVzdWx0OiAke3RoaXMuYXJyYXlTdHJFeGFtcGxlfWBcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIGFycmF5U3RyRXhhbXBsZT1cIlsnYScsICdiJ11cIj48L3NpbXBsZS1ncmVldGluZz5cbiAgPGJyLz5cbiAgPHNpbXBsZS1ncmVldGluZyBhcnJheVN0ckV4YW1wbGU9J1tcImFcIiwgXCJiXCJdJz48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9XQ)

[Another example in the Lit playground with type Object](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BwIHsgY29sb3I6IGJsdWUgfWA7XG5cbiAgQHByb3BlcnR5KHt0eXBlOiBBcnJheX0pXG4gIGFycmF5TnVtRXhhbXBsZSA9IFtdO1xuXG4gIEBwcm9wZXJ0eSh7dHlwZTogQXJyYXl9KVxuICBhcnJheVN0ckV4YW1wbGUgPSBbXTtcbiAgXG4gIEBwcm9wZXJ0eSh7dHlwZTogQXJyYXl9KVxuICBhcnJheVN0ckV4YW1wbGUyID0gW107XG4gIFxuICBAcHJvcGVydHkoe3R5cGU6IEFycmF5fSlcbiAgbWl4ZWRUeXBlQXJyYXkgPSBbXTtcbiAgXG4gIEBwcm9wZXJ0eSh7dHlwZTogT2JqZWN0fSlcbiAgb2JqZWN0U3RyRXhhbXBsZSA9IHt9O1xuICBcbiAgQHByb3BlcnR5KHt0eXBlOiBPYmplY3R9KVxuICBvYmplY3RTdHJFeGFtcGxlMiA9IHt9O1xuXG4gIHJlbmRlcigpIHtcbiAgICBjb25zdCBsaSA9ICh0eXBlLCB2YWwpID0-IGh0bWxgPGxpPiR7dHlwZX06ICR7SlNPTi5zdHJpbmdpZnkodmFsKX08L2xpPmBcbiAgICByZXR1cm4gaHRtbGA8dWw-XG4gICAgICAgICR7bGkoJ2FycmF5TnVtRXhhbXBsZScsIHRoaXMuYXJyYXlOdW1FeGFtcGxlLmpvaW4oJyAnKSl9XG4gICAgICAgICR7bGkoJ2FycmF5U3RyRXhhbXBsZScsIHRoaXMuYXJyYXlTdHJFeGFtcGxlLmpvaW4oJyAnKSl9XG4gICAgICAgICR7bGkoJ2FycmF5U3RyRXhhbXBsZTInLCB0aGlzLmFycmF5U3RyRXhhbXBsZTI_LmpvaW4oJyAnKSl9XG4gICAgICAgICR7bGkoJ21peGVkVHlwZUFycmF5JywgdGhpcy5taXhlZFR5cGVBcnJheT8uam9pbignICcpKX1cbiAgICAgICAgJHtsaSgnb2JqZWN0U3RyRXhhbXBsZScsIHRoaXMub2JqZWN0U3RyRXhhbXBsZSl9XG4gICAgICAgICR7bGkoJ29iamVjdFN0ckV4YW1wbGUyJywgdGhpcy5vYmplY3RTdHJFeGFtcGxlMil9XG4gICAgICAgIDwvdWw-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmdcbiAgICAgIGFycmF5TnVtRXhhbXBsZT1cIlsxLDJdXCJcbiAgICAgIGFycmF5U3RyRXhhbXBsZT0nW1wiMVwiLFwiMlwiXSdcbiAgICAgIGFycmF5U3RyRXhhbXBsZTI9XCJbJzEnLCcyJ11cIlxuICAgICAgbWl4ZWRUeXBlQXJyYXk9J1sxLFwiMlwiLCBbMywgNF1dJ1xuICAgICAgb2JqZWN0U3RyRXhhbXBsZT0ne1wiaGVsbG9cIjogXCJ3b3JsZFwifSdcbiAgICAgIG9iamVjdFN0ckV4YW1wbGUyPVwieydoZWxsbyc6ICd3b3JsZCd9XCI-XG4gIDwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn1d).

## Expected Results

I expected the following two snippets of HTML to render the same:

 1. `<my-component arrayStrExample='["1","2"]'></my-component>`

 2. `<my-component arrayStrExample2="['1','2']"></my-component>`

And similarly with object attributes, these don't get converted the same: `objectStrExample='{"hello": "world"}'` (works) and `objectStrExample2="{'hello': 'world'}"` (undefined).

## Actual Results

You must wrap Array and Object attributes with a single quote, or they are undefined.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [Couldn't test ] Safari 11
- [Couldn't test ] Safari 10
- [Couldn't test ] IE 11

Is this expected? If so some documentation & examples of this behavior would be useful.
Otherwise I think it'll reduce friction to make the behavior consistent between quotes.

**Comment by abraham** [comment]
[The default converter ](https://lit.dev/docs/components/properties/#conversion-type) uses `JSON.parse` and JSON doesn't allow single quotes. If you run `JSON.parse("['a', 'b']")` you'll get a SyntaxError.

**Comment by hnryjms** [comment]
What about when you're doing something like:

```js
const element = {
  name: "My 'string' with single quotes"
};
const elementSerialized = JSON.stringify(element);
  // -> {"name":"My 'string' with single quotes"}

###

<my-element val='${element}'></my-element>
```

In this case, the single quote inside the `JSON.stringify()` output is unescaped, so it ends the `val` attribute (and adding `\` in front will not escape, since [this isn't how HTML works](https://stackoverflow.com/a/34880976)).

The correct solution is that HTML attributes should be `encodeURIComponent()` wrapped, so it can escape any unsafe values... so the proper converter should be `JSON.parse(decodeURIComponent())` for `Object` and `Array`
