### ISSUE TITLE
Importing files from lit require the `.js` extension in TypeScript

### ISSUE THREAD

**Issue by e111077** [lit/lit#1986]
# Description

Importing files such as `lit/decorators.js` in typescript requires `.js` extension to be in the import name. This is very weird as in TS it is common to exclude the extension and intellisense defaults to autocompleting without the `.js` due to the presence of `.d.ts` files

Repro:

1. `import {customElement} from 'lit/decorators'`
2. see errors

## Expected Results

Importing from `lit/decorators` should work

## Actual Results

It does not work unless you import from `lit/decorators.js`

**Comment by justinfagnani** [comment]
This is very much intentional. We want to enable usage of import maps that don't list every file used in the lit packages. This means that import maps need to be able to use prefix mappings: https://github.com/WICG/import-maps#packages-via-trailing-slashes That requires that imports use the full file path including extension, which is why we require that via our package exports.

**Comment by e111077** [comment]
Can we write our own imports like that but allow the user to consume our library with or without them?

**Comment by justinfagnani** [comment]
No, because that would require even more import map lines. With the restrictions we have now, each package only needs two lines.

What's the problem with the extension?

**Comment by AndrewJakubowicz** [comment]
I might have a naïve VsCode setup, but whenever the IDE tries to auto-magically fill in the import, it's always without the `.js` extension. Then I have to manually add the extension to make the build succeed.

You can learn to work around it quite quickly, but it creates a more painful onboarding.

Is there an setting from the IDE side of things that corrects the incorrect automatic imports?

**Comment by justinfagnani** [comment]
VS Code by default adds the extension based on whether or not other imports in the file use extensions. There's a setting `typescript.preferences.importModuleSpecifierEnding` to control this.

Build systems that resolve and rewrite import specifiers have blurred things here, but in a browser an import must either end in an extension or have a specific import map entry. We don't want to require large import maps to use Lit, and we cannot have the same file loadable from two URLs or we get module duplication, so we can't even give extensionless imports as an option. It has to be one way or the other.

**Comment by e111077** [comment]
As you know, it's not common in TS to include the extension and seems like a code smell to deviate from the norms. I'm mostly just echoing what I've seen from the slack. Though I agree quite a bit on the benefits of import maps

**Comment by aomarks** [comment]
@rollup/plugin-resolve doesn't support extensionless imports anymore, so there's another reason to avoid them.

https://github.com/rollup/plugins/issues/684#issuecomment-770517359

**Comment by e111077** [comment]
Brought up by Liz in the office: this is going to cause issues with internal style guide where users importing decorators or directives will have to insert the extension. This will cause lint errors and might slow down engineers seeking readability.

Might be able to sidestep it with an index.ts file that reexports everything or just slash the extensions and serve js bundles that don't require import maps

**Comment by justinfagnani** [comment]
Google's internal TypeScript guide continues to have issues with reality. I suggest we file issues there.

**Comment by e111077** [comment]
While I generally agree with it being backwards in some spots it tends to follow de facto convention here. Though an index file might sidestep it with `import {...} from 'lit/index'`

**Comment by hailwood** [comment]
Just ran into this issue as well, The thing that throws me is that it's not consistent - e.g. this works

```js
import {customElement, property, state} from 'lit/decorators.js'; // js required
import {asyncReplace} from 'lit/directives/async-replace'; // js optional
```

But this doesn't work

```diff
-import {customElement, property, state} from 'lit/decorators.js';
+import {customElement, property, state} from 'lit/decorators';
import {asyncReplace} from 'lit/directives/async-replace';
```

Of course this also works

```diff
import {customElement, property, state} from 'lit/decorators.js';
-import {asyncReplace} from 'lit/directives/async-replace';
+import {asyncReplace} from 'lit/directives/async-replace.js';
```

but it feels strange needing to remember to add the extension on for just this one package.

Ended up spending about 20 minutes trying to find out what's going on since the error message is a somewhat cryptic
> Module not found: Error: Package path ./decorators is not exported from package

made worse by the fact the IDEs appear to believe it's valid with or without, so if nothing is going to change then a highly visible note in the docs would be good.

**Comment by justinfagnani** [comment]
> Though an index file might sidestep it with import {...} from 'lit/index'

A re-exporting index file obscures the module graph and over fetches modules. It's much better for modules to directly import exactly what they use.

**Comment by justinfagnani** [comment]
@hailwood 

> ```ts
> import {customElement, property, state} from 'lit/decorators.js'; // js required
> import {asyncReplace} from 'lit/directives/async-replace'; // js optional
> ```

I'm not sure what environment would require the extension on decorators.js but not async-replace.js. Sounds like a bog somewhere.

> Ended up spending about 20 minutes trying to find out what's going on since the error message is a somewhat cryptic
> 
> > Module not found: Error: Package path ./decorators is not exported from package

This error is technically correct - we don't export that module from lit. It would be nice if the tool found what file you probably were referring to and added a "Did you mean ... ?". What tools are you using so we can file a bug?

**Comment by hailwood** [comment]
@justinfagnani 

IDE: PHPStorm 2021.2 (though VScode has the same result)
Build Tool: Webpack@^5.35 (via symfony/webpack-encore@1.5.0) with ts-loader@^8.3.0
OS: Ubuntu 21.04

Babel Plugins:
* @babel/plugin-proposal-export-default-from
* @babel/plugin-proposal-optional-chaining
* @babel/plugin-proposal-nullish-coalescing-operator

**Comment by justinfagnani** [comment]
For the record, we're going to keep the package exports that require extensions on imports.

@hailwood's issue with inconsistency seems to be because we have a specific mapping for `lit/decorators.js ` and a subpath folder mapping for `./directives/`. We can fix this inconsistency by making a mapping for each file.

**Comment by kevinpschaaf** [comment]
Closing, as we will continue requiring extension for reasons [described above](https://github.com/lit/lit/issues/1986#issuecomment-870084329), as well as https://github.com/lit/lit/pull/2103 making imports consistently require `.js` suffix.
