### ISSUE TITLE
Create a description attribute for properties.

### ISSUE THREAD

**Issue by jcdalton2201** [lit/lit#1988]
# Description

It would be nice to have a description attribute added to the properties items. This would make it easier for something like https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer to scan the code and add a description to each property. 

# Steps to Reproduce

1. Write this code

```js
import {LitElement} from 'lit';
export class MyAnchor extends LitElement 
static get properties() {
        return {
            href:{type:String, description:''},
       
        };
    }
render(){
  return `<a href=${this.href}></a>`
}
```

2. See this output...

## Expected Results

This is more for documentation.

## Actual Results

This is more for documentation.

**Comment by justinfagnani** [comment]
This would be better served with a JSDoc comment on the property and the analyzer being able to understand that it corresponds to a comment on a class property.

In fact, are you sure that the analyzer doesn't already support that? cc @thepassle

**Comment by sorvell** [comment]
Closing based on @justinfagnani's suggestion.
