### ISSUE TITLE
[help] Package path ./decorators is not exported from package [project_dir]/node_modules/lit

### ISSUE THREAD

**Issue by djalmajr** [lit/lit#1993]
# Description

I have setup a startup project with `next@11` and `lit@2.0.0-rc.2` and when I create a component with `@lit-labs/react` I'm getting this error:

![image](https://user-images.githubusercontent.com/1858147/123960014-33ed4e80-d985-11eb-83fc-f814b41d6864.png)

Could someone help me with this?

## Live Reproduction Link

https://codesandbox.io/s/nextjs-lit-itj0x?file=/components/Button.tsx

**Comment by justinfagnani** [comment]
You have to import with file extensions:

```ts
import { customElement } from "lit/decorators.js";
```

**Comment by djalmajr** [comment]
I had tried this before, but it didn't work either. If I use Create React App, `import { customElement } from "lit/decorators"` (with no extension) works fine. Note: I've updated the _Live Reproduction Link_ with your suggestion if you want to check it out.

Thanks btw.

**Comment by justinfagnani** [comment]
That's a different problem. I wonder if Next or Webpack is running in development mode. We did have a configuration bug where we didn't published the development mode files: https://github.com/lit/lit/issues/1912 We haven't released that fix yet. Working on it now actually.

**Comment by sandrolain** [comment]
Hello,
I ran into the same problem after upgrading from webpack 4 to webpack 5 using TypeScript.
As a workaround I modified the "package.json" file of the "lit" module by adding the following in the "exports" section:

```
    "./decorators": {
      "default": "./decorators.js"
    },
```

**Comment by web-padawan** [comment]
See #1986

**Comment by justinfagnani** [comment]
@sandrolain Webpack 5 is now using the package exports feature. Rather than modify our package.json, which won't persist through updates or other installs, you should just import `decorators.js`

**Comment by djalmajr** [comment]
Any news about that? :)

**Comment by justinfagnani** [comment]
We published the missing development folder in labs/motion with the latest 1.0.0-rc.3 release. Other than that, importing with file extensions is required and how we're moving forward with modules in Lit now. Closing this as I don't think there's anything else remaining.
