### ISSUE TITLE
How to get the name of a custom element through the class?

### ISSUE THREAD

**Issue by luzhenqian** [lit/lit#1996]
I have a component, which is defined as follows:
```TS
@customElement("zt-checkbox")
export default class Checkbox extends LitElement {
  render() {
    return html`<div></div>`;
  }
}
```

I want to get a custom name by class(zt-checkbox), the pseudo code is as follows:

```ts
const name = Checkbox.customElementName// zt-checkbox
```

But the class does not contain this field, what should i do?

**Comment by justinfagnani** [comment]
What's your use case?

We could have the `@customElement()` decorator write the class name somewhere on the class, but we're reluctant to do that because there's no standard property to use, so it wouldn't be available on elements built with other libraries, and the tag name wouldn't be there if you used `customElements.define()`, which is what you do in JS and completely valid in TypeScript as well. The property could also be wrong in cases where you subclass an element but don't use the decorator to register it.

For some background on adding this to the custom elements API see: https://github.com/WICG/webcomponents/issues/566

The most general thing to do is to patch CustomElementRegistry so you can get the tag name for any class:

```ts
const originalDefine = CustomElementRegistry.prototype.define;
const tagNameMap = new Map();
CustomElementRegistry.prototype = function(name, constructor, options) {
  tagNameMap.set(name, constructor);
  return originalDefine.call(this, name, constructor, options);
};
```

**Comment by matthewp** [comment]
Is there an issue with doing: `new Checkbox().localName` ?

**Comment by luzhenqian** [comment]
> 你的用例是什么？
> 
> 我们可以让`@customElement()`装饰器在类的某个地方写下类名，但我们不愿意这样做，因为没有标准属性可以使用，所以它不会在用其他库构建的元素上可用，并且标签名不会如果您使用`customElements.define()`，则不会在那里，这就是您在 JS 中所做的并且在 TypeScript 中也完全有效。在您对元素进行子类化但不使用装饰器注册它的情况下，该属性也可能是错误的。
> 
> 有关将此添加到自定义元素 API 的一些背景信息，请参阅：[WICG/webcomponents#566](https://github.com/WICG/webcomponents/issues/566)
> 
> 最常见的做法是修补 CustomElementRegistry 以便您可以获得任何类的标记名称：
> 
> ```ts
> const  originalDefine  =  CustomElementRegistry 。原型。定义；
> const  tagNameMap  =  new  Map ( ) ; 
> 自定义元素注册表。原型 = 函数（名称、 构造函数、 选项） { 
>   tagNameMap . 设置（名称， 构造函数）；
>   返回 originalDefine 。调用(这个, 名称, 构造函数， 选项）；
> } ;
> ```

Thanks, this is useful!

I made a component library with lit, because I don’t want to bind to the framework, Such as Vue, React... so that I can use this component library in any framework. 

I need to splice string DOM when using node for SSR, so I ran into this problem.

**Comment by luzhenqian** [comment]
> 这样做有问题`new Checkbox().localName`吗：？

Normally it’s okay, But in some special cases I cannot call the class, but just want to get a string of html strings.

**Comment by luzhenqian** [comment]
> What's your use case?
> 
> We could have the `@customElement()` decorator write the class name somewhere on the class, but we're reluctant to do that because there's no standard property to use, so it wouldn't be available on elements built with other libraries, and the tag name wouldn't be there if you used `customElements.define()`, which is what you do in JS and completely valid in TypeScript as well. The property could also be wrong in cases where you subclass an element but don't use the decorator to register it.
> 
> For some background on adding this to the custom elements API see: [WICG/webcomponents#566](https://github.com/WICG/webcomponents/issues/566)
> 
> The most general thing to do is to patch CustomElementRegistry so you can get the tag name for any class:
> 
> ```ts
> const originalDefine = CustomElementRegistry.prototype.define;
> const tagNameMap = new Map();
> CustomElementRegistry.prototype = function(name, constructor, options) {
>   tagNameMap.set(name, constructor);
>   return originalDefine.call(this, name, constructor, options);
> };
> ```

Thanks, this is useful!

I made a component library with lit, because I don’t want to bind to the framework, Such as Vue, React... so that I can use this component library in any framework.

I need to splice string DOM when using node for SSR, so I ran into this problem.

**Comment by luzhenqian** [comment]
> Is there an issue with doing: `new Checkbox().localName` ?

Normally it’s okay, But in some special cases I cannot call the class, but just want to get a string of html strings.
