### ISSUE TITLE
unsafeHTML import bug in typescript

### ISSUE THREAD

**Issue by RoXuS** [lit/lit#1997]
In typescript I can't import unsafeHTML, I am not sure about the bug.

When I import `import { unsafeHTML } from 'lit/directives/unsafe-html.js';` the browser try to get unsafe-html.ts:

![image](https://user-images.githubusercontent.com/3296671/124976947-32302480-e030-11eb-902b-463e1171eef3.png)
```
import { unsafeHTML } from 'lit/directives/unsafe-html.js';
```

This import is ok on a `js` component.

I fix this issue by adding this rewrite rules inside my web-dev-server conf:
```
      if (/.*unsafe-html\.ts.*/.test(context.url)) {
        context.url = '/node_modules/lit/directives/unsafe-html.js';
      }
```

**Comment by justinfagnani** [comment]
@RoXuS sorry for the delay here. Is this still an issue? I can't think of why unsafe-html.js would be redirected to unsafe-html.ts. What server are you using?

**Comment by RoXuS** [comment]
@justinfagnani, it seems to be ok on rc4, sorry for the disturb!
