### ISSUE TITLE
[Question] What is this @wcd/a10k.hello-lit used in Lit?

### ISSUE THREAD

**Issue by dtanp-rft** [lit/lit#2011]
Hi Lit! -- We are using your awesome work to create our design system components. When we use BlackDuck code scan for license checking, the report shows that you're using [@wcd/a10k.hello-lit](https://www.npmjs.com/package/@wcd/a10k.hello-lit) which has **unknown** license.

Would you please clarify what this module is for and that'd be great if you can add type of license properly to this module (if it's really your dependency)? 

We're unable to find how you use this module in the code....

**Comment by justinfagnani** [comment]
Can you please point to where this is used? We're unaware of it.

**Comment by dtanp-rft** [comment]
Thanks for quick response Justin!

There are little information about this that I can find. I have installed it and it's custom element named `ss-hello`. Not sure why npmjs said that it's used by Lit as it isn't installed with Lit at all.

```
customElements.define("ss-hello", MyCounter);
```

Thanks for your response again. Let me discuss with my team again and I will come back to close this question later.
