### ISSUE TITLE
[lit-html] renders nothing when template has string like '\3002'

### ISSUE THREAD

**Issue by Tundon** [lit/lit#2013]
# Description

When the html content has string literal like '\3002', the whole template is not rendered.

# Steps to Reproduce

1. Write this code

```ts
// Import lit-html functions
import { html, render } from 'lit-html';

// Define a template function
const myTemplate = () =>
  html`
  <style type="text/css">
    .style-a {
      content: '\3002';
    }
  </style>
  <p>Hello</p>
  `;

// Render the template with some data
render(myTemplate('lit-html'), document.body);
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-laswpd

## Expected Results

The page should render "Hello"

## Actual Results

The page renders "undefined"

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

## NOTE
If removed the slash leaving only '3002', that works perfectly fine.

**Comment by abraham** [comment]
Likes like it might be the same issue as #1093.

**Comment by Tundon** [comment]
@Abraham Agreed, will close this one.

**Comment by justinfagnani** [comment]
We should add a dev mode warning for this now that we have those.
