### ISSUE TITLE
upgrading to "lit" package, type error "inferred type cannot be named without a reference" ts(2742)

### ISSUE THREAD

**Issue by chase-moskal** [lit/lit#2021]
:wave: hello

in my attempt to upgrade from `lit-element` + `lit-html` to simply `lit` i've encountered a typescript compile time error that i don't understand

i have a module called `component.ts` which re-exports some lit things
```typescript
export * from "lit"
export * from "lit/decorators.js"
// and my own classes that extend lit for my own purposes
```

however, a whole bunch of my modules like `render-roles.ts` are now encountering this type error
```typescript
import {User} from "../../../auth/aspects/users/types/user.js"
import {html} from "../../../../framework/component/component.js"

export function renderRoles(user: User) {
 //             ^^^^^^^^^^^
 //        🚨 TYPESCRIPT ERROR 🚨
 // The inferred type of 'renderRoles' cannot be named without a reference
 // to 'lit/node_modules/lit-html'. This is likely not portable. A type
 // annotation is necessary. ts(2742)
 //

  return html`
    <ul class=roles>
      ${user.roles.map(role => html`
        <li
          data-role-label="${role.label}"
          data-role-id="${role.roleId}">
            ${role.label}
        </li>
      `)}
    </ul>
  `
}
```

i'm not sure what's causing this problem, or what i can do to solve it.  
`The inferred type of 'renderRoles' cannot be named without a reference to 'lit/node_modules/lit-html'. This is likely not portable. A type annotation is necessary. ts(2742)`

this error should reproduce in a branch of my project https://github.com/chase-moskal/xiome/tree/broken-lit-upgrade with `npm i -s && npm run build` and here is the [commit where i upgrade to 'lit'](https://github.com/chase-moskal/xiome/commit/088d5cbacdb472da99f365a64e588656c64eec39)

in the meantime i'm going to keep using `lit-element` and `lit-html`

🍻 thanks folks

**Comment by sorvell** [comment]
Closing since this is pretty old and there's been a number of releases since this was posted. Please re-open a new issue if this is still an issue. Thanks.
