### ISSUE TITLE
Can't use ReactiveController if not using Typescript

### ISSUE THREAD

**Issue by PaquitoSoft** [lit/lit#2023]
# Description

Want to use ReactiveController element in a non Typescript application but it seems it is not exported.
I'm using ```lit@2.0.0-rc.2```.

# Steps to Reproduce

1. Write this code

```js
import {ReactiveController} from 'lit';

class FetchDataController extends ReactiveController {}
```

2. See this output...

## Expected Results

ReactiveController to be correctly imported.

## Actual Results

```
'ReactiveController' is not exported by node_modules\lit\index.js, imported by src\controllers\fetch-data-controller.js
```

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

## Example
I have [this repo](https://github.com/PaquitoSoft/podcaster-lit-element) where you can:
```
npm install
```

and then 
```
npm run build
```

This is the output:
![image](https://user-images.githubusercontent.com/166022/126896874-6d952fef-6da5-4277-9e23-65a2f7f47051.png)

[Here](https://stackblitz.com/edit/js-nsajyp?file=index.js) is a basic example.

**Comment by web-padawan** [comment]
The `ReactiveController` is an [interface](https://github.com/lit/lit/blob/040d8b7dae9ee9bc1845659d70829598a5d682f8/packages/reactive-element/src/reactive-controller.ts#L53) and not a class. When using JS, you need to declare a class which does not extend anything:

```js
class FetchDataController {
}
```

**Comment by PaquitoSoft** [comment]
My bad :man_facepalming:

Thanks for the explanation.
