### ISSUE TITLE
Lit 2.0 'buildless'

### ISSUE THREAD

**Issue by bevand10** [lit/lit#2024]
Is there an intent in 2.0 to support in-browser use of ES6 imports of lit 2.0 minified distribution bundles from CDNs?

**Comment by mrts** [comment]
Absolutely, getting the `SimpleGreeting` example working with CDN would be pure awesomeness:

```html
<!doctype html>
<html>
<body>
  <script type="module">
    import {html, css, LitElement} from 'https://unpkg.com/lit/lit.js?module';
    
    export class SimpleGreeting extends LitElement {
      static get styles() {
        return css`p { color: blue }`;
      }

      static get properties() {
        return {
          name: {type: String}
        }
      }

      constructor() {
        super();
        this.name = 'Somebody';
      }

      render() {
        return html`<p>Hello, ${this.name}!</p>`;
      }
    }

    customElements.define('simple-greeting', SimpleGreeting);
  </script>

  <simple-greeting name="World"></simple-greeting>  
</body>
</html>
```

@justinfagnani, is there anything holding us back?

**Comment by taneltm** [comment]
@mrts That works for me just fine. You only need to change the import url.
```js
import {html, css, LitElement} from 'https://unpkg.com/lit?module';
```

**Comment by mrts** [comment]
@taneltm, perfect, thank you, works like a charm!

@bevand10, does this cover your needs?

**Comment by bevand10** [comment]
> @taneltm, perfect, thank you, works like a charm!
> 
> @bevand10, does this cover your needs?

Yes, it does. Thank you.
