### ISSUE TITLE
Violation of "style-src 'self'" CSP when injecting component styles

### ISSUE THREAD

**Issue by swissmanu** [lit/lit#2025]
# Description

When using a Lit web component on a page served from a web server having the `style-src` CSP set to `'self'`, current versions of Firefox and Safari report a CSP violation and prevent loading the components styles.

Surprisingly, Chrome works perfectly.

Tested browsers:
- ❌ Firefox: macOS, 90.0.2 (64-bit)
- ❌ Safari: macOS, Version 14.1.1 (16611.2.7.1.4)
- ✅ Chrome: macOS, 92.0.4515.107 (Official Build) (x86_64)

# Steps to Reproduce

TL;DR: Run following command to bring up the reproduction example on port `3000`:

```shell
docker run --it -rm -p 3000:80 ghcr.io/swissmanu/firefox-csp-lit:latest
```

The reproduction of this issue requires a specific web server setup. Please see https://github.com/swissmanu/firefox-csp-lit where I prepared a minimal reproducible example.
It consists of the actual code as well as ready-to-use Docker image serving that code via nginx having the regarding HTTP headers set.

## Expected Results

Styles get injected without violating any CSP, unrelated to the browser which the web component is used in.

## Actual Results

Along with an unstyled button, the Firefox dev tools console shows a CSP violation error:

<img width="850" alt="Screenshot 2021-07-27 at 10 52 47" src="https://user-images.githubusercontent.com/170832/127125746-745e7601-2531-4694-a72c-53265b1f3f3e.png">

## Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Edge (untested)
- [X] Safari 11
- [X] Safari 10
- [ ] IE 11 (untested)

**Comment by justinfagnani** [comment]
This is because we create `<style>` tags in Firefox and Chrome for element styles. I think you'll need `unsafe-inline` for that to work. We could also possibly add nonce support...

**Comment by unrelentingtech** [comment]
There is a proposal for `strict-dynamic` CSP to affect styles created by scripts: https://github.com/w3c/webappsec-csp/issues/399 / https://github.com/google/WebFundamentals/issues/8817 but sadly zero momentum there.

Also, [Constructable Stylesheets tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1520690); you can test the current implementation in Nightly (`layout.css.constructable-stylesheets.enabled`, also in about:preferences#experimental)

Nonce support would be a nice workaround for now.

**Comment by swissmanu** [comment]
we settled building sha256 hashes ourselves using a postcss plugin (since we are using postcss anyway already) and provide them in a JSON file when packaging our components.

here is what we do:

```javascript
// postcss-csp-style-src-hash.js:
const crypto = require('crypto');
const { dirname } = require('path');
const fs = require('fs');
const mkdirp = require('mkdirp');

function hash(css, algorithm) {
  return crypto.createHash(algorithm).update(css).digest('base64');
}

function readJson(f) {
  if (!fs.existsSync(f)) {
    return {};
  }
  const data = fs.readFileSync(f, 'utf-8');
  if (data && data.length > 0) {
    return JSON.parse(data);
  } else {
    return {};
  }
}

module.exports = (opts) => {
  opts = Object.assign(
    {
      algorithm: 'sha256',
      out: './dist/csp.json',
    },
    opts
  );

  return {
    postcssPlugin: 'postcss-csp-style-src-hash',
    OnceExit(root) {
      const newCsp = {};
      newCsp['style-src'] = opts.algorithm + '-' + hash(root.toString(), opts.algorithm);

      const outFile = typeof opts.out === 'function' ? opts.out() : opts.out;
      mkdirp.sync(dirname(outFile));
      const oldCsp = readJson(outFile);

      const data = JSON.stringify(Object.assign(oldCsp, newCsp), null, 2);
      fs.writeFileSync(outFile, data, 'utf-8');
    },
  };
};

module.exports.postcss = true;
```

```
// postcss.config.js:
module.exports = {
  plugins: [
    // other plugins ...
    require('./postcss/postcss-csp-style-src-hash')()
  ],
};
```

applications which import any of our components need to extract the hash value from the JSON file and include it in their web servers CSP header. this is a bit cumbersome since its different from target application to target application, but it's safe and working well :)

i hope this helps some of you having the same problems.

**Comment by justinfagnani** [comment]
I just posted https://github.com/lit/lit/pull/2134 as a possible fix. This would let you set a global nonce that's used in all ReactiveElement-generated styles. You would still have to generate a nonce on the server, but hopefully it's set up to be easy to do in the HTML with no modification of the app bundle needed.

**Comment by justinfagnani** [comment]
I added `window.litNonce` in #2134 to fix this.

I want to point out that `'strict-dynamic'` looks like it'll also solve this. If the script running Lit is trusted, the `<style>` tags inserted by Lit should be. Has anyone tried that?

**Comment by unrelentingtech** [comment]
> I want to point out that 'strict-dynamic' looks like it'll also solve this.

As I wrote above https://github.com/lit/lit/issues/2025#issuecomment-890881862 `strict-dynamic` affecting styles (not just scripts) was just a proposal that unfortunately went nowhere so far. (Unless I'm not aware of something…)

**Comment by sr258** [comment]
@justinfagnani We're currently having the same issue when putting our lit-based component into an application that uses CSP. I wonder whether using the global litNonce is really in the spirit of CSP and safe to use. Couldn't attackers use this nonce themselves to inject arbitrary styles?
