### ISSUE TITLE
lit-html@next build with rollup doesn't work

### ISSUE THREAD

**Issue by lrembacz** [lit/lit#2027]
# Description

New lit-html package is not able to build with rollup and iife format.

# Steps to Reproduce

Code on https://github.com/PolymerLabs/lit-html-build with lit-html@next doesn't work for iife format.

## Expected Results

Build should work.

## Actual Results

Package is resolved in wrong way with some random characters in code.

`Uncaught SyntaxError: Invalid or unexpected token`

`Î£i)||void 0===n?void 0:n[s]:i.Î£o`

## Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by sorvell** [comment]
Closing this since Lit2 has been published. Please open a new issue if there's any problem with the current release. Thanks.
