### ISSUE TITLE
createtreewalker deprecated

### ISSUE THREAD

**Issue by lordent** [lit/lit#2035]
# Description

TreeWalker method is deprecated
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker

# Steps to Reproduce

https://github.com/lit/lit/blob/0186e4ded648b70e1440838a1df81c1ff554d106/packages/lit-html/src/lit-html.ts#L413

**Comment by AndrewJakubowicz** [comment]
As an additional note, TreeWalker isn't implemented in some browsers (Cobalt).

**Comment by kevinpschaaf** [comment]
TreeWalker is not deprecated; it is part of the current [DOM spec](https://dom.spec.whatwg.org/#interface-treewalker) and is supported in all modern browsers.

If you're referring to the "👎 Deprecated. Not for use in new websites" snippet at the bottom of the MDN page under the compatibility table, that is an icon legend for where the "👎" icon is used in the table (`expandEntityReferences`, which _is_ deprecated), and doesn't refer to the entire `TreeWalker` feature.

Please open a new issue if there is a specific concern with use of `TreeWalker`.

**Comment by lordent** [comment]
@kevinpschaaf thx for answer
