### ISSUE TITLE
Error thrown by lit-html on subsequent rendering of my custom element: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by drochgenius** [lit/lit#2038]
# Description

I have a custom element built with Lit-Element that I'm trying to migrate to the new Lit.

The first rendering lifecycle is fine, but on the second render, I am getting an exception on the following line in [lit-html](https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L1053)

```
lit-html.ts:1532 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
```

The element is a special *lit-html* comment, and it's somehow removed from the HTML page when the expection occurs. That is, the element has no parentNode.

I am not yet able to create a reproduction case for it, but was wondering if you can give me some pointers to continue my investigation.

This component was working fine with thje former versions of `lit-element` and `lit-html`, but breaks with `lit-html@2.0.0-rc.3`. I have looked at the breaking changes listed in the upgrade guide, and cannot identify which one if causing this breakage.

# Steps to Reproduce

I have isolated a reproducible use case in the following git repository: https://github.com/drochgenius/lit-render-issue

## Expected Results

No error should be thrown when triggering a rendering lifecycle my custom element.

## Actual Results

Error thrown:

```
lit-html.ts:1532 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
```

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by drochgenius** [comment]
I have just identified the root cause of the issue. 

My component is a drop-down component that's making use of [MDC Select](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select). The MDC Select adapter is updating HTML values that are also bound to a `lit-html` template. The sequence goes as follows:

* First rendering lifecycle stamps the lit-html template in the DOM
* MDC Select adapter makes an update to the generated HTML, wiping out the special lit comment around the bound item.
* I change a property of my component, which triggers a rendering lifecycle
* lit-html fails to make the update, because it's unable to find the lit marker.

I've updated the description with a reproducible use case: https://github.com/drochgenius/lit-render-issue

**Comment by justinfagnani** [comment]
Seems like you need to get rid of one of a lit-html binding or MDC Select. Both can't manage the same DOM at the same time. Have you considered using MWC Select? I'm not sure how it manages this, maybe @e111077 knows?

**Comment by drochgenius** [comment]
Thanks for you response @justinfagnani . That's what I figured out, and it makes total sense, if I want lit-html to manage my DOM, I can't have JS code messing with it at the same time.

Thanks also for sharing *MWC*. I didn't know about this project before. I'll check it out.

My issue being resolved now, I will close this ticket.

Thanks

**Comment by e111077** [comment]
for SSR compat Select will be rewritten such that this is not an issue
