### ISSUE TITLE
Lit 2.0 shadowRoot is null when it didn't used to be

### ISSUE THREAD

**Issue by dlockhart** [lit/lit#2040]
# Description

I'm in the early stages of upgrading from `lit-element`/`lit-html` to Lit 2.0 and have run into a few unexpected things that I don't believe were called out in the [upgrade guide](https://lit.dev/docs/releases/upgrade/).

The biggest one so far is that `this.shadowRoot` used to be defined even in the constructor, whereas now it's `null` seemingly up until `connectedCallback`. I'm not questioning whether or not we _should_ have been trying to access `this.shadowRoot` before the element was connected, but more wanting to call out a breaking change that folks may not have been expecting.

We have a lot of code that does stuff like this:

```javascript
focus() {
  // when we are focused, delegate focus to some element in our shadow root
  const elem = this.shadowRoot.querySelector('input');
  if (elem) elem.focus();
}
```

If this was called before the element rendered, it wouldn't find it. So we were protecting against that by ensuring that the element was found, whereas now we need to additionally protect against the `shadowRoot` itself being `null`.

New Lit 2.0-safe code:

```javascript
focus() {
  // when we are focused, delegate focus to some element in our shadow root
  const elem = this.shadowRoot?.querySelector('input');
  if (elem) elem.focus();
}
```

# Steps to Reproduce

Try to access `this.shadowRoot` in the constructor, `attributeChangedCallback` or property setter before `connectedCallback`.

Previously this would have returned the shadow root (but likely nothing was in it) whereas in Lit 2.0 it's `null`.

## Live Reproduction Link

Here's an example in lit-html@1/lit-element@2 where things work correctly:
https://stackblitz.com/edit/lit-element-y8hmve?file=src/index.js

Same thing in lit@2.0.0-rc.2 with the null shadow root:
https://stackblitz.com/edit/lit-element-ybcmxm?file=src/index.js

## Expected Results

Either `this.shadowRoot` isn't `null` like it was prior, or if that's not possible in Lit 2.0 then calling this out as a breaking change in the upgrade guide would be good.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

**Comment by justinfagnani** [comment]
This is an intentional change done to better support SSR and declarative shadow roots. We don't definitively know if a component has a declarative shadow root when the constructor is invoked, neither can we read an attribute that might tell us that the element will receive a declarative shadow root, so we defer shadow root creation.

You're right, this should be mentioned here: https://lit.dev/docs/releases/upgrade/#adapt-to-minor-breaking-changes

**Comment by kevinpschaaf** [comment]
The upgrade guide documents this as a breaking change:
> The createRenderRoot method is now called just before the first update rather than in the constructor. Element code can not assume the renderRoot exists before the element hasUpdated. This change was made for compatibility with server-side rendering.

**Comment by dlockhart** [comment]
Ah yes, you're correct!

I guess it didn't jump out at me as I was looking for something mentioning `shadowRoot` specifically. This may end up being a bigger deal than a "minor breaking change"... it [affected 40+ of our components](https://github.com/BrightspaceUI/core/commit/7bd899cd596c97fcacb6b9ac057ae2d39350554b) (mostly the `focus()` example from above).

Thanks for the quick responses!
