### ISSUE TITLE
LitElement Function "Does Not Exist"

### ISSUE THREAD

**Issue by Lazarus404** [lit/lit#2049]
I don't know where else to ask this question and I don't want to have to rewrite my entire app to support the alternative.

I'm currently rewriting a Polymer app to the latest Lit.  In the original app, custom functions will be called on the elements even if they are not yet added to the DOM.

When calling a LitElement instances custom function (non-Lit API), it will call fine if the element is added to the DOM, but if it hasn't yet been added, I get a `function does not exist` error.  Is there something I need to do prior to invocation, without adding the element to the DOM, to get the function to execute?

**Comment by Lazarus404** [comment]
I'm also finding the same issue when accessing properties of these nodes.  I'm using Lit with vanilla JavaScript, here.

**Comment by justinfagnani** [comment]
Can you provide more details or ideally some kind of reproduction? Online on lit.dev or Stackblitz would be best.

**Comment by nicolejadeyee** [comment]
Hi Lazarus404. closing this issue, please reopen if needed.
