### ISSUE TITLE
Templating: event listener not working alongside .value on HTMLInputElement unless reversed in order

### ISSUE THREAD

**Issue by eavichay** [lit/lit#2053]
# Description

Text input not responding to `@input` event listener alongside `.value` property-setter on native HTMLInputElement
Could work this around by changing the order of directives.

## Non-working code:
```lit
<input type="${question.type}" inputmode="${question.type}" .value=${this.currentValue} @input=${(e: Event) => this.handleChange((<HTMLInputElement>e.target).value)}/>
```

## Working Code:
```lit
<input type="${question.type}" @input=${(e: Event) => this.handleChange((<HTMLInputElement>e.target).value)} inputmode="${question.type}" .value=${this.currentValue} />
```

(This happens only on our production build - will describe all the rollup plugins involved)

The difference between the two is that the working code places the `@input` directive before the the `.value` directive.
Checked using the chrome dev tools and saw that there are no listeners on the input element when the first block is in the code.

### Rollup plugins
- resolve `"@rollup/plugin-node-resolve": "9.0.0"`
- minifyHTML `"rollup-plugin-minify-html-literals": "1.2.6"` - production build only
- typescript `"rollup-plugin-typescript2": "0.30.0"`
- terser `"rollup-plugin-terser": "7.0.2"` - production build only

Terser configuration:
```javascript
    environment === 'production' && terser({
      ecma: 2017,
      module: true,
      warnings: true,
      mangle: {
        properties: {
          regex: /^__/,
        },
      },
    }),
```

# Steps to Reproduce

Could reproduce multiple times on the project itself. Cannot reveal the code. Please advise on that.

## Expected Results

Both code blocks should work the same

## Actual Results

Accidently found that re-ordering works around it.

## Browsers Affected

- [ X] Chrome
- [X] Mobile Chrome

**Comment by justinfagnani** [comment]
If this is happening on the production build only, can you reduce the build steps further to try to see which one is causing the issue? I would suspect `rollup-plugin-minify-html-literals` could have a bug around the templates themselves, or Terser if it's running against Lit source.

If it's possible to located and paste in the minified template that might help too.

**Comment by eavichay** [comment]
`rollup-plugin-minify-html-literals` to be blamed. Closing, will create an issue there.

Thanks.
