### ISSUE TITLE
npm releases and release notes

### ISSUE THREAD

**Issue by jimmont** [lit/lit#2055]
## Description

- Who wants the functionality:
as a consumer of lit and lit-*
- What it is they want
when finding info about releases
via npm and the github Releases link https://github.com/lit/lit/releases
I want to be able to find current release info
- Why they want it
so that I can appropriately update/audit/manage my dependencies
- Functional description of task/subtask
easy solution: please link from the github /releases page to the various specific lit-* release notes as fits

## Acceptance criteria

What the card must do in order to accept it as complete. Acceptance Criteria must be concrete or measurable.
----> when I search npm for "lit" and follow links for the associated owned results, I can select the obvious releases link or directly arrive at a page where I can either see or more likely link to the current release info for that specific thing
----> when following to the /releases link I can find/follow links to release info for relevant specific lit-* things

How this came up: I was using `npm outdated` and we couldn't figure out (superficially) why there was a release of lit-html beyond 1.3.0, because we couldn't find the release notes, as we were preparing to update all our lit-* dependencies and had a few problems in our bundling process as well where it was (superficially) unclear if it was caused by the update or the (overly complicated) build+bundle process.

**Comment by kevinpschaaf** [comment]
Thanks for pointing this out. We manually updated the release text for all the releases on https://github.com/lit/lit/releases, and are working on automating this process. Thanks for bearing with us.

**Comment by kevinpschaaf** [comment]
Release notes based on changelogs (which are enforced and automated via [changesets](https://github.com/changesets/changesets#readme)) are now automatically posted to https://github.com/lit/lit/releases on each release.
