### ISSUE TITLE
Documentation: final release roadmap

### ISSUE THREAD

**Issue by rallets** [lit/lit#2069]
Hi, I'm actually using lit-element 2.5.1 and lit-html 1.4.1, and the [documentation website](https://lit-html.polymer-project.org/guide) is saying there is a new version of LIT. 
But after a while I noticed it's still in RC.3. 
Do you have a roadmap about a stable release version? Or do you think it's safe to use? Also the typescript template is using RC1.
Thanks

**Comment by thescientist13** [comment]
I observed they have a couple milestones open in their repo and once called [_Lit RC.next_](https://github.com/lit/lit/milestone/21) which might be a good representation of gauging remaining scope.

That said, it would be great to hear something more formal (blog post, tweet) to get a sense of where this new RC may put the project in the context of a final release.

**Comment by justinfagnani** [comment]
The final 2.0 release was made last week!
