### ISSUE TITLE
[lit-html] Vend a testing utility to strip part markers

### ISSUE THREAD

**Issue by Waxolunist** [lit/lit#2080]
# Description

I have a template, which uses repeat. Snapshot tests fail now. 

Before updating to lit@2.0 snapshots looked as follows:

```
<!----> <my-element ....
```

Now they look as follows:

```
<!--?lit$936338967$--><!----> <my-element ....
```

the test:

```
  it('renders correctly', async () => {
    const element = await fixture(
      html` <my-element></my-element>`
    );
    expect(element.shadowRoot!.innerHTML).toMatchSnapshot();
  });
```

How can I force lit to not render this comment.

**Comment by Waxolunist** [comment]
I remove now comments with a regex, that works. Maybe you can give a hint to the utilities in the doc?

**Comment by Waxolunist** [comment]
Here is my code, just in case, someone has the same problem:

```
export const cleanHTML = (el: Element): string => {
  const innerHTML = el.shadowRoot!.innerHTML;
  return innerHTML.replace(/<!--([\s\S]*?)-->/g, '');
};
```

Usage:
```
  it('renders correctly', async () => {
    const element = await fixture(
      html` <my-element></my-element>`
    );
    expect(cleanHTML(element)).toMatchSnapshot();
  });
```

**Comment by justinfagnani** [comment]
I think we should address this by publishing a test utility package that includes functions to strip expression markers.

**Comment by justinfagnani** [comment]
We have this in `@lit-labs/testing` now.
