### ISSUE TITLE
documentation lit-html usage within/from Lit

### ISSUE THREAD

**Issue by jimmont** [lit/lit#2185]
in the lit-html usage, upgrade guide and standalone, please add a mention that the installed version of `lit` exports everything it has (including `render`, etc) from it's respective version of lit-html via `lit/html.js`

in my case I wanted to render to the DOM/light-dom so:

```
import { render } from 'lit/html.js';
// then example usage as expected for lit-html later
class extends LitElement{
  connectedCallback(){
    super.connectedCallback()
    render(html`...`, this)
  }
  render(){
    return html`<slot></slot>`;
  }
  ...
```

thanks

**Comment by kevinpschaaf** [comment]
Fixed in https://github.com/lit/lit.dev/pull/514, site is now live: https://lit.dev/docs/releases/upgrade/#update-standalone-lit-html-imports
