### ISSUE TITLE
[Starter kits] Can't run demo

### ISSUE THREAD

**Issue by arthurevans** [lit/lit#2213]
The starter kit instructions (https://lit.dev/docs/tools/starter-kits/#try-out-your-project) tell you to access the project demo at `http//localhost:8000/dev/` ... However, the new WDS-based serve command has its root in the `/docs/` folder, so you can't access the demo. 

There's a separate `docs:serve` command that sets the root dir to `/docs/`, so this just seems like an oversight in the config.

**Comment by kevinpschaaf** [comment]
@AndrewJakubowicz Did https://github.com/lit/lit/pull/2300 close this issue?

**Comment by AndrewJakubowicz** [comment]
Yes! https://github.com/lit/lit/pull/2300 resolved this issue. Demo and docs both work now.
