### ISSUE TITLE
polyfill-support: (import all lit during build) / lit2 css: (Force PolyFill) solved 2x

### ISSUE THREAD

**Issue by busynest** [lit/lit#2224]
# Description

Firebase Hosting does not load webcomponents + polyfill-support + es5 adapter properly.
All projects upload normal, but are unread because Firebase creates .js.map, and adds HTML header to js file.

# Steps to Reproduce

1. Index file with script source to webcomponents + pollyfill-support
2. Upload

## Live Reproduction Link

super basic project just started: https://github.com/busynest/gubbled

## Expected Results

Firebase Hosting to load webcomponents without .js.map, without HTML header within js files.

## Actual Results

`Uncaught SyntaxError: Unexpected token '<'`

## Browsers Affected
- [*] Chrome
- [*] Firefox
- [*] Edge
- [*] Safari 11
- [*] Safari 10
- [*] IE 11

**Comment by justinfagnani** [comment]
Sorry, I'm having trouble understanding this issue. Are you saying that Firebase Hosting is adding HTML markup to a .js file? If so that sounds like either a Firebase Hosting bug or a misconfiguration.

**Comment by busynest** [comment]
Hard to pinpoint the problem.
* TypeScript : working in circles configuring and uploading
* Rollup vs Polymer Build : Both give off same errors
* Firebase: Single Page App routing,

Files upload normal, but don't know what injects HTML into JS
All three webpack + rollup + polymer build - sort of suck
on top of that, need to learn open-ui bundle + TypeScript -- Project build

It's a lot of parts. Build is the most important part of web app.

**Comment by busynest** [comment]
Compared to the master project:
* working js files : YELLOW
* wrongly mapped js fils : BLUE

**Comment by busynest** [comment]
I have remove / disabled  everything.

even removed hosting single page app

Firebase is broken in my opinion

**Comment by busynest** [comment]
@justinfagnani Thank you for the input. It helped a lot!
The issue was configuration of dependencies and firebase.json

**Comment by busynest** [comment]
Still getting an error for polyfill-support.js

**Comment by busynest** [comment]
importing the entire "lit" folder seems to make it work. 
(polyfill-support.js has sourceMap comment that requires d.ts files)
but it's based on the other browsers, chrome has some deep chache that doesn't clear.

because the other brower is show okay. It has to be good.
I will try not to comment and text again for a few days. sorry for bugging everyone.

**Comment by busynest** [comment]
Why has the render glitch come back to a new project?
polyfill-support must be acting up

**Comment by busynest** [comment]
Oh yea this:

      
      <script
        async
        Set-Cookie: polyr=poly; SameSite=Lax>
          // Force Polyfills
          if (window.customElements) window.customElements.forcePolyfill = true;
          ShadyDOM = { force: true };
          ShadyCSS = { shimcssproperties: true};
      </script>
