### ISSUE TITLE
[labs/ssr] Cannot SSR a dynamic tag with `unsafeStatic`

### ISSUE THREAD

**Issue by shakyShane** [lit/lit#2246]
https://gist.github.com/shakyShane/423b19e9f479b06369eb90f4f503310a

The following stand-alone code examples both cause the error `Error: unexpected final partIndex: 0 !== 1`. 

I'm using `unsafeStatic` in a controlled way (eg: not user-provided data).

```js
import "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { render as renderDomShim } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { html, unsafeStatic } from 'lit/static-html.js'
import { LitElement } from 'lit'

/**
 * Rendering a static `<p>` fails
 *
 * ```
 * Error: unexpected final partIndex: 0 !== 1
 * ```
 */
const staticP = unsafeStatic('p');
for (const part of renderDomShim(html`<${staticP}>hello</${staticP}>`)) {
  console.log(part);
}

/**
 * Rendering a custom element also fails
 */
customElements.define('any-thing', class extends LitElement {
  render() {
    return html`<p>Hello world</p>`
  }
})

const element = unsafeStatic('any-thing');
for (const part of renderDomShim(html`<${element}>hello</${element}>`)) {
  console.log(part);
}
```

Any help will be greatly appreciated :)

**Comment by shakyShane** [comment]
@justinfagnani thanks for the clarity. I've worked around it with a patch for the time being, but who knows what that patch might otherwise break 😢

**Comment by justinfagnani** [comment]
@shakyShane I can't speak to the priority of this quite yet, but I am ramping up on a bunch of SSR work. I will try to take a closer look soon.

**Comment by justinfagnani** [comment]
btw, @shakyShane just so you're aware, SSR support for static templates might be very tricky. It's probably similar to React and `dangerouslySetInnerHtml` where for hydration you'll need to overwrite the whole template instance.

**Comment by dunqan** [comment]
@justinfagnani is there any update for it? even partial one, i.e. to be able to render dynamic tags without hydration support (or with some drawback, like dropping server side rendered shadow DOM, and just recreate it on client side completely)?

If not, what would be the best approach for now, to have some data driven dynamic tags with Lit, working both on SSR and client side?

**Comment by tpluscode** [comment]
I just found this and would really appreciate if dynamic tags worked in SSR

@shakyShane can you share your patch? It could just work for me for the time being too

**Comment by PonomareVlad** [comment]
@tpluscode try this:

```js
const tag = unsafeStatic(`${this.route.page}-page`);
return html`<${tag}></${tag}>${null} `;
```

**Comment by tobi-or-not-tobi** [comment]
@PonomareVlad great catch! Thanks for sharing!

@justinfagnani our project would benefit massively from the trick found by @PonomareVlad. The question if we can trust this to continue to work, or if it could fail in future versions? Also, would this magic help you to standardise this as a feature?

**Comment by PonomareVlad** [comment]
@tobi-or-not-tobi I've been using this method for a while in production, but with caution. 🥴

In my case, I've tested some legacy directives and they (seem to) work correctly without mismatch on hydration.  

However, I have not yet tested how this works with "new" tools such as labs/context and labs/virtualizer.

**Comment by dgp1130** [comment]
Ran into this today and just wanted to add a motivating use case. `<template />` tags require static expressions which means that declarative shadow DOM also requires static expressions. I know shadow DOM is usually done at the component level, but I think there's still significant value in supporting it at the template level:

```typescript
render(html`
  <template shadowrootmode="open">
    <div>Hello, World!</div>
    <style>div { color: red; }</style>
  </template>
`);
```

I don't fully understand why `<template />` tags require static expressions, but does that reasoning also apply in the declarative shadow DOM case? I would imagine Lit can mostly treat a DSD template as containing regular HTML rather than arbitrary template text which could represent anything. I'm not sure if that helps address the need for static expressions, or if they still need to be supported in SSR for DSD use cases.
