### ISSUE TITLE
Use `Set.size` instead of `Set.length`

### ISSUE THREAD

**Issue by mghweb** [lit/lit#2278]
# Description

You are unable to return an array of styles in `static get styles()` for LitElement extended classes.

In the `ReactiveElement.finalizeStyles` method you are referencing `Set.length` which is not a property that exists. Use `Set.size` instead.

## Expected Results

Allow an array of styles to be returned from `static get styles()`

## Actual Results

No errors are thrown. It just simply does not adopt the stylesheets if you use an array.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
@mghweb I can't find the code you're talking about, nor reproduce any problem with using arrays of styles. Can you clarify and add a reproduction?

Here's my attempt: https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgQ1NTUmVzdWx0R3JvdXB9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbmNsYXNzIEJhc2VFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXM6IENTU1Jlc3VsdEdyb3VwID0gW1xuICAgIGNzc2BwIHsgY29sb3I6IGJsdWUgfWAsXG4gICAgY3NzYDpob3N0eyBkaXNwbGF5OiBibG9jazsgYmFja2dyb3VuZDogeWVsbG93O31gXG4gIF07XG59XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgQmFzZUVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gW0Jhc2VFbGVtZW50LnN0eWxlcywgY3NzYHAge2ZvbnQtd2VpZ2h0OiBib2xkO31gXTtcblxuICBAcHJvcGVydHkoKVxuICBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-YDtcbiAgfVxufVxuXG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

**Comment by sorvell** [comment]
Going to close this as we can't identify that issue. Please open a new issue with more info if necessary. Thanks.
