### ISSUE TITLE
Question about class fields, decorator proposal

### ISSUE THREAD

**Issue by jogibear9988** [lit/lit#2284]
I've discoverd in polymer that "observe" does not work when I use es2022 class fields.
see: https://github.com/Polymer/polymer/issues/5695

I then looked in lit, how you have solved this here, only to find you didn't. :-)
see: 
https://lit.dev/docs/components/properties/#avoiding-issues-with-class-fields
https://lit.dev/docs/components/decorators/#avoiding-issues-with-class-fields

as you state in the second link, 
"but it should be solved as the proposal evolves and matures."
I wanted to know, is there an issue at https://github.com/tc39/proposal-decorators wich mentions the problem?
where I could see what's planned?

At the moment I solve this using get/set on the class, is this the best way atm?

**Comment by justinfagnani** [comment]
This issue is very well known by the decorators champions. It's why the `accessor` keyword exists - to make a field generate accessors on the prototype that can be metaprogramed over.
