### ISSUE TITLE
allow `host` to be any object rather than just `EventTarget`

### ISSUE THREAD

**Issue by 43081j** [lit/lit#2285]
Currently lit types `host` as `EventTarget`, which means we can only ever set the event context as an element. Internally, though, it doesn't actually care if it is an event target or not and just passes it directly through `call` (i.e. `call(host, arg)`).

So logically it seems we could type `host` as pretty much anything (`unknown`?).

Our use case is that we have some cell renderers for [ag-grid](https://github.com/ag-grid/ag-grid) which render lit templates, and we want the event handlers in them to be bound to the cell render (which isn't an element).

**Comment by justinfagnani** [comment]
The `host` option is already typed as `object`: https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L380

Are you looking at an old version?

**Comment by 43081j** [comment]
Aha good catch. Looks like I was pulling in an old lit by accident through a dependency. 

My mistake 🙈
