### ISSUE TITLE
`addInitializer` callbacks should be called in the constructor

### ISSUE THREAD

**Issue by bennypowers** [lit/lit#2289]
# Description

`addInitializer` is primarily suited to adding controllers via decorators, and so it's described in the [documentation](https://lit.dev/docs/components/lifecycle/#external-lifecycle-hooks:-controllers-and-decorators), but it's implementation makes that overly difficult for users. Allow me to explain:

I might add a `LoggerController` via `addInitializer`, but if I then call `this.logger.log` on an element between the `constructor` and `firstUpdated`, I’ll get an error.

```ts
class Logger implements ReactiveController {
  constructor(private host: ReactiveElement) {
    host.logger = this;
    host.addController(this);
  }

  hostConnected() {
    console.log('Don\'t Miss this!');
  }
  
  log(...x) { console.log(...x) }
}
  
function logger(proto: typeof ReactiveElement) {
  proto.addInitializer(x => new Logger(x));
}

@logger @customElement('simple-greeting')
export class WhoopsE extends LitElement {
  static styles = css`p { color: blue }`;

  @property() name = 'Somebody';

  render() { return html`<p>Hello, ${this.name}!</p>`; }
  
  constructor() {
    super();
    this.logger.log('whoops');
  }
}
```

[playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgUmVhY3RpdmVDb250cm9sbGVyLCBSZWFjdGl2ZUVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbmNsYXNzIExvZ2dlciBpbXBsZW1lbnRzIFJlYWN0aXZlQ29udHJvbGxlciB7XG4gIGNvbnN0cnVjdG9yKHByaXZhdGUgaG9zdDogUmVhY3RpdmVFbGVtZW50KSB7XG4gICAgaG9zdC5sb2dnZXIgPSB0aGlzO1xuICAgIGhvc3QuYWRkQ29udHJvbGxlcih0aGlzKTtcbiAgfVxuXG4gIGhvc3RDb25uZWN0ZWQoKSB7XG4gICAgY29uc29sZS5sb2coJ0RvblxcJ3QgTWlzcyB0aGlzIScpO1xuICB9XG4gIFxuICBsb2coLi4ueCkgeyBjb25zb2xlLmxvZyguLi54KSB9XG59XG4gIFxuZnVuY3Rpb24gbG9nZ2VyKHByb3RvOiB0eXBlb2YgUmVhY3RpdmVFbGVtZW50KSB7XG4gIHByb3RvLmFkZEluaXRpYWxpemVyKHggPT4gbmV3IExvZ2dlcih4KSk7XG59XG5cbkBsb2dnZXIgQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgV2hvb3BzRSBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBAcHJvcGVydHkoKSBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7IHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMubmFtZX0hPC9wPmA7IH1cbiAgXG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKCk7XG4gICAgdGhpcy5sb2dnZXIubG9nKCd3aG9vcHMnKTtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

As well, if the controller that I add using` addInitializer` has a `hostConnected` callback, it won’t get called if it’s added via addInitializer, because that will get called after the component is already connected. so in short, `addInitializer` may break controller composition.

We could guard against that in the controller's constructor:

```ts
  constructor(private host: PFElement) {
    host.addController(this);
    if (host.isConnected)
      this.hostConnected();
  }
```
but that kind of breaks the contract (or at least the user’s expectations) with controllers - they shouldn’t have to have prior knowledge like that

Note that we can work around these issues above by calling the `@logger` decorator before the `@customElement()` decorator so as to prevent element upgrades until the logger is instantiated, but this seems an artificial limitation to me.

Is it possible to move `addInitializer` callback calls up into the constructor?

**Comment by sorvell** [comment]
I don't think there's anything good we can do here.

Applying the `@logger` decorator *before* the `@customElement` decorator in the code means it runs after it and the custom element is defined and elements are constructed before the initializer is installed. This causes the call to `this.logger` to fail since the initializer hasn't been installed on the class yet and it sets up this reference.

We could make `@customElement` async but this would be a breaking change.
