### ISSUE TITLE
[labs/task] `render` does not return a useful type

### ISSUE THREAD

**Issue by mohe2015** [lit/lit#2301]
# Description

When using `render` of a `@lit-labs/task` `Task` the method is typed as having a return type of `unknown`.

# Steps to Reproduce

1. Write this code

```ts
import type { Task } from "@lit-labs/task/task.js";

const task: Task = undefined!;

// Type 'unknown' is not assignable to type 'number'.ts(2322)
const test: number = task.render({
  complete: () => 1
})
```

2. The code does not typecheck because it tries to assign type `unknown` to `number`. (Adding the three other handlers does not help as you can see in how the source code is typed)

**Comment by mohe2015** [comment]
Sorry for bumping but I think this is one of the main annoyances and from my attempt you can see that the current thing is really hard to type

**Comment by sorvell** [comment]
We'll likely want to introduce a generic that's set when the task is defined and piped to the render return type.

**Comment by e111077** [comment]
I think this should be fixable in TS, but the underlying issue here is that `Task.render` is not intended to be used outside of rendering. With the latest release, `Task.value` should not change value needlessly to `undefined` anymore and be more "stable". Does `Task.value` fit your use case?

additionally, pedantic issue, in your case, your typing is wrong – it should be:

```ts
const test: number|undefined = task.render({
  complete: () => 1
})
```

**Comment by taylor-vann** [comment]
I have an existing PR that addresses this issue. It's been a while though. I'll update and post.

https://github.com/lit/lit/pull/2821

**Comment by justinfagnani** [comment]
I'm not sure there's anything very useful to do here. We could type `render()` as returning the union of the renderer methods passed to it. That's about the most accurate thing we can do, but I'm not sure what value that has.
