### ISSUE TITLE
[lit-localize] [ssr] Return a setLocale method along side withLocale when calling configureSsrLocalization

### ISSUE THREAD

**Issue by pika11** [lit/lit#2313]
## Description

- Who
Your friends at Reddit <3

- What 
A way to change the locale inside the `withLocale` async context, returned from [`configureSsrLocalization`](https://github.com/lit/lit/blob/main/packages/localize-tools/src/ssr.ts#L43) 

- Why 
`withLocale` context can be initialize very early on the request/response flow, sometime there's a need to change the `locale` value after getting async data from external sources.

- Functional description
`configureSsrLocalization` to return a `setLocale` method that provides an API to access and update the AsyncLocalStorage locale value. https://github.com/lit/lit/blob/main/packages/localize-tools/src/ssr.ts#L68 

## Acceptance criteria

It should be possible to change the AsyncLocalStorage storage locale value from inside the `withLocale` async context.

**Comment by aomarks** [comment]
Is this because you are rendering multiple locales within the same request?

**Comment by pika11** [comment]
no, it's just one locale for one request.

**Comment by aomarks** [comment]
Then can you do the async call that tells you the locale before calling `withLocale`? Something like this:

```js
async handleRequest() {
  const locale = await getLocale(...);
  withLocale(locale, () => {
    ...
  });
}
```

**Comment by pika11** [comment]
That would be ideal yeah. But currently our withLocale wrapping happens early in a middleware and the locale request happens after that on the request resolution.

**Comment by aomarks** [comment]
> That would be ideal yeah. But currently the withLocale wrapping happens early in a middleware and the locale request happens after that on the request resolution.

I see. I guess I feel a little reluctant to add complexity to the API here, since it seems like it's a workaround for a factoring issue. It doesn't really make sense for a user to call `withLocale` if they don't know what the locale is yet.

I think you should be able to just make another `withLocale` call from within the first one -- would that be a good enough workaround?

**Comment by pika11** [comment]
Oh I see. This might work, allow me some time to test this out.

**Comment by pika11** [comment]
Changing the location of where the withLocale wrapping happens ended up being the best way to move forward 

Closing this issue, thank you @aomarks
