### ISSUE TITLE
[@lit-labs/task] Task function never call if there are no deps

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#2317]
# Description

There are two related problems with using Task with no deps (an always executed once task):
  1. new Task() doesn't support being called with no deps function
  2. A deps function of `() => []` causes the task function to never be called

# Steps to Reproduce

1. Write this code

```ts
  new Task(this, fn, () => [])
```

2. See this output...

## Live Reproduction Link
https://lit.dev/playground/#project=W3sibmFtZSI6Im15LWVsZW1lbnQudHMiLCJjb250ZW50IjoiaW1wb3J0IHtMaXRFbGVtZW50LCBodG1sfSBmcm9tICdsaXQnO1xuaW1wb3J0IHt1bnRpbH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvdW50aWwuanMnO1xuaW1wb3J0IHtpbml0aWFsU3RhdGUsIFN0YXR1c1JlbmRlcmVyLCBUYXNrfSBmcm9tICdAbGl0LWxhYnMvdGFzayc7XG5cbmNvbnN0IGZldGNoRGF0YSA9IGFzeW5jICgpID0-IHtcbiAgLy8gQWRkIHNvbWUgZGVsYXkgZm9yIGRlbW8gcHVycG9zZXNcbiAgYXdhaXQgbmV3IFByb21pc2U8dm9pZD4oKHIpID0-IHNldFRpbWVvdXQoKCkgPT4gcigpLCAxMDAwKSk7XG4gIGlmIChNYXRoLnJhbmRvbSgpIDwgMC4yKSB7XG4gICAgdGhyb3cgbmV3IEVycm9yKCdTb21lIGVycm9yJyk7XG4gIH1cbiAgXG4gIHJldHVybiAnTG9yZW0gaXBzdW0nO1xufTtcblxuY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgX2NvbnRlbnQgPSBuZXcgVGFzayh0aGlzLCBmZXRjaERhdGEsICgpID0-IFtdKTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8aDM-VGFzayBleGFtcGxlPC9oMz5cbiAgICAgICR7dGhpcy5fY29udGVudC5yZW5kZXIoe1xuICAgICAgICBwZW5kaW5nOiAoKSA9PiBodG1sYDxzcGFuPkxvYWRpbmcuLi48L3NwYW4-YCxcbiAgICAgICAgZXJyb3I6IChlcnIpID0-IGh0bWxgPHNwYW4-JHtlcnJ9PC9zcGFuPmAsXG4gICAgICAgIGNvbXBsZXRlOiAoY29udGVudCkgPT4gY29udGVudCxcbiAgICAgIH0pfVxuICAgIGA7XG4gIH1cbn1cbmN1c3RvbUVsZW1lbnRzLmRlZmluZSgnbXktZWxlbWVudCcsIE15RWxlbWVudCk7XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjxzdHlsZT5cbiAgYm9keSB7IGZvbnQtZmFtaWx5OiBzYW5zLXNlcmlmOyB9XG48L3N0eWxlPlxuXG48c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL215LWVsZW1lbnQuanNcIj48L3NjcmlwdD5cblxuPG15LWVsZW1lbnQ-PC9teS1lbGVtZW50PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

## Expected Results

The task function is called

## Actual Results

It's not

**Comment by mohe2015** [comment]
Not sure about empty parameters or no `deps` function but I think there should be a way to create a `Task` without letting it fire at the start. Because then you can use it for form submission etc. Also I think an explicit `forceRerun` function should be provided.

**Comment by justinfagnani** [comment]
@mohe2015 let's open a new issue for that.

**Comment by justinfagnani** [comment]
Opened https://github.com/lit/lit/issues/2323 for non-automatic tasks. The solution might overlap with this.

**Comment by mohe2015** [comment]
I think this can be closed.

**Comment by sorvell** [comment]
Closing based on merged PRs listed above.
