### ISSUE TITLE
[ssr] No easy interop with 3rd party custom elements

### ISSUE THREAD

**Issue by shakyShane** [lit/lit#2321]
# Description

If I load into memory (via a bundler for example) a 3rd-party custom element script such as [@github/clipboard-copy-element](https://www.npmjs.com/package/@github/clipboard-copy-element) - Lit will not render its attributes since it cannot find a suitable elementRenderer.

This is a huge foot-gun since a user of my framework would expect Lit to simply skip over something it cannot render (which it does) but to preserve it's inline attributes in the resulting HTML. 

It occurs here:

https://github.com/lit/lit/blob/dcab56b0eeef6e05969c3682d3275a30ddf18d97/packages/labs/ssr/src/lib/render-lit-html.ts#L695-L699

# Steps to Reproduce

1. Write this code

```js
import "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import "@github/clipboard-copy-element";
import { render } from "@lit-labs/ssr";
import { html } from "lit";

const input = html`
  <clipboard-copy for="login" shane="here">
    Copy
    <span class="notice" hidden>Copied!</span>
  </clipboard-copy>
`;

for (let string of render(input)) {
  console.log(string);
}
```

Output: 

```html
<!--lit-part uzegxRF9tt8=-->

  <clipboard-copy  
>

    Copy
    <span class="notice" hidden>Copied!</span>
  </clipboard-copy>

<!--/lit-part-->

```

Is there a go-to solution for this problem, outside of a custom elementRenderer?

Thanks :)

**Comment by shakyShane** [comment]
Actually, even a custom element renderer will not work for custom elements that do work inside of their constructors.

**Comment by shakyShane** [comment]
For the example above, the following works and allows the custom-element to be server-rendered with it's attributes.

```ts
class MyRenderer extends ElementRenderer {
  constructor(tagName) {
    super(tagName);
    const attrs = [];
    this.element = {
      attributes: attrs,
      getAttribute: (qualifiedName) => {
        return attrs.find((x) => x.name === qualifiedName);
      },
      setAttribute: (qualifiedName, value) => {
        attrs.push({ name: qualifiedName, value });
      },
    };
  }
  attributeChangedCallback(name, old, value) {
    // no-op
  }

  static matchesClass(arg1, arg2) {
    return true;
  }
}
```

**Comment by justinfagnani** [comment]
I think this is just a bug in that if there is no renderer available, we should always write attributes.

**Comment by shakyShane** [comment]
@justinfagnani thank you! I'm glad I was thinking along the correct tracks here.

**Comment by shakyShane** [comment]
thanks @aomarks this looks great :)
