### ISSUE TITLE
[ssr] unnecessary dependencies

### ISSUE THREAD

**Issue by mohe2015** [lit/lit#2339]
# Description

the `@lit-labs/ssr` package seems to have unnecessary dependencies like https://github.com/lit/lit/search?q=koa-node-resolve that only seem to be used in tests/demos. Maybe they should be split up into a separate package?

**Comment by justinfagnani** [comment]
Those should probably just move into `devDependencies`. I don't think we need another package necessarily, though we might want separate demos packages independently.
