### ISSUE TITLE
[labs/task] Improve ergonomics of `taskComplete` promise

### ISSUE THREAD

**Issue by sorvell** [lit/lit#2347]
There are a few issues with the `taskComplete` promise.

* It's marked with `!` on the class, but it's only created when the task runs. 
* If a user accesses it before the task runs for example when the Task is created, there's an error.
* If a user accesses it for a manually run task, `autoRun` set to false, there's an error.

Perhaps it can just be initialized when the Task is created?

**Comment by sorvell** [comment]
The `taskComplete` promise should always be available and should always be resolved when the next "run" completes or errors. We'll do this by making the promise when the Task is created and refreshing it whenever a run completes or errors.

**Comment by justinfagnani** [comment]
This should be fixed by https://github.com/lit/lit/pull/3947 which makes `taskComplete` a getter. It's now ok to access the getter at any time.
