### ISSUE TITLE
[ssr] Make test utility for testing components in SSR

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#2351]
We need a way for component authors to ensure that their components are SSR compatible. This might include running all or a subset of existing component tests via SSR, or a set of utilities for writing SSR-specific tests.

We have some SSR test utilities in the @lit-labs/ssr package itself, but they probably aren't in the shape we'd want to our users to consume.

**Comment by augustjk** [comment]
Completed in https://github.com/lit/lit/pull/2957
