### ISSUE TITLE
Depricated web standard

### ISSUE THREAD

**Issue by milcaunicorn** [lit/lit#2355]
https://github.com/lit/lit/blob/483943034a62bded13eca0c982ff7c93ac6639b6/packages/lit-html/src/lit-html.ts#L467-L472

expandEntityReferences parameter is depricated.

https://dom.spec.whatwg.org/#dom-document-createtreewalker

Understand the backwards compatebility, but this looks like it is not necessary since it actually is optional parameter anyway.
https://developer.mozilla.org/en-US/docs/Web/API/TreeWalker/expandEntityReferences

It is also make it confusing since if you do not deal with the same, but  newer version of typescript one would get this:
error: TS2554 [ERROR]: Expected 1-3 arguments, but got 4.
  false

see typscript type libs here:
https://github.com/microsoft/TypeScript/blob/4e39023396f03907f7c9fecb9ad72d5f42256eff/lib/lib.dom.d.ts#L4564-L4569

**Comment by web-padawan** [comment]
See https://github.com/lit/lit/issues/2035#issuecomment-893677602 where the same concern was answered previously.

**Comment by milcaunicorn** [comment]
> See [#2035 (comment)](https://github.com/lit/lit/issues/2035#issuecomment-893677602) where the same concern was answered previously.

Yes, totally aware of calling it with 4 parameters, does not matter if you do it directly in in the browser it is the transpeiling/bundling where it goes bad since expandEntityReferences parameter is removed in ts.

In this case what to do to get it to work with the new changes in microsofts; lib.dom.ts?

**Comment by justinfagnani** [comment]
IE requires all four parameters. But this is our code, what's the problem if there's a deprecated parameter?

**Comment by milcaunicorn** [comment]
Nope, and you should not change your code. Just that it would have been nice with types that makes it forward compatible with ts 4.4.*

**Comment by milcaunicorn** [comment]
> IE requires all four parameters. But this is our code, what's the problem if there's a deprecated parameter?

Nope, and you should not change your code. Just that it would have been nice with types that makes it forward compatible with ts 4.4.*

**Comment by kevinpschaaf** [comment]
Closing issue, as this is not a user-facing issue afaict.
