### ISSUE TITLE
[labs/observers] Unable to install

### ISSUE THREAD

**Issue by himerus** [lit/lit#2366]
# Description

Unable to install `@lit-labs/observers` via `npm` or `yarn`. 

# Steps to Reproduce

Run either `npm install @lit-labs/observers` per [installation instructions](https://github.com/lit/lit/blob/main/packages/labs/observers/README.md#installation) or `yarn add @lit-labs/observers` 

## Expected Results

Ability to add `@lit-labs/observers` to my repo for testing. :) 

## Actual Results

- `➜ npm install @lit-labs/observers`
```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lit-labs%2fobservers - Not found
```
- `➜ yarn add @lit-labs/observers --dev`
```shell
yarn add v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@lit-labs%2fobservers: Not found".
```

**Comment by thescientist13** [comment]
It probably hasn't been published yet, as it looks like package is only [3 days old](https://www.npmjs.com/search?q=%40lit-labs%2Fobservers) 😅

**Comment by himerus** [comment]
Yes, but I've been needing this functionality for the last 2 weeks! ;) 

I jest, thanks for all the hard work on the latest version of Lit, and the power it's giving our team to do all sorts of great work!

I'm really excited to try this controller out!

**Comment by AndrewJakubowicz** [comment]
This labs package is now published here: https://www.npmjs.com/package/@lit-labs/observers

Looking forward to hearing how it works for you, and thank you for your patience!
