### ISSUE TITLE
[labs/task] Allow setting initial data

### ISSUE THREAD

**Issue by mohe2015** [lit/lit#2367]
# Description

If you do navigation preloading or similar you may already have the data for the task at component creation time. Then it would make sense to be able to either set that data manually at Task creation time or using some attributes.

The simplest but probably also most unclean change would be to make `_value`

https://github.com/lit/lit/blob/57a53e1c85216a4255e9f700402ef6cbe37a4167/packages/labs/task/src/task.ts#L108

 public and name it `value`

# Steps to Reproduce

```ts
import {Task} from '@lit-labs/task';

this._apiTask = new Task(
  this,
  taskFunction,
  () => /** @type {[URLSearchParams]} */ ([this.history.url.searchParams])
);
 if (this.initial !== undefined) {
  this._apiTask.status = TaskStatus.COMPLETE;
  // TODO FIXME don't use this private attribute that got minified
  this._apiTask.P = this.initial;
}
```

**Comment by sorvell** [comment]
We are planning to add a mechanism for setting an initial value. This will be independent of the task's status. In other words, the task can have a value and be in the initial status.
