### ISSUE TITLE
'node_modules/lit/index.js' does not provide an export named 'TemplateResult'

### ISSUE THREAD

**Issue by angrycat9000** [lit/lit#2371]
# Description

TemplateResult is not exported, but is listed in [the documentation](https://lit.dev/docs/api/templates/#TemplateResult).

# Steps to Reproduce

1. Write this code

```ts
import {TemplateResult} from 'lit';
```

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-pyk2ve?devtoolsheight=33&file=src/index.js

## Expected Results

TemplateResult is imported and the code runs.

## Actual Results

Uncaught SyntaxError: The requested module '/node_modules/lit@2.0.2/index.js' does not provide an export named 'TemplateResult'

## Browsers Affected

Probably all but here is what I tested in.

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by aomarks** [comment]
`TemplateResult` is purely a typescript type, so it doesn't have a corresponding value in javascript.

**Comment by angrycat9000** [comment]
Thanks for the info @aomarks 

That was confusing for me as a Javascript developer because it used to have an exported value in `lit-element@2.5.1` and is listed in the current docs with an export example.

I also found [this comment](https://github.com/lit/lit/issues/1821#issuecomment-829719229) which had the solution I needed of using `isTemplateResult` to test a value.

**Comment by aomarks** [comment]
> 

We should probably mention is template result in the docs for TemplateResult.

**Comment by orty** [comment]
Hi, 

I am also struggling with this issue since I try to declare variables using this interface to strongly-type them.

An example below :
```
export type Card = {
    title: string | TemplateResult;
    description: string | TemplateResult;
    logo: string | TemplateResult;
};
```

Back when we were using `lit-html` v1, no issue occurred with the linter, and we could also do `import { TemplateResult } from 'lit-html';`. Now that we are on `lit` v2, I understand that we cannot import this anymore, but the linter complains about `TemplateResult` not being found
![image](https://user-images.githubusercontent.com/759736/150171117-8594716a-27d5-4f52-a799-9c27882d1ff7.png)

What can we be missing ?

Thanks

**Comment by p-ob** [comment]
> Hi,
> 
> I am also struggling with this issue since I try to declare variables using this interface to strongly-type them.
> 
> An example below :
> 
> ```
> export type Card = {
>     title: string | TemplateResult;
>     description: string | TemplateResult;
>     logo: string | TemplateResult;
> };
> ```
> 
> Back when we were using `lit-html` v1, no issue occurred with the linter, and we could also do `import { TemplateResult } from 'lit-html';`. Now that we are on `lit` v2, I understand that we cannot import this anymore, but the linter complains about `TemplateResult` not being found ![image](https://user-images.githubusercontent.com/759736/150171117-8594716a-27d5-4f52-a799-9c27882d1ff7.png)
> 
> What can we be missing ?
> 
> Thanks

Can you do the following:
```ts
import type { TemplateResult } from 'lit';
```

They do [export the type](https://github.com/lit/lit/blob/4a5369c8c9b282c4f47a70126da11810e9754745/packages/lit-html/src/lit-html.ts#L259) still.

**Comment by andyjessop** [comment]
This is to do with your own tsconfig, not lit-html. You probably have this setting as "error": https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues

Instead:

```ts
import type { TemplateResult } from 'lit-html';
```
