### ISSUE TITLE
Wrong default export for choose directive

### ISSUE THREAD

**Issue by nkabrown** [lit/lit#2379]
# Description

Export for the `choose` directive is being resolved to `lit/directives/cache.js` and failing.

Caused by wrong default path for choose directive in the `exports` field at `packages/lit/package.json`.

```ts
"./directives/choose.js": {
   "default": "./directives/cache.js"
},
```

**Comment by aomarks** [comment]
This should now be fixed in lit 2.1.1 -- just released.
