### ISSUE TITLE
Using a HTMLTemplateElement with binding causes incorrect binding assignments

### ISSUE THREAD

**Issue by angrycat9000** [lit/lit#2382]
# Description

Rendering a `<template>` element with a binding inside of it causes bindings following it to be mis-matched.

Found this when upgrading to `lit@2` from `lit-element@2` .   Trying to render content that includes a web-component that uses the `<template>` tag for some of its data.  When bindings are present in the `<template>` element, it throws off all the other bindings that follow it.

# Steps to Reproduce

1. Write this code

```ts

import { html, render } from 'lit';

const someString = 'not the right string to show in the heading';

const myTemplate = (name) =>
  html`
    <template id="template-for-other-component">${someString}</template>
    <h1>value=${name}!</h1>
  `;

render(myTemplate('lit-html'), document.body);

```

2. See this output...

value=not the right string to show in the heading!

## Live Reproduction Link

https://stackblitz.com/edit/lit-html-eutfyg

## Expected Results

The DOM is rendered as 
```html
<template id="template-for-other-component">not the right string to show in the heading</template>
<h1>value=lit-html!</h1>
```

## Actual Results

![screen shot with a document fragment as the contents of the template element](https://user-images.githubusercontent.com/48362463/148400133-5fb0404e-e32f-459e-89df-feee1a650db4.png)

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by kevinpschaaf** [comment]
This is a documented limitation: https://lit.dev/docs/templates/expressions/#invalid-locations

> Expressions should generally not appear in the following locations:
>
> Inside `<template>` element content (attribute expressions on the template element itself are allowed). Lit does not recurse into template content to dynamically update expressions and will error in development mode.

**Comment by justinfagnani** [comment]
We need to add guidance about what to do in this case, ie use static templates

**Comment by angrycat9000** [comment]
Thanks for pointing out that limitation @kevinpschaaf.   It was difficult finding info with all the results that come up for template in the documentation.

> We need to add guidance about what to do in this case, ie use static templates

That is great that there is a work around @justinfagnani .  I was thinking I was going to have to figure out a way to not use `<template>`



I'd also suggest throwing an error if this is detected when parsing.

It wasn't initially obvious what was causing the expression values to shift when it was rendered.  The problem shows up with the expressions **after** the invalid one in a `<template>`.   In my case I ended up focused several expressions later since there were several string values in a row that did not throw errors when shifted.   Then it hit expression that was expecting an array but got a string threw an error.  I had to spend some time cutting out different chunks of HTML finally realize that it was the presence of a `<template>` several elements before that was root cause and not the binding to the array.

**Comment by kevinpschaaf** [comment]
Good call, I'll re-open to keep this as a documentation issue to suggest using static.

Note that we do detect this error and give a [proactive warning](https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L716-L734) when running in [development mode](https://lit.dev/docs/tools/development/#development-and-production-builds), so you should consider turning that on in your development setup if possible.

**Comment by augustjk** [comment]
The end of the [invalid locations for expressions](https://lit.dev/docs/templates/expressions/#invalid-locations) already has the following:

> Note that expressions in all the invalid cases above are valid when using static expressions, although these should not be used for performance-sensitive updates due to the inefficiencies involved (see below).

and is immediately followed by the static expressions documentation, so it seems we're already providing guidance with regards to this scenario.
