### ISSUE TITLE
[lit] Lit Skypack support

### ISSUE THREAD

**Issue by codecycletechnologies** [lit/lit#2383]
Hello there,

We tried to use lit element from https://www.skypack.dev/view/lit.
We are receiving below error if we try with the given sample code in documentation.

```
Property 'render' in type 'MyElement' is not assignable to the same property in base type 's'.
  Type '() => { _$litType$: any; strings: any; values: any[]; }' is not assignable to type '() => symbol'.
    Type '{ _$litType$: any; strings: any; values: any[]; }' is not assignable to type 'symbol'.deno-ts(2416)
(method) MyElement.render(): {
    _$litType$: any;
    strings: any;
    values: any[];
}

```

However if we add `as unknown as symbol` at the end of render method then this type error is getting resolved.

```
 render () {
        return html`Web Components are <span>${ this.mood }</span>!` as unknown as symbol;
 }
```

It would be great if skypack import work in similar way as npm lit module render method. 
And if render method needs some changes in skypack then it should be available in documentation.

**Comment by aomarks** [comment]
For reference, it sounds like the snippet being run is the one from https://github.com/lit/lit/tree/main/packages/lit#overview

```ts
import {LitElement, html, css} from 'lit';
import {customElement, property} from 'lit/decorators.js';

// Registers the element
@customElement('my-element')
export class MyElement extends LitElement {
  // Styles are applied to the shadow root and scoped to this element
  static styles = css`
    span {
      color: green;
    }
  `;

  // Creates a reactive property that triggers rendering
  @property()
  mood = 'great';

  // Render the component's DOM by returning a Lit template
  render() {
    return html`Web Components are <span>${this.mood}</span>!`;
  }
}
```

**Comment by aomarks** [comment]
@codecycletechnologies Can you give a little more information about how you are evaluating this code? Are you using deno, or some other build tools?

**Comment by taylor-vann** [comment]
Hey @codecycletechnologies thanks for reaching out!

Wanted to ask a few clarifying questions :) Sorry if they're basic

1) How are we importing LIt? And are we loading the `d.ts` file as well?

Something like 

```
// @deno-types="https://cdn.skypack.dev/lit?dts"
import * as coolLib from "https://cdn.skypack.dev/lit";
```

2) Mind if we see a code snippet or a repo with this issue in action?

**Comment by albertosantini** [comment]
I cannot reproduce it, but I think there is a misunderstanding,

For example, https://jsbin.com/vizayohedu/edit?html,output

```
        import { LitElement, html } from "https://cdn.skypack.dev/lit?min";

        class MyElement extends LitElement {
            static properties = {
                _counter: { state: true }
            };

            constructor() {
                super();

                this._counter = 0;
            }

            render() {
                return html`
                    <p>Hello from my template.</p>
                    <p>Counter: ${this._counter}</p>
                    <button @click = "${this.inc}">+</button>
                    <button @click = "${this.dec}">-</button>
                `;
            }

            dec() {
                this._counter--;
            }
            inc() {
                this._counter++;
            }
        }
        customElements.define('my-element', MyElement);
 
```

And in my project I have the file `skypack.d.ts`:
```
// https://docs.skypack.dev/skypack-cdn/code/javascript#using-skypack-urls-in-typescript
// First, let TypeScript allow all module names starting with "https://".
// This will suppress TS errors.
declare module "https://*";
```

Anyway it seems I can reproduce it using Deno playground.

If you copy the snippet at https://deno-playground.mahardi.me/ 

```
import {LitElement, html, css} from 'https://cdn.skypack.dev/lit';
import {customElement, property} from 'https://cdn.skypack.dev/lit/decorators.js';

// Registers the element
@customElement('my-element')
export class MyElement extends LitElement {
  // Styles are applied to the shadow root and scoped to this element
  static styles = css`
    span {
      color: green;
    }
  `;

  // Creates a reactive property that triggers rendering
  @property()
  mood = 'great';

  // Render the component's DOM by returning a Lit template
  render() {
    return html`Web Components are <span>${this.mood}</span>!`;
  }
}
```

you get the following result:

```
error: TS2416 [ERROR]: Property 'render' in type 'MyElement' is not assignable to the same property in base type 's'.
  Type '() => { _$litType$: any; strings: any; values: any[]; }' is not assignable to type '() => symbol'.
    Type '{ _$litType$: any; strings: any; values: any[]; }' is not assignable to type 'symbol'.
  render() {
  ~~~~~~
```

I am afraid, if I am not wrong, this is not the way to use Lit in that environment (Deno): you should use a build step to use Lit.

**Comment by taylor-vann** [comment]
Hey there! Checking in :)

I updated my deno cache and my Lit setup broke too! So with a little digging, I found that we are using [TustedHTML](https://developer.mozilla.org/en-US/docs/Web/API/TrustedHTML) which is part of the browser stack but also it needs types for deno.

So i used the [TustedTypes](https://openbase.com/js/@types/trusted-types/documentation) repo

```
import "https://cdn.skypack.dev/trusted-types?dts";

// @deno-types="https://cdn.skypack.dev/lit?dts"
import {LitElement, html} from "https://cdn.skypack.dev/lit";

```

Let me know if that helps!
It unblocked me!

**Comment by taylor-vann** [comment]
Dug a little deeper

```
import "https://cdn.skypack.dev/trusted-types?dts";
```
^ this will add all the code in trusted-types, we just need types

But deno seems to require some specific ordering to make this work currently (Jan 2022). From what I can gather, the following will get a build:

1 only deno types (must be separated by a full line \n)
2 imports with side effects
3 imports with deno types (must be separated by a full line \n)
3 exports with deno types (must be separated by a full line \n)
4 exports


So you can also use the following to only import the trusted-types d.ts and avoid it showing up in your build!
```
// @deno-types="https://cdn.skypack.dev/trusted-types?dts";

// @deno-types="https://cdn.skypack.dev/lit?dts"
export { html, LitElement } from "https://cdn.skypack.dev/lit";
```

**Comment by taylor-vann** [comment]
potentially resolved if trusted types makes it into the typescript DOM lib

https://github.com/microsoft/TypeScript/issues/30024

**Comment by duncanmak** [comment]
I'm trying to use this, but I wonder if I should be using Skypack or the link listed in https://lit.dev/docs/getting-started/#use-bundles instead?

Also, what about getting access to the decorators? I don't see the decorators in neither Skypack nor https://cdn.jsdelivr.net/gh/lit/dist/.

**Comment by taylor-vann** [comment]
Currently importing trusted types will unblock me, and i still get to use decorators :) curious if this doesn't help?

```
import "https://cdn.skypack.dev/trusted-types?dts";

// @deno-types="https://cdn.skypack.dev/lit?dts"
export { css, html, LitElement } from "https://cdn.skypack.dev/lit";

export {
  customElement,
  property,
  state,
} from "https://cdn.skypack.dev/lit/decorators";
```

**Comment by justinfagnani** [comment]
Skypack seems to be abandoned. See https://github.com/skypackjs/skypack-cdn/issues/362
