### ISSUE TITLE
[labs/observers] ResizeController code example in announcement blog post does not compile

### ISSUE THREAD

**Issue by peschee** [lit/lit#2390]
# Description

The code example in the [blog post](https://lit.dev/blog/2022-01-05-lit-2.1-release/#easy-to-use-observers-with-@lit-labsobserver) announcing the `@lit-labs/observer` does not compile.

# Steps to Reproduce

1. Write this code

```ts
import {html, css, LitElement} from 'lit';
import {customElement} from 'lit/decorators.js';
import {ResizeController} from '@lit-labs/observers/resize_controller.js';

@customElement('simple-greeting')
class SimpleGreeting extends LitElement {

  _resizeController = new ResizeController(this);

  render() {
    return html`Current size is ${this.offsetWidth} x ${this.offsetHeight}`;
  }
}

```

2. See this output...

TypeScript compiler barks:

```shell
TS2554: Expected 2 arguments, but got 1.
```

[Lit Playground Repro](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudH0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0IHtSZXNpemVDb250cm9sbGVyfSBmcm9tICdAbGl0LWxhYnMvb2JzZXJ2ZXJzL3Jlc2l6ZV9jb250cm9sbGVyLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5jbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuXG4gIF9yZXNpemVDb250cm9sbGVyID0gbmV3IFJlc2l6ZUNvbnRyb2xsZXIodGhpcyk7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYEN1cnJlbnQgc2l6ZSBpcyAke3RoaXMub2Zmc2V0V2lkdGh9IHggJHt0aGlzLm9mZnNldEhlaWdodH1gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

## Expected Results

Either `ResizeControllerConfig` should be made entirely optional (using the defaults provided by the package) or the blog post needs to be updated with a working code example (related but most probably another issue: this page does not mention the `@lit-labs/observer` package).

This works:

```ts
import {html, css, LitElement} from 'lit';
import {customElement} from 'lit/decorators.js';
import {ResizeController} from '@lit-labs/observers/resize_controller.js';

@customElement('simple-greeting')
class SimpleGreeting extends LitElement {

  _resizeController = new ResizeController(this, {});

  render() {
    return html`Current size is ${this.offsetWidth} x ${this.offsetHeight}`;
  }
}
```

**Comment by AndrewJakubowicz** [comment]
Thank you for this issue. I've updated the lit.dev blog post with working code as well as an example `import` statement. Also fixed the accidental singular form of `observer`.

See https://lit.dev/blog/2022-01-05-lit-2.1-release/ for fixed page.
Cheers!
