### ISSUE TITLE
[labs/task] An easier way to execute logic after a task completed without chaining tasks

### ISSUE THREAD

**Issue by e111077** [lit/lit#2454]
## Description

Say you execute a `Task` called `this.task` a first time. We'll call this `invocation-1` and then it gets called again and we'll call this `invocation-2`..

if `invocation-2` ends before `invocation-1`, `this.task.value` will be the return value of `invocation-2` and will essentially ignore `invocation-1`. `Task` will call `this._host.requestUpdate()` since `ReactiveControllerHost` does not allow passing in properties to `requestUpdate`.

For example:

```ts
task = new Task(this, async ([url]) => {
  // fetch to invocation-1 takes substantially longer than fetch to invocation-2
  return await fetch(url);
}, () =>[this.someURL]);
```

If you want to call javascript when `this.task` has settled you either have to memoize `this.task.value`'s old value every update and check it with the current value. e.g.

```ts
private oldTaskValue = this.task.value;

willUpdate() {
  if (this.task.value !== undefined && this.oldTaskValue !== this.task.value) {
    this.oldTaskValue = this.task.value;
    // execute logic
    this.setReactiveProps(this.task.value);
  }
}
```

or chain another task

```ts
// note this one will still trigger when this.task.value === undefined on each run
private setReactivePropsTask = new Task(this, ([value]) => {
  this.setReactiveProps(value);
}, () => [this.task.value])
```

The reason you'd have to do this, is because if you call `setReactiveProps(value)` inside of `this.task`'s async function, `this.setReactiveProps` may be subject to race conditions or a stale value from the `fetch` unless the user puts in specific race-condition checks e.g. `url === this.someURL`.

It would be cool to have a callback like:

`onComplete` or for the calls to `requestUpdate` to be able to pass a name once `Task._value` is set.

- Who wants the functionality
  - Users who are using task
- What it is they want
  - a way to execute javascript after a task just finished without creating another task
- Why they want it
  - chaining tasks is "infectious" and steps out of the lit-lifecycle
- Functional description of task/subtask
  - implement a way to escape from the task chain by providing a way to execute logic after a task

## Acceptance criteria

`onComplete` or something similar implemented in Task

**Comment by kevinpschaaf** [comment]
It sounds like you want to be able to see each individual result of a task rather than the latest one at the time the update cycle runs?

Can you explain a little more clearly why? I think it likely goes beyond the scope of use cases that Task was envisioned for (i.e. _rendering_ the most recent state of a task, not responding to individual results)... but maybe there's an addition that can support that case.

**Comment by sorvell** [comment]
This is pretty confusing and it would be good to have a more concise description / repro of the use case.

Note, it's currently possible to take an action when a task completes either by:
1. awaiting the task's `taskComplete` promise (caveats #2347)
2. implement the `complete` callback in the render method.

**Comment by e111077** [comment]
[Here is a repro](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHksIHN0YXRlfSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQge1Rhc2t9IGZyb20gJ0BsaXQtbGFicy90YXNrJztcblxubGV0IGludm9jYXRpb25OdW0gPSAwO1xuXG4vLyBUaGlzIHRhc2sgaXMgc2xvdyBpbiBpbnZvY2F0aW9uIDAgYW5kIDEgYW5kIGZhc3QgYWZ0ZXIgdGhhdFxuY29uc3QgYXN5bmNUYXNrID0gKCkgPT4ge1xuICBsZXQgdGltZW91dCA9IGludm9jYXRpb25OdW0gPCAyID8gMjAwMCA6IDEwO1xuICBsZXQgcmVzb2x2ZTogYW55O1xuICBjb25zdCBwcm9tID0gbmV3IFByb21pc2U8bnVtYmVyPihyZXMgPT4ge3Jlc29sdmUgPSByZXN9KTtcbiAgY29uc3QgbG9jYWxJbnZvY2F0aW9uTnVtID0gaW52b2NhdGlvbk51bTtcbiAgXG4gIHNldFRpbWVvdXQoKCkgPT4ge3Jlc29sdmUobG9jYWxJbnZvY2F0aW9uTnVtKX0sIHRpbWVvdXQpO1xuICBcbiAgaW52b2NhdGlvbk51bSsrO1xuICBcbiAgcmV0dXJuIHByb207XG59XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIEBzdGF0ZSgpXG4gIHRvZ2dsZSA9IGZhbHNlO1xuICBcbiAgb2xkVGFza1ZhbHVlOiBudW1iZXJ8dW5kZWZpbmVkO1xuXG4gIHRhc2sgPSBuZXcgVGFzayh0aGlzLCBhc3luYyAoKSA9PiB7XG4gICAgY29uc3QgdmFsID0gYXdhaXQgYXN5bmNUYXNrKCk7XG4gICAgLy8gdGhpcyBpcyBzdWJqZWN0IHRvIHJhY2UgY29uZGl0aW9uc1xuICAgIC8vIHRoaXMuZG9FeHBlbnNpdmVUaGluZyh2YWwpO1xuICAgIHJldHVybiB2YWw7XG4gIH0sICgpID0-IFt0aGlzLnRvZ2dsZV0pO1xuICBcbiAgd2lsbFVwZGF0ZSgpIHtcbiAgICBpZiAodGhpcy50YXNrLnZhbHVlICE9PSB1bmRlZmluZWQgJiYgdGhpcy50YXNrLnZhbHVlICE9PSB0aGlzLm9sZFRhc2tWYWx1ZSkge1xuICAgICAgdGhpcy5vbGRUYXNrVmFsdWUgPSB0aGlzLnRhc2sudmFsdWU7XG4gICAgICAvLyBUaGlzIGlzIHRoZSByaWdodCBwbGFjZSB0byBjYWxsIGl0XG4gICAgICB0aGlzLmRvRXhwZW5zaXZlVGhpbmcodGhpcy50YXNrLnZhbHVlKTtcbiAgICB9XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8aDM-UHJlc3MgdGhlIGJ1dHRvbiB3aGlsZSB0aGUgdGFzayBpcyBwZW5kaW5nIHRvIHNpbXVsYXRlIGEgcmFjZSBjb25kaXRpb248L2gzPlxuICAgICAgPGg0PkZpcnN0IGNsaWNrIHNpbXVsYXRlcyBhIHNsb3cgdGFzayBhbmQgc3Vic2VxdWVudCBjbGlja3Mgc2ltdWxhdGUgYSBmYXN0IHRhc2s8L2g0PlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHsoKSA9PiB7dGhpcy50b2dnbGUgPSAhdGhpcy50b2dnbGV9fT5maXJlIHRhc2s8L2J1dHRvbj5cbiAgICAgIDxkaXY-cmVzb2x2ZWQgaW52b2NhdGlvbiBudW1iZXI6ICR7dGhpcy50YXNrLnJlbmRlcih7XG4gICAgICAgaW5pdGlhbDogKCkgPT4gJ1ByZXNzIHRoZSBidXR0b24nLFxuICAgICAgIGNvbXBsZXRlOiB2YWwgPT4ge1xuICAgICAgICAgLy8gSXQgaXMgY2FsbGVkIHR3aWNlIGhlcmUgd2hlbiB0YXNrIGlzIGNvbXBsZXRlIGJ1dCByZW5kZXIgd2FzXG4gICAgICAgICAvLyBjYWxsZWQgZS5nLiB0aGlzLnRvZ2dsZSBpcyB0b2dnbGVkXG4gICAgICAgICAvLyB0aGlzLmRvRXhwZW5zaXZlVGhpbmcodmFsKTtcbiAgICAgICAgIHJldHVybiB2YWw7XG4gICAgICAgfSxcbiAgICAgICBwZW5kaW5nOiAoKSA9PiAncGVuZGluZy4uLidcbiAgICAgIH0pfTwvZGl2PlxuICAgIGA7XG4gIH1cbiAgXG4gIGRvRXhwZW5zaXZlVGhpbmcodmFsOiBudW1iZXIpIHtcbiAgICBjb25zb2xlLmxvZyhgTm9uLXJlbmRlcmluZyBleHBlbnNpdmUgdGFzayBjYWxsZWQgd2l0aCAke3ZhbH1gKTtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d).

1. There is not a good place to await `taskComplete` because there is no good way to know whether a new task has been scheduled without re-implementing the logic inside of `Task`.
2. complete can get called multiple times in the render method. Additionally, there may be logic that needs to be run when this task is complete that is not relevant to rendering and may be expensive.

**Comment by sorvell** [comment]
Thanks for the repro. OK, so you want to do work on the edges of the Task (e.g. when it completes or potentially cancels).

Here's an [update of the example](https://lit.dev/playground/?mods=gists#gist=ea47afd087335322a181d8b5d9655538) showing a few options. Two of the options are API changes to consider: (1) adding task callbacks or (2) allowing you to see the task status within the task run. The last option is just a reformulation of what the example was already doing which, to me, makes it seem less an anti-pattern but that's debatable.

**Comment by e111077** [comment]
Great breakdown!

Option 1 feels like a leaky implementation

Option 2 seems like great DX but maybe is pushing logic too much to be a "task" thing rather than a Lit thing?

Option 3 looks better than before, but would be cool if reactive controllers could pass an argument to `requestUpdate` like `this.host.requestUpdate('Controller:Task:value')`

**Comment by justinfagnani** [comment]
This was fixed by https://github.com/lit/lit/pull/3287
