### ISSUE TITLE
[ssr] Document restrictions on SSR compatible components

### ISSUE THREAD

**Issue by aomarks** [lit/lit#2494]
Investigate and document all of the current restrictions that determine whether a component can be pre-rendered with `@lit-labs/ssr`, including which lifecycle methods will be invoked, and what can and can't be done in each of those lifecycle methods.

See also https://github.com/lit/lit/issues/2351 and https://github.com/lit/lit/issues/2433

**Comment by augustjk** [comment]
Closed by https://github.com/lit/lit.dev/pull/880
