### ISSUE TITLE
[meta] Changeset release script PRs fails CLA check

### ISSUE THREAD

**Issue by aomarks** [lit/lit#2502]
Since https://github.com/lit/lit/pull/2465, we use `lit-robot` for changesets. We had hoped that this would make those PRs pass the Google CLA check, because `lit-robot` is allowlisted as a known good robot. However, it still fails.

Example: https://github.com/lit/lit/pull/2500/checks

```
The following contributors were found for this pull request:

❌ https://github.com/lit/lit/commit/6d58996417b6173a193203b64d58d120bcd28b54 PR Opener: @lit-robot
❌ https://github.com/lit/lit/commit/6d58996417b6173a193203b64d58d120bcd28b54 Author: @github-actions[bot] <github-actions[bot]​@users.noreply.github.com>

(Only the first commit for a unique contributor is listed.)
```

**Comment by AndrewJakubowicz** [comment]
Fixed in https://github.com/lit/lit/pull/2543

Fixed by https://github.com/lit/lit/pull/2540
