### ISSUE TITLE
[meta] Integrate release notes generator into release process

### ISSUE THREAD

**Issue by aomarks** [lit/lit#2503]
- Update https://github.com/PolymerLabs/release-image to work with multiple package CHANGELOGs
- Integrate it into the release GitHub action
  - Simplest way is to define a GitHub artifact (https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts)
  - Even better would be to post a comment with the image embedded
- Consider moving the changelog generator into the monorepo under `scripts/` or something. It has never been released to NPM, and we probably don't want to release it.

**Comment by AndrewJakubowicz** [comment]
Marking as done. Ergonomics still present a bit to be desired, however the release-image CLI has been improved to handle:
 - Multiple packages (and versions). Including multiple versions of the same package.
 - Rendering an arbitrary markdown file.
 - A github action that renders a release image for any "Version Packages" PRs.

Improving the visuals of the release-image tracked in https://github.com/lit/lit/issues/3145
