### ISSUE TITLE
Integrate Google Monetization

### ISSUE THREAD

**Issue by busynest** [lit/lit#2511]
# Description

Would be nice to see Google Adsense Documentation with lit, or official adsense-lit-Element. Similar is AMP-auto-ads, maybe it's a solution? I remember captaincodeman created an ad-unit-element, but it might not have been updated. 
Adsense does work in a limited way. The issue is with testing solutions,  because I don't want to accidentally break any rules.

Maybe more people could use an adsense solution aswell.

# Steps to Reproduce

`index.html`

1. meta tag link to Adsense
2. Ad unit element provided by Adsense.
3. Problem: ad unit is only allowed to render inside of index, but I overcome the render order and placement by nesting the ad-unit into the <slot></slot> of app-shell.

2. See this output...

## Live Reproduction Link

https://stackblitz.com/edit/node-i2k8mm?file=index.html

## Expected Results

Would be nice to have an offical lit (plus) adsense element, or best practices documentation, to reduce risk of breaking rules due to accidental test setup.

## Actual Results

works, could work a lot better.

**Comment by busynest** [comment]
https://support.google.com/adsense/answer/10762946?hl=en&ref_topic=9183242

**Comment by kevinpschaaf** [comment]
The issue report doesn't make it clear what the connection between AdSense and Lit would be, or what we could do to help. Vending specific components for ad integrations is likely outside the scope of what we would consider in the core library.

**Comment by busynest** [comment]
Okay, sorry for not making it clear. I simply want to know how to properly place an ad unit inside a component, without the need to 1. render adunit at top level window. 2. Place advert by nesting using slot.

Ill try to deal with this today, I probably know what to do, but will talk with adsense team first, to see what is allowed.

Because the Google people already think paranoid thoughts about me. I didn't mean to be mean on Twitter, but I only know you guys by your writing style. I actually love this damn awesome lit team. Sorry for talking trash Twitter, I couldn't handle the politics, And i saw Googlers talking trash, so I did too. Bottom line, I don't actually know you people, I don't stalk, I am serious when it comes to following the rules. I am moral 100%, and would never allow my own beliefs interfere with anyone else.

Sorry for Twitter. Sucks hard. I'll was thinking angular, but I don't want to be Shadowing you guy.

C'ya, and thanks for not mentoring me, nor having a normal talk with me. I'll take my self away now.
