### ISSUE TITLE
The new PropertyValues type definition causes breaking compile errors.

### ISSUE THREAD

**Issue by mattpowell** [lit/lit#2513]
# Description

A [change](https://github.com/lit/lit/pull/2482) in `@lit/reactive-element` at version `1.2.2` causes previously working TypeScript compilations to fail.

# Steps to Reproduce

**tl;dr**: Use typescript to compile the following code with `@lit/reactive-element` version `1.2.2`:
```typescript
import {LitElement} from 'lit';

export class Component extends LitElement {
  override updated(properties: Map<string, string>) {
    // noop
  }
}
```

For more detail see: https://gist.github.com/mattpowell/f772e99ddefaad6ebf1190d5bd60b112

## Expected Results

Compilation is successful and there are no type errors.

(Upgrading from 1.2.1 to 1.2.2 should be backwards compatible and previously allowed types/function signatures should still be valid)

## Actual Results

An error is thrown:
```
component.ts:4:12 - error TS2416: Property 'updated' in type 'Component' is not assignable to the same property in base type 'LitElement'.
  Type '(properties: Map<string, string>) => void' is not assignable to type '(_changedProperties: PropertyValues<any>) => void'.
    Types of parameters 'properties' and '_changedProperties' are incompatible.
      Type 'PropertyValues<any>' is not assignable to type 'Map<string, string>'.
        Types of property 'forEach' are incompatible.
          Type '(callbackfn: <K extends string | number | symbol>(value: any, key: K, map: Map<K, any>) => void, thisArg?: unknown) => void' is not assignable to type '(callbackfn: (value: string, key: string, map: Map<string, string>) => void, thisArg?: any) => void'.
            Types of parameters 'callbackfn' and 'callbackfn' are incompatible.
              Types of parameters 'key' and 'key' are incompatible.
                Type 'K' is not assignable to type 'string'.
                  Type 'string | number | symbol' is not assignable to type 'string'.
                    Type 'number' is not assignable to type 'string'.
```

Also, see [comment here](https://gist.github.com/mattpowell/f772e99ddefaad6ebf1190d5bd60b112?permalink_comment_id=4058032#gistcomment-4058032).

**Comment by mattpowell** [comment]
This was linked in the PR that merged the type change, but linking it here for completeness: https://github.com/vmware/clarity/issues/6654

**Comment by justinfagnani** [comment]
btw, for bug reports it'd be nice to see the code and error inline to the bug rather than behind a link. It makes it easier to glance and see what the bug is about.

**Comment by coryrylan** [comment]
This is something that I'll have patched in Clarity for our next release. We should had been using `PropertyValues` in our components. There is a valid workaround for our users until our release as well.

**Comment by mattpowell** [comment]
Totally agree that the repro code is a misuse/incorrect use of the intended types; however, the issue was probably more around the semantics of the version that was created (and how those versions are pulled in to the various packages), so I probably should've linked to that change instead!

Nonetheless, appreciate the team digging in to this! And, noted about bug reports... I'll update it in a bit, so it's all in one place and glanceable! :)

**Comment by WickyNilliams** [comment]
Ever since this issue, I'm getting sporadic typescript build failures like:

```
TS2502: 'changedProperties' is referenced directly or indirectly in its own type annotation.
src/some-component/SomeComponent.ts (185:14)

185   willUpdate(changedProperties: PropertyValues<this>) {
```

It's always the same component that causes the error, which is strange because i use that exact same signature in many components. 

I can workaround by deleting `tsconfig.tsbuildinfo` (so i assume there's some weird cache issue going on), but it's really annoying. Any insight what might be causing the error?
