### ISSUE TITLE
[lit-html] render issue: always have <!----> added in front

### ISSUE THREAD

**Issue by chxx-v** [lit/lit#2522]
# Description

For using lit1, we can simply do _templateResult.getHTML()_ to get the html;
However in lit2, we need to do 
```
const div = document.createElement('div');
render(templateResult, div);
return div.innerHTML;
```
which will always give back `<!---->templateResult`
with `<!---->`in front, which results parsing issues later

Is this a bug? Why will the empty comment always be added to front? Please help! Thanks!

**Comment by justinfagnani** [comment]
What is it you're trying to do?

Yes, we need to emit the marker comment nodes so that we know where in the DOM to update. If you're never updating the DOM you can remove these nodes.

**Comment by chxx-v** [comment]
I am trying to get the string out from the templateResult and set that string as **mwc-formfield .label**
But I always got `<!---->labeltext`
Currently I used `div.innerHTML.replace('<!---->', '');` as workaround.

**Comment by chxx-v** [comment]
The reason I cannot use `div.innerText` is because I need to keep the html tags, for other use cases

**Comment by kevinpschaaf** [comment]
Can you maybe explain why `option.display` would be a TemplateResult (and why you'd want to parse the label out of the TemplateResult rather than e.g. `option` carrying both `label` and `display` in a more structured form)?

**Comment by chxx-v** [comment]
I noticed that in lit1.0 TemplateResult has **.getHTML()** method, is that possible to also have that in 2.x?

**Comment by justinfagnani** [comment]
No. We purposefully removed all behavior from TemplateResult to increase the ability for it to be used across copies and versions of lit-html.

You can get the strings and values and join them though. I'm still unsure of the overall reason here and whether there's a more straightforward way. Is it tru that you want the text of HTML tags, like a literal `<div>` to possibly appear in your label?

**Comment by chxx-v** [comment]
I use the text with HTML tags not only for the label here, but also other parts.... They share the code of getting text out of TemplateResult. If it's not doable, I will use the workaround of `return div.innerHTML.replace('<!---->', '');`
thanks!

**Comment by justinfagnani** [comment]
Like I said, you can get the strings and values from a TemplateResult and join them.
