### ISSUE TITLE
[meta] Changeset action fails on "Version Packages" PR

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit#2544]
During release, a Version Packages PR is created.

The changeset action fails with error:

```
> changeset
> changeset "status" "--since=main"

🦋  error Some packages have been changed but no changesets were found. Run `changeset add` to resolve this error.
🦋  error If this change doesn't need a release, run `changeset add --empty`.
```

See previous Version Package pull requests as reference:

 - https://github.com/lit/lit/runs/5207461948?check_suite_focus=true
    - From https://github.com/lit/lit/pull/2543

### Why?

Speculatively, the "Version Packages" PR deletes all the changeset markdown files, and bumps some version numbers. Thus when `changeset` checks against the `main` branch, it finds changes without a changeset markdown file associated.

**Comment by kevinpschaaf** [comment]
Should we file an issue on changesets? Seems like we're using their stuff in the way they intend?
