### ISSUE TITLE
Improved event types inference in `@lit-labs/react`

### ISSUE THREAD

**Issue by mihar-22** [lit/lit#2546]
## Description

The `createComponent` function exposed by `@lit-labs/react` defaults to all events in the event callback being of type `Event` [on this line](https://github.com/lit/lit/blob/main/packages/labs/react/src/create-component.ts#L87-L89). This means consumers of our component libraries are expected to cast events to the correct type, which is both time consuming and error prone.

## Proposed Solution

There's a standard global event map in the TypeScript DOM library called `GlobalEventHandlersEventMap` that as a library author I reguarly extend with new event definitions that are part of my library. Here's an example of an [event map](https://github.com/vidstack/player/blob/main/src/media/events.ts#L23-L65), and here's the [global event map being extended](https://github.com/vidstack/player/blob/main/src/global/types.ts#L22-L40). It'd be ideal if the event types were inferred from this map. If the event type is not defined there you can fallback to `Event` as it was before - no breaking changes.

Here's how I got it working:

```diff
// packages/labs/react/src/create-component.ts

type Events<S> = {
- [P in keyof S]?: (e: Event) => unknown;
+ [P in keyof S]?: (
+  e: S[P] extends keyof GlobalEventHandlersEventMap 
+    ? GlobalEventHandlersEventMap[S[P]] 
+    : Event
+  ) => unknown;
};

- export const createComponent = <I extends HTMLElement, E>(
+ export const createComponent = <I extends HTMLElement, E extends Record<string, string>>(
  React: typeof ReactModule,
  tagName: string,
  elementClass: Constructor<I>,
- events?: StringValued<E>,
+  events?: E,
  displayName?: string
);
```

```ts
// Usage Example

class MyEvent extends Event {
  // ...
} 

declare global {
  interface GlobalEventHandlersEventMap {
    'my-event': MyEvent;
  }
}

export default createComponent(React, 'my-element', MyElement, {
  onActivate: 'my-event',
} as const); // <- need `const` to ensure event types are passed through.
```

**Comment by taylor-vann** [comment]
addressed in #2648 :)
