### ISSUE TITLE
[@lit-labs/react]: when React ref is passed to a wrapped component attribute `l="[Object object]` ends up in DOM

### ISSUE THREAD

**Issue by WickyNilliams** [lit/lit#2593]
# Description

When a React ref is passed a React-wrapper component, then an attribute like `l="[Object object]` ends up in the DOM.

# Steps to Reproduce

1. Write this code

```ts
import { useRef } from "react";
import { MyReactInput } from "./web-component";

export default function App() {
  const ref = useRef();

  return (
      <MyReactInput ref={ref} />
  );
}

```

2. See this output...

## Live Reproduction Link

Used Codesandbox as its what I am familiar with:

https://codesandbox.io/s/goofy-lederberg-bjiwkb?file=/src/App.tsx:794-857

## Expected Results

No unexpected attributes added to DOM.

## Actual Results

```html
<my-input l="[Object object]"></my-input>
```

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 14

Didn't test the rest:

- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by taylor-vann** [comment]
closing this issue, the forwardedRef will no longer be attached to the webcomponent itself

**Comment by WickyNilliams** [comment]
Just to confirm, I'm no longer seeing this issue with the latest version. Thanks!

**Comment by taylor-vann** [comment]
Fantastic! Thanks for confirming this for us @WickyNilliams
