### ISSUE TITLE
[lit-starter-ts] Including node modules in the build (here: cytoscape)

### ISSUE THREAD

**Issue by nilsboy** [lit/lit#2604]
What is the easiest way to include node modules in the build?
I am trying to add cytoscape (https://js.cytoscape.org) to my element.
I got it working with rollup but it takes 11s to build.
Is there a pure typescript way to do that and maybe only compile modules that have changed?

Thank you.

**Comment by kevinpschaaf** [comment]
Closing, unclear if this is still an issue. Please re-open if the comments above don't help.
