### ISSUE TITLE
[lit-starter-ts] Doc site footer issue

### ISSUE THREAD

**Issue by houghtonap** [lit/lit#2606]
The documentation site that is generated contains the wrong link and text to this project's github repository. Update the footer to:
```html
<footer>
  <p>
    Made with
    <a href="https://github.com/PolymerLabs/lit-element-starter-ts">lit-element-starter-ts</a>
  </p>
</footer>`;
```
See `docs-src/_includes/footer.11ty.cjs`.

**Comment by sorvell** [comment]
We'll address this as part of https://github.com/lit/lit/issues/2890.
