### ISSUE TITLE
[lit-starter-ts] Difference / relation to @open-wc's boilerplate?

### ISSUE THREAD

**Issue by tony** [lit/lit#2607]
Today I came into contact with this:

https://open-wc.org/guides/developing-components/getting-started/#base-libraries

It provides a similar boilerplate to this project

```
npm init @open-wc --destinationPath
my-component --type scaffold
--scaffoldType wc --features linting testing demoing --typescript true
--scaffoldFilesFor testing demoing --tagName o-embed --writeToDisk true
--installDependencies yarn
```

Thoughts on what makes this template different?

`@open-wc`'s `yarn test` fails for me on WSL. `lit-element-starter-ts` works out of the box.

**Comment by sorvell** [comment]
Closing based on the previous comment.
