### ISSUE TITLE
[lit-starter-ts] es-dev-server became web dev server

### ISSUE THREAD

**Issue by gonzalo-novak** [lit/lit#2608]
Hello! 

I see that in the documentation of es-dev-server they recommend to use web dev server, as it is its successor [https://www.npmjs.com/package/es-dev-server](url). I think it would be good to use it, because with es-dev-server I had problems starting the server, I got these 3 messages:

1. Error compiling: [BABEL] /Users/gonzalo/Downloads/lit-element-starter-ts-master/my-element.js: Unknown version 74 of Opera (While processing: "/Users/gonzalo/Downloads/lit-element-starter-ts-master/node_modules/@babel/preset-env/lib/index.js")

2.  GET http://localhost:8001/my-element.js net::ERR_ABORTED 500 (Internal Server Error)

3. [polyfills-loader] failed to load: ../my-element.js check the network tab for HTTP status.

With web dev server it didn't give me any problem. I just had to install that dependency and change the serve script in the package.json.

I comment on this in case it needs to be done.

Thanks!

**Comment by sorvell** [comment]
We'll consider this when addressing https://github.com/lit/lit/issues/2890.
