### ISSUE TITLE
[lit-starter-ts] Get stared really not help

### ISSUE THREAD

**Issue by EwaMakowska** [lit/lit#2609]
Hi, I tried to create new project, but your doc is quite messy and show almost nothing. Library looks great but is really hard to start.

I have cloned this repo, but:
1. how can I add childe element to my-element? Why there are my-element.js in root directory? What is a differents between this two files? I have to create both file (my-element.js in src directory and root) or one of it is created automaticlly? 
2. Why in index.html I have importent file from root directory?
3. how can add I sibling element?

I strongly recommend add to readme about child and sibling element. It will be really easier for everyone.

**Comment by e111077** [comment]
Heya, we are starting to take a look at revamping the entire starter kit. You can follow the tracking bug at #2890

**Comment by sorvell** [comment]
Closing in favor of #2890.
