### ISSUE TITLE
[lit-starter-ts] Running test script finds 0 tests

### ISSUE THREAD

**Issue by balint729** [lit/lit#2613]
Hi!

I found that running **npm test** results in:
√ 0 tests completed

I suppose the file pattern should be modified in karma.conf.cjs to:
```
- pattern: config.grep ? config.grep : 'test/**/*_test.js',
+ pattern: config.grep ? config.grep : 'src/test/**/*_test.ts',
```

But after modifying that the test process throws:
```
  Error: Could not resolve import "/base/src/test/my-element_test.ts" in "./context.html".
      at maybeResolveImport (C:\Users\212714836\Documents\Practice\lit-element-starter-ts\node_modules\es-dev-server\dist\utils\resolve-module-imports.js:163:13)
```

Could you please help what would cause the issue?
Thanks,
BB

**Comment by sorvell** [comment]
Closing due to age. Please open a new issue if this is still a problem.
