### ISSUE TITLE
[lit-starter-js] Lit 2.0 issues - Serve, Test

### ISSUE THREAD

**Issue by Stebeber** [lit/lit#2622]
Hey, 

1. `npm run serve` works fine at the beginning but fails after running `npm run docs`.

![image](https://user-images.githubusercontent.com/6450906/135036836-68f2d7fd-c3f5-4664-8c47-80f0df44a460.png)

I receive this error: "cp is not found"

![image](https://user-images.githubusercontent.com/6450906/135037438-922bff01-6a44-4651-8aa2-e7d98ce29748.png)

2. When running `npm test` I receive

![image](https://user-images.githubusercontent.com/6450906/135037196-f8ef30b3-4bb5-425a-8445-95ddb2eaa093.png)

3. After running `npm run docs` I always receive `not found` (404)

![image](https://user-images.githubusercontent.com/6450906/135039236-ec62be21-4a4c-4362-93e6-7f0799a21952.png)

**Comment by sorvell** [comment]
@AndrewJakubowicz Please verify if this is fixed and close if so.

**Comment by justinfagnani** [comment]
I'll close this for now. If it's still an issue, we can re-open.
