### ISSUE TITLE
Child element constructor is called twice

### ISSUE THREAD

**Issue by RandomEngy** [lit/lit#2632]
# Description

When you render a child Lit element, the constructor is called twice.

This has been causing some problems: particularly with the `web-dialog` component that is throwing exceptions when it's rendered inside of a Lit element. It's logging a console error on the second element creation.

Minimal repro: https://github.com/RandomEngy/lit-double-ctor-repro

I write a console message each time the child element class instance is constructed and you see two entries for `Sub element created.`

Using lit `2.2.0`.

# Steps to Reproduce

1. Render a child Lit element as part of a parent lit element.
2. Observe the number of times the child element constructor is called.

## Expected Results

Constructor is called once

## Actual Results

Constructor is called twice

## Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

(Possibly more, only tested in Edge and Chrome)

**Comment by justinfagnani** [comment]
That seems like a large project for a reproduction... what should I be looking at? Can you make a live reproduction on lit.dev?

**Comment by RandomEngy** [comment]
I copied the official Lit starter project to get this repro. I'll try to get a lit.dev repro this weekend.

**Comment by RandomEngy** [comment]
[Here's an repro on the Lit playground](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3N1Yi1jb21wb25lbnQnKVxuZXhwb3J0IGNsYXNzIFN1YkNvbXBvbmVudCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBjb25zdHJ1Y3RvcigpIHtcbiAgICBzdXBlcigpO1xuICAgIGNvbnNvbGUuaW5mbygnU3ViIGNvbXBvbmVudCBjdG9yIGNhbGxlZC4nKTtcbiAgfVxuICBcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYEknbSBhIHN1Yi1jb21wb25lbnQuYDtcbiAgfVxufVxuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYHAgeyBjb2xvcjogYmx1ZSB9YDtcblxuICBAcHJvcGVydHkoKVxuICBuYW1lID0gJ1NvbWVib2R5JztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-PHN1Yi1jb21wb25lbnQ-PC9zdWItY29tcG9uZW50PmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ). It reproduces if you clear the console then refresh.
