### ISSUE TITLE
[ssr] throws when using a number as property that gets reflected to an attribute

### ISSUE THREAD

**Issue by daKmoR** [lit/lit#2633]
# Description

Trying to ssr a number value that gets reflected as an attribute of a LitElement throws.

# Steps to Reproduce

1. Write this code

```ts
import { render } from "@lit-labs/ssr/lib/render-with-global-dom-shim.js";
import { html, LitElement, css } from 'lit';

class MyElement extends LitElement {
  static properties = {
    activeIndex: { type: Number, reflect: true, attribute: 'active-index' },
  }

  constructor() {
    super();
    this.activeIndex = 0;
  }

  render() {
    return html`
      <h2>MyElement ${this.activeIndex}</h2>
    `;
  }
}

customElements.define('my-element', MyElement);

const template = () => html`
  <my-element></my-element>
`;

const ssrResult = render(template());

let ssrString = '';
for (const s of ssrResult) {
  ssrString += s;
}

console.log(ssrString);
```

2. execute `node file.js`

## Expected Results

no error thrown

## Actual Results

```
node bug-number-property.js
file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/util/escape-html.js:19
export const escapeHtml = (str) => str.replace(/[&<>"']/g, (char) => replacements[char]);
                                       ^

TypeError: str.replace is not a function
    at escapeHtml (file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/util/escape-html.js:19:40)
    at LitElementRenderer.renderAttributes (file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/element-renderer.js:88:40)
    at renderAttributes.next (<anonymous>)
    at renderTemplateResult (file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:467:33)
    at renderTemplateResult.next (<anonymous>)
    at renderValue (file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:354:16)
    at renderValue.next (<anonymous>)
    at render (file:///html/test-ssr/node_modules/@lit-labs/ssr/lib/render-lit-html.js:336:12)
    at render.next (<anonymous>)
    at file:///html/test-ssr/bug-number-property.js:30:12

Node.js v17.6.0
```

## Suggested changed

Convert value always to string - or check explicitly for a number?

in here https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/element-renderer.ts#L147

```diff
  *renderAttributes(): IterableIterator<string> {
    if (this.element !== undefined) {
      const {attributes} = this.element;
      for (
        let i = 0, name, value;
        i < attributes.length && ({name, value} = attributes[i]);
        i++
      ) {
        if (value === '' || value === undefined || value === null) {
          yield ` ${name}`;
        } else {
-          yield ` ${name}="${escapeHtml(value)}"`;
+          yield ` ${name}="${escapeHtml(String(value))}"`;
        }
      }
    }
  }
```

## How can I best help?

would it help to prepare a PR?

**Comment by aomarks** [comment]
Sorry for the slow responses lately. Handling number sounds good here in the default. Unsure about always converting to String -- I wonder if it would clearer to throw on unexpected values.

However, I think the other big piece that's missing here is that the [`LitElementRenderer`](https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/lit-element-renderer.ts) doesn't provide its own implementation of `renderAttributes`. I think it should, and it should exactly match the behavior of `ReactiveElement`, meaning it also does JSON conversion for objects and arrays by default, and it uses the `converter` attribute if specified in the property metadata:

https://cs.github.com/lit/lit/blob/365cd09a88a1c390045452aac82510c143ffe257/packages/reactive-element/src/reactive-element.ts?q=attribute+convert#L308

https://cs.github.com/lit/lit/blob/365cd09a88a1c390045452aac82510c143ffe257/packages/reactive-element/src/reactive-element.ts?q=attribute+convert#L1071

**Comment by justinfagnani** [comment]
We shouldn't _just_ convert to String, but it is the correct fallback, since this is what the browser does for `setAttribute()`. I think we can add `String(value)` into ElementRenderer now and also open an issue to implement `renderAttributes` in LitElementRenderer to call the attribute converter.

**Comment by justinfagnani** [comment]
Oh, and we should probably eventually have a `ReactiveElementRenderer` with that level of implementation, extended by `LitElementRenderer`.

**Comment by aomarks** [comment]
Filed https://github.com/lit/lit/issues/2669 to track adding the full implementation of `renderAttributes` to `LitElementRenderer`.

@daKmoR If you still wanted to send over a PR that calls `String(value)` in the default renderer, that would be great! Otherwise let us know and we can do it sometime soon.
