### ISSUE TITLE
[infra] Incorrect sourcemaps causing warning in Astro, Vite

### ISSUE THREAD

**Issue by FredKSchott** [lit/lit#2645]
# Description

`dom-shim.js.map` sourcemap points to incorrect source file, causing a Vite warning in Vite, Astro, etc.

```
Sourcemap for "/home/projects/owaiwjnnp.github/node_modules/@lit-labs/ssr/lib/dom-shim.js" 
points to missing source files
```

The issue appears to be this line of the sourcemap: https://unpkg.com/browse/@lit-labs/ssr@2.0.4/lib/dom-shim.js.map

```
"sources":["../src/lib/dom-shim.ts"]
```

Where `@lit-labs/ssr/src/lib/dom-shim.ts` does not exist in package. 

The line is most likely meant to point to `../lib/dom-shim.ts` or even `./dom-shim.ts`.

This warning has probably existed for a while in Vite, but is new in Astro as we stopped swallowing/hiding Vite warnings from the user.

# Steps to Reproduce

1. Start a new Lit + Astro project: https://astro.new/framework-lit?on=stackblitz
2. See the warning in your console on startup. Also occurs on build.

## Live Reproduction Link

https://astro.new/framework-lit?on=stackblitz

## Expected Results

No warnings.

## Actual Results

```
Sourcemap for "/home/projects/owaiwjnnp.github/node_modules/@lit-labs/ssr/lib/dom-shim.js" 
points to missing source files
```

**Comment by jose8a** [comment]
does this bug render Lit unuseable in Astro then? Right after this warning, the vite dev server bails and complains with this error:

`vite internal server error package may have incorrect main/module/exports specified in its package.json. Failed to resolve entry ...`

if I remove the root Lit component the error then returns.
