### ISSUE TITLE
[ssr] Consider supporting `HTMLElement.shadowRoot` in SSR dom-shim.

### ISSUE THREAD

**Issue by nicholasrice** [lit/lit#2652]
# Description
I noticed today that the default dom-shim in `@lit-labs/ssr` does not implement the `HTMLElement.shadowRoot` property. Specifically, invoking `attachShadow()` with an open shadow-root configuration does not cause the created shadow root for the element to be exposed from the `shadowRoot` property; [it only returns the shadow root object.](https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/dom-shim.ts#L63)

I know that you're trying to keep the dom-shim lean, but I was wondering if you would consider a PR that implements the [shadow root getter behavior](https://dom.spec.whatwg.org/#dom-element-attachshadow).

For context, I'm working on FAST's SSR implementation. We're hoping to align to the same dom-shim constraints as Lit, however, FAST only caches shadow root references for elements defined with a closed shadow root. In open shadow root cases, the shadow root will simply be retrieved from the element's `shadowRoot` property anytime the shadow root needs to be manipulated or inspected. This is currently causing a core code path to throw.

I'm sure we can adjust our runtime or dom-shim code to accommodate this gap, but I thought I would file an issue with ya'll first to see if this is a feature you're interested in taking. I'm happy to put up a PR if it is.

**Comment by aomarks** [comment]
Just to be clear, in a Lit SSR context, there is no actual emulation of the shadow root object, since we're not emulating the DOM tree at all, rather we stream shadow children out as text and leave it at that.

So, would your use case be addressed if `<host>.shadowRoot` simply returned a `{host: <host>}` object (the same object returned by `attachShadow`?).

Can you say a little more about the FAST shadow root caching behavior? What is it for, and is it actually doing something functionally useful in an SSR context, or are you just hitting the code path incidentally?

**Comment by nicholasrice** [comment]
Yep, clear on the fact that there is no real implementation. A `<host>.shadowRoot` getter as you describe is exactly what I need.

FAST uses an element's shadowRoot as a target for attaching stylesheets to a component, with code resembling:

```ts
Styles.attachTo(getShadowRoot(elementInstance));
```

where  `getShadowRoot()` is a internal function that returns an element's shadow root, preferring to access the `shadowRoot` property of the element and deferring to an internal cache (`WeakMap<HTMLElement, ShadowRoot>`). Currently that cache is only populated with elements with a closed shadow root to avoid un-necessary bloating of the cache. The fallback case to both of those invokes `Node.getRootNode()`, which is also not implemented, which is where the exception is currently occurring.

**Comment by kevinpschaaf** [comment]
Yeah, if it's just a matter of assigning the faux shadowRoot to `this.shadowRoot`, seems fine.

```js
    attachShadow() {
      this.shadowRoot = {host: this};
      return this.shadowRoot;
    }
```

Want to be pragmatic about enabling common patterns without being super strict or heavyweight.

**Comment by nicholasrice** [comment]
Great, I'll put up a PR then. Thanks!
