### ISSUE TITLE
Accessing a mixin's static `styles` property fails when built with TypeScript

### ISSUE THREAD

**Issue by GeekyEggo** [lit/lit#2668]
# Description

When accessing the styles of a mixin via `super.styles` using TypeScript, everything builds successfully, but the component fails to render and results in the following error:
```
Uncaught TypeError: Cannot read property 'styles' of undefined
```

# Steps to Reproduce
- Tested with TypeScript v4.6.3
- Note the JS version of the example works successfully.

_Example taken from https://lit.dev/playground/#sample=docs/mixins/highlightable._
```ts
/* playground-fold */
import {LitElement, css, html} from 'lit';
import {classMap} from 'lit/directives/class-map.js';
import {property} from 'lit/decorators/property.js';

type Constructor<T> = new (...args: any[]) => T;

export declare class HighlightableInterface {
  highlight: boolean;
  renderHighlight(content: unknown): unknown;
}
/* playground-fold-end */

export const Highlightable =
  <T extends Constructor<LitElement>>(superClass: T) => {
    class HighlightableElement extends superClass {
      // Adds some styles...
      static styles = css`.highlight { background: yellow; }`

      // ...a public `highlight` property/attribute...
      @property({type: Boolean}) highlight = false;

      // ...and a helper render method:
      renderHighlight(content: unknown) {
        return html`
          <div class=${classMap({highlight: this.highlight})}>
            ${content}
          </div>`;
        }
      }
      return HighlightableElement as Constructor<HighlightableInterface> & T;
    };
```

```ts
import {LitElement, html, css} from 'lit';
import {customElement} from 'lit/decorators.js';
import {Highlightable} from './highlightable.js'

@customElement('element-two')
export class ElementTwo extends Highlightable(LitElement) {
  static styles = [
    super.styles || [],
    css`:host { display: block; }`
  ];
  render(){
    return this.renderHighlight(html`
      <label>
        <input type="checkbox"
          .checked=${this.highlight}
          @change=${this.toglgleHighlight}>
        Toggleable highlight
      </label>
    `);
  }
  private toglgleHighlight(event: Event) {
    this.highlight = (event.target as HTMLInputElement).checked;
  }
}

```

## Live Reproduction Link

https://lit.dev/playground/#sample=docs/mixins/highlightable

## Expected Results

- I am able to reference `super.styles` of an extended mixin, if the super class is `LitElement`.
- I am able to reference `super.styles` when building with TypeScript.
- The component correctly renders all styles.

## Actual Results

- ✅ I am able to reference `super.styles` of an extended mixin, if the super class is `LitElement`.
- ✅ I am able to reference `super.styles` when building with TypeScript.
- ❌ The component errors.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'styles')
    at element-two.js:26:14
```

## Browsers Affected

- Chrome
- Firefox
- Edge

_Untested_
- Safari 11
- Safari 10
- IE 11

**Comment by GeekyEggo** [comment]
Ref: https://www.typescriptlang.org/docs/handbook/mixins.html#static-property-mixins-17829

From further investigation, this appears to be because of the use of variable types, i.e. generics.
> More of a gotcha than a constraint. The class expression pattern creates singletons, so they can’t be mapped at the type system to support different variable types.

**Comment by p-ob** [comment]
You should be able to do this if you convert your "styles" static field declaration to a getter (code snippet is from some projects I work on):
```ts
static get styles() {
   return [super.styles, style];
}
```

**Comment by GeekyEggo** [comment]
What an wonderfully simple fix, thank you so much.
