### ISSUE TITLE
[@lit-labs/router] Use new version of URLPattern polyfill

### ISSUE THREAD

**Issue by kenchris** [lit/lit#2697]
3.0.0 was just released https://www.npmjs.com/package/urlpattern-polyfill and it made some changes to import and the d.ts file

@justinfagnani

**Comment by Michael-Gungaram** [comment]
Even 4.0.3 now. I have a TS error like : 

node_modules/@lit-labs/router/routes.d.ts:7:15 - error TS2305: Module '"urlpattern-polyfill"' has no exported member 'URLPattern'.urlpattern-polyfill"' has no exported member 'URLPattern'

=>  import type { URLPattern as URLPatternType } from 'urlpattern-polyfill;

I don't know if it's related.
