### ISSUE TITLE
[reactive-element] Error: "The following properties on element ... will not trigger updates as expected because they are set using class fields"

### ISSUE THREAD

**Issue by jarrodek** [lit/lit#2716]
# Description

Until today everything was working with my projects as expected. However, today I've update the lit library and I started seeing a bunch of errors like the following:

```
Uncaught (in promise) Error: The following properties on element [...] will not trigger updates as expected because they are set using class fields: [...]. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
```

Two independent projects started having the same problem after updating lit. Not really sure what version I was using before but I was working on these projects for the past few weeks and I was keeping them up-to-date.

I read the related article. I am using TS to write my components. I am little bit lost here. It looks like my code is good to work with decorators. It was working well before. Now everything is broken. I am not even sure how to reproduce this. One of the elements that triggers these errors has the following properties declaration:

```typescript
export default class UserAvatarElement extends LitElement {
  static get styles(): CSSResult {
    return css`...`;
  }

  private _user?: IUser;

  /**
   * Whether has user information
   */
  @state() protected hasUser = false;

  /**
   * Set with the user. The computed user initials.
   */
  @state() protected userInitials?: string;

  /**
   * Whether the main dropdown is opened
   */
  @property({ type: Boolean }) opened = false;

  /**
   * @attribute
   */
  @property({ type: Object })
  get user(): IUser | undefined {
    return this._user;
  }

  set user(value: IUser | undefined) {
    const old = this._user;
    if (old === value) {
      return;
    }
    if (old && value && old.key === value.key) {
      return;
    }
    this._user = value;
    this.requestUpdate('user', old);
    this._processUser(value);
  }
  ...
}
```
This element produces the following error:

```
The following properties on element user-avatar will not trigger updates as expected because they are set using class fields: hasUser, userInitials, opened. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
```

I tried to move all initializers to the constructor but nothing changed. Any help is be appreciated.

**Comment by jarrodek** [comment]
The walk-around for now is to change `exportConditions` in the `web-dev-server.config.mjs` file to contain `production`. This way I can continue working on my projects.

**Comment by jarrodek** [comment]
After spending even more time I pinpointed the problem to the latest release of `@web/dev-server-esbuild` version 0.3.0. In one of my projects this was the only change in the dependencies. After downgrading it to `0.2.16` all started working again.
I will cross reference this issue there.

**Comment by justinfagnani** [comment]
`"useDefineForClassFields": false` is the right setting to apply here:  https://lit.dev/docs/components/decorators/#enabling-decorators

Though how to apply that setting can be complicated with tools that wrap `tsc` or don't use `tsc` at all like `esbuild.

It seems like from https://github.com/evanw/esbuild/issues/2220 and https://github.com/modernweb-dev/web/issues/1921 that the problem here is that `@web/dev-server-esbuild` isn't reading tsconfig.json and so useDefineForClassFields can't be set to false. I'll close this as a bug in `@web/dev-server-esbuild`.

cc @LarsDenBakker and @daKmoR if they know if that bug has a solution.

**Comment by beephotography** [comment]
Solution to the problem:
- update to "@web/dev-server-esbuild": "^0.3.1"
- set `useDefineForClassFields` to `false` in tsconfig
- load `tsconfig.json` file with
```
        esbuildPlugin({
            ts: true,
            target: "auto",
            tsconfig: fileURLToPath(new URL('./tsconfig.json', import.meta.url)),
        }),
```
(according to https://github.com/modernweb-dev/web/blob/master/packages/dev-server-esbuild/CHANGELOG.md#031 there is a possible setting to keep the `tsconfig.json` file in sync)

**Comment by duanbaosheng** [comment]
i use rollup

`
"experimentalDecorators": true,
"useDefineForClassFields": false,
`
the config is not helpful for me
