### ISSUE TITLE
ReactiveController is a Component part

### ISSUE THREAD

**Issue by zalelion** [lit/lit#2718]
## Description

- Who wants the functionality
Component part

- What it is they want
Component part management

- Why they want it
lightweight component part

- Functional description of task/subtask
`ReactiveController` is a Component part, `ReactiveController` can use decorators.

## Acceptance criteria

ReactiveController can use decorators.

component's part
```ts
import { ReactiveController, html, css } from "lit";
import { query, state } from "lit/decorators.js";

export class MyPart implements ReactiveController {

    static styles = css`  .mypart  > button { color :blue } `;

    constructor(private host:ReactiveControllerHost){
       host.addController(this);
    }

    @query(".mypart  > button")
    btn: HTMLELement;

    @state()
    num = 1;

    add(){ 
         ++this.num;
     }

    render(){
        return html` <div >
         ${this.num}
          <button @click=${this.add}>click me</button>
        </div>`;
     }
}
```

**Comment by WickyNilliams** [comment]
I think you want a mixin, which can do everything you've described here

**Comment by justinfagnani** [comment]
Yes, mixins do all of this already. See our discussion of controllers vs mixins in the Composition docs: https://lit.dev/docs/composition/overview/#controllers-and-mixins and on writing mixins in TypeScript: https://lit.dev/docs/composition/mixins/#mixins-in-typescript

Here's your example ported to a mixin in the lit.dev playground: https://lit.dev/playground/#gist=ec576b58e02739f7e2c273573c93f5f0
