### ISSUE TITLE
Lit library doesn't work with older versions of typescript (typescript 3.5.x)

### ISSUE THREAD

**Issue by elycruz** [lit/lit#2730]
## Description

Project's using typescript 3.5.x do not work with the new 'lit' library - Typescript compilers, in this instance, report typescript errors with lit library type (*.d.ts) files.

Issue also mentioned here: #2644 

## Steps to Reproduce

1. Setup an Angular 8 project - `npm i @angular/cli@8 -g && ng new ng8lit`.
2. Add 'lit' library to the project - `cd ng8lit && npm i lit --save`.
3. Add usage of 'lit' library to project sources:
```ts
// ./src/web_components/XElement.ts

import {html, LitElement} from 'lit';
import {customElement} from 'lit/decorators';

@customElement('x-element')
export class XElement extends LitElement {
  render() {
    return html`Hello from XElement`;
  }
}
```

Add entry in './src/app/app.module.ts'

```ts
// ...

import { XElement } from '../web_components';

console.log(XElement.name);

// ...
```

5. See this output, in terminal when trying to run the app - `$ ng serve` (from project root dir.).

## Expected Results

Project runs without any typescript errors.

## Actual Results

Getting typescript errors when importing, and using, the 'lit' library.

![lit-not-working-with-typescript-3 5-and-angular-8](https://user-images.githubusercontent.com/603428/163414747-bab7987c-c05c-46e6-8fb1-bc327f4abda3.PNG)

![lit-not-working-with-typescript-3 5-and-angular-8--2](https://user-images.githubusercontent.com/603428/163415272-65fd69d2-5800-4f5f-8181-3348eacc20fa.PNG)

![lit-not-working-with-typescript-3 5-and-angular-8--3](https://user-images.githubusercontent.com/603428/163415304-79c59003-ea06-4fb2-87d5-65de3e8cb27b.PNG)

**Note:** Issue above also happens when installing, and using, the 'lit-element' package.

## Environment where Issue identified

- Node: 14.19.1
- Npm: 7 & 6
- Angular cli: 8 (note: issue not present on `@angular/cli@9` (typescript `~3.8.3`)).
- OS: Windows 10

**Comment by philkunz** [comment]
@elycruz The web is shifting to use esm. If your setup does not work with esm, you are free to pin an older version of the lib.

**Comment by elycruz** [comment]
@philkunz Thanks for the reply - Even though your suggestion is correct a multitude of typescript versions are used across a multitude of projects so knowing what base versions are expected to work, with specific versions of the (lit) library, would help users make the right decisions when working on/setting up projects that contain multiple dependencies that depend on typescript.

E.g.,
  I think some thing as simple would be enough to close this issue (of course in best case scenario some them like a "downleveled" version of the output *.d.ts files might be the more ideal solution):

________________________________
| lit library | typescript version |
| ---------- | ------------------- |
| ~2.x.x      |  >=4.1                  |

**Comment by justinfagnani** [comment]
We'll document our TypeScript version support as tracked by #2731, but 3.5 is almost certainly not going to be supported. I'll close this in favor of #2731

**Comment by elycruz** [comment]
Sounds good @justinfagnani (thanks)
