### ISSUE TITLE
[labs/context] Investigate late-provider/early-provider issues

### ISSUE THREAD

**Issue by benjamind** [lit/lit#2763]
## Description
As outlined [in this comment](https://github.com/lit/lit/pull/1955#discussion_r840126503) it is possible for a context provided by a late hydrating component to never be provided to its children because an earlier provider at a location higher in the DOM already provided it.

Not sure if this situation is actually solveable without tracking all context requests ever which has memory usage implications.

**Comment by justinfagnani** [comment]
I don't really see how we can do anything here.

I think that if a middle provider was late-upgraded and needed to provide a value, that it's possible that the initial state should _not_ be that the higher provider provided the value, instead in an ideal world the middle element would have been automatically upgraded to provide the value when it was requested.

That requires knowing what element could provide a value _before_ upgrade, which is impossible without a central coordinator and serializing which context keys the element could provide. This is doable - Google's internal framework Wiz does something similar - but requires a bunch of conventions and constraints.

I think the best thing we do here is say that it should be _possible_ for a central coordinator to plug-in to the page to give this kind of behavior. Possibly it could do so with capturing event handlers that override all providers and delegate to some loading system. Maybe elements have eagerly loaded stub classes that handle the context protocol and load the rest of the class when needed.

As long as these kind of add-on behaviors are possible, I think we're ok with not having every last use case covered in the core package.

**Comment by benjamind** [comment]
Agreed. I'd want to see a bunch of use case examples for this behavior before any real effort was put into this as part of the core package. I'm not yet convinced it's a real need that isn't easily worked around with other patterns.
