### ISSUE TITLE
[labs/context] Add more README.md docs on installation

### ISSUE THREAD

**Issue by benjamind** [lit/lit#2767]
## Description

Currently the context readme has no notes on published package name and npm installation.

**Comment by steve2507** [comment]
I currently cannot find this package published is that correct? `@lib-labs/context` does not seem to exist in the npm registry.

**Comment by justinfagnani** [comment]
It's not published just yet. We just got the initial PR and a bug fixe merged. I'll get it out this week.

**Comment by justinfagnani** [comment]
This issue is outdated
