### ISSUE TITLE
[ts-transformers] @property decorator should transform to static property 

### ISSUE THREAD

**Issue by sorvell** [lit/lit#2775]
Currently `@property()` transforms to `__decorate` instead of `static properties`. See https://github.com/lit/lit.dev/pull/773#discussion_r857807782 for more info.

**Comment by AndrewJakubowicz** [comment]
I'm interested in working on this.

**Comment by AndrewJakubowicz** [comment]
Addressed in https://github.com/lit/lit/pull/2780
