### ISSUE TITLE
[lit] Consider a single import for lit directives

### ISSUE THREAD

**Issue by sorvell** [lit/lit#2791]
When using LitElement, you can easily get *all* of the supported decorators by importing:

```
 import {property, customElement} from 'lit/decorators.js';
 ```

However, for directives there is not a single entry point and users must import each piecemeal:

```
import {styleMap} from 'lit/directives/style-map.js; 
import {classMap} from 'lit/directives/class-map.js'
```

The amount of code being imported is not dramatically different (_needs to be confirmed_) between the two and it's unclear why this is done differently.

Since it's generally more convenient to just import from one module, consider creating a single entry point for all (or the most common) built in directives.

**Comment by sorvell** [comment]
If it is considered "just too much code" to import them all, consider:

`directives/common.js` which could leave out some of the less used or bigger directives (some potential candidates):
* async-append/replace
* template-content
* unsafe-html/svg
* repeat (maybe?)

**Comment by sorvell** [comment]
The difference in code size here is actually a lot:
* decorators: < ~0.7KB
* directives: ~10KB
* directives (common): ~5KB

**Comment by jolleekin** [comment]
It would be nice if the `.js` extension can be removed. Right now, it is required.
![image](https://user-images.githubusercontent.com/5405376/166101137-5d679323-9251-4cd2-b960-75b410ba3607.png)

**Comment by justinfagnani** [comment]
I don't think we want do this this due to the extra size of directives. They're not as often used in common combinations are decorators.
