### ISSUE TITLE
[labs/react] Properties with custom accessors (get/set) does not work with createComponent

### ISSUE THREAD

**Issue by lideen** [lit/lit#2799]
# Description

Properties with custom accessors (get/set) does not work with createComponent:

```ts
export class BasicElement extends LitElement {
  set customAccessors(customAccessors: Foo) {
    const oldValue = this._customAccessors;
    this._customAccessors = customAccessors;
    this.requestUpdate('customAccessors', oldValue);
  }
  get customAccessors(): Foo {
    return this._customAccessors;
  }
  private _customAccessors = {
    bar: 'inital',
  };

  static elementName = "basic-element";

  static properties = {
    customAccessors: { type: Object },
  };

  render(): TemplateResult {
    return html`<span>${this.customAccessors.bar}</span>`;
  }
}

const BasicElementComponent = createComponent(
  React,
  BasicElement.elementName,
  BasicElement,
  {}
);

class App extends React.Component<AppProps, AppState> {
  render() {
    return (
      <React.Fragment>
        <BasicElementComponent />
        <BasicElementComponent customAccessors={{ bar: 'updated' }} /> {/* <- Property is not being set */}
      </React.Fragment>
    );
  }
}

```

# Steps to Reproduce

1. See example in the description

## Live Reproduction Link

https://stackblitz.com/edit/react-ts-cpu8mh

## Expected Results

I expect properties with custom accessors work just as normal properties

## Actual Results

See stackblitz example

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by sorvell** [comment]
This fails because these are non-enumerable and we're using `for (const i in elementClass.prototype)` to find properties. The PR above has one possible fix and another is to use `Object.getOwnPropertyNames`.

**Comment by ashleyryan** [comment]
Following up from slack with, I think, a related issue.

When defining a property with a getter and setter, the `@property` directive ignores the `type` or `converters.toAttribute` options for boolean attributes/properties.

There's a stackblitz here: https://stackblitz.com/edit/clarity-react-experimental?file=package.json

With a simple property, rendering a component with `<MyElement myprop></MyElement>` renders `<my-element myprop></my-element>`. With a getter/setter,  it renders as `<my-element myprop="true"></my-element>` with a string value instead.

**Comment by justinfagnani** [comment]
Fixed in https://github.com/lit/lit/pull/2800
