### ISSUE TITLE
[labs/context] prevent context-request event to listen to itself

### ISSUE THREAD

**Issue by christophe-g** [lit/lit#2843]
Thanks a lot for the work around lit-lab/context. I was not aware of the [context proposal](https://github.com/webcomponents-cg/community-protocols/blob/main/proposals/context.md) and recently discovered (with pleasure) it was implemented. 

Since nothing prevents an element to be a provider AND a consumer of the same context, I am wondering if we should not prevent the `context-request` event to listen to itself (https://github.com/lit/lit/blob/f1b26bfe706ad93a3a312932b0eca5b0261023e0/packages/labs/context/src/lib/controllers/context-provider.ts#L59).

My use-case where this would happen : the DOM tree loosely mapping a json database with some elements holding references to the database hierarchy. One top-level element (context provider) holds a reference to a path in database. Some elements hold child reference relative to this top level reference (context consumer), but could also be context provider for further children down the DOM tree.

**Comment by justinfagnani** [comment]
@benjamind this sounds important for any element that wants to redefine a context binding in terms of what's provided by a parent.

Is there any use case for consuming objects you provide yourself? If not, we can do this always. If so, we'd need a configuration.

**Comment by benjamind** [comment]
I agree this is a needed change.

I don't think we need this to be configurable, I can't immediately think of any cases where you'd want to throw an event just to catch it locally? Could always add configuration later if the need arises?

**Comment by benjamind** [comment]
I can see this change also being necessary if we wanted to create a portalling / routing context handler. Since we sometimes portal elements into other locations in the DOM to avoid containment issues (Spectrum Web Components Overlays do this), we may want to proxy a context hierarchy for these elements, in this case being able to catch and refire context requests without interception at the host is possibly valuable?
