### ISSUE TITLE
[HELP NEEDED] CDN

### ISSUE THREAD

**Issue by angelhdzmultimedia** [lit/lit#2906]
# Description

# Steps to Reproduce

1.  I tried using the CDN from https://unpkg.com/lit-element@3.2.0 using `?module `at the end of the imports like this:
```ts
import {LitElement, html, customElement} from 'https://unpkg.com/lit-element@3.2.0?module'
```

2.  It works, the typescript project on codepen renders the component using the `@customElement` decorator, but I get an error (warning?) in the console that lit-element is deprecated.

![image](https://user-images.githubusercontent.com/10191085/168458218-a2cceda1-aff7-4eaa-bb8d-1adf579f3002.png)

3. So I tried https://unpkg.com/lit@2.2.3 instead, but lit-element isn't available there, and then some errors because it can't find html, LitElement, customElement, etc.

4. Tried using jsDelivr instead. It created many links to each `.d.ts` and `.js` modules, but adding `?module` at the end didn't work to import them.

## Live Reproduction Link

https://codepen.io/angelhdzmultimedia/pen/jOZVLqL

## Browsers Affected

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

**Comment by p-ob** [comment]
You'll need to change where you are importing files from. I've updated your CodePen with what would fix it: https://codepen.io/p-ob/pen/ExQNqBB. A lot of the supplemental, non-required stuff got moved into opt-in import statements to allow for smaller bundle sizes for those that don't use decorators, certain directives, etc.

`?module` is a feature of the UNPKG CDN. You can read about it on the homepage, https://unpkg.com/, under "Query Parameters". It's not a feature of Lit or of other CDNs.

Also, I think the lit group would appreciate "help" questions to be opened up in [Discussions](https://github.com/lit/lit/discussions).

**Comment by angelhdzmultimedia** [comment]
> You'll need to change where you are importing files from. I've updated your CodePen with what would fix it: https://codepen.io/p-ob/pen/ExQNqBB. A lot of the supplemental, non-required stuff got moved into opt-in import statements to allow for smaller bundle sizes for those that don't use decorators, certain directives, etc.
> 
> `?module` is a feature of the UNPKG CDN. You can read about it on the homepage, https://unpkg.com/, under "Query Parameters". It's not a feature of Lit or of other CDNs.
> 
> Also, I think the lit group would appreciate "help" questions to be opened up in [Discussions](https://github.com/lit/lit/discussions).

You are so kind! Thank you very much!

**Comment by angelhdzmultimedia** [comment]
> You'll need to change where you are importing files from. I've updated your CodePen with what would fix it: https://codepen.io/p-ob/pen/ExQNqBB. A lot of the supplemental, non-required stuff got moved into opt-in import statements to allow for smaller bundle sizes for those that don't use decorators, certain directives, etc.
> 
> `?module` is a feature of the UNPKG CDN. You can read about it on the homepage, https://unpkg.com/, under "Query Parameters". It's not a feature of Lit or of other CDNs.
> 
> Also, I think the lit group would appreciate "help" questions to be opened up in [Discussions](https://github.com/lit/lit/discussions).

By the way, I didn't post this in discussion because this is an issue. This should be addressed in the main page of the repository. I always read the official docs and the main page of a repository to find direction and guides.
I couldn't find direction about a CDN with TypeScript support so I got lost in the process.

And I searched in Google "Lit CDN TypeScript" in Google multiple times before submitting this issue.
