### ISSUE TITLE
[labs/react] Evaluate for labs graduation

### ISSUE THREAD

**Issue by taylor-vann** [lit/lit#2915]
## Description

- Who wants the functionality
The react-o-sphere!
- What it is they want
A type-safe way to use web components in react
- Why they want it
React is everywhere and so are web components!
- Functional description of task/subtask
Follow internal documentation to progress `@labs/react` to the graduation process

## Acceptance criteria

- README has sufficient documentation to explain usage suitable for evaluation.
- The labs page on lit.dev describes the package and solicits for feedback from a specific discussion thread.
- Feedback via discussions & issues may drive frequent breaking changes.
- add feedback on #2734, whether we should support in future releases or next

**Comment by rictic** [comment]
Tracking at https://github.com/lit/lit/discussions/3358
