### ISSUE TITLE
[lit-html] ifDefined not rendering attributes with valid uses of -1 and "-1"

### ISSUE THREAD

**Issue by StephenRiosDev** [lit/lit#2924]
# Description

`ifDefined()` evaluates valid values of  `-1` as `undefined`.

# Steps to Reproduce

1. Use `ifDefined` when attempting to define a valid `-1` values such as in `style="order: -1"` attribute.

```ts
import {html, render} from 'lit-html';
import {ifDefined} from 'lit/directives/if-defined.js';

const order = "-1"; // It doesn't matter if this is -1 or "-1", both result in the same outcome
render(html`<div style="order: ${ifDefined(order)}"></div>`, document.body);
```

2. See this output...

```html
<div></div>
```

## Expected Results

ifDefined should render attributes when valid values are passed, including -1 and "-1".

## Actual Results

Attributes using valid values of -1 and "-1" are not rendered.

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by justinfagnani** [comment]
It seems to work [here](https://lit.dev/playground/#project=W3sibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9pbmRleC5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoiaW5kZXgudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCByZW5kZXJ9IGZyb20gJ2xpdCc7XG5cbmltcG9ydCB7aWZEZWZpbmVkfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9pZi1kZWZpbmVkLmpzJztcblxuY29uc3Qgb3JkZXIgPSBcIi0xXCI7IC8vIEl0IGRvZXNuJ3QgbWF0dGVyIGlmIHRoaXMgaXMgLTEgb3IgXCItMVwiLCBib3RoIHJlc3VsdCBpbiB0aGUgc2FtZSBvdXRjb21lXG5yZW5kZXIoaHRtbGA8ZGl2IHN0eWxlPVwib3JkZXI6ICR7aWZEZWZpbmVkKG9yZGVyKX1cIj5IaTwvZGl2PmAsIGRvY3VtZW50LmJvZHkpOyJ9XQ)

**Comment by justinfagnani** [comment]
@StephenRiosDev do you have a reproduction of the bug?
