### ISSUE TITLE
[@lit-labs/react] use-controller.js hook state not updating

### ISSUE THREAD

**Issue by ajmchambers** [lit/lit#2950]
# Description

I've created a [stackblitz example](https://stackblitz.com/edit/vitejs-vite-sem6tx?file=src%2FApp.tsx,src%2Flit%2Flib%2Fuse-controller.ts,src%2Flit%2Fcomponents%2Flit-controller-example.ts,src%2Fcomponents%2FLitControllerExample.ts,src%2Fcomponents%2FReactHookExample.tsx&terminal=dev).

NOTE: use-controller was recreated locally in '/src/lit/lib/use-controller.ts' due to https://github.com/lit/lit/issues/2948

There are two controllers: mouse-controller and clock-controller.

First example is a lit element that uses the two controllers (wrapped into react component).
Second example is a react component using the two hooks (wrapped using use-controller).

In the second example using the wrapped hooks, the state is not updating for some reason.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/5426717/170233518-d14dd6a3-fdeb-4a97-a08b-0c1fd522c35d.png">

**Comment by AndrewJakubowicz** [comment]
Did a quick investigation. This seems to be an issue with React 18. Stackblitz example works when down versioned to React 17.

**Comment by justinfagnani** [comment]
And this likely has something to do with the "kick" mechanism we use to force a re-render when a controller calls `host.requestUpdate()`: https://github.com/lit/lit/blob/main/packages/labs/react/src/use-controller.ts#L119

**Comment by sorvell** [comment]
The `useState` call in `useController` is not pure and that's a no-no. I believe this would be the fix they'd recommend. The stateful part (calling connected) is done in `useLayoutEffect`. This means that controllers that do anything side effect-ful in the constructor would be bad.

https://stackblitz.com/edit/vitejs-vite-uiqary?file=src%2FApp.tsx,src%2Flit%2Flib%2Fuse-controller.ts,src%2Flit%2Fcomponents%2Flit-controller-example.ts,src%2Fcomponents%2FLitControllerExample.ts,src%2Fcomponents%2FReactHookExample.tsx&terminal=dev
