### ISSUE TITLE
[labs/analyzer] Improve event typing

### ISSUE THREAD

**Issue by sorvell** [lit/lit#2974]
To better type event handler functions, we'll want to add some way to configure typing for an event's payload. 

See https://github.com/lit/lit/pull/2880#discussion_r884024730.

**Comment by cyantree** [comment]
What about some class decorator like:
```
@customElement('my-component')
@event<CustomEvent<{data: string}>>('my-event')
export class MyComponent extends LitElement {
```

Maybe also add information about `bubbles` that could give TS more hints when the event can be used (only on the emitting element or anywhere in the DOM).

Ideally this also type information would apply when dispatching an event.

**Comment by justinfagnani** [comment]
What we would need out of a decorator or other solution is a way to turn an event into a "payload". A property name would usually suffice, but a callback would be more general.

**Comment by sorvell** [comment]
Fixed via https://github.com/lit/lit/pull/3377.
