### ISSUE TITLE
Typing for directives is incorrect when using lit-html

### ISSUE THREAD

**Issue by andyjessop** [lit/lit#3040]
# Description

It seems that the typing for directives is incorrect when used in lit-html. I'm following the example for custom directives [here](https://lit.dev/docs/v1/lit-html/creating-directives/).

# Steps to Reproduce

1. Write this code

```
import { html } from 'lit-html';
import { directive } from 'lit-html/directive';

const helloDirective = directive(() => (part) => { part.setValue('Hello')});

const helloTemplate = html`<div>${helloDirective()}</div>`
```

It seems that function directives are not typed. Is it possible to use directives in lit-html with TypeScript?

2. See this output...
```
Argument of type '() => (part: any) => void' is not assignable to parameter of type 'DirectiveClass'.
  Type '() => (part: any) => void' provides no match for the signature 'new (part: PartInfo): Directive'
```

**Comment by justinfagnani** [comment]
This is the error you see when you try to use a lit-html 1.0 directive with lit-html 2.0. Are you reading the old lit-html doc site

You can see the lit-html 2.0 directive interface here: https://lit.dev/docs/templates/custom-directives/#creating-class-based-directives

**Comment by andyjessop** [comment]
Thanks very much.
