### ISSUE TITLE
[labs/virtualizer] `virtualize` directive only re-renders children if `items` or `renderItem` have changed

### ISSUE THREAD

**Issue by najikahalsema** [lit/lit#3052]
# Description

When using the `virtualize` directive, children fail to re-render in response to certain types of data changes.

Specifically, children are only re-rendered if data within the `items` array changes (or if the `renderItem` template itself is replaced). This means that any changes to data stored _outside_ the `items` array will fail to trigger re-rendering, even if logic or bindings in the `renderItem` template refer to the changed data.

# Steps to Reproduce

1. Go to the demo link
2. Click "update selected" button
3. See that selected changes in the second list, but not in the first. 

## Live Reproduction Link

[Demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7dmlydHVhbGl6ZX0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL3ZpcnR1YWxpemUuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgOmhvc3QgeyBcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIGhlaWdodDogMjAwcHg7XG4gICAgICB9YDtcblxuICBAcHJvcGVydHkoKSBcbiAgcHVibGljIHNlbGVjdGVkID0gbmV3IFNldChbMiwgNV0pO1xuICBcbiAgQHByb3BlcnR5KClcbiAgcHVibGljIGl0ZW1zID0gQXJyYXkuZnJvbShBcnJheSgxMDApLmtleXMoKSk7XG4gIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgIDxkaXY-XG4gICAgICAke3ZpcnR1YWxpemUoe1xuICAgICAgICBzY3JvbGxlcjogdHJ1ZSwgXG4gICAgICAgIGl0ZW1zOiB0aGlzLml0ZW1zLCBcbiAgICAgICAgcmVuZGVySXRlbTogKGl0ZW0pID0-IGh0bWxgPGRpdj4ke2l0ZW19ICR7dGhpcy5zZWxlY3RlZC5oYXMoaXRlbSkgPyAnc2VsZWN0ZWQnIDogJyd9PC9kaXY-YFxuICAgICAgfSl9XG4gICAgIDwvZGl2PlxuICAgIGA7XG4gIH1cbn0ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vb3RoZXItZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgXG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZz48L3NpbXBsZS1ncmVldGluZz5cbiAgPG90aGVyLWdyZWV0aW5nPjwvb3RoZXItZ3JlZXRpbmc-XG4gIDxidXR0b24-VXBkYXRlIGBzZWxlY3RlZGA8L2J1dHRvbj5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCI-XG4gICAgbGV0IHVwZGF0ZXMgPSAwOyBcbiAgICBjb25zdCBidXR0b24gPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdidXR0b24nKTtcbiAgICBjb25zdCBzaW1wbGVHcmVldGluZyA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ3NpbXBsZS1ncmVldGluZycpO1xuICAgIGNvbnN0IG90aGVyR3JlZXRpbmcgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdvdGhlci1ncmVldGluZycpO1xuXG4gICAgYnV0dG9uLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4ge1xuICAgICAgY29uc3Qgc2VsZWN0ZWQgPSB1cGRhdGVzJTIgPT0gMCA_IG5ldyBTZXQgKFsxLCA3XSkgOiBuZXcgU2V0IChbMCwgM10pO1xuICAgICAgdXBkYXRlcyArPSAxO1xuICAgICAgc2ltcGxlR3JlZXRpbmcuc2VsZWN0ZWQgPSBzZWxlY3RlZDtcbiAgICAgIG90aGVyR3JlZXRpbmcuc2VsZWN0ZWQgPSBzZWxlY3RlZDtcblxuICAgIH0pO1xuICA8L3NjcmlwdD5cbjwvYm9keT4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoib3RoZXItZ3JlZXRpbmcudHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQgJ0BsaXQtbGFicy92aXJ0dWFsaXplcic7XG5cbkBjdXN0b21FbGVtZW50KCdvdGhlci1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgT3RoZXJHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgOmhvc3QgeyBcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIGhlaWdodDogMjAwcHg7XG4gICAgICB9YDtcblxuICAgIEBwcm9wZXJ0eSgpIFxuICBwdWJsaWMgc2VsZWN0ZWQgPSBuZXcgU2V0KFsyLCA1XSk7XG4gIFxuICBAcHJvcGVydHkoKVxuICBwdWJsaWMgaXRlbXMgPSBBcnJheS5mcm9tKEFycmF5KDEwMCkua2V5cygpKTtcbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgPGxpdC12aXJ0dWFsaXplclxuICAgICAgICBzY3JvbGxlciBcbiAgICAgICAgLml0ZW1zPSR7dGhpcy5pdGVtc31cbiAgICAgICAgLnJlbmRlckl0ZW09JHsoaXRlbSkgPT4gaHRtbGA8ZGl2Pk90aGVyICR7aXRlbX0gJHt0aGlzLnNlbGVjdGVkLmhhcyhpdGVtKSA_ICdzZWxlY3RlZCcgOiAnJ308L2Rpdj5gfVxuICAgID5cbiAgICAgPC9saXQtdmlydHVhbGl6ZXI-XG4gICAgYDtcbiAgfVxufSJ9XQ)

## Expected Results

`selected` should change in both lists. 

cc: @Westbrook

**Comment by graynorton** [comment]
Thanks for the catch, @najikahalsema.

@usergenic, to make the `virtualize` directive match the (correct) behavior of the `<lit-virtualizer>` element, I believe we just need to replace `return noChange;` with `return this.render();` in the directive's `update` method:

https://github.com/lit/lit/blob/bf13dae231d26f350c117271a45e047ee151fc20/packages/labs/virtualizer/src/virtualize.ts#L95-L108

**Comment by usergenic** [comment]
@graynorton I'll update and include it in first round of functional tests this week.

**Comment by Westbrook** [comment]
If this return is the only change here, would it be possible for us to submit this update so we can get a release with this fix soon-ish?

**Comment by usergenic** [comment]
> If this return is the only change here, would it be possible for us to submit this update so we can get a release with this fix soon-ish?

I have been trying to get testing working so I could include but have had some difficulties which delayed that fix.  I'm back at work on Thursday, will try to get fix in with or without the tests.

**Comment by usergenic** [comment]
@najikahalsema @Westbrook I really wanted to figure out how to be able to prove this was not working by writing a regression test first, but I'm unable to repro in terms of my test assertions.

If you see anything obvious why my test passes even though the actual in-browser experience shows failure, let me know.  I'm going to sign off now because it is late but I will probably pick up again on Sunday.
https://github.com/lit/lit/pull/3133/files#diff-ef8342c7715ff44941917fad1c544b56e4d39bbd4cd665fb379b293b681cc14b

Will probably cut a release Monday with the suggested fix-- but as I am out tomorrow I don't want to publish without being on-hand to manage potential fallout.  (publishing/tagging from the new location in lit monorepo and all that).

**Comment by usergenic** [comment]
Yay!  I fixed the test fixture to demonstrate the noChange behavior and have updated the code in #3133 to return `this.render()`.  Will get this through and release next.  Thanks for your patience :)
