### ISSUE TITLE
[labs/context]: Invalid example code

### ISSUE THREAD

**Issue by oliversalzburg** [lit/lit#3058]
# Description

The example given under "Consuming a context" is invalid. The code raises a TypeScript error.

# Steps to Reproduce

The code in the example already produces the error. It also imports `contextRequest` and then uses `contextProvided`.

## Expected Results

The example code should be valid.

## Actual Results

```
Argument of type 'Logger' is not assignable to parameter of type 'ReactiveElement & Record<"logger", Logger>'.
  Type 'Logger' is not assignable to type 'Record<"logger", Logger>'.
    Types of property 'logger' are incompatible.
      Type 'Logger | undefined' is not assignable to type 'Logger'.
        Type 'undefined' is not assignable to type 'Logger'.
```

## Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 11
- [x] Safari 10
- [x] IE 11

**Comment by oliversalzburg** [comment]
Maybe the code in the implementation is actually wrong. If I make this `Record` a `Partial<Record<...>>`, the error goes away: https://github.com/lit/lit/blob/main/packages/labs/context/src/lib/decorators/context-provided.ts#L50

**Comment by drk-mtr** [comment]
Doing this from memory so apologies if I'm sharing bad info. It may be as simple as changing `logger?` -> `logger!` - and obviously updating the import for `contextProvided`.

**Comment by justinfagnani** [comment]
I have a fix for this in https://github.com/lit/lit/pull/3398
