### ISSUE TITLE
Can not get @query to work, think its broken

### ISSUE THREAD

**Issue by herrKlein** [lit/lit#3066]
# Description

@query is broken
I tried several notations, read the queried property in different callbacks, but no avail.
The example shows query the div, and reading it in the connectedCallback

# Steps to Reproduce

```ts
import {customElement, property, query} from 'lit/decorators.js';

@query('#tree', true)
private tree!: HTMLDivElement;
```

## Live Reproduction Link

[playground link](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHksIHF1ZXJ5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIEBxdWVyeSgnI3RyZWUnLCB0cnVlKVxuICBwcml2YXRlIHRyZWUhOiBIVE1MRGl2RWxlbWVudDtcbiAgXG4gIEBwcm9wZXJ0eSgpXG4gIG5hbWUgPSAnU29tZWJvZHknO1xuXG4gIGNvbnN0cnVjdG9yKCkge1xuICAgIHN1cGVyKCk7XG4gIH1cbiAgXG4gIGNvbm5lY3RlZENhbGxiYWNrKCkge1xuICAgIHN1cGVyLmNvbm5lY3RlZENhbGxiYWNrKClcbiAgICB0aGlzLm5hbWUgPSB0aGlzLnRyZWUuaW5uZXJUZXh0O1xuICB9XG4gIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-XG4gICAgICAgIDxkaXYgaWQ9XCJ0cmVlXCI-am93PC9kaXY-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

## Expected Results

query should deliver the tree object

## Actual Results

Uncaught TypeError: Cannot read properties of null (reading 'innerText')
    at SimpleGreeting.connectedCallback 

## Browsers Affected
- [x] Chrome

**Comment by aomarks** [comment]
`connectedCallback` runs before the first render, so in your example `this.tree` is `null` at that time. If you use `firstUpdated` instead of `connectedCallback`, then it will run after first render, and should work.
