### ISSUE TITLE
[infra] Sources not inlined in sourcemap

### ISSUE THREAD

**Issue by gberaudo** [lit/lit#3107]
### Which package(s) are affected?

Localize (@lit/localize)

### Description

The `tsconfig.json` of serveral lit packages do not use the `inlineSources: true` configuration. This is inconsistent with the other packages and make `lit-localize` original source not available for debugging.

Here is the list of packages:
- localize-tools;
- localize;
- tests.

I prepared a commit with the fix locally but I don't have the Google CLA signed yet.
It will certainly be faster if someone with accepted CLA creates the pull request.

### Reproduction

I detected the issue while using the parceljs v2 bundler.

### Workaround

None

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 0.11.3

### Browser/OS/Node environment

This is independent of the browser.

**Comment by justinfagnani** [comment]
Thanks for the good report!
