### ISSUE TITLE
[reactive-element] `ComplexAttributeConverter`, `this` is `undefined` in `fromAttribute` method

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [lit/lit#3108]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I try to implement a `ComplexAttributeConverter` whereas I want to pass a default value to it that should be used as a fallback in the `fromAttribute` method. Unfortunately `this` is undefined in this method. I debugged why this is the case and it seems the function is not called via [apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) which results in `this` being undefined.

I wonder why is this the case. Can we fix this?

### Reproduction

- Implement converter that allows passing a default value via constructor

``` ts
import { ComplexAttributeConverter } from "lit-element";

export class IntegerAttributeConverter implements ComplexAttributeConverter<Number> {
  private _defaultValue: Number;

  constructor(defaultValue: Number) {
    this._defaultValue = defaultValue;
  }

  toAttribute(value: Number, _type?: unknown): unknown {
    return `${value}`;
  }

  fromAttribute(value: string|null, _type?: unknown): Number {
    if (value) {
      const result = Number.parseInt(value, 10);

      if (isNaN(result))
        return this._defaultValue;
      else
        return result;
    }
    else
      return this._defaultValue;
  }
}
```

- Use converter in a property decoration

``` ts
const defaultPageSize: number = 10;

@property({ type: Number, converter: new IntegerAttributeConverter(defaultPageSize) })
  pageSize: number = defaultPageSize;
``` 

### Workaround

Implement the converter as a callback function

``` ts
const defaultPageSize: number = 10;

@property({
  type: Number,
  converter: (attributeValue: string | null, _type?: unknown): Number => {
    // same code as IntegerAttributeConverter.fromAttribute with access to defaultPageSize
  })
pageSize: number = defaultPageSize;
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.2

### Browser/OS/Node environment

Doesn't matter

**Comment by justinfagnani** [comment]
Thanks for the report! This is indeed a bug.

**Comment by nebarf** [comment]
Will take a look at this if it sounds good to you.

**Comment by ViRuSTriNiTy** [comment]
@nebarf Go for it.

**Comment by ViRuSTriNiTy** [comment]
Works as expected now, thanks a bunch!
