### ISSUE TITLE
[lit-html] lit-html has a dependecy to a @types package (should be a dev dependency)

### ISSUE THREAD

**Issue by jogibear9988** [lit/lit#3124]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

In the package.json there seems to be a wrong dependecy:

https://github.com/lit/lit/blob/main/packages/lit-html/package.json#L281

### Reproduction

look at https://github.com/lit/lit/blob/main/packages/lit-html/package.json#L281

### Workaround

it's still usable

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

current

### Browser/OS/Node environment

not relevant

**Comment by augustjk** [comment]
Thank you for the report but this is intended. See https://github.com/lit/lit/issues/3308#issuecomment-1275297241
