### ISSUE TITLE
Render bug

### ISSUE THREAD

**Issue by lillallol** [lit/lit#3197]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When `html` is inline in `render`,  elements get replaced that should not.

### Reproduction

[playground link](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge3JlbmRlcixodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5cbnNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnN0IG15VGVtcGxhdGUgPSAobmFtZSkgPT4gaHRtbGA8ZGl2IGlkPVwibXktZGl2XCI-SGVsbG8gJHtuYW1lfTwvZGl2PmA7XG4gICAgXG4gICAgcmVuZGVyKG15VGVtcGxhdGUoXCJlYXJ0aFwiKSwgZG9jdW1lbnQuYm9keSk7XG4gICAgXG4gICAgbGV0IGRpdiA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKFwibXktZGl2XCIpO1xuICAgIFxuICAgIGZ1bmN0aW9uIGNoZWNrRGl2KCkge1xuICAgICAgICBpZiAoZGl2ICE9PSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZChcIm15LWRpdlwiKSkgZG9jdW1lbnQuYm9keS5zdHlsZS5iYWNrZ3JvdW5kQ29sb3IgPSBcInJlZFwiO1xuICAgICAgICBlbHNlIGRvY3VtZW50LmJvZHkuc3R5bGUuYmFja2dyb3VuZENvbG9yID0gXCJncmVlblwiO1xuICAgIH1cbiAgICBcbiAgICBzZXRUaW1lb3V0KCgpID0-IHtcbiAgICAgICAgLyoqXG4gICAgICAgICAqICBUaGlzIHJlbmRlciBkb2VzIG5vdCByZXBsYWNlIGBkaXZgLCBhcyBleHBlY3RlZC5cbiAgICAgICAgICovXG4gICAgICAgIHJlbmRlcihteVRlbXBsYXRlKFwibWFyc1wiKSwgZG9jdW1lbnQuYm9keSk7XG4gICAgICAgIGNoZWNrRGl2KCk7XG4gICAgfSwxZTMpO1xuICAgIFxuICAgIHNldFRpbWVvdXQoKCkgPT4ge1xuICAgICAgICAvKipcbiAgICAgICAgICogIEJVRyA6IFRoaXMgcmVuZGVyIGlzIHJlcGxhY2luZyBgZGl2YCwgd2hpbGUgaXQgc2hvdWxkIG5vdC5cbiAgICAgICAgICovXG4gICAgICAgIHJlbmRlcihodG1sYDxkaXYgaWQ9XCJteS1kaXZcIj5IZWxsbyAke1wibWFyc1wifTwvZGl2PmAsIGRvY3VtZW50LmJvZHkpO1xuICAgICAgICBjaGVja0RpdigpO1xuICAgIH0sMmUzKTtcbn0sMCk7In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-PC9ib2R5PiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

### Workaround

I have not found a workaround. That is the responsibility of render. It makes no sense for me to find a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Tried with lit-html@2.2.7, as I got it from here: https://unpkg.com/lit-html@2.2.7/lit-html.js

### Browser/OS/Node environment

Chrome 103.0.5060.114 (64bit)
Windows 10 Pro 21H2

Just used a single html file with an inline script tag and nothing more than that.

**Comment by justinfagnani** [comment]
This is working as intended. lit-html implements DOM stability at the _template_ level, avoid any kind of DOM diff. If you render a new template to a location, the location is cleared before rendering the template.

**Comment by lillallol** [comment]
> If you render a new template to a location

Are you saying that `lit-html` is treating this:

```js
html`<div id="my-div">Hello ${"mars"}</div>`
```

different than this:

```js
myTemplate("mars")
```

?

1. How is this done?
2. Why is this done?
3. Is there any place in the documentation that I can read about it?

**Comment by justinfagnani** [comment]
All template expressions are unique, even if they have the same content. So, yes, they are different because `myTemplate` has a different template expression in it.

**Comment by lillallol** [comment]
TIL. Thx for your time.
