### ISSUE TITLE
[reactive-element] Support standard (stage 3) decorators

### ISSUE THREAD

**Issue by XGHeaven** [lit/lit#3200]
### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Now, lit does not support the version `2021-12` decorator proposal.

### Alternatives and Workarounds

No.
The version `2018-09` and `legacy` work, but I cannot convert other decorators back to the old version.

**Comment by justinfagnani** [comment]
We'll probably support the current decorators proposal when it ships in TypeScript and one native runtime.

**Comment by gund** [comment]
FYI native decorators already implemented in TS v5 https://github.com/microsoft/TypeScript/pull/50820

**Comment by justinfagnani** [comment]
But not metadata, which we need for attribute conversion. I'm hoping that's settled by TypeScript 5.1

**Comment by pmcelhaney** [comment]
Tentatively scheduled for TypeScript 5.2.

https://github.com/microsoft/TypeScript/issues/53461#issuecomment-1481760507

**Comment by rictic** [comment]
This is fixed in 3.0 branch.
