### ISSUE TITLE
libraries used to create MVC frameworks should not do top level DOM access

### ISSUE THREAD

**Issue by lillallol** [lit/lit#3207]
### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

lit-html can be used to create client side MVC frameworks (e.g. MobX + lit-html + web components). When creating an MVC app, it is natural to create tests that deal purely with the model of the app and hence no need for DOM. However, top level DOM access of lit-html prevents those tests from getting executed in nodejs.

### Alternatives and Workarounds

1. The MVC entry point has to split in two entry points, one for the pure-model, i.e. not top level DOM access, and one for the non-model (this increases complexity).
2. Manually edit lit-html so that it does not do top level DOM access (tried it, and failed, maybe I should try more).
3. Execute tests in browser (this increases complexity).

**Comment by justinfagnani** [comment]
This is fixed by https://github.com/lit/lit/pull/3156

On the next release there will be an export condition named `"node"` that will be used in Node versions that support package exports (newer than v13.7.0 or v12.16.0).
