### ISSUE TITLE
[labs/react] Add back the reserved React property warning

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3212]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

React (@lit-labs/react)

### Description

https://github.com/lit/lit/pull/2800 removed our warning for reserved React property names because it changed how we detect custom element properties. We should add this back, but only in a dev build, which we'll need to set up for the react package.

### Alternatives and Workarounds

n/a

**Comment by taylor-vann** [comment]
Curious if we can close this issue.

We don't iterate over the element like we didn't with #2800 which doesn't give us the opportunity to warn users about properties except for on component updates.
