### ISSUE TITLE
[labs/react] Custom element property detection doesn't match React 19

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3213]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

React 19's custom element support does an `in` check on a component instance, after creating it, and without any filtering of properties in HTMLElement.prototype.

We should try to match this behavior as closely as we can.

### Reproduction

n/a

### Workaround

n/a

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

all

### Browser/OS/Node environment

all

**Comment by justinfagnani** [comment]
See this table that we can use to derive tests: https://josepharhar.github.io/react-custom-elements/

**Comment by taylor-vann** [comment]
@justinfagnani would this be covered in the recent #3128 submission?

**Comment by taylor-vann** [comment]
Closing with #3128 submission.
Can always reopen if behavior does not match React 19
