### ISSUE TITLE
'@lit-labs/cli@*' is not in this registry

### ISSUE THREAD

**Issue by thomasverleye** [lit/lit#3220]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

When i'm following the instructions to install Lit Labs CLI I get following error:
```bash
$  npm i -g @lit-labs/cli
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lit-labs%2fcli - Not found
npm ERR! 404 
npm ERR! 404  '@lit-labs/cli@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thomasverleye/.npm/_logs/2022-08-17T08_08_23_943Z-debug-0.log
```

### Reproduction

Run `npm i -g @lit-labs/cli`

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.3.0

### Browser/OS/Node environment

Node version: v16.16.0
NPM version: 8.16.0

**Comment by aomarks** [comment]
We haven't published the Lit CLI yet. Though I can see that it is confusing that our README is not clear about this. We do actually plan to do a `-pre` release soon, possibly as early as this week.
