### ISSUE TITLE
Uncaught ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by beijingbeef** [lit/lit#3230]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Some users with old browsers get this error. 
```
Uncaught ReferenceError: globalThis is not defined
```
It looks like `reactive-element` build for node always. 

https://github.com/lit/lit/blob/ae6f6808f539254b72ec7efcff34b812173abe64/packages/reactive-element/rollup.config.js#L34

https://github.com/lit/lit/blob/ae6f6808f539254b72ec7efcff34b812173abe64/packages/reactive-element/src/reactive-element.ts#L1542

### Reproduction

Use a old browser

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.2.1

### Browser/OS/Node environment

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3947.100 Safari/537.36

**Comment by aomarks** [comment]
Thanks for the report.

How/why are you serving the node build to a browser?

**Comment by beijingbeef** [comment]
I didn't set anything for the build preference. It seems all builds will be the node build.

https://github.com/lit/lit/blob/ae6f6808f539254b72ec7efcff34b812173abe64/packages/reactive-element/rollup.config.js#L34

Looks like `includeNodeBuild` always is `true`

**Comment by aomarks** [comment]
What server are you using (e.g. @web/dev-server), and what if any build tools are you running (e.g. rollup, webpack)?

The `includeNodeBuild` configuration you referenced enables a separate node build. There are multiple builds for each package. The default browser build is in the top-level of the package, and the node-specific build is in the `/node/` directory. Only if a tool you are using has selected the `node` export condition would you end up loading the node build instead of the default browser build.

**Comment by beijingbeef** [comment]
Thanks, I'm using webpack. Any idea how to check if set `node export condition` or not? Like in what conditions, it is a "note export condition". How does the tool determine if a build is node export or not. 

Thanks in advance.

**Comment by augustjk** [comment]
I haven't actually used it myself but I believe this is the setting: https://webpack.js.org/configuration/resolve/#resolveconditionnames
I'm not sure what webpack's default behavior is but the `'default'` export condition is meant to be for browsers in the `lit` packages.

**Comment by beijingbeef** [comment]
Thanks, the link you posted is very useful. I found out the root cause for my case. We have a mirror of all npm repositories. The approved version of reactive-element is still 1.3.4. There is no node build yet at 1.3.4 and globalThis is used in that version. https://github.com/lit/lit/blob/%40lit/reactive-element%401.3.4/packages/reactive-element/src/reactive-element.ts#L1524

Thanks for the help.
