### ISSUE TITLE
Can not render svg element

### ISSUE THREAD

**Issue by happy-little-one** [lit/lit#3247]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

```
import {html, render } from 'lit-html'
    
const plus = [
  'M474 152m8 0l60 0q8 0 8 8l0 704q0 8-8 8l-60 0q-8 0-8-8l0-704q0-8 8-8Z',
  'M168 474m8 0l672 0q8 0 8 8l0 60q0 8-8 8l-672 0q-8 0-8-8l0-60q0-8 8-8Z',
]
    
 const app = (plus) => html`
  <svg width="18" height="18" viewBox="0 0 1024 1024 ">
    ${plus.map(d => html`<path d=${d} />`)}
   </svg> 
  `
    
 render(app(plus), document.body)
```
this will not be rendered

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIHJlbmRlciB9IGZyb20gJ2xpdC1odG1sJ1xuICAgIFxuY29uc3QgcGx1cyA9IFtcbiAgJ000NzQgMTUybTggMGw2MCAwcTggMCA4IDhsMCA3MDRxMCA4LTggOGwtNjAgMHEtOCAwLTgtOGwwLTcwNHEwLTggOC04WicsXG4gICdNMTY4IDQ3NG04IDBsNjcyIDBxOCAwIDggOGwwIDYwcTAgOC04IDhsLTY3MiAwcS04IDAtOC04bDAtNjBxMC04IDgtOFonLFxuXVxuICAgIFxuIGNvbnN0IGFwcCA9IChwbHVzKSA9PiBodG1sYFxuICA8c3ZnIHdpZHRoPVwiMThcIiBoZWlnaHQ9XCIxOFwiIHZpZXdCb3g9XCIwIDAgMTAyNCAxMDI0IFwiPlxuICAgICR7cGx1cy5tYXAoZCA9PiBodG1sYDxwYXRoIGQ9JHtkfSAvPmApfVxuICAgPC9zdmc-IFxuICBgXG4gICAgXG4gcmVuZGVyKGFwcChwbHVzKSwgZG9jdW1lbnQuYm9keSlcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

### Workaround

I have not found a workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 2.3.1

### Browser/OS/Node environment

brower: Edge latest
node: 16.x

**Comment by augustjk** [comment]
Hi! For providing svg fragments in expressions, you need to use the [`svg`](https://lit.dev/docs/api/templates/#svg) tag function.

Like this: https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIHJlbmRlciwgc3ZnIH0gZnJvbSAnbGl0LWh0bWwnXG4gICAgXG5jb25zdCBwbHVzID0gW1xuICAnTTQ3NCAxNTJtOCAwbDYwIDBxOCAwIDggOGwwIDcwNHEwIDgtOCA4bC02MCAwcS04IDAtOC04bDAtNzA0cTAtOCA4LThaJyxcbiAgJ00xNjggNDc0bTggMGw2NzIgMHE4IDAgOCA4bDAgNjBxMCA4LTggOGwtNjcyIDBxLTggMC04LThsMC02MHEwLTggOC04WicsXG5dXG4gICAgXG4gY29uc3QgYXBwID0gKHBsdXMpID0-IGh0bWxgXG4gIDxzdmcgd2lkdGg9XCIxOFwiIGhlaWdodD1cIjE4XCIgdmlld0JveD1cIjAgMCAxMDI0IDEwMjQgXCI-XG4gICAgJHtwbHVzLm1hcChkID0-IHN2Z2A8cGF0aCBkPSR7ZH0gLz5gKX1cbiAgIDwvc3ZnPiBcbiAgYFxuICAgIFxuIHJlbmRlcihhcHAocGx1cyksIGRvY3VtZW50LmJvZHkpXG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

**Comment by bicknellr** [comment]
Thanks, @augustjk!
