### ISSUE TITLE
Error: `live` bindings can only contain a single expression

### ISSUE THREAD

**Issue by andyjessop** [lit/lit#3259]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Rendering the following form, I get an error from the `live` directive:
```
Error: `live` bindings can only contain a single expression
```
Here, `emailValue` is `null`.

```ts
function template() {
    return html`
      <form>
        <input
          type="text"
          name="${email.name}"
          placeholder="${email.placeholder}"
          @change=${(e: Event) => onChange(email.name, (e.target as HTMLInputElement).value)}
          .value=${live(emailValue)}"
        />
        ${email.errorMessages.length && !email.isPristine
          ? html`${map(email.errorMessages, error => html`<div>${error}</div>`)}`
          : null
        }
        <input
          type="password"
          name="${password.name}"
          placeholder="${password.placeholder}"
          @change=${(e: Event) => onChange(password.name, (e.target as HTMLInputElement).value)}
          .value=${live(password.value)}"
        />
        ${password.errorMessages.length && !password.isPristine
          ? html`${map(password.errorMessages, error => html`<div>${error}</div>`)}`
          : null
        }
        <button @click=${onSubmit}>Submit</button>
      </form>
    `;
  }
```

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgcmVuZGVyfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgbGl2ZSB9IGZyb20gJ2xpdC1odG1sL2RpcmVjdGl2ZXMvbGl2ZS5qcyc7XG5pbXBvcnQgeyBtYXAgfSBmcm9tICdsaXQtaHRtbC9kaXJlY3RpdmVzL21hcC5qcyc7XG5cbmZ1bmN0aW9uIG5vb3AoKSB7fVxuY29uc3QgZW1haWwgPSB7XG4gICAgZXJyb3JNZXNzYWdlczogW10sXG4gICAgaXNQcmlzdGluZTogdHJ1ZSxcbiAgICBuYW1lOiAnZW1haWwnLFxuICAgIHBsYWNlaG9sZGVyOiAnWW91ciBlbWFpbCBhZGRyZXNzJyxcbiAgICBzdWNjZXNzTWVzc2FnZTogbnVsbCxcbiAgfTtcbiAgICBjb25zdCBwYXNzd29yZCA9IHtcbiAgICBlcnJvck1lc3NhZ2VzOiBbXSxcbiAgICBpc1ByaXN0aW5lOiB0cnVlLFxuICAgIG5hbWU6ICdwYXNzd29yZCcsXG4gICAgcGxhY2Vob2xkZXI6ICdZb3VyIGVtYWlsIGFkZHJlc3MnLFxuICAgIHN1Y2Nlc3NNZXNzYWdlOiBudWxsLFxuICAgIHZhbHVlOiBudWxsLFxuICB9O1xuIGNvbnN0IGVtYWlsVmFsdWUgPSBudWxsO1xuXG4gIHJlbmRlcih0ZW1wbGF0ZSgpLCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncm9vdCcpKTtcblxuICBmdW5jdGlvbiB0ZW1wbGF0ZSgpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxmb3JtPlxuICAgICAgICA8aW5wdXRcbiAgICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgICAgbmFtZT1cIiR7ZW1haWwubmFtZX1cIlxuICAgICAgICAgIHBsYWNlaG9sZGVyPVwiJHtlbWFpbC5wbGFjZWhvbGRlcn1cIlxuICAgICAgICAgIEBjaGFuZ2U9JHtub29wfVxuICAgICAgICAgIC52YWx1ZT0ke2xpdmUoZW1haWxWYWx1ZSB8fCAnJyl9XCIgLz5cbiAgICAgICAgJHtlbWFpbC5lcnJvck1lc3NhZ2VzLmxlbmd0aCAmJiAhZW1haWwuaXNQcmlzdGluZVxuICAgICAgICAgID8gaHRtbGAke21hcChlbWFpbC5lcnJvck1lc3NhZ2VzLCBlcnJvciA9PiBodG1sYDxkaXY-JHtlcnJvcn08L2Rpdj5gKX1gXG4gICAgICAgICAgOiBudWxsXG4gICAgICAgIH1cbiAgICAgICAgPGlucHV0XG4gICAgICAgICAgdHlwZT1cInBhc3N3b3JkXCJcbiAgICAgICAgICBuYW1lPVwiJHtwYXNzd29yZC5uYW1lfVwiXG4gICAgICAgICAgcGxhY2Vob2xkZXI9XCIke3Bhc3N3b3JkLnBsYWNlaG9sZGVyfVwiXG4gICAgICAgICAgQGNoYW5nZT0ke25vb3B9XG4gICAgICAgICAgLnZhbHVlPSR7bGl2ZShwYXNzd29yZC52YWx1ZSB8fCAnJyl9XCIgLz5cbiAgICAgICAgJHtwYXNzd29yZC5lcnJvck1lc3NhZ2VzLmxlbmd0aCAmJiAhcGFzc3dvcmQuaXNQcmlzdGluZVxuICAgICAgICAgID8gaHRtbGAke21hcChwYXNzd29yZC5lcnJvck1lc3NhZ2VzLCBlcnJvciA9PiBodG1sYDxkaXY-JHtlcnJvcn08L2Rpdj5gKX1gXG4gICAgICAgICAgOiBudWxsXG4gICAgICAgIH1cbiAgICAgICAgPGJ1dHRvbiBAY2xpY2s9JHtub29wfT5TdWJtaXQ8L2J1dHRvbj5cbiAgICAgIDwvZm9ybT5cbiAgICBgO1xuICB9XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vcmVwcm8uanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IGlkPVwicm9vdFwiPjwvZGl2PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

^2.3.1

### Browser/OS/Node environment

Chrome, MacOS, node v18.3.0, npm 8.11.0

**Comment by andyjessop** [comment]
[This](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgcmVuZGVyfSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgbGl2ZSB9IGZyb20gJ2xpdC1odG1sL2RpcmVjdGl2ZXMvbGl2ZS5qcyc7XG5pbXBvcnQgeyBtYXAgfSBmcm9tICdsaXQtaHRtbC9kaXJlY3RpdmVzL21hcC5qcyc7XG5cbmZ1bmN0aW9uIG5vb3AoKSB7fVxuXG4gY29uc3QgZW1haWxWYWx1ZSA9IG51bGw7XG5cbiAgcmVuZGVyKHRlbXBsYXRlKCksIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdyb290JykpO1xuXG4gIGZ1bmN0aW9uIHRlbXBsYXRlKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPGZvcm0-XG4gICAgICAgIDxpbnB1dCAudmFsdWU9JHtsaXZlKGVtYWlsVmFsdWUpfVwiIC8-XG4gICAgICAgIDxidXR0b24gQGNsaWNrPSR7bm9vcH0-U3VibWl0PC9idXR0b24-XG4gICAgICA8L2Zvcm0-XG4gICAgYDtcbiAgfVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3JlcHJvLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGRpdiBpZD1cInJvb3RcIj48L2Rpdj5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0) is a more minimal example. I think I must be misunderstanding how `live` works.

**Comment by justinfagnani** [comment]
There's an error in your template: you have an unbalanced `"` after the `live()` expression. Attributes need to be either quoted or not. If they don't have an opening quote (and no whitespace), then an unbalanced closing quote will be part of the attribute _value_, so to Lit the expression looks like: `${live(emailValue)}"`

Also, `<input>` is a void element, not a self-closing element (HTML doesn't have those), so you don't need the `/` at the end of the tag.

**Comment by andyjessop** [comment]
Thank you! Keep up the great work, I love this project!
