### ISSUE TITLE
Rename `decorator.js` exports field to `decorator`

### ISSUE THREAD

**Issue by mahdi-farnia** [lit/lit#3275]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

It would be REALLY useful to remove the extesions from the exports field in package.json to disable webpack errors like this:

> Package path `lit/decorators` is not exported from package

Otherwise we should always add extension the auto import path :(

### Alternatives and Workarounds

just remove the extensions from package.json

**Comment by justinfagnani** [comment]
We very specifically require file extensions so that Lit imports work in browsers and Lit bare module specifiers are able to be resolved with short import maps.

**Comment by mahdi-farnia** [comment]
But this is sooo annoying when using a bundler like webpack, because every one (almost every one) uses auto import services, U should ALWAYS provide the extension, which is very uncommon.

The libraries like react, exports every single api from the main module ('react') which is very helpful to not using multiple imports like this:

```ts
import {...} from "lit"
import {...} from "lit/directive"
import {...} from "lit/directives/..."
import {...} from "lit/decorators"
```

I think simplicity is on of the key of an open source project! Better to fix this or do a workaround at least for now, because Lit is new born and this should not affect too many projects and make many problems!

**Comment by justinfagnani** [comment]
We don't export everything from one module because we don't want pages to only load the code that they use. If you import exactly what you use you get smaller transferred payloads.
