### ISSUE TITLE
Support for class fields

### ISSUE THREAD

**Issue by LarsDenBakker** [lit/lit#3278]
This issue has been reported before with typescript (https://github.com/Polymer/lit-element/issues/855 and https://github.com/Polymer/lit-element/issues/878)

With class fields coming to Safari 14, we will start to see more developers using it outside of typescript.

The [class field specification](https://github.com/tc39/proposal-class-fields) changed from using assignment to using [defineProperty](https://github.com/tc39/proposal-class-fields#public-fields-created-with-objectdefineproperty). This is a problem when using LitElement properties without decorators.

This is a small example: https://jsbin.com/zesedefeqe/1/edit?html,output

Is there any way we can support standard class fields in JS without decorators? Otherwise this will become a common source for confusion for developers.

**Comment by justinfagnani** [comment]
I think we can close this for now. We've documented that you shouldn't use class fields in JavaScript, and ways to get around the problem in TypeScript with `"useDefineForClassFields": false` or `declare`. The stage 3 decorators proposal also solves with with the `accessor` keyword.
