### ISSUE TITLE
[lit] Closure Compiler: JSC_UNDEFINED_VARIABLE `JSCompiler_renameProperty`

### ISSUE THREAD

**Issue by sgammon** [lit/lit#3279]
### Description
Cannot build with Closure Compiler, even in `ADVANCED` mode with `use_types_for_optimization`, due to `JSCompiler_renameProperty` and `trustedTypes`

#### Live Demo
See repro [here](https://github.com/sgammon/lit-element-repro)

#### Steps to Reproduce
1. Set up an environment with `lit-element` via `npm` or `yarn` (in my case, `yarn` from `bazel`)
2. Write a little sample element that imports `lit-element` and uses it
3. Compile it with Closure Compiler in `ADVANCED` mode, with `use_types_for_optimization` set to `true`

#### Expected Results
Built bundle, with `JSCompiler_renameProperty` being treated as a special compiler primitive

#### Actual Results
Instead, it is treated like a regular variable name, which is missing from the compilation unit, yielding a `JSC_UNDEFINED_VARIABLE` error

### Browsers Affected
N/A (Build tooling)

### Versions
- lit-element: `v2.4.0` via NPM
- webcomponents: N/A

**Comment by rictic** [comment]
This is a jscompiler bug, reported there as https://github.com/google/closure-compiler/issues/3991

**Comment by sgammon** [comment]
thank you @rictic

**Comment by rictic** [comment]
Sorry for the really slow response!

**Comment by sgammon** [comment]
no worries, i'll take it! 😁

**Comment by sgammon** [comment]
@rictic let me dig in and get back to you. curious now

**Comment by sgammon** [comment]
the response from the closure team makes sense -- thank you for running this to ground
