### ISSUE TITLE
[labs/virtualizer] Padding does not trigger layout like gap does

### ISSUE THREAD

**Issue by Westbrook** [lit/lit#3285]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

The [setter workflow for `padding`](https://github.com/lit/lit/blob/main/packages/labs/virtualizer/src/layouts/shared/SizeGapPaddingBaseLayout.ts#L177-L196) in `SizeGapPaddingBaseLayout` does not include calls to `this._triggerReflow();` the way that the [setter workflow for `gap`](https://github.com/lit/lit/blob/main/packages/labs/virtualizer/src/layouts/shared/SizeGapPaddingBaseLayout.ts#L157-L175) does, which prevents updates to the `padding` value of the layout from effecting layout until changes to something else in the calculation is updated.

### Reproduction

Visit this [demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7dmlydHVhbGl6ZX0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL3ZpcnR1YWxpemUuanMnO1xuaW1wb3J0IHsgZ3JpZCB9IGZyb20gJ0BsaXQtbGFicy92aXJ0dWFsaXplci9sYXlvdXRzL2dyaWQuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgOmhvc3QgeyBcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIGhlaWdodDogMjAwcHg7XG4gICAgICB9XG4gICAgICBkaXYge1xuICAgICAgYm9yZGVyOiAxcHggc29saWQ7XG4gICAgfSAgICBcbiAgYDtcblxuICBAcHJvcGVydHkoeyB0eXBlOiBOdW1iZXIgfSkgXG4gIHB1YmxpYyBwYWRkaW5nID0gMTA7XG5cbiAgQHByb3BlcnR5KHsgdHlwZTogTnVtYmVyIH0pIFxuICBwdWJsaWMgZ2FwID0gMTA7XG4gIFxuICBAcHJvcGVydHkoKVxuICBwdWJsaWMgaXRlbXMgPSBBcnJheS5mcm9tKEFycmF5KDEwMCkua2V5cygpKTtcbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgPGRpdj5cbiAgICAgICR7dmlydHVhbGl6ZSh7XG4gICAgICAgIHNjcm9sbGVyOiB0cnVlLCBcbiAgICAgICAgaXRlbXM6IHRoaXMuaXRlbXMsIFxuICAgICAgICByZW5kZXJJdGVtOiAoaXRlbSkgPT4gaHRtbGA8ZGl2PiR7aXRlbX08L2Rpdj5gLFxuICAgICAgICBsYXlvdXQ6IGdyaWQoe1xuICAgICAgICAgIGl0ZW1TaXplOiB7XG4gICAgICAgICAgICB3aWR0aDogJzEwMHB4JyxcbiAgICAgICAgICAgIGhlaWdodDogJzEwMHB4JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHBhZGRpbmc6IGAke3RoaXMucGFkZGluZ31weGAsXG4gICAgICAgICAgZ2FwOiBgJHt0aGlzLmdhcH1weGAsXG4gICAgICAgIH0pXG4gICAgICB9KX1cbiAgICAgPC9kaXY-XG4gICAgYDtcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9vdGhlci1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmc-PC9zaW1wbGUtZ3JlZXRpbmc-XG4gIDxvdGhlci1ncmVldGluZz48L290aGVyLWdyZWV0aW5nPlxuICA8YnV0dG9uIGNsYXNzPVwiZ2FwXCI-VXBkYXRlIGBnYXBgPC9idXR0b24-XG4gIDxidXR0b24gY2xhc3M9XCJwYWRkaW5nXCI-VXBkYXRlIGBwYWRkaW5nYDwvYnV0dG9uPlxuICA8aHI-XG4gIDxvdXRwdXQgY2xhc3M9XCJnYXAtb3V0cHV0XCI-R2FwOjwvb3V0cHV0PlxuICA8aHI-XG4gIDxvdXRwdXQgY2xhc3M9XCJwYWRkaW5nLW91dHB1dFwiPnBhZGRpbmc6PC9vdXRwdXQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiPlxuICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5nYXAnKS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0-IHtcbiAgICAgIGNvbnN0IGdhcCA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDUwKTtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5nYXAtb3V0cHV0JykuaW5uZXJIVE1MICs9IGA8YnI-JHtnYXB9YDtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ3NpbXBsZS1ncmVldGluZycpLmdhcCA9IGdhcDtcbiAgICB9KTtcbiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcucGFkZGluZycpLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4ge1xuICAgICAgY29uc3QgcGFkZGluZyA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDUwKTtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5wYWRkaW5nLW91dHB1dCcpLmlubmVySFRNTCArPSBgPGJyPiR7cGFkZGluZ31gO1xuICAgICAgZG9jdW1lbnQucXVlcnlTZWxlY3Rvcignc2ltcGxlLWdyZWV0aW5nJykucGFkZGluZyA9IHBhZGRpbmc7XG4gICAgfSk7XG4gIDwvc2NyaXB0PlxuPC9ib2R5PiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

1. See that \`padding\` and `gap` are `10px` each
2. Click "Update \`gap\`" to see `gap` change
3. Click "Update \`padding\`" to see `padding` updated but not effect the layout
4. Click "Update \`padding\`" until it reports a larger number, then click "Update \`gap\`" and see the layout finally update the "padding"

### Workaround

Patch package works to just add a call to `this._triggerReflow();` at the end of the `padding` setter, or only change both together.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.7.1

### Browser/OS/Node environment

All browsers

**Comment by graynorton** [comment]
Hi, @Westbrook! It looks like you may have pasted the wrong Playground link in. Can you double-check?

**Comment by Westbrook** [comment]
Indeed, [updated](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7dmlydHVhbGl6ZX0gZnJvbSAnQGxpdC1sYWJzL3ZpcnR1YWxpemVyL3ZpcnR1YWxpemUuanMnO1xuaW1wb3J0IHsgZ3JpZCB9IGZyb20gJ0BsaXQtbGFicy92aXJ0dWFsaXplci9sYXlvdXRzL2dyaWQuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgOmhvc3QgeyBcbiAgICAgICAgZGlzcGxheTogYmxvY2s7XG4gICAgICAgIGhlaWdodDogMjAwcHg7XG4gICAgICB9XG4gICAgICBkaXYge1xuICAgICAgYm9yZGVyOiAxcHggc29saWQ7XG4gICAgfSAgICBcbiAgYDtcblxuICBAcHJvcGVydHkoeyB0eXBlOiBOdW1iZXIgfSkgXG4gIHB1YmxpYyBwYWRkaW5nID0gMTA7XG5cbiAgQHByb3BlcnR5KHsgdHlwZTogTnVtYmVyIH0pIFxuICBwdWJsaWMgZ2FwID0gMTA7XG4gIFxuICBAcHJvcGVydHkoKVxuICBwdWJsaWMgaXRlbXMgPSBBcnJheS5mcm9tKEFycmF5KDEwMCkua2V5cygpKTtcbiAgXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgPGRpdj5cbiAgICAgICR7dmlydHVhbGl6ZSh7XG4gICAgICAgIHNjcm9sbGVyOiB0cnVlLCBcbiAgICAgICAgaXRlbXM6IHRoaXMuaXRlbXMsIFxuICAgICAgICByZW5kZXJJdGVtOiAoaXRlbSkgPT4gaHRtbGA8ZGl2PiR7aXRlbX08L2Rpdj5gLFxuICAgICAgICBsYXlvdXQ6IGdyaWQoe1xuICAgICAgICAgIGl0ZW1TaXplOiB7XG4gICAgICAgICAgICB3aWR0aDogJzEwMHB4JyxcbiAgICAgICAgICAgIGhlaWdodDogJzEwMHB4JyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHBhZGRpbmc6IGAke3RoaXMucGFkZGluZ31weGAsXG4gICAgICAgICAgZ2FwOiBgJHt0aGlzLmdhcH1weGAsXG4gICAgICAgIH0pXG4gICAgICB9KX1cbiAgICAgPC9kaXY-XG4gICAgYDtcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9vdGhlci1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmc-PC9zaW1wbGUtZ3JlZXRpbmc-XG4gIDxvdGhlci1ncmVldGluZz48L290aGVyLWdyZWV0aW5nPlxuICA8YnV0dG9uIGNsYXNzPVwiZ2FwXCI-VXBkYXRlIGBnYXBgPC9idXR0b24-XG4gIDxidXR0b24gY2xhc3M9XCJwYWRkaW5nXCI-VXBkYXRlIGBwYWRkaW5nYDwvYnV0dG9uPlxuICA8aHI-XG4gIDxvdXRwdXQgY2xhc3M9XCJnYXAtb3V0cHV0XCI-R2FwOjwvb3V0cHV0PlxuICA8aHI-XG4gIDxvdXRwdXQgY2xhc3M9XCJwYWRkaW5nLW91dHB1dFwiPnBhZGRpbmc6PC9vdXRwdXQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiPlxuICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5nYXAnKS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0-IHtcbiAgICAgIGNvbnN0IGdhcCA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDUwKTtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5nYXAtb3V0cHV0JykuaW5uZXJIVE1MICs9IGA8YnI-JHtnYXB9YDtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJ3NpbXBsZS1ncmVldGluZycpLmdhcCA9IGdhcDtcbiAgICB9KTtcbiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcucGFkZGluZycpLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4ge1xuICAgICAgY29uc3QgcGFkZGluZyA9IE1hdGguZmxvb3IoTWF0aC5yYW5kb20oKSAqIDUwKTtcbiAgICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoJy5wYWRkaW5nLW91dHB1dCcpLmlubmVySFRNTCArPSBgPGJyPiR7cGFkZGluZ31gO1xuICAgICAgZG9jdW1lbnQucXVlcnlTZWxlY3Rvcignc2ltcGxlLWdyZWV0aW5nJykucGFkZGluZyA9IHBhZGRpbmc7XG4gICAgfSk7XG4gIDwvc2NyaXB0PlxuPC9ib2R5PiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0).

**Comment by usergenic** [comment]
Adding tests to prove behavior as part of https://github.com/lit/lit/issues/3608
