### ISSUE TITLE
[labs/react] Figure out pattern and/or fix types for using a wrapped component in React and Preact

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3289]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

React (@lit-labs/react)

### Description

[A bug report on Shoelace](https://github.com/shoelace-style/shoelace/issues/868) indicates that our wrapper typings don't work well in Preact when the wrappers have been made by the component author for React - this is not a case where the Preact API was given to `createComponent()`.

### Alternatives and Workarounds

Unknown

**Comment by michaelwarren1106** [comment]
Related issue: https://github.com/lit/lit/issues/3188

The above issue is about this package providing a super extensive built-in type for a custom element used in react. IMO these issues go together. If this package can provide great types for react wrappers and also custom elements it would help out a lot I think.

**Comment by tigrr** [comment]
Here is a  workaround I am currently using in my components library:

```ts
// This file is taken from https://github.com/lit/lit/blob/main/packages/labs/react/src/create-component.ts
// with a few modifications for Preact
import { ComponentType, Ref } from 'preact'
import { HTMLAttributes, TargetedEvent } from 'preact/compat'
// In fact createComponent doesn't really work with refs due to this issue
// https://github.com/lit/lit/issues/3211
import { createComponent as litCreateComponent } from '@lit-labs/react'

type Constructor<T> = { new (): T }

/***
 * Typecast that curries an Event type through a string. The goal of the type
 * cast is to match a prop name to a typed event callback.
 */
export type EventName<T extends Event = Event> = string & {
    __event_type: T
}

type Events = Record<string, EventName | string>

type EventProps<R extends Events, I extends HTMLElement> = {
    [K in keyof R]: R[K] extends EventName
        ? (e: R[K]['__event_type']) => void
        : (e: TargetedEvent<I>) => void
}

const createComponent = <
    I extends HTMLElement,
    E extends Events = Record<string, never>,
>(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    React: any,
    tagName: string,
    elementClass: Constructor<I>,
    events?: E,
    displayName?: string,
) => {
    // Props the user is allowed to use, includes standard attributes, children,
    // ref, as well as special event and element properties.
    type ReactProps = Omit<
        HTMLAttributes<I>,
        keyof E | keyof Omit<I, 'children'>
    >
    type ElementWithoutPropsOrEvents = Omit<I, keyof E | keyof ReactProps>
    type UserProps = Partial<
        ReactProps & ElementWithoutPropsOrEvents & EventProps<E, I>
    >

    // Props used by this component wrapper. This is the UserProps and the
    // special `__forwardedRef` property. Note, this ref is special because
    // it's both needed in this component to get access to the rendered element
    // and must fulfill any ref passed by the user.
    type ComponentProps = UserProps & {
        __forwardedRef?: Ref<unknown>
    }

    return litCreateComponent(
        React,
        tagName,
        elementClass,
        events,
        displayName,
    ) as ComponentType<ComponentProps>
}

export default createComponent
```

This way I need to create a separate Preact wrapper in addition or instead of the React wrapper, which is not a very good solution.

**Comment by taylor-vann** [comment]
I have a hunch that using the minimum shared interface between React and Preact could alleviate this.
There's a lot in React that is not included in Preact so the type errors from React to Preact make sense to me.

Re-opening
https://github.com/lit/lit/pull/3109

If we provide a generic interface that could include both preact and react types

**Comment by augustjk** [comment]
Type refactor done in https://github.com/lit/lit/pull/4027 with current version of `preact/compat` make it so that wrapped components are compatible type-wise. #4111 adds a test Preact project into the repo to make sure that remains to be the case.
