### ISSUE TITLE
[labs/virtualizer] export Virtualizer and virtualizerRef symbol

### ISSUE THREAD

**Issue by megheaiulian** [lit/lit#3290]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When using virtualizer as a `lit-html` directive there is not way to access the `Virtualizer` instance (via a `ref()`) because the `virtualizerRef` symbol is not exported. 
`virtualizeRef` should be re-exported in `virtualize.ts` and maybe `Virtualizer.ts` should also be in the exports map.

### Reproduction

See above.

### Workaround

Bypassed this by listing all ref's symbols.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

all ?

### Browser/OS/Node environment

any env

**Comment by graynorton** [comment]
Thanks for the report, @megheaiulian!

Yes, this was an oversight in previous releases, but `virtualizerRef` will be exported in the next version, along with the `VirtualizerHostElement` type. You can see this on a branch here: https://github.com/lit/lit/blob/rethink-scroll-to/packages/labs/virtualizer/src/virtualize.ts#L14

It's also in a one-off snapshot release if you'd like to try it out: https://www.npmjs.com/package/@lit-labs/virtualizer/v/0.0.0-masonry-preview-20220906220426

For now, we're not planning to add `Virtualizer.js` to the export map, as we're trying to be very conservative about the API surface we support. If there are specific use cases you have in mind, let us know and we'll consider them.

We'll leave this issue open until the next release goes out.

**Comment by usergenic** [comment]
Confirmed fd7d86a50 now in main (thanks, @graynorton) and will be in forthcoming release.
