### ISSUE TITLE
Dynamic SVG Linear Gradient is not rendered on SVG elements as fill

### ISSUE THREAD

**Issue by Atokulus** [lit/lit#3305]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When creating a dynamic linear gradient definition `<linear-gradient id="#gradient">` within `<svg><defs /></svg>` and applying it to another element within the SVG such as a `<rect fill="url(#gradient)">`, the gradient fill does not get rendered.

The linear gradient color stops are defined within an array which is iterated in the `render()` function.

Applying the linear gradient statically is working correctly.

### Reproduction

Please find a full example at https://codesandbox.io/s/lit-dynamic-svg-linear-gradient-bug-rp0g1t?file=/src/test_svg_gradient.ts

The left rectangle with red border should actually look like the right rectangle (with a rainbow linear gradient fill), but it does not.

<img width="149" alt="image" src="https://user-images.githubusercontent.com/1159506/192257029-b4fcd0fc-6f21-4b54-aced-06a07072f4df.png">

### Workaround

I could not workaround this issue so for.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Probably all.

### Browser/OS/Node environment

Chrome 105.0.5195.127

**Comment by Westbrook** [comment]
Inside of the `linearGradient` tag you’ll need to leverage https://lit.dev/docs/api/templates/#svg to ensure the content is created on the correct namespace.

**Comment by Atokulus** [comment]
Thanks very much @Westbrook
This is indeed working 😄👍
