### ISSUE TITLE
[labs/virtualizer] Typings issue with renderItem requires explicit TemplateResult return typing to satisfy compiler

### ISSUE THREAD

**Issue by usergenic** [lit/lit#3322]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Consider this code:

```ts
  render() {
    return html`
      <lit-virtualizer
        .items=${this.things}
        .renderItem=${(thing: Thing) => html`<span>${thing}</span>`}>
      </lit-virtualizer>
    `;
  }
```

There is some kind of typing vagueness that causes the renderItem property to display a warning in VSCode when using the lit-plugin:

> Type '(thing: string) => TemplateResult<1>' is not assignable to '<T>(item: T, index: number) => TemplateResult<1 | 2>'lit-plugin(no-incompatible-type-binding)(2304)

However, I can make the warning go away by explicitly typing the return of the function given to renderItem:

```ts
  render() {
    return html`
      <lit-virtualizer
        .items=${this.things}
        .renderItem=${(thing: Thing): TemplateResult => html`<span>${thing}</span>`}>
      </lit-virtualizer>
    `;
  }
```

I feel like this could/should be addressed in the lit-virtualizer typings so I don't have to explicitly express a TemplateResult type to get the plugin or compiler to be happy.

### Reproduction

```ts
import {LitElement, css, html, TemplateResult} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import '@lit-labs/virtualizer';

type Thing = string;
@customElement('an-element')
export class AnElement extends LitElement {
  @property({type: Array})
  things: Thing[] = [];
  
  render() {
    return html`
      <lit-virtualizer
        .items=${this.things}
        .renderItem=${(thing: Thing) => html`<span>${thing}</span>`}>
      </lit-virtualizer>
    `;
  }
}
```

### Workaround

Explicitly type the return of the renderItem function to `TemplateResult` and the compiler is happy.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.7.2

### Browser/OS/Node environment

TypeScript 4.8.4

**Comment by usergenic** [comment]
I'm not sure this isn't maybe actually an issue with the lit-plugin instead of virtualizer?  `lit-plugin(no-incompatible-type-binding)(2304)`. After reinstalling lit-plugin now I no longer encounter this error with current version of virtualizer.

**Comment by davie-robertson** [comment]
I'm running lit-plugin 1.4.3 and the issue seems to be back, your workaround still removes the warning though.
