### ISSUE TITLE
[labs/ssr] Events

### ISSUE THREAD

**Issue by aomarks** [lit/lit#3365]
We should have some form of support in SSR for events.

https://github.com/lit/lit/pull/2309 proposes an implementation. Questions (copied from that PR description):

* Can we have an event path of just the custom elements without materializing the built-ins that would be on the path with a full DOM structure? This seems ok if the only event patterns we support are for cross-custom-element communication, ie context.
* Where do elements install event listeners? I added a call to `connectedCallback()` in here, but that only doesn't throw because none of the test elements do anything with the DOM in `connectedCallback()`. That wouldn't be viable in general.
* Do we need to implement the capture phase?
* How could we implement the proper composed path? We would need some concept of slotted elements being in the custom element instance stack.

**Comment by marsDes** [comment]
``` ts
...
@customElement('x-button')
...
html`<button ?disabled=${this.disabled} @click=${console.log('lit')}><slot></slot></button>`
...
```
```html
<x-button onClick="console.log('html')" disabled>button</x-button>
```

when set disabled ,it also console'html' , how to forbidden？
@justinfagnani
