### ISSUE TITLE
[reactive-element] addInitializer adds initializer to superclass

### ISSUE THREAD

**Issue by christophe-g** [lit/lit#3373]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

While looking #3296 a bit more in depth, I realize that the culprit is not @lit-labs/context but `ReactiveElement.addInitializer`, which will add intializers to the superclass if it already contains its own initializers. 

[Documentation states](https://lit.dev/docs/components/lifecycle/#addInitializer): 

> Initializers are stored per-constructor. Adding an initializer to a subclass does not add it to a superclass. Since initializers are run in constructors, initializers will run in order of the class hierarchy, starting with superclasses and progressing to the instance's class.

This is not what happens as `addInitializer` only checks if this._initializer exists on the Class prototype chain. In case a superclass already has one, it will be added to it (the superclass). We should have a `hasOwnProperty` check there. 

```ts
   /*
   * Initializers are stored per-constructor. Adding an initializer to a
   * subclass does not add it to a superclass. Since initializers are run in
   * constructors, initializers will run in order of the class hierarchy,
   * starting with superclasses and progressing to the instance's class.
   *
   * @nocollapse
   */
  static addInitializer(initializer: Initializer) {
    this._initializers ??= [];
    this._initializers.push(initializer);
  }

```

### Reproduction

- go to [this playground](https://lit.dev/playground/#gist=410407cc4c6bb0051849d6633d0f0f5d)
- See that the base class has 2 initializers (while it shoul donly have one)

### Workaround

none

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 2.4.0

### Browser/OS/Node environment

NA

**Comment by christophe-g** [comment]
Hmm, we might have a similar issue with `addController` ( see `(this.__controllers ??= []).push(controller);`)

```ts
  /**
   * Registers a `ReactiveController` to participate in the element's reactive
   * update cycle. The element automatically calls into any registered
   * controllers during its lifecycle callbacks.
   *
   * If the element is connected when `addController()` is called, the
   * controller's `hostConnected()` callback will be immediately called.
   * @category controllers
   */
  addController(controller: ReactiveController) {
    (this.__controllers ??= []).push(controller);
    // If a controller is added after the element has been connected,
    // call hostConnected. Note, re-using existence of `renderRoot` here
    // (which is set in connectedCallback) to avoid the need to track a
    // first connected state.
    if (this.renderRoot !== undefined && this.isConnected) {
      controller.hostConnected?.();
    }
  }
```

**Comment by justinfagnani** [comment]
Thanks for investigating this and for the repro @christophe-g !

We can prioritize a fix for this, or you could contribute it if you would like to. The biggest requirement would be a good test.

**Comment by sorvell** [comment]
Just a quick note, this should be fixed in the `finalize` step where we handle similar behavior for properties and styles. The superclass initializers should be copied into a set of initializers owned by (and not shared with!) the superclass.

**Comment by christophe-g** [comment]
@justinfagnani - honestly, while I'd like to contribute, I am already pretty stretched over a couple of important deadlines on my end ; )  

The fix should be pretty straighforward and the lit team shall be in better position to efficiently tackle this (esp. on the good test requirement).
