### ISSUE TITLE
[labs/ssr] Add localName to DOM emulation for SSR

### ISSUE THREAD

**Issue by calebdwilliams** [lit/lit#3375]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr)

### Description

When running the SSR script the element's `localName` and `tagName` are not added to the element. This has lead to a bug in the [`ElementInternals` polyfill at this line](https://github.com/calebdwilliams/element-internals-polyfill/blob/main/src/element-internals.ts#L329). 

This line exists to make sure that the node being referenced by the internals object is a custom element. This might be useful server-side behavior so that elements using `AriaMixin` via the `ElementInternals` spec can sprout attributes on their hosts (yet to be tested).

### Alternatives and Workarounds

A current workaround for the polyfill has already been implemented, returning an empty object for the internals instance in case no localName is present.

**Comment by willmartian** [comment]
Hi, I would love to try and help if this is open to external contributors. 

@justinfagnani, is this just a matter of adding the `localName` field when initializing the `ElementRenderer`, or is it deeper than that? https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/element-renderer.ts#L49

**Comment by justinfagnani** [comment]
@willmartian sorry for the delayed response. We're definitely open to external contributors (and would love to erase even the external distinction over time). That's one reason I tagged this as a "Good First Issue".

I think what's needed is to implement a `.localName` getter on `Element` and to get the tag name of the element from the custom elements registry in the constructor with `new.target`. We don't have to worry about upgrades on the server.

**Comment by Rishab49** [comment]
after making the required changes how can i test it?
