### ISSUE TITLE
All versions of IE and low versions of chrome cannot render properly

### ISSUE THREAD

**Issue by zandko** [lit/lit#3381]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

1、Uncaught ReferenceError: globalThis is not defined
2、Uncaught SyntaxError: Unexpected token
3、IE11 Can't render properly

### Reproduction

 <script type="module" src="/src/index.js"></script>

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.3.1

### Browser/OS/Node environment

Browser: IE11 OR chrome 63.0.3239.132
Node: v16.13.0
Npm: 8.1.0

**Comment by kevinpschaaf** [comment]
As @ba55ie noted in the docs, Lit uses modern JavaScript, so for IE it must be compiled to ES5, and certain JavaScript polyfills must be loaded, such as https://www.npmjs.com/package/core-js.

If you're following the requirements for legacy browsers and still having an issue, please re-open. Thanks!
