### ISSUE TITLE
[labs/react] Custom Element lifecycle methods are exposed as props in types

### ISSUE THREAD

**Issue by keithamus** [lit/lit#3394]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

When creating a component using `createComponent`, the props for the component include not only the classes immediate properties, but additionally all methods including the lifecycle callbacks such as `connectedCallback`. This means if folks are using TypeScript for auto-complete, they're presented with `connectedCallback` as an available property to set, it also means that `connectedCallback` is actually settable.

### Reproduction

```tsx
import React from "react";
import { createComponent } from "@lit-labs/react";

class SomeElement extends HTMLElement {
  connectedCallback() {
    setInterval(() => {
      this.textContent = this.connectedCallback.toString();
    }, 1000);
  }
}
customElements.define("some-el", SomeElement);

const SomeEl = createComponent(React, "some-el", SomeElement);

export default function App() {
  return (
    <div className="App">
      <SomeEl connectedCallback={() => alert("hi")}>Not Connected</SomeEl>
    </div>
  );
}
```

This demo will eventually render `() => alert("hi")`, because `SomeEl` is allowed to set `connectedCallback`.

https://codesandbox.io/s/intelligent-lamarr-u3e08p?file=/src/App.tsx

### Workaround

I have not found a workaround.

I believe the problem stems from this:

https://github.com/lit/lit/blob/2d10c26d6c526faafacc5d28d0f70f671e72560d/packages/labs/react/src/create-component.ts#L315-L320

which checks if the property is part of the elements direct prototype. It might be worth also guarding against a fixed list of available lifecycle methods to ensure that the lifecycle methods cannot be replaced.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.9

### Browser/OS/Node environment

I don't think these details are relevant to this issue.

**Comment by taylor-vann** [comment]
@keithamus thanks!

I'm actually wondering if this is an odd case of 'working as intended'.

Like you mentioned, we look for properties on a component and use those properties as react `props`.

Properties like `connectedCallback` and `disconnectedCallback` are technically on the prototype chain and will be a part of those react `props`.

We're trying to avoid lists as much as possible ;_; but this is also an interesting edge case.


@justinfagnani how do you feel about this?

**Comment by taylor-vann** [comment]
The changes made in `1.1.0` better reflect expected component behavior in the React ecosystem. 

Any property or method found on a web component, including lifecycle methods like `connectedCallback`, will be set if passed as props. There is no real reason to set lifecycle methods but as @keithamus points out, it's possible and even type inferred.

Unfortunately, I don't think there is a way avoid setting lifecycle methods without using a checklist.

Cosing this bug as `working as intended`.
