### ISSUE TITLE
 [labs/react] Custom Element class fields cannot be set on a React component

### ISSUE THREAD

**Issue by keithamus** [lit/lit#3395]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

When using a Class Field in a Web Component, it's not possible to set this as a prop on the React component.

### Reproduction

```tsx
import React from "react";
import { createComponent } from "@lit-labs/react";

class SomeElement extends HTMLElement {
  x = "Hello World";
  connectedCallback() {
    setInterval(() => {
      this.textContent = this.x;
    }, 1000);
  }
}
customElements.define("some-el", SomeElement);

const SomeEl = createComponent(React, "some-el", SomeElement);

export default function App() {
  return (
    <div className="App">
      <SomeEl x={"Hello Web Components"}>Not Connected</SomeEl>
    </div>
  );
}
```

The demo will eventually render `Hello World` but never `Hello Web Components`.

https://codesandbox.io/s/sad-sky-q5tosq?file=/src/App.tsx

### Workaround

The workaround is to refactor the web components properties to not be class fields, and instead use getter/setters:

```tsx
import React from "react";
import { createComponent } from "@lit-labs/react";

class SomeElement extends HTMLElement {
  #x = "Hello World";
  get x() {
    return this.#x
  }
  set x(v: string) {
    this.#x = v
  }
  connectedCallback() {
    setInterval(() => {
      this.textContent = this.x;
    }, 1000);
  }
}
customElements.define("some-el", SomeElement);

const SomeEl = createComponent(React, "some-el", SomeElement);

export default function App() {
  return (
    <div className="App">
      <SomeEl x={"Hello Web Components"}>Not Connected</SomeEl>
    </div>
  );
}
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

1.0.9

### Browser/OS/Node environment

I don't think these details are relevant to this issue.

**Comment by taylor-vann** [comment]
Hey @keithamus thanks for submitting!

I don't think the above example would work even without the wrwapper.

**Comment by taylor-vann** [comment]
@keithamus thanks for submitting!

I don't believe the above would work
Here's a gist on lit.dev showing the vanilla behavior here.
https://lit.dev/playground/#gist=a9139562a4ae08ce32c3b27e31a4fdd6

The main takeaway is `Element.textContent` on a custom web component is (most likely) not reactive.

However using `attributes` as a way to change props gives the web component to update what is rendered.

Here's an example showing how to get the functionality you demonstrated with a `shadowRoot` and using `getAttribute('x')`.

https://codesandbox.io/s/beautiful-shadow-dglv3v?file=/src/App.tsx:0-691

**Comment by taylor-vann** [comment]
Closing issue, feel free to reopen :)
