### ISSUE TITLE
HTMLElement is not defined when using NextJS with the lit react wrappers

### ISSUE THREAD

**Issue by kevin-coyle** [lit/lit#3407]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

When I use the React wrappers in a NextJS application I get the following error:

`ReferenceError: HTMLElement is not defined`

This looks like the stumbling block is where the props are checked in the HTMLElement prototype (Line 318 in createComponent.ts)

Thanks in advance for checking out this issue and hopefully someone can point me in the right direction

### Reproduction

1. Create a simple web component
2. Create a wrapper:
```
import * as React from 'react';
import { createReactWrapperComponent } from '../../../utils/create-react-wrapper-component';
import { createComponent } from '@lit-labs/react';
import CustomButton from '../src/lib/components/button/button'; // This can be anywhere you have the component


export const MyButton = createComponent(
  React,
  'my-button',
  CustomButton,
)
```

3. Now add this react component to a NextJS project and run a build or an export.

This should produce the error. I'm more than happy to make up a quick monorepo to demonstrate this if desired.

### Workaround

I haven't yet found a workaround with using the lit react wrappers. 

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.4.0

### Browser/OS/Node environment

Browser: N/A
Node: 16
OS: Mac OS 13.0

**Comment by sshmaxime** [comment]
Has this issue been fixed ? Still facing it

**Comment by justinfagnani** [comment]
@sshmaxime what version of `lit` are you using? We added a minimal HTMLElement definition so that elements can load. This requires the `node` import condition to be used.

**Comment by creamIcec** [comment]
Can be confirmed when trying to create react component with `createComponent` using `@lit/react` version `1.0.5`. Any news about this issue?

**Comment by Lookwe69** [comment]
I don't know if this can help but i have the same issue when I upgrade the package "@emotion/..." to the lastest version

**Comment by cscheffauer** [comment]
facing the same issue - please reopen since this is still an issue!

**Comment by justinfagnani** [comment]
@cscheffauer you might have new details for your specific case. Can you open a new issue?
