### ISSUE TITLE
[labs/virtualizer] Chromium crash: children w/many DOM nodes, zooming in and out

### ISSUE THREAD

**Issue by Avocher** [lit/lit#3426]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Lit virtualizer seems to randomly crash the browser if an item contains a css grid. Quickest way to consistantly trigger it is to zoom in and out using `ctrl` key and mouse wheel or `ctrl` with `+` and `-`.

You can try it in the demo below by clicking the "use virtualizer" and start zooming in and out.

### Reproduction

https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eSwgc3RhdGV9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcbmltcG9ydCB7IHZpcnR1YWxpemUgfSBmcm9tICdAbGl0LWxhYnMvdmlydHVhbGl6ZXIvdmlydHVhbGl6ZS5qcyc7XG5pbXBvcnQgeyByZXBlYXQgfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9yZXBlYXQuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgneC1yZXBybycpXG5leHBvcnQgY2xhc3MgWFJlcHJvIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgXG4gICAgICA6aG9zdCB7XG4gICAgICAgIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAgICAgIGhlaWdodDogY2FsYygxMDB2aCAtIDIwcHgpO1xuICAgICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgfVxuICAgICAgLmdyaWQge1xuICAgICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgICAgY29udGFpbjogc3RyaWN0O1xuICAgICAgICBmbGV4OiAxO1xuICAgICAgfVxuICAgICBcbiAgICAgIC5yb3cge1xuICAgICAgICBkaXNwbGF5OiBncmlkO1xuICAgICAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCgxMDAsIDQwcHgpO1xuICAgICAgICBnYXA6IDhweDtcbiAgICAgICAgaGVpZ2h0OiA0OHB4O1xuICAgICAgICB3aWR0aDogNjAwcHg7XG4gICAgICB9XG4gICAgICAub3ZlcmZsb3cge1xuICAgICAgICBvdmVyZmxvdzogYXV0bztcbiAgICAgIH1cbiAgYDtcblxuICBAc3RhdGUoKVxuICByb3dzID0gQXJyYXkoMTAwMCkuZmlsbCgwKS5tYXAoKHZhbCwgaW5kZXgpID0-IGluZGV4KTtcbiBcbiAgQHN0YXRlKClcbiAgY29sdW1ucyA9IEFycmF5KDEwMCkuZmlsbCgwKS5tYXAoKHZhbCwgaW5kZXgpID0-IGluZGV4KTtcbiBcbiAgQHN0YXRlKClcbiAgdmlydHVhbGl6ZSA9IGZhbHNlXG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPHA-TnVtYmVyIG9mIHJvd3M6ICR7dGhpcy5yb3dzLmxlbmd0aH08L3A-XG4gICAgICAgIDxsYWJlbCBjbGFzcz1cInN3aXRjaFwiPlxuICAgICAgICAgIDxpbnB1dCAuY2hlY2tlZD0ke3RoaXMudmlydHVhbGl6ZX0gQGNoYW5nZT0ke3RoaXMuX29uQ2hhbmdlQ2hlY2tib3h9IHR5cGU9XCJjaGVja2JveFwiPlxuICAgICAgICAgIDxzcGFuPlVzZSB2aXJ0dWFsaXplcjwvc3Bhbj5cbiAgICAgICAgPC9sYWJlbD5cbiAgICAgIFxuICAgICAgICAgJHt0aGlzLnZpcnR1YWxpemUgXG4gICAgICAgID8gaHRtbGA8ZGl2IGNsYXNzPVwiZ3JpZFwiPiR7dmlydHVhbGl6ZSh7XG4gICAgICAgICAgIGl0ZW1zOiB0aGlzLnJvd3MsXG4gICAgICAgICAgIHNjcm9sbGVyOiB0cnVlLFxuICAgICAgICAgICBrZXlGdW5jdGlvbjogaXRlbSA9PiBpdGVtLFxuICAgICAgICAgICByZW5kZXJJdGVtOiBpdGVtID0-IGh0bWxgXG4gICAgICAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgICAgJHtyZXBlYXQodGhpcy5jb2x1bW5zLCAoY2VsbCkgPT4gY2VsbCwgKGNlbGwpID0-IGh0bWxgPGRpdiBjbGFzcz1cImNlbGxcIj4ke2l0ZW0gKyBjZWxsfTwvZGl2PmApfVxuICAgICAgICAgICAgIDwvZGl2PmBcbiAgICAgICAgIH0pfTwvZGl2PmAgXG4gICAgICAgIDogaHRtbGA8ZGl2IGNsYXNzPVwiZ3JpZCBvdmVyZmxvd1wiPiR7cmVwZWF0KHRoaXMucm93cywgKGl0ZW0pID0-IGl0ZW0sIGl0ZW0gPT4gaHRtbGBcbiAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI-XG4gICAgICAgICAgICAgICAke3JlcGVhdCh0aGlzLmNvbHVtbnMsIChjZWxsKSA9PiBjZWxsLCAoY2VsbCkgPT4gaHRtbGA8ZGl2IGNsYXNzPVwiY2VsbFwiPiR7aXRlbSArIGNlbGx9PC9kaXY-YCl9XG4gICAgICAgICAgICAgYCl9YH1cbiAgICBgO1xuICB9XG4gXG4gIF9vbkNoYW5nZUNoZWNrYm94KGUpIHtcbiAgICB0aGlzLnZpcnR1YWxpemUgPSBlLmN1cnJlbnRUYXJnZXQuY2hlY2tlZDtcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9yZXByby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx4LXJlcHJvPjwveC1yZXBybz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

### Workaround

~~It seems to be connected to the `grid-template-columns` somehow. Removing it seems to reduce the risk or remove the problem totally.~~ There is none.

### Is this a regression?

Yes. This used to work, but I don't know which version of chrome that broke virtualizer.

### Affected versions

Atleast all 0.7.* versions

### Browser/OS/Node environment

Browser: 107.0.5304.87
OS: Windows 10/11

**Comment by Avocher** [comment]
I have to ammend my statement. It does crash with any type of layout. It's just more likely with `grid`.

**Comment by graynorton** [comment]
Thanks for the report and the simple repro case, @Avocher!

One quick question for you:

> I don't know which version of chrome that broke virtualizer

Are you quite certain that there's a Chrome regression involved here? That is, how confident are you that you have used `0.7.*` versions of virtualizer in a similar way in previous Chrome builds and not experienced a crash?

FWIW, here's what I found:

- Crashes in Chrome and Edge on Mac, so clearly not Windows-specific
- Doesn't crash in Firefox or Safari, so there's something browser-specific happening
- As you note, using CSS `grid` in the virtualizer child elements isn't required to repro this crash (as shown in this [modified example](https://lit.dev/playground/#gist=4e720155b54ece9db2df42ea1f34364b))
- Changing the number of elements within each virtualizer does have an impact. [This example with only 50 columns](https://lit.dev/playground/#gist=690dfc34a886d2aef2d3e4b8ce85125c) doesn't crash for me.
- However, there does seem to be something specific about virtualizer that is triggering the crash; [this roughly equivalent example](https://lit.dev/playground/#gist=3328a3e1de0acbd4385c6919265734f1) that uses `repeat()` and some crude bespoke virtualization logic to limit the number of rows doesn't crash.
- Neither does [this example](https://lit.dev/playground/#gist=d03cf3793b9b3323171378a4652780ce), which builds on the previous one and adds a mutation observer on the virtualizer host element and connects / disconnects a child element resize observer on each update (this isn't exactly how virtualizer uses its mutation and resize observers, but seemed close enough to be worth trying).
- I also tried using DevTools profiling to see if I could spot an obvious memory leak or anything along those lines. I could not, though I am admittedly not an expert in this sort of profiling.

That's about all I could think to try quickly. I think the next steps involve seeing if we can get someone in Chrome to take a look or advise on how to debug further. Failing that, we'll need to do a deep dive into virtualizer internals that I suspect would be very time-consuming.

**Comment by graynorton** [comment]
Filed a Chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1381598

**Comment by Avocher** [comment]
> Are you quite certain that there's a Chrome regression involved here?

Yes, this got reported from our customers that it is relatively a new phenomenon. I do not recall getting any reports of this before this autumn. But I will do some digging into this.

Our customers get this crash randomly while working in our app, so its not directly connected to zooming in and out. It's just the most reproduceable way to triggering it.

> Crashes in Chrome and Edge on Mac, so clearly not Windows-specific

This is interesting. I played around with the sizes to get it to crash on Mac and I do get it crash when I crank up the numbers but it does not seem to be the same type of crash. You get slightly more information about the crash when you run it the tab compared to an iframe. So when it crashes on Mac I get error `code 11`, but when I run it on Windows i get `STATUS ACCESS VIOLATION`. The former is probably some kind of memory leak or slow GC and the latter, I'm guessing, is virtualizer  trying to compute sizes of something where the memory has already been GC'd?

> Filed a Chromium bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1381598

Much appreciated, since you are a Googler I'm guessing that the ticket is not open to public per default?

**Comment by graynorton** [comment]
Thanks for the additional information, @Avocher.

> I'm guessing that the ticket is not open to public per default?

Yeah, it turns out that these crash report tickets are actually only visible to the reporter and Chromium engineers. I can tell you that progress is being made on this—it's a ResizeObserver issue. I'm hopeful that a fix will be coming soon.

Thanks again for the well constructed repro case—that's what has enabled this to get prompt attention.

**Comment by graynorton** [comment]
FYI, it appears that a fix has been committed in the Chromium codebase. Not sure what the timeline looks like for release, but a resolution is on the way. Thanks again!

Will leave this open until the fix lands.

**Comment by Avocher** [comment]
That is good news! Thank you for reacting so quickly, our users will be delighted to hear that a fix is on its way.

**Comment by graynorton** [comment]
Following up: the fix for this is supposed to land in Chrome 109, which is intended to roll out to stable shortly.

**Comment by Avocher** [comment]
Thank you for helping out. Our users will be happy to hear the news!

**Comment by Avocher** [comment]
This is issue has been fixed. Thanks for the help!
