### ISSUE TITLE
[labs/react] Version 1.1.0 causes Typechecking error for createComponent(), expects React v18 types

### ISSUE THREAD

**Issue by rblakeman** [lit/lit#3429]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

After upgrading our usage of `@lit-labs/react` recently from `v1.0.9` to `v1.1.0`, we get Typechecking errors on all our usages of the `createComponent()` method:

```
Argument of type import("typeof .../node _modules/@types/react/index") is not assignable to parameter of type "typeof React'
    Type "typeof React' is missing the following properties from type "typeof React' :
        useDeferredValue, useTransition, startTransition, useId, and 2 more. ts(2345)
```

![lit-labs 1 1 0 ts error](https://user-images.githubusercontent.com/20215264/200052032-07476a97-5cf8-4aa8-9232-89e9181da5fe.png)

It appears that `createComponent()` method is expecting v18 of React types but I don't see it in the `changelog` or in the `package.json` as an expectation. Only React v17 is listed as expected and we are already using that.

### Reproduction

Unfortunately, I cannot provide an example or exact steps to reproduce it as the work is in a private repo.

### Workaround

Reverting `@lit-labs/react` back to `v1.0.9` resolves this issue.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 1.1.0, working in 1.0.9

### Browser/OS/Node environment

OS: macOS 12.6.1
Node: 16.14.0
NPM: 8.3.1
Yarn: 1.22.18

**Comment by augustjk** [comment]
That's interesting.. I want to say the `@lit-labs/react` package doesn't actually ship any React types itself, it's pulling in the user's installed `@types/react` by doing `typeof window.React`.

Is it possible that during the upgrade you also got a new `@types/react` installed? Maybe `npm ls @types/react` or `yarn list @types/react` might help find that.

**Comment by rblakeman** [comment]
That would make sense, thanks for the reply! This was likely some tech debt bubbling up as I discovered the monorepo involved had multiple versions of Typescript being used in various places. After wrangling them back down to the lowest common denominator this error went away.
