### ISSUE TITLE
[localize] Preserve target state when running lit-localize extract (XLIFF format)

### ISSUE THREAD

**Issue by enqueue** [lit/lit#3439]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Localize (@lit/localize)

### Description

It would be useful to preserve the state of the target elements in the generated XLIFF files. This makes it easier to keep track of the stuff that really needs a new translation. Over the lifetime of a product many new messages are added, and the translators should immediately see what they need to do in a concrete iteration. While I have not performed a diligent market analyisis, I expect many tools that support the XLIFF file format to support the [`state`](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state) attribute of a target. Thus it would be helpful if the lit-localize CLI tool could respect it.

### Alternatives and Workarounds

It is possible to have a manual workflow for creating a todo list for the translators, but this is error-prone.

**Comment by aomarks** [comment]
Yeah, we should do this. https://github.com/lit/lit/issues/1879 is related, which is the general approach of doing an _update_ instead of a full re-generation. That way we don't actually need any special handling for whatever extra metadata is in the xliff file.
