### ISSUE TITLE
[lit-element] Failure to re-use dom nodes on Chromium 107(?)

### ISSUE THREAD

**Issue by voidus** [lit/lit#3445]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

First of all: This is pretty hard to debug, but I have a theory. I might be wrong though, so feel free to check me on potential other issues. I've tried my best to minimize the code in action, but it's still a lot.

**Situation**
I have a page with
- An element `<application-form>` ([code](https://gitlab.com/sea-watch.org/planner/-/tree/reproduce-lit-issue/public-client/src/js/elements/ApplicationForm/index.js))
- This element contains a text input and another element `<multi-select>` ([code](https://gitlab.com/sea-watch.org/planner/-/tree/reproduce-lit-issue/public-client/src/js/elements/MultiSelect/index.js))
- The `<multi-select` wraps [choices.js](https://www.npmjs.com/package/choices.js?ref=vanillalist) and emits a custom event on change.
  - I have tried the following simplifications, all of which caused the bug to disappear (see later note about reproducibility though)
    - Replacing the `<multi-select>` with a button that emits the custom event on click
    - Replacing the contents of `<multi-select>` with that button
    - Removing all but two elements from the choices.js options.
  - N.B. while I cannot see any way how, I don't want to rule out the possibility that the dom manipulations that choices.js is doing are impacting this. Feel free to point something out at me. It did work fine with Chrome 106 though.
- I am running automated tests using playwright ([code](https://gitlab.com/sea-watch.org/planner/-/blob/reproduce-lit-issue/end-to-end-test/test/test_e2e_playwright.py)) that:
  1. Open the page
  2. put "Peter" in the first name field
  3. type "Palau" into the choices.js search field
  4. click "Palau" in the dropdown list.

Let me know if I should elaborate on anything.

Running the relevant parts of the project requires the following:
- `cd public-client && npm install && npm run build`
- `cd public-backend && poetry install && ./django-admin runserver` (leave running)
- `cd end-to-end-test && poetry install && playwright install && pytest -k repro --headed --slowmo 200` to run the tests

If you're using nix and direnv, all the install stuff should happen automatically, if not you need to install python (preferably 3.10), node (preferably 16) and poetry yourself. Playwright might also need additional stuff.

**Expected Behaviour**:
Inputs should be filled according to the test

**Actual Behaviour**:
- On *most* runs, all form inputs get cleared at some point.

[19d589488439e75771e3426786b67cfd.webm](https://user-images.githubusercontent.com/124298/201168678-5916daf5-2a8d-45b0-bf13-245682467139.webm)

**Reproducibility**:
This mostly occurs when clicking "Palau" in the dropdown, but sometimes already when moving focus into the search box and sometimes not at all. It's reproducible by hand when stopping the test with a `breakpoint()`, but I couldn't reproduce it when I start the playwright-chromium myself. I was able to reproduce it with a new tab in the playwright-launched chromium though.

I didn't find anything hinting at playwright being involved, so I cannot assume that this wouldn't happen outside of it, but I cannot spend more time on minimizing the code right now.

**Analysis and Theory**:
I've spend the last few days stepping through the code, trying to understand if this is us, playwright, lit, choices.js or chrome. (I would accept astronomy-based explanations by now if they assured me this couldn't happen in prod)

When capturing an element below `<application-form>` in the dev console (using `foo = $0`), it wasn't in the tree anymore after the issue occurs. This makes me think it's re-rendering the whole thing when it shouldn't.
I then stepped through the code and was led to [`_$getTemplate`](https://github.com/lit/lit/blob/1e1e2e00e3ff655e6f48a42b2e739f47dc681420/packages/lit-html/src/lit-html.ts#L1555). In the failing configuraiton, the template for `<application-form>` was not found in the cache, but it was re-created with the same value.
Since it's a different object, [the comparison](https://github.com/lit/lit/blob/1e1e2e00e3ff655e6f48a42b2e739f47dc681420/packages/lit-html/src/lit-html.ts#L1516) failed. As far as I understand, this causes a re-rendering, since now lit thinks the template changed and not just the interpolated values.

I think this might be caused by an incorrect usage of WeakMap for the templateCache:
1. It is not an actual cache, since whether the results are available has an impact on whether the dom is re-used or not
2. While the values of the WeakMap are saved as `<application-form>.__childPart._$committedValue._$template`, this is not sufficient to keep it from being collected, since `Once an object used as a key has been collected, its corresponding values in any WeakMap become candidates for garbage collection as well — as long as they aren't strongly referred to elsewhere.` ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)) - Basically, it's the keys, not the values, that we'd need to save.

Please let me know if that makes sense to you.

I tried looking for chromium or v8 changelogs, but I couldn't really make sense of what I found.

Disregarding the fact that I couldn't reproduce it outside of the test, I don't see any reason why this couldn't happen for users, which makes me a little concerned.

### Reproduction

see above

### Workaround

Adding `.value="${...}"` works for text inputs, but not for file inputs. I can downgrade playwright so that it uses chromium 106, but I can't downgrade my users browsers.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

lit-element 3.2.2 lit-html 2.4.0

### Browser/OS/Node environment

Chromium Version 107.0.5304.18 (Developer Build) (64-bit)

Specific versions see the `pyproject.toml` and `poetry.lock` [here for the test code](https://gitlab.com/sea-watch.org/planner/-/tree/617039992912eee2646501f17fc6b612045784ed/end-to-end-test) and `package.json` and `package-lock.json` [here for the javascript stuff](https://gitlab.com/sea-watch.org/planner/-/tree/617039992912eee2646501f17fc6b612045784ed/public-client). We're also using a somewhat convoluted webpack config, just so you're warned.

**Comment by voidus** [comment]
I'm a bit concerned that this might affect our production system. It would be greatly appreciated if someone with knowledge of the lit codebase could chime in.

**Comment by voidus** [comment]
I have changed the `WeakMap` back to a `Map` locally using [patch-package](https://github.com/ds300/patch-package/) (Which was a bit of a pain, since it [doesn't support the current npm lockfile version](https://github.com/ds300/patch-package/issues/393)), and that resolved the issue.

I'm not a maintainer so take this with a grain of salt, but I see three ways forward:

1. Revert back to using a Map. Afaict the WeakMap was introduced for performance reasons, so I'm not sure if that is desirable.
2. Store the key somewhere so the entries don't get garbage collected. I've looked a bit at the code and this would have to happen at quite some distance from the `_$getTemplate` function, which I personally think doesn't look great.
3. Make it a proper cache, i.e. make whether we re-use DOM nodes independent of cache hit/misses. I'm not sure if this is even possible, but it seems the cleanest.

Either way, there needs to be a decision whether it is a cache of not, and this should be explicitly stated.

As someone affected by this issue working on a small-scale application, I'd prefer reverting to use a `Map` and not call it a cache any more, but that's just my perspective.

The fact that I've started seeing this with Chrome 107 makes me think there was a change that impacted weakmaps and this issue might become big soon.

**Comment by justinfagnani** [comment]
This _should_ have been fixed in V8: https://bugs.chromium.org/p/v8/issues/detail?id=13190

@voidus what versions of Chrome are you seeing this in?

fwiw, our cache is a cache - it caches the prepared Template objects that we compute from the template strings. The template strings themselves are what ultimately determines identity (whether we compare directly or the Template object which should be stable as well). The bug here is the browser freeing the template strings, which should not be done at all if the template literal expression is able to be evaluated again.

**Comment by voidus** [comment]
This was on Chromium Version 107.0.5304.18 (Developer Build) (64-bit), and I didn't see it on 106 with the same code.

I wasn't very clear on the "real cache" thing, sorry about that. What I meant was that a cache hit or miss has behavioral impact and not only improves performance because a hit will cause dom nodes to be re-used, while a miss causes them to be re-created.

As far as I can tell, this is a lit issue, but it's complicated so I might be wrong. Let me lay out my reasoning step by step.

1. [lit correctness] The dom nodes should be preserved so that input state isn't lost. This seems very obvious to me and is listed as a starting point.
2. Cache hits or misses determine whether they are re-used.
3. The cache is populated in `_$getTemplate` with `templateCache.set(result.strings, (template = new Template(result)));`
4. To guarantee that the template isn't collected, we need to keep `result.strings` from being collected.
5. `result` is passed as a parameter into `_$getTemplate` in `_commitTemplateResult` (only place I can see where `_$getTemplate` is called)
6. `_commitTemplateResult` also gets it passed in from `_$setValue` (only place I can see where `_commitTemplateResult` is called)
7. `result` is created in `_$setValue` using `value = resolveDirective(this, value, directiveParent);`
8. When we take the branch that calls `_commitTemplateResult`, `value` is not attached to any non-local variable.

As far as I understand, that allows `value` (or `result` lower in the call stack) to be collected.
The `Template` returned by `_$getTemplate` is persisted in the `TemplateInstance` `this._$committedValue`, but that is the *value* in the WeakMap, while we would need to store the `key` to prevent collection.

Reading the issue you linked closer, I do think that this is closely related.
Am I correct in understanding that the standard guarantees that the `result.strin`g is never collected?

We patched the `WeakMap` back to a `Map` in our prod code, but I'll remove the fix from our main codebase and see if I run into it again.

**Comment by justinfagnani** [comment]
This was marked as fixed upstream in Chrome. The bug was that Chrome was incorrectly freeing TemplateStringsArrays even though their containing function was still reachable.

Since it was fixed upstream, I'm going to close this bug. If you run into it again, you can reopen.

**Comment by voidus** [comment]
Will do, thank you for the pointers and the patience

**Comment by voidus** [comment]
This seems to not happen anymore with Chromium Version 111.0.5563.19
