### ISSUE TITLE
Property is not rendering in Firefox

### ISSUE THREAD

**Issue by gavinbarron** [lit/lit#3463]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When using a property directive to render with the `html` function the attribute is not rendered into the browser when using Firefox. 

This was discovered in our branch that had not been updated to the latest version of lit but was reproduced in the playground which I assume is using the latest version of lit.

Component code:
```typescript
import {html, css, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';

@customElement('x-input')
class LoginElement extends LitElement {
  /**
   * Label that can be set on the people picker input to provide context to
   * assistive technologies
   */
   @property({
    attribute: 'aria-label',
    type: String
  })
  public ariaLabel: string;

  render() {
    return html`     
      <input
        type="text"
        .ariaLabel=${this.ariaLabel}
      />
    `;
  }
}
```
Html usage
```html
<x-input aria-label="A label"></x-input>
```

Rendered output in Chromium
```html
<input type="text" aria-label="A label">
```

Rendered output in Firefox
```html
<input type="text">
```

### Reproduction

[Working reproduction in Playground](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgneC1pbnB1dCcpXG5jbGFzcyBMb2dpbkVsZW1lbnQgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgLyoqXG4gICAqIExhYmVsIHRoYXQgY2FuIGJlIHNldCBvbiB0aGUgcGVvcGxlIHBpY2tlciBpbnB1dCB0byBwcm92aWRlIGNvbnRleHQgdG9cbiAgICogYXNzaXN0aXZlIHRlY2hub2xvZ2llc1xuICAgKi9cbiAgIEBwcm9wZXJ0eSh7XG4gICAgYXR0cmlidXRlOiAnYXJpYS1sYWJlbCcsXG4gICAgdHlwZTogU3RyaW5nXG4gIH0pXG4gIHB1YmxpYyBhcmlhTGFiZWw6IHN0cmluZztcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgICAgICBcbiAgICAgIDxpbnB1dFxuICAgICAgICB0eXBlPVwidGV4dFwiXG4gICAgICAgIC5hcmlhTGFiZWw9JHt0aGlzLmFyaWFMYWJlbH1cbiAgICAgIC8-XG4gICAgYDtcbiAgfVxufSJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9yZXByby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx4LWlucHV0IGFyaWEtbGFiZWw9XCJBIGxhYmVsXCI-PC94LWlucHV0PlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

failing in lit-element :^2.4.0", and lit: ^2.3.1

### Browser/OS/Node environment

Browser: Firefox 107
OS: Windows 11

**Comment by sorvell** [comment]
Thanks for the repro. Unfortunately, the browsers are not consistent here and we have to work around that. Chrome has a property binding for the `aria-label` attribute to the `ariaLabel` property. Therefore that property binding on the input works. Firefox does not, so you need to bind to the attribute. You may also want to reflect the property on the host element. Here's a working example: https://lit.dev/playground/#gist=7fca344381c667b7f35dcb1ebcc6b3f0

**Comment by gavinbarron** [comment]
Oh. That's unfortunate and means additional work to correctly handle undefined values for the `ariaLabel` property. Such is browser compatibility.
