### ISSUE TITLE
[labs/ssr] handle shadowRootOptions during SSR

### ISSUE THREAD

**Issue by hrmcdonald** [lit/lit#3483]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr)

### Description

When shadowRootOptions are declared on a component like in the snippet below, they are not used to render SSR components. It sounds like this could be achieved by declaring some additional attributes on the template for the declarative shadow dom.

```
static shadowRootOptions = {...LitElement.shadowRootOptions, delegatesFocus: true};
```

---

### Recreation

On both of the examples below, focus the "button" by tabbing to it and then tab again. The non-SSR example focuses only the inner button and not the host element because of the `delegatesFocus` shadowRootOption. The SSR example focuses the host element first, but then also the inner button.

Expected behavior without SSR: [lit playground reproduction](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ2V4LWJ1dHRvbicpXG5leHBvcnQgY2xhc3MgRXhCdXR0b24gZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHNoYWRvd1Jvb3RPcHRpb25zID0ge1xuICAgIC4uLkxpdEVsZW1lbnQuc2hhZG93Um9vdE9wdGlvbnMsXG4gICAgZGVsZWdhdGVzRm9jdXM6IHRydWUsXG4gIH07XG5cbiAgY29ubmVjdGVkQ2FsbGJhY2soKSB7XG4gICAgc3VwZXIuY29ubmVjdGVkQ2FsbGJhY2soKTtcbiAgICB0aGlzLnRhYkluZGV4ID0gMDtcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGA8YnV0dG9uPjxzbG90Pjwvc2xvdD48L2J1dHRvbj5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGV4LWJ1dHRvbj5IZWxsbyBXb3JsZDwvZXgtYnV0dG9uPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

Behavior with SSR: https://stackblitz.com/edit/lit-ssr-global-3cktrx?file=src/components/ex-button.js

### Alternatives and Workarounds

None I am aware of.

**Comment by augustjk** [comment]
@hrmcdonald this is now released in `@lit-labs/ssr@2.3.0`
