### ISSUE TITLE
[labs/virtualizer] Doesn't update on scroll when a clipping ancestor is in Shadow DOM

### ISSUE THREAD

**Issue by Westbrook** [lit/lit#3493]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When slotting places a Virtualizer within a scrolling parent, the current parent gathering workflow does not acquire that parent. This means that when the content is scrolled, the virtualization is not triggered and subsequent pages of content are not rendered.

### Reproduction

https://lit.dev/playground/#gist=d12a3422f91b2b55eee102a491b74e3d

### Workaround

Patch the package...

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

All

### Browser/OS/Node environment

All

**Comment by graynorton** [comment]
@Westbrook It looks to me like you may have pasted the wrong Playground link. Can you double-check?

**Comment by graynorton** [comment]
@Westbrook Thanks for clarifying what's going on with the Playground in our Discord chat. Here are two more minimal repros derived from yours:

https://lit.dev/playground/#gist=4431876002ed36881754a665e8ea4818 (slot within a scrolling element)
https://lit.dev/playground/#gist=f60d8ccb1361c0373669336e136f2990 (slot is a scrolling element)
