### ISSUE TITLE
[Feature Request] Where is $ ? :(

### ISSUE THREAD

**Issue by vdegenne** [lit/lit#3567]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

Ids from elements that lay in the main DOM (not in a ShadowDom) are automatically bound to the main window object. e.g.

```html
<img id=myimage>
<script>
  const imgElement = window.myimage // <- 
</script>
```

I remember in Polymer there were this accessor `$` registered on any Custom Element built from this API

```javascript
myCustomElement.$.myimage
```

This is something that was lost over new specifications, I believe because you guys are trying to make the library as much lightweight as possible. 
But I also see that you are trying to make writing applications easier offering many cool features from directives to experimental tools from the Lit lab.

This is how you would access an element with an id in Lit now
```typescript
class extends LitElement {
  @query('#myimage') imgElement?: HTMLImageElement;
}
```
*(and you have to add a new query directive everytime you want to access a new element...)*  

But worst if you use plain JavaScript
```javascript
this.shadowRoot?.querySelector('#myimage') // erk
```

So basically, how would one implement that on his own:
```javascript
class LitWithIds extends LitElement {
  get $ () {
    return Object.fromEntries(
      [...this.shadowRoot?.querySelectorAll('[id]')].map(el => [el.id, el])
    )
  }
}

class MyElement extends LitWithIds {}
```
It's really not much of a deal to write but I have to include that in a custom element every time I want to use this feature (that is almost every time by default). And the problem here `$` will return a `any` object in TypeScript.  

I don't understand why it's not a build feature directly available in the framework... and why Polymer had it?

So here's what I propose, if you want to keep the main library tiny, why not giving this as a Lit-labs feature?

```javascript
import { bindIds } from '@lit-labs/helpers';

class extends LitElement {
  @bindIds() $
}
```
*(I couldn't think of a better name but just providing an example)*

Or it could just be a directive, so plain JavaScript users still can use it

```javascript
import { IdsBinder } from '@lit-labs/helpers';

class extends LitElement {
  const $ = new IdsBinder(this);
}
```

Just sharing ideas here. Again I could code it myself every time I make a new project but It's always comforting to use a feature that was made by you from the Lit team and to know that everyone is using the same thing.

🙇‍♂️

### Alternatives and Workarounds

alternatives already provided into the description

**Comment by justinfagnani** [comment]
Polymer's `$` feature really isn't necessary. `this.shadowRoot.querySelector()` works fine. Lit is just much more minimal than Polymer was and we try to have the smallest API possible over the standard DOM.
