### ISSUE TITLE
[Feature Request] @lit/reactive-element should expose `decorateProperty`

### ISSUE THREAD

**Issue by xenobytezero** [lit/lit#3568]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

While writing new Decorators for Lit elements, I found myself replicating a bunch of code that is currently in `reactive-element/src/decorators/base.ts` `decorateProperty` function to take account of the two different formats of decorator.

Also ` decorateProperty` is just generally a much nicer API to use when making property decorators.

It would be really handy if this function was exposed to developers.

### Alternatives and Workarounds

Currently I have just taken a copy of this function into my own code.

**Comment by justinfagnani** [comment]
We're going to move to the new standard stage 3 decorators, and will eventually deprecate the existing legacy decorators. The two forms that we currently support include an API that only Babel supports. I recommend not supporting that and only supporting TypeScript's experimental decorators for now, and standard decorators soon (after TypeScript 5.2 ships them maybe, Babel already supports them).

As such, I'm going to close this issue as we don't intend to expand support for the current decorators.
