### ISSUE TITLE
[reactive-element] Initial render is delayed

### ISSUE THREAD

**Issue by tigrr** [lit/lit#3581]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

On update, the rendering is delayed on a microtask level. This is fine for updates as a response to changes in reactive properties, however it creates problems when initial rendering of the shadow DOM is delayed in such way.

The particular problem I am facing is, when using Preact, at the time of executing a layout effect the shadow DOM of the custom element is still empty. Thus, trying to query or modify elements inside shadow DOM, whether directly from within the effect, or utilizing the appropriate component interfaces, will fail, most likely producing an error.

This happens:
- in `useLayoutEffect`
- or even in `useEffect` if
  - it was preceded by `useLayoutEffect` (see [useEffect sometimes fires before paint](https://dev.to/thoughtspile/useeffect-sometimes-fires-before-paint-3o4h))
  - if _"it’s the result of a discrete user input such as a click, or when it’s the result of an update wrapped in `flushSync`"_ (see [timing of effects](https://reactjs.org/docs/hooks-reference.html#timing-of-effects) in React docs)

I think the cause of this problem is awaiting `this.__updatePromise` in `__enqueueUpdate()` of [reactive element](https://github.com/lit/lit/blob/main/packages/reactive-element/src/reactive-element.ts#L1227).

### Reproduction

1. `git clone https://github.com/tigrr/test-lit.git`
2. `git switch preact-delayed-lit-render`
3. `cd test-lit`
4. `npm ci`
5. `npm run dev`
6. Open the app in the browser
7. Open Dev tools console
8. Observe logs order:
   1. `Preact useLayoutEffect called`
   2.  `Shadow root is attached. Shadow DOM is empty`
   3.  `Lit render called`

### Workaround

I have not found a workaround. Replacing all `useLayoutEffect`s in a project with `useEffect`s doesn't seem feasible, and even if it was, there is still the "user input" scenario (such as navigating to a page by clicking on a menu link).

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.4.1

### Browser/OS/Node environment

Browser: Chrome 109.0.5414.75
OS: Windows 10
Node version: 16.15.0
npm version: 8.5.5

**Comment by augustjk** [comment]
Have you found a solution for this?

Assuming you have a ref to the element within the effect, perhaps you can `await element.updateComplete` before doing things on the element?

**Comment by justinfagnani** [comment]
Async rendering is a fundamental design choice of Lit. It's usually a pure benefit and not noticable, but some cases like this might have to take it into account.

Hopefully you can `await element.updateComplete` like @augustjk recommended. It's like to see what the specific use cases are to make better recommendations.

We can try to look at your repo, but fyi, it's much easier to see reproductions in an online environment like lit.dev's playground.

**Comment by tigrr** [comment]
@augustjk , your solution would work technically, but
1. It is quite painful to use that workaround everywhere you need to call `focus()`, `select()`, to query size, style or other properties of an element, because of an unexpected behavior of a library;
1. `await element.updateComplete` is an implementation detail, the consuming application does not have to be concerned or informed about it.

@justinfagnani , my expectation was that a custom element created using a web component library, such as Lit, should provide the closest compatibility with the native HTML elements. For native elements you could do

```js
const input = document.createElement('input')
document.body.append(input)
input.focus()
```

but for a custom input control that uses a native input element in its shadow DOM (think shoelace `sl-input` for example) the same will throw an error:

```js
const input = document.createElement('sl-input')
document.body.append(input)
input.focus()
```

Surely async rendering has benefits in the consequent re-renders. But for the initial rendering, I don't know what benefits postponing gives, but here it creates an incapability, which is very hard to work around. You would either need to await in each and every "proxy" method (such as `focus()`, or do that workaround in the consuming application (which shouldn't be its responsibility). Sometimes, there are not even any "proxy" methods: you could simply try querying the size of an element after creating and appending it to the DOM, and that would fail. How bad is that!

Why isn't it possible not to postpone rendering of the shadow DOM only for the initial render? What are the possible pitfalls?

**Comment by justinfagnani** [comment]
We render asynchronously even on first render because we don't know if we've received initial properties from a parent yet. If we rendered synchronously, we would immediately re-render asynchronously which would have a seriously negative performance impact on first page render.

**Comment by tigrr** [comment]
So, between having a performance penalty or a bug, you are choosing to have a bug. 😣 
Are you sure there is no way of knowing those initial properties synchronously on first render?

**Comment by justinfagnani** [comment]
Async rendering is fundamental to our design for ReactiveElement and we can't reasonably change that.

There's a potential future with standard signals where we could move to synchronous, batched rendering, but it's a ways out.
