### ISSUE TITLE
[lit-html] get ParentNode should handle when parentNode is null

### ISSUE THREAD

**Issue by JamieKook** [lit/lit#3611]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I recently had an issue with how I was working with a lit component. In attempting to debug my problem, I encountered this. 
In the _$setValue method in lit-html.ts, there is an error thrown when this.parentNode === null 

```
_$setValue(value: unknown, directiveParent: DirectiveParent = this): void {
    if (DEV_MODE && this.parentNode === null) {
      throw new Error(
        `This \`ChildPart\` has no \`parentNode\` and therefore cannot accept a value. This likely means the element containing the part was manipulated in an unsupported way outside of Lit's control such that the part's marker nodes were ejected from DOM. For example, setting the element's \`innerHTML\` or \`textContent\` can do this.`
      );
    } 
```

However, I was not seeing this useful error because in get ParentNode() in the same file, the first if statement checks the nodeType of the parentNode which fails because the parentNode is null and I got a less helpful error. It seems that if we can have this.parentNode === null, a null value for the parentNode should be handled in the get ParentNode method.

```
get parentNode(): Node {
    let parentNode: Node = wrap(this._$startNode).parentNode!;
    const parent = this._$parent;
    if (
      parent !== undefined &&
      parentNode.nodeType === 11 /* Node.DOCUMENT_FRAGMENT */
    ) { 
```

### Reproduction

1. Create a lit component that will exit and reenter the document
2. Have that lit component render a second lit component in the template
3. Foolishly change the innerText of the parent lit component to remove the child in the Updated method
4. Debug 

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.6.1

### Browser/OS/Node environment

Browser: Chrome 109.0.5414.87
macOS Ventura 13.1

**Comment by justinfagnani** [comment]
I think we could address this make making the check for a DocumentFragment parent null-safe:

```ts
      parentNode?.nodeType === 11 /* Node.DOCUMENT_FRAGMENT */
```

@sorvell wdyt?

**Comment by justinfagnani** [comment]
@JamieKook how are you getting a directive with no parent in the first place? Are you doing manual DOM mutation?

**Comment by JamieKook** [comment]
@justinfagnani yes, I was setting the innerHTML on one of my elements which was causing issues when I later tried to request update. I was trying to figure out what was causing things to be incorrectly rendered and eventually got to the error that says you can't set the inner text. And I had the light bulb moment and fixed how I was doing things. But I had to get around the null has no node type error first. When I added the question mark after parentNode, like you did in the above comment, then I got the error that really helped me debug.
