### ISSUE TITLE
[all] Test flakiness is killing productivity

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3641]
Our tests have gotten way more flaky recently. Often I have to re-run failed jobs 4 or more times to get a fully passing run on a PR. There seem to be several sources of flakiness, increasing the chances that any run fail for various reasons.

So far I've seen:

- Sauce tests failing because the `sc` command is "busy". These are usually, or possibly always, the SSR tests.
- Motion tests failing because of a failed expectation.
- 11ty plugin tests failing because of a timeout
- IE11 sauce test so flaky they fail more often then pass. We're already mostly ignoring these.

I believe I've also seen a virtualizer test be flaky too, but I haven't kept a good enough log.

I think this is critical to fix. Having to monitor and re-run tests this much is really sapping productivity, especially when trying to do what should otherwise be quick fixes.

**Comment by justinfagnani** [comment]
Motion failure. Sauce tests on Safari:

```
../labs/motion/development/test/animate_test.js:

 ❌ Animate > adjusts for ancestor position (failed on macOS 11 Safari latest)
      AssertionError: expected 40 to be close to 22 +/- 0.1
```

The actual value seems to be 40 consistently when this fails. Maybe the flake is that one too many or too few frames pass when the measurement is taked?

**Comment by usergenic** [comment]
Virtualizer has had a few flaky tests that I adjusted and one whole file now that is skipped as a result of changes in chrome behavior we haven't accounted for.

I am in favor of adding .skip to describe blocks and a TODO around flaky assertions to get CI green and PR flow humming along again.

**Comment by justinfagnani** [comment]
`eleventy-plugin-lit:test` failure:

```
✘   (17 / 18)

   FAIL  "template files with `permalink: false` in frontmatter"
    11ty process didn't exit in 10000ms.  (not)

    at assert (file:///home/runner/work/lit/lit/node_modules/uvu/assert/index.mjs:33:8)
    at Module.not (file:///home/runner/work/lit/lit/node_modules/uvu/assert/index.mjs:103:2)
    at file:///home/runner/work/lit/lit/packages/labs/eleventy-plugin-lit/test/eleventy-plugin-test.js:462:24
    at async Object.handler (file:///home/runner/work/lit/lit/packages/labs/eleventy-plugin-lit/test/eleventy-plugin-test.js:458:9)
    at async Number.runner (file:///home/runner/work/lit/lit/node_modules/uvu/dist/index.mjs:78:5)
    at async Module.exec (file:///home/runner/work/lit/lit/node_modules/uvu/dist/index.mjs:141:33)
    at async Module.run (file:///home/runner/work/lit/lit/node_modules/uvu/run/index.mjs:12:2)
    at async /home/runner/work/lit/lit/node_modules/uvu/bin.js:26:5



  Total:     18
  Passed:    17
  Skipped:   2
  Duration:  107295.20ms

❌ [packages/labs/eleventy-plugin-lit:test] Failed with exit status 1
```

**Comment by justinfagnani** [comment]
> I am in favor of adding .skip to describe blocks and a TODO around flaky assertions to get CI green and PR flow humming along again.

Yeah, we might need to do that. I'm just worried about forgetting these. If we can fix any of them first, that'd be nice.

**Comment by justinfagnani** [comment]
SSR failures:

```
[Saucelabs] Setting up Sauce Connect proxy...
Error while running tests:
Error: spawn ETXTBSY
    at ChildProcess.spawn (node:internal/child_process:420:11)
    at spawn (node:child_process:733:9)
    at SauceLabs._startSauceConnect (/home/runner/work/lit/lit/node_modules/saucelabs/build/index.js:296:41) {
  errno: -26,
  code: 'ETXTBSY',
  syscall: 'spawn'
}


❌ [test:integration:unshimmed:dev] Failed with exit status 1
Error while running tests:
[Error: ETXTBSY: text file is busy, open '/home/runner/work/lit/lit/node_modules/saucelabs/build/sc-loader/.sc-v4.8.0/bin/sc'] {
  errno: -26,
  code: 'ETXTBSY',
  syscall: 'open',
  path: '/home/runner/work/lit/lit/node_modules/saucelabs/build/sc-loader/.sc-v4.8.0/bin/sc'
}


❌ [test:integration:shimmed:prod] Failed with exit status 1

```

**Comment by augustjk** [comment]
https://github.com/lit/lit/pull/3653 will help deflake Sauce SSR failures.

**Comment by justinfagnani** [comment]
Between that, skipping the motion test, and https://github.com/lit/lit/pull/3642 we already seem to be in a much better place

**Comment by justinfagnani** [comment]
I think we can probably close this now. Thanks @augustjk for the PRs!

@usergenic not sure if virtualizer still has flakiness, maybe wireit is working to not run them often, but tests seem to me to mostly pass. If those are still happening we could open a specific issue for them?
