### ISSUE TITLE
Textareas which rely on the same state seem to not get updated properly

### ISSUE THREAD

**Issue by deanveloper** [lit/lit#3647]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

There seems to be an issue when I form this "circular" dependency. Essentially, I have two textareas, one of them being a "transformed" version of the other. When I update one of them, the other should update as well.

The way that this is accomplished is by storing a single value as state, which is directly tied to one of the textareas. The other textarea's value is the result of a function, which calls on that state. Then, I tie the `@input` of the first textarea to update the state, and the `@input` of the second textarea to a function.

It seems that when I do this, I'm successfully able to do this in one direction, whichever one I edit first. For instance, if I load the page and type in the first one, the second one successfully updates. However, if I then type in the second one, the first one does not update. This also happens vice-versa -- if I load the page and type in the second textarea first, then editing the first textarea no longer updates the second.

### Reproduction

[minimum reproducible example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy5qcyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcblxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIHN0YXRpYyBwcm9wZXJ0aWVzID0ge1xuICAgIHRleHQ6IHtzdGF0ZTogdHJ1ZX0sXG4gIH07XG5cbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKTtcbiAgICB0aGlzLnRleHQgPSAnJztcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPGRpdj5cbiAgICAgICAgICA8c3Bhbj50ZXh0PC9zcGFuPjxicj5cbiAgICAgICAgICA8dGV4dGFyZWEgQGlucHV0PSR7KGV2KSA9PiB0aGlzLnRleHQgPSBldi50YXJnZXQudmFsdWV9PiR7dGhpcy50ZXh0fTwvdGV4dGFyZWE-XG4gICAgICAgIDwvZGl2Pjxicj5cbiAgICAgICAgPGRpdj5cbiAgICAgICAgICA8c3Bhbj5jb2RlIHBvaW50czwvc3Bhbj48YnI-XG4gICAgICAgICAgPHRleHRhcmVhIEBpbnB1dD0keyhldikgPT4gdGhpcy5zZXRDb2RlUG9pbnRzKGV2LnRhcmdldC52YWx1ZSl9PiR7dGhpcy5jb2RlUG9pbnRzKCl9PC90ZXh0YXJlYT5cbiAgICAgICAgPC9kaXY-XG4gICAgYDtcbiAgfVxuXG4gIGNvZGVQb2ludHMoKSB7XG4gICAgcmV0dXJuIFsuLi50aGlzLnRleHRdLm1hcChjaGFyID0-IGNoYXIuY29kZVBvaW50QXQoMCkpLmpvaW4oJywnKTtcbiAgfVxuICBzZXRDb2RlUG9pbnRzKHZhbHVlU3RyKSB7XG4gICAgdHJ5IHtcbiAgICAgIGNvbnN0IHBvaW50cyA9IHZhbHVlU3RyLnNwbGl0KCcsJykubWFwKChzdHIpID0-IHBhcnNlSW50KHN0cikpO1xuICAgICAgdGhpcy50ZXh0ID0gU3RyaW5nLmZyb21Db2RlUG9pbnQoLi4ucG9pbnRzKTtcbiAgICB9IGNhdGNoIChlcnIpIHtcbiAgICAgIHRoaXMudGV4dCA9IFwiXCI7XG4gICAgfVxuICB9XG59XG5jdXN0b21FbGVtZW50cy5kZWZpbmUoJ3NpbXBsZS1ncmVldGluZycsIFNpbXBsZUdyZWV0aW5nKTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

1. Type some stuff into the "text" textarea
2. Notice the "code points" textarea changes
3. Type some stuff into the "code points" textarea
4. Notice the "text" textarea does not change.

Then, try it vice-versa:

1. Type some stuff into the "code points" textarea
2. Notice the "text" textarea changes
3. Type some stuff into the "text" textarea
4. Notice the "code points" textarea does not change.

### Workaround

I have not found a workaround, although I'm sure that one exists.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

6.6.1

### Browser/OS/Node environment

Browser: 109.0.5414.120 (Official Build) (64-bit)
OS: Windows 11
Node: N/A, I have no build step

**Comment by justinfagnani** [comment]
See https://lit.dev/docs/templates/expressions/#invalid-locations

Specifically:

Inside <textarea> element content (attribute expressions on the textarea element itself are allowed). Note that Lit can render content into textarea, however editing the textarea will break references to the DOM that Lit uses to dynamically update, and Lit will warn in development mode. Instead, bind to the .value property of textarea.

```html
<!-- BEWARE -->
<textarea>${content}</textarea>

<!-- OK -->
<textarea .value=${content}></textarea>

<!-- OK -->
<textarea id="${attrValue}">static content ok</textarea>
```

Your example works if you update it to use `.value`bindings.

**Comment by deanveloper** [comment]
Ahh perfect, thank you for the information! This fixes my issue.
