### ISSUE TITLE
[labs/context] Expose a dependency less entry point so we can also use the module and implement on DOM directly 

### ISSUE THREAD

**Issue by renoirb** [lit/lit#3665]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Context (@lit-labs/context)

### Description

This is a follow up in some comments I've made bringing up the idea that one could import lit-labs/context and implement themselves directly on the DOM. ([see comment](https://github.com/lit/lit/pull/1955#discussion_r711378966))

**Usage scenario**: I'd like to use *Context API* directly on client side module over http (import from ...). I currently have a few custom elements exposed this way and I'd love to have this code not to depend on any framework (don't get me wrong, I love Lit!)

To start, I've been thinking of using [jspm][jspm-gen] to import only what I need, but I would need more than one file: value-notifier, create-context, etc.

Otherwise I would have to copy paste and transpile code and expose over HTTP.  I'd like to avoid that.

I can provide an HTML file where I setup client-side only where I'm trying to implement my own DOM backed ContextProvider and ContextConsumer. But I need what's at the root of lib/ to start from.

[jspm-gen]: https://generator.jspm.io/#U2VhYGBkDM0rySzJSU1hcMjJLNHNSUwq1k/OzytJrShxMNAz0jMAAFKaYfwmAA

### Alternatives and Workarounds

- add exports for what's in lib/*.js, that doesn't require lit (oh. Right.) add a publish step of the same, but without dependency
- config to allow to ´import { createContext } from "...";´ from over https

**Comment by justinfagnani** [comment]
This is a Lit-specific implementation of the context protocol, and uses Lit -specific APIs.

I'm not sure what it would mean to use this implementation without Lit, or what http has to do with it, but you can implement the context protocol yourself for your elements.

**Comment by renoirb** [comment]
I'm aware it's lit specific. I'm suggesting to publish the typings and an abstract of context-root so one could use it on DOM.

**Comment by rictic** [comment]
Context is a light weight API already, I don't think we're interested in exposing a more light weight entrypoint.

**Comment by renoirb** [comment]
I agree it's light. The neat bit where we can have a listener that keeps track of context request events even when the handler isn't loaded, and helps it catch up so to speak.  That neat bit is hooked on lit's event lifecycle convention.  It's most probable one could copy that and use native.   Would have been cool if that was something separate and available for non lit users.

Since I'm probably the only one who sees this, and it's just a hunch.  I'll try it someday and if it works, I'll do a PR here.
