### ISSUE TITLE
[labs/router] Can't goto/link to route

### ISSUE THREAD

**Issue by jrj2211** [lit/lit#3666]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

If I create a router and then from the same element try to link or go to it based on its name, it errors saying route not found.

I see that `goto(name: string, params: object)` has a note saying `not implemented` but thats not the case for `goto(url: string)` or `link()`.

Very well could be interpreting the docs wrong but it seems like this should be correct.

```
export class XRepro extends LitElement {

  router = new Router(this, [
    { name: 'test', path: '/test', render: () => html`Hello World` },
    { name: 'home', path: '(/home)?', render: () => html`Home` }
  ]);

  render() {
    return html`
      <button @click=${() => this.router.goto('test');}>Click me</button>
    `;
  }
}
```

```
Uncaught (in promise) Error: No route found for test
```

### Reproduction

Here is a non working demo:
[lit.dev/playground](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLmpzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgUm91dGVyIH0gZnJvbSAnQGxpdC1sYWJzL3JvdXRlcic7XG4gICAgXG5leHBvcnQgY2xhc3MgWFJlcHJvIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIHJvdXRlciA9IG5ldyBSb3V0ZXIodGhpcywgW1xuICAgIHsgbmFtZTogJ3Rlc3QnLCBwYXRoOiAnL3Rlc3QnLCByZW5kZXI6ICgpID0-IGh0bWxgSGVsbG8gV29ybGRgIH0sXG4gICAgeyBuYW1lOiAnaG9tZScsIHBhdGg6ICcoL2hvbWUpPycsIHJlbmRlcjogKCkgPT4gaHRtbGBIb21lYCB9XG4gIF0pO1xuXG4gICAgICBcbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKTtcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxwPkNsaWNraW5nIHRoZSBidXR0b24gYmVsb3cgaXMgZXhwZWN0ZWQgdG8gdXBkYXRlIHRoZSB0ZXh0LCBidXQgaXQgZG9lc24ndDo8L3A-XG4gICAgICA8YnV0dG9uIEBjbGljaz0ke3RoaXMuX29uQ2xpY2tCdXR0b259PkNsaWNrIG1lPC9idXR0b24-XG4gICAgYDtcbiAgfVxuICBcbiAgX29uQ2xpY2tCdXR0b24oKSB7XG4gICAgLy8gQSB0eXBvIGZvciBidWcgZGVtb25zdHJhdGlvbiBwdXJwb3Nlcy4gVGhlIGxlYWRpbmcgXyBpcyBtaXNzaW5nLlxuICAgIHRoaXMucm91dGVyLmdvdG8oJ3Rlc3QnKTtcbiAgfVxufVxuY3VzdG9tRWxlbWVudHMuZGVmaW5lKCd4LXJlcHJvJywgWFJlcHJvKTsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vcmVwcm8uanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8eC1yZXBybz48L3gtcmVwcm8-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.1.1

### Browser/OS/Node environment

Browser: Chrome
Version 110.0.5481.78 (Official Build) (64-bit)
Windows 10 pro
Node 16.16

**Comment by Antony92** [comment]
First you will need an outlet to display the selected route and second you need to specify the full path I guess.

[https://lit.dev/playground](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLmpzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHsgUm91dGVyIH0gZnJvbSAnQGxpdC1sYWJzL3JvdXRlcic7XG4gICAgXG5leHBvcnQgY2xhc3MgWFJlcHJvIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIHJvdXRlciA9IG5ldyBSb3V0ZXIodGhpcywgW1xuICAgIHsgbmFtZTogJ3Rlc3QnLCBwYXRoOiAnL3Rlc3QnLCByZW5kZXI6ICgpID0-IGh0bWxgSGVsbG8gV29ybGRgIH0sXG4gICAgeyBuYW1lOiAnaG9tZScsIHBhdGg6ICcoL2hvbWUpPycsIHJlbmRlcjogKCkgPT4gaHRtbGBIb21lYCB9XG4gIF0pO1xuXG4gICAgICBcbiAgY29uc3RydWN0b3IoKSB7XG4gICAgc3VwZXIoKTtcbiAgfVxuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxwPkNsaWNraW5nIHRoZSBidXR0b24gYmVsb3cgaXMgZXhwZWN0ZWQgdG8gdXBkYXRlIHRoZSB0ZXh0LCBidXQgaXQgZG9lc24ndDo8L3A-XG4gICAgICA8YnV0dG9uIEBjbGljaz0ke3RoaXMuX29uQ2xpY2tCdXR0b259PkNsaWNrIG1lPC9idXR0b24-XG4gICAgICA8ZGl2PiR7dGhpcy5yb3V0ZXIub3V0bGV0KCl9PC9kaXY-XG4gICAgYDtcbiAgfVxuICBcbiAgX29uQ2xpY2tCdXR0b24oKSB7XG4gICAgLy8gQSB0eXBvIGZvciBidWcgZGVtb25zdHJhdGlvbiBwdXJwb3Nlcy4gVGhlIGxlYWRpbmcgXyBpcyBtaXNzaW5nLlxuICAgIHRoaXMucm91dGVyLmdvdG8oJy90ZXN0Jyk7XG4gIH1cbn1cbmN1c3RvbUVsZW1lbnRzLmRlZmluZSgneC1yZXBybycsIFhSZXBybyk7In0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3JlcHJvLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHgtcmVwcm8-PC94LXJlcHJvPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

**Comment by jrj2211** [comment]
Thank you, I misread the docs. I thought the named goto/link was implemented, but just didn't support passing in attributes to be replaced yet.
