### ISSUE TITLE
[labs/nextjs] Custom element registry can cause error on dev mode rebuild

### ISSUE THREAD

**Issue by augustjk** [lit/lit#3672]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

While running Next.js's dev mode, making changes to any file that include a custom element registration cause the error:
```
error - Error: Failed to execute 'define' on 'CustomElementRegistry'
```

This isn't necessarily a problem with the `labs/nextjs` package in itself but is due to the `CustomElementRegistry` shim included with node builds of the lit package, and how we're running the SSR code in the global scope.

I anticipate most use case of custom elements in Next.js wouldn't be bothered by this much as they'd be importing a ready-to-use component and not touching its definition to be re-registered. For components that require users to import and register separately, this may be more of a problem.

### Reproduction

.

### Workaround

For now, restart dev server.

Possible fixes for this:

- Make our `CustomElementRegistry` shim not throw on re-registers. This lives in `@lit-labs/ssr-dom-shim` https://github.com/lit/lit/blob/e00f6f52199d5dbc08d4c15f62380422e77cde7f/packages/labs/ssr-dom-shim/src/index.ts#L89-L94
- Patch the `CustomElementRegistry` somewhere in the labs/nextjs plugin to not throw
- When available, incorporate https://github.com/lit/lit/issues/3627

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

N/A

### Browser/OS/Node environment

N/A

**Comment by FriedRiceNoodles** [comment]
same problem exists on remix.

**Comment by FriedRiceNoodles** [comment]
https://github.com/remix-run/remix/issues/5888

**Comment by augustjk** [comment]
As this is mainly a concern for dev mode, and we want to keep the production behavior for the custom element registry shim to match the browser behavior, I think a potential fix for this would be for the CE registry shim to warn instead of throwing on repeat registrations _only_ in dev mode. This would require adding a development export for the `@lit-labs/ssr-dom-shim` package.

**Comment by ba55ie** [comment]
> As this is mainly a concern for dev mode, and we want to keep the production behavior for the custom element registry shim to match the browser behavior, I think a potential fix for this would be for the CE registry shim to warn instead of throwing on repeat registrations _only_ in dev mode. This would require adding a development export for the `@lit-labs/ssr-dom-shim` package.

I also ran into this problem after upgrading the `@astrojs/lit` integration to [`v2.0.x`](https://github.com/withastro/astro/blob/main/packages/integrations/lit/CHANGELOG.md#200).

As a workaround I have created a patched version locally with the conditional `development` export as mentioned.

`fix/ssr-dom-shim/package.json`:

```json
"exports": {
    ".": {
      "development": "./index.dev.js", // copy of index.js without the error thrown
      "types": "./index.d.ts",
      "default": "./index.js"
    }
  },
  ```
  
  ```bash
  npm i -D ./fix/ssr-dom-shim
  ```

**Comment by alexandre-lelain** [comment]
Hello,

The problem persists for me. Something still throws a runtime error in development mode when using LitElements :

```
NotSupportedError: CustomElementRegistry.define: 'X' has already been defined as a custom element
```
