### ISSUE TITLE
Support for using "@" in css class names

### ISSUE THREAD

**Issue by yantevanham** [lit/lit#3689]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Hi! If this is not a bug and it is documented somewhere, please feel free to direct me! I did not come across this information or any similar issues.

I want to use the `@` symbol in the name of a CSS class, e.g. `media@md`, for responsive suffixes (for more, see [this article](https://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/)). In plain CSS/HTML, this works when you escape the `@` symbol when defining the CSS (using `.media\@md` in the css and `class="media@md"` in the html). 
This does not seem to work in lit.

### Reproduction

[Lit playground link](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIC5tZWRpYUBtZCB7IFxuICAgICAgIGJvcmRlcjogMnB4IHNvbGlkIHJlZDsgXG4gICAgICB9XG4gICAgICAubWVkaWFcXEBtZCB7IFxuICAgICAgIGJvcmRlcjogMnB4IHNvbGlkIGJsdWU7XG4gICAgICB9XG4gICAgICAubWVkaWEtbWQgeyBcbiAgICAgICBib3JkZXI6IDJweCBzb2xpZCBncmVlbjsgXG4gICAgICB9XG4gICAgICBgO1xuXG4gIEBwcm9wZXJ0eSgpXG4gIG5hbWUgPSAnU29tZWJvZHknO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPHAgY2xhc3M9XCJtZWRpYUBtZFwiPkhlbGxvLCAke3RoaXMubmFtZX0hPC9wPlxuICAgICAgICA8cCBjbGFzcz1cIm1lZGlhLW1kXCI-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.2.8

### Browser/OS/Node environment

Browser: Chrome 110.0.5481.100
OS: macOS 13.0.1
Node version: 18.10.0
npm version: 8.19.2

**Comment by bicknellr** [comment]
This is an awkward quirk of nesting one language in strings in another language where both use the same escape character: the `\` in `.media\@md` is interpreted as an escape sequence for the template string in JS before the CSS parser even sees it. (I.e. the `css` tag function sees this string as containing `.media@md` and writes that into the style sheet.) To get `\@` passed into the style sheet, the `\` itself needs to be escaped: [writing `.media\\@md` instead does what you're looking for](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIC5tZWRpYUBtZCB7IFxuICAgICAgIGJvcmRlcjogMnB4IHNvbGlkIHJlZDsgXG4gICAgICB9XG4gICAgICAubWVkaWFcXFxcQG1kIHsgXG4gICAgICAgYm9yZGVyOiAycHggc29saWQgYmx1ZTtcbiAgICAgIH1cbiAgICAgIC5tZWRpYS1tZCB7IFxuICAgICAgIGJvcmRlcjogMnB4IHNvbGlkIGdyZWVuOyBcbiAgICAgIH1cbiAgICAgIGA7XG5cbiAgQHByb3BlcnR5KClcbiAgbmFtZSA9ICdTb21lYm9keSc7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgICA8cCBjbGFzcz1cIm1lZGlhQG1kXCI-SGVsbG8sICR7dGhpcy5uYW1lfSE8L3A-XG4gICAgICAgIDxwIGNsYXNzPVwibWVkaWEtbWRcIj5IZWxsbywgJHt0aGlzLm5hbWV9ITwvcD5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0).

**Comment by yantevanham** [comment]
Ah, yes, I did not try that one. Thank you!

**Comment by bicknellr** [comment]
np!
