### ISSUE TITLE
Unable to access object property values in LitElement styles

### ISSUE THREAD

**Issue by sergiopani** [lit/lit#3721]
### Should this be an RFC?

- [x] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Hello! I'm having trouble accessing the values of properties from the component in the styles section of my LitElement. I find this very frustrating because I'm having to create CSS variables in the render method instead.

Here's an example of what I'm trying to do:

```js
class MyElement extends LitElement {
  static get styles() {
    return css`
      .my-class {
        background-color: ${this.property}; // This doesn't work
      }
    `;
  }

  static get properties() {
    return {
      property: { type: string },
    };
  }

  render() {
    return html`
      <div class="my-class">Hello world!</div>
    `;
  }
}

```

### Alternatives and Workarounds

Instead of trying to access the property values directly in the styles section, you can define CSS variables in the render() method and use them in the styles section. This way, you can access the property values and use them to set the values of the CSS variables.

```js
class MyElement extends LitElement {
  static get styles() {
    return css`
      :host {
        --my-bg-color: var(--my-obj-my-prop);
        background-color: var(--my-bg-color);
      }
    `;
  }

  static get properties() {
    return {
      color: { type: String },
    };
  }

  render() {
    return html`
      <div style="--my-obj-my-prop: ${this.color}">
        <slot></slot>
      </div>
    `;
  }
}

```

**Comment by augustjk** [comment]
This is working as intended due to the nature of `static styles` being evaluated once per class. If you need the style to be per _instance_, you can use a `<style>` tag with an expression in the template rendered like

```ts
  render() {
    return html`
      <style>.my-class { background-color: ${this.property}; }</style>
      <div class="my-class"></div>
    `;
  }
```

See https://lit.dev/docs/components/styles/#style-element

Though if the "color" property is being provided by the consumer, and all you're using it is for the styling, css custom properties are more appropriate as shown https://lit.dev/docs/components/styles/#customprops

**Comment by sergiopani** [comment]
I was wondering if there are any plans to implement per-instance styles in the future? I think this would be a really useful feature for my specific use case.

**Comment by justinfagnani** [comment]
Not really. `<style>` tags _are_ per instance styles. What would you want to see on top of that?
