### ISSUE TITLE
[@lit-labs/ssr-react]When will it be released?

### ISSUE THREAD

**Issue by FriedRiceNoodles** [lit/lit#3729]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

https://github.com/lit/lit/tree/main/packages/labs/ssr-react
@augustjk 
It looks powerful! When will it be released?

### Alternatives and Workarounds

-

**Comment by augustjk** [comment]
Thank you for the interest @FriedRiceNoodles this has now been released! Please give it a try and let us know how it goes.

Feel free to open new bug issues or a [discussion](https://github.com/lit/lit/discussions) topic if you have any questions!
