### ISSUE TITLE
[lit-element] lit component

### ISSUE THREAD

**Issue by marsDes** [lit/lit#3735]
lit component
```ts
// t-button
@customElement('t-button')
...
return html`<button ?disabled=${this.disabled} @click=${console.log('button')}>
  <solt>
  </solt>
</button>`
...
```
use in html
```html
<t-button disabled onClick="console.log('t-button')">button</t-button>
```
it also log:'t-button',how can forbidden by add a `<slot></slot>`

_Originally posted by @marsDes in https://github.com/lit/lit/discussions/3734_

**Comment by justinfagnani** [comment]
What's the question here?

**Comment by marsDes** [comment]
like this
```ts 
// t-button
@customElement('t-button')
...
return html`<button ?disabled=${this.disabled} @click=${console.log('button')}>button</button>`
...
```
use 
```html
<t-button disabled onClick="console.log('t-button')">button</t-button>
```
when set disabled, nothing happed

**Comment by justinfagnani** [comment]
Can you make a reproduction of what you're trying to do on https://lit.dev/playground ?

**Comment by justinfagnani** [comment]
@marsDes we need more info if we're going to be able to help

I suspect that you might need to use `type: Boolean` in your definition of `disabled`. Like:

```ts
@customElement('t-button')
class TButton extends LitElement {
  @property({type: Boolean, reflect: true})
  disabled = false;
}
```

**Comment by hanifmhd** [comment]
i think it is related to this https://stackoverflow.com/questions/32745276/explicitly-set-disabled-false-in-the-html-does-not-work

**Comment by justinfagnani** [comment]
If this is still an issue, please re-open. We will need a clear question and hopefully a reproduction.
