### ISSUE TITLE
Override static styles within a Lit component based on an external property

### ISSUE THREAD

**Issue by psygo** [lit/lit#3742]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

> This was originally [a StackOverflow question](https://stackoverflow.com/q/75802794/4756173).

I'm trying to specify a theme as a property, and then override the `static styles` property on the Lit element.

This would be handy because then I could share an interface with my users such that they would have a type-safe way of composing custom themes of my web components for their own apps.

However, when I change the `static styles` property, Lit doesn't seem aware of the change, nothing actually happens. I've tried doing it in both the `constructor` and `connectedCallback` methods, but neither worked. In my real-world use case, it's slightly more complicated because I have a `BaseComponent` being inherited with its styles by other components, but let's leave it aside for this question, I guess.

Is this really possible? Or should I stick to using `styleMap`, `classMap` and [regular CSS custom properties](https://lit.dev/docs/components/styles/#customprops).

On the Lit's Discord server, another user mentioned that I might need to use [Constructable Stylesheets](https://web.dev/constructable-stylesheets/) &mdash; and it's apparently what Lit uses under the hood &mdash; but I'm not sure where to even start with that.

> You can take a look at this example on Lit's playground [here](https://lit.dev/playground/#project=W3sibmFtZSI6ImhlbGxvLXdvcmxkLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCB1bnNhZmVDU1MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbnR5cGUgQ29sb3IgPSBzdHJpbmc7XG5pbnRlcmZhY2UgQ3VzdG9tVGhlbWUge1xuICBwcmltYXJ5OiBDb2xvcjtcbn1cblxuY29uc3QgY3VzdG9tVGhlbWUgPSB7XG4gIHByaW1hcnk6IFwib3JhbmdlXCJcbn1cbiAgICBcbmZ1bmN0aW9uIHRoZW1lVG9MaXRDc3ModGhlbWU6IEN1c3RvbVRoZW1lKSB7XG4gIHJldHVybiBjc3NgXG4gICAgIHAge1xuICAgICAgIGNvbG9yOiAke3Vuc2FmZUNTUyh0aGVtZS5wcmltYXJ5KX1cbiAgICAgfVxuICBgXG59XG5cbkBjdXN0b21FbGVtZW50KCdoZWxsby13b3JsZCcpXG5leHBvcnQgY2xhc3MgSGVsbG9Xb3JsZCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gW107XG5cbiAgQHByb3BlcnR5KHtcbiAgYXR0cmlidXRlOiAnY3VzdG9tLXRoZW1lJyxcbiAgY29udmVydGVyOiAoYXR0clZhbHVlOiBzdHJpbmcgfCB1bmRlZmluZWQpID0-XG4gICAgYXR0clZhbHVlID8gSlNPTi5wYXJzZShhdHRyVmFsdWUpIDogdW5kZWZpbmVkLFxuICB9KVxuICBjdXN0b21UaGVtZT86IEN1c3RvbVRoZW1lO1xuICBcbiAgb3ZlcnJpZGUgY29ubmVjdGVkQ2FsbGJhY2soKSB7XG4gICAgc3VwZXIuY29ubmVjdGVkQ2FsbGJhY2soKTtcbiAgICBcbiAgICBjb25zb2xlLmxvZyh0aGlzLmN1c3RvbVRoZW1lKTtcbiAgICAvLyBPdmVycmlkaW5nIHRoZSBzdHlsZXMgd2l0aCBhbiBleHRlcm5hbCB0aGVtZSBzcGVjaWZpZWQgYnkgdGhlIHVzZXJcbiAgICBpZiAodGhpcy5jdXN0b21UaGVtZSkgSGVsbG9Xb3JsZC5zdHlsZXMgPSBbdGhpcy5jdXN0b21UaGVtZV07XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8gV29ybGQ8L3A-YDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL2hlbGxvLXdvcmxkLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPGhlbGxvLXdvcmxkIGN1c3RvbS10aGVtZT0ne1wicHJpbWFyeVwiOiBcIm9yYW5nZVwifSc-PC9oZWxsby13b3JsZD5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0).

I think part of the problem is that I just can't seem to change the stylesheet part of components (`static styles`) during runtime, only at compile (transpile) time.

Lit Component:

```typescript
import {html, css, unsafeCSS, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';

type Color = string;
interface CustomTheme {
  primary: Color;
}

const customTheme = {
  primary: "orange"
}
    
function themeToLitCss(theme: CustomTheme) {
  return css`
    p {
      color: ${unsafeCSS(theme.primary)}
    }
  `
}

@customElement('hello-world')
export class HelloWorld extends LitElement {
  static styles = [];

  @property({
  attribute: 'custom-theme',
  converter: (attrValue: string | undefined) =>
    attrValue ? JSON.parse(attrValue) : undefined,
  })
  customTheme?: CustomTheme;
  
  override connectedCallback() {
    super.connectedCallback();
    
    // Overriding the styles with an external theme specified by the user
    if (this.customTheme) HelloWorld.styles = [this.customTheme];
  }

  render() {
    return html`<p>Hello World</p>`;
  }
}
```

The HTML would look like this:

```html
<hello-world custom-theme='{"primary": "orange"}'></hello-world>
```

### Alternatives and Workarounds

The current workarounds are:

- `styleMap`
- `classMap`
- [regular CSS custom properties](https://lit.dev/docs/components/styles/#customprops).

**Comment by justinfagnani** [comment]
`static styles` are always applied for the entire class. Dynamically setting them would not apply to existing element instances, but would apply to _all_ future element instances.

If you want something custom per-instance, you need to use a `<style>` tag or one of the other workarounds you mention.

```ts
  render() {
    return html`
      <style>
        p {
          color: ${this.customTheme?.primary ?? 'inherit'}
        }
      </style>
      <p>Hello World</p>`;
  }
```

**Comment by psygo** [comment]
Hi @justinfagnani, it just so happens that I *do* want to apply on every instance of a class.

**Comment by justinfagnani** [comment]
But you theme is set as an instance property. Do you want the last instance to get a theme set to effect every other instance no matter what their theme was?

Also modifying the static styles won't do that, since existing instances will have already had their styles set.

If you want a global theme switch to effect all instances, then you also need a way to notify all instances on changes. I would use something like context for that.

**Comment by psygo** [comment]
@justinfagnani, thank you very much for your comments! After clearing my head a bit, I think the `<style></style>` solution you proposed pretty much fills all of my requirements. (I do think that having something like what I had sketched for `static styles` natively on Lit would be a nice feature though.)

Here's the adapted example with it:

```typescript
import {html, css, unsafeCSS, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';

type Color = string;
interface CustomTheme {
  primary: Color;
}
    
function themeToLitCss(theme: CustomTheme) {
  return css`
     p {
       color: ${unsafeCSS(theme.primary)}
     }
  `
}

@customElement('hello-world')
export class HelloWorld extends LitElement {
  static styles = [];

  @property({
  attribute: 'custom-theme',
  converter: (attrValue: string | undefined) =>
    attrValue ? JSON.parse(attrValue) : undefined,
  })
  customTheme?: CustomTheme;

  render() {
    return html`
      <style>
        ${themeToLitCss(this.customTheme)}
      </style>
        
      <p>Hello World</p>
    `;
  }
}
```

It works on a per instance basis indeed:

```html
<hello-world custom-theme='{"primary": "orange"}'></hello-world>
<hello-world custom-theme='{"primary": "red"}'></hello-world>
```

> [Here is the link to it on Lit's playground](https://lit.dev/playground/#project=W3sibmFtZSI6ImhlbGxvLXdvcmxkLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCB1bnNhZmVDU1MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5cbnR5cGUgQ29sb3IgPSBzdHJpbmc7XG5pbnRlcmZhY2UgQ3VzdG9tVGhlbWUge1xuICBwcmltYXJ5OiBDb2xvcjtcbn1cbiAgICBcbmZ1bmN0aW9uIHRoZW1lVG9MaXRDc3ModGhlbWU6IEN1c3RvbVRoZW1lKSB7XG4gIHJldHVybiBjc3NgXG4gICAgIHAge1xuICAgICAgIGNvbG9yOiAke3Vuc2FmZUNTUyh0aGVtZS5wcmltYXJ5KX1cbiAgICAgfVxuICBgXG59XG5cbkBjdXN0b21FbGVtZW50KCdoZWxsby13b3JsZCcpXG5leHBvcnQgY2xhc3MgSGVsbG9Xb3JsZCBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gW107XG5cbiAgQHByb3BlcnR5KHtcbiAgYXR0cmlidXRlOiAnY3VzdG9tLXRoZW1lJyxcbiAgY29udmVydGVyOiAoYXR0clZhbHVlOiBzdHJpbmcgfCB1bmRlZmluZWQpID0-XG4gICAgYXR0clZhbHVlID8gSlNPTi5wYXJzZShhdHRyVmFsdWUpIDogdW5kZWZpbmVkLFxuICB9KVxuICBjdXN0b21UaGVtZT86IEN1c3RvbVRoZW1lO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxzdHlsZT5cbiAgICAgICAgJHt0aGVtZVRvTGl0Q3NzKHRoaXMuY3VzdG9tVGhlbWUpfVxuICAgICAgPC9zdHlsZT5cbiAgICAgICAgXG4gICAgICA8cD5IZWxsbyBXb3JsZDwvcD5cbiAgICBgO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vaGVsbG8td29ybGQuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8aGVsbG8td29ybGQgY3VzdG9tLXRoZW1lPSd7XCJwcmltYXJ5XCI6IFwib3JhbmdlXCJ9Jz48L2hlbGxvLXdvcmxkPlxuICA8aGVsbG8td29ybGQgY3VzdG9tLXRoZW1lPSd7XCJwcmltYXJ5XCI6IFwicmVkXCJ9Jz48L2hlbGxvLXdvcmxkPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ).

Would you like to use this to post an answer on StackOverflow and gain some points?

**Comment by justinfagnani** [comment]
Oh, I don't care much about the points. Thanks for copying this over!
