### ISSUE TITLE
[labs/ssr] generates wrong path for import.meta.url assets

### ISSUE THREAD

**Issue by LasseRosenow** [lit/lit#3757]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

When I call litServerSideRender() on a component that uses:
```typescript
const litLogo = new URL("./assets//lit-ea869eb0.svg", import.meta.url).href;
```
I get this file path as a result:
`file:///C:/Users/Lasse/Desktop/lit-ssr/dist/server/assets/lit-ea869eb0.svg`
but this file is hosted on a server, so what I would expect is to get:
`./assets/lit-ea869eb0.svg

### Reproduction

1. git clone git@github.com:LasseRosenow/lit-ssr-bug.git
2. cd lit-ssr-bug
3. npm install
4. npm run build
5. npm run serve
6. The rendered html with the incorrect path should be printed to the console.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 3.1.0

### Browser/OS/Node environment

Browser: Chrome 111
OS: Windows 11
Node.js: 19.0
npm: 8.19

**Comment by LasseRosenow** [comment]
> This is just the behavior of `URL`. You're grabbing the `.href` which in Node will be the file url. If you know what the relative path to your asset should be from the server, I would just add that as a string. There's no way during SSR to know what the actual base URL would be to construct the full URL.

The problem is, that bundlers like rollup need to somehow be able to find the assets that I reference in my code and copy them and change their name to some hash value, so they are not cached.

The modern-web page recommends me to use the import.meta.url thing for that, which works super fine without SSR in the browser as the browser would not make the whole file path of it, but use the given local path.
The problem is that ssr is executed in the node.js context and thus as you said would use the full file path. And ssr needs to convert it to something that doesn't have javascript so, I see this is what must happen :(

But still I need some way to make both requirements work.
I need a way for rollup to find the assets that I use in my code, but I also need to somehow SSR not make it some filepath because I use "import.meta.url" for it.

Is there maybe some way to tell node.js to behave like a browser and specify its root path, so it could translate it to some relative path instead?

**Comment by LasseRosenow** [comment]
I have also tried alternative approaches like `@flemist/rollup-plugin-import-assets` which allows me this syntax:

```typescript
import profilePicture from './img/photo.jpg';
```

But this plugin does not work with `@web/dev-server` whereas the `import.meta.url` approach works with `@web/dev-server` and also feels more correct as it just works in the browser and is no `custom syntax that would not work without bundling`

**Comment by justinfagnani** [comment]
In order to translate a filesystem absolute path to a site path, you'll need at least one, possibly two, root parameters. One root is the project root on disk, and you need to calculate a relative path from the module to that. The other is the mount root of the app on your domain, which you need to add to that relative path.

You can probably use [`isServer`](https://lit.dev/docs/ssr/authoring/#browser-only-code) to use Node APIs to calculate this on the server, though you would need to import Node libraries in dynamic imports inside that.

If we saw something work, maybe we could add a utility to SSR.
