### ISSUE TITLE
[all] Lit 3.0 prereleases

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3774]
I think this is a list of what we need to do to make the first 3.0 pre-releases:

- [x] Release webcomponents polyfills with `toggleAttribute()` support
- [x] Update and merge `toggleAttribute()` PR: https://github.com/lit/lit/pull/3750
- [x] Merge move of hydration files into `main`: https://github.com/lit/lit/pull/3720
- [x] Delete old hydration files in `3.0` (@augustjk)
- [x] Merge `main` branch into `3.0`
- [x] Update TypeScript output target to ES2021: https://github.com/lit/lit/pull/3775
- [x] Update lit, lit-element, lit-html, reactive-element READMEs with temporary upgrade section (no API changes, IE is dead, hydration files moved)
- [x] (optional for pre-release) Add v3 docs to lit.dev
- [x] optional for pre-release) Update Tooling & Workflows in v3 docs
- [x] Announce the prerelease on Discord and Twitter

cc @rictic @augustjk @bicknellr

**Comment by bicknellr** [comment]
I just published the polyfills: https://github.com/webcomponents/polyfills/commit/90cb97f847ce918289dac0978c50dcda0a0afd72

**Comment by augustjk** [comment]
Can we add https://github.com/lit/lit/pull/3693 to 3.0?

**Comment by justinfagnani** [comment]
@augustjk yeah, that's a great call.
