### ISSUE TITLE
[all] Size regression when emitting ES2021

### ISSUE THREAD

**Issue by rictic** [lit/lit#3777]
In #3775 we're advancing our output to ES2021, but we're seeing a size regression in our built output.

We're probably going to move forward for now with ES2021 in the pre-releases, just to get early signal about whether that breaks anything, but before we launch we need to reevaluate this because it's probably not worth it to advance the language version at the cost of size.

**Comment by justinfagnani** [comment]
We published ES2019 in 2021. Publishing ES2021 in 2023 is pretty in line with that.

We're somewhat more aggressive here than other libraries, but this matches our past language support going back to lit-html 1.0 and Polymer 3.0. ES2021 has excellent support across browsers. Logical assignment support goes back to Chrome 85 / Firefox 79 / Safari 14. Nullish coalescing (ES2020) goes to 80 / 71 / 13.1. And all syntax is compilable to older language levels without polyfills for applications that need to do that.

**Comment by rictic** [comment]
Steve tracked this down, dead code elimination of the debugEventLog statements wasn't triggering, I guess the version of terser we're using can't dead code eliminate code like:

```typescript
const foo = undefined;
foo?.();
```

**Comment by rictic** [comment]
With that fixed, lit-html.js minifies down to 7,220B, down from a bit over eight thousand

**Comment by rictic** [comment]
This is fixed
