### ISSUE TITLE
[labs/router] Make router work in SSR

### ISSUE THREAD

**Issue by LasseRosenow** [lit/lit#3786]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

If I use the `@lit-labs/router` module in SSR, I get the following error:

```
ReferenceError: location is not defined
    at file:///C:/Users/Lasse/Desktop/Cedgetec/Websites/urspruenglich-unverpackt/node_modules/@lit-labs/router/router.js:7:9
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### Alternatives and Workarounds

There is not workaround, except not using `@lit-labs/ssr` for SSR.

**Comment by justinfagnani** [comment]
The way we've been using the router with SSR is to set `globalThis.location` to the request URL, similar to this: https://github.com/webcomponents/webcomponents.org/blob/5bf9c8c97f3acbf2c0faa24c5993a3c831d53043/packages/site-server/src/lib/catalog/routes/element/element-route.ts#L133
