### ISSUE TITLE
customElement decorator causes DOM exception when accidentally executed twice

### ISSUE THREAD

**Issue by tronicboy1** [lit/lit#3794]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When using the `@customElement('my-wc')`, I occasionally get DOM exceptions like as follows:

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "litwc-hello-world" has already been used with this registry
    at target.
```

Obviously, this is because I am importing and running the script twice somewhere. However it would be nice to have `customElement` check if it is defined before attempting to re-define it in the registry.

It would be quite simple to implement so I will attempt to make a PR.

### Reproduction

```html
<script type="module" src="my-wc.js"></script>
<!-- Accidentally include the same script twice --!>
<script type="module" src="my-wc.js"></script>
```

### Workaround

No workaround yet. We could change the implementation to check if the `MyWc` tag is registered before defining.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.7.2

### Browser/OS/Node environment

Browser: Chrome Version 111.0.5563.146 (Official Build) (arm64)
OS: Mac OS

**Comment by rosofo** [comment]
This seem to be hitting this while using Vite's dynamic import features.

**Comment by augustjk** [comment]
There's more discussion in the linked PR but, as it stands, I think we consider this working as intended.

I would like to point out that the reproduction code actually shouldn't cause an issue as duplicate imports of the same module should actually deduplicate, and not execute twice.

This would become an issue if different modules had the same element registration, like multiple entrypoints that happened to bundle the same component. Or sometimes in cases of dev tools trying to hot module reload, causing the modified code with the same component registration to run without the global registry being cleared.

**Comment by tronicboy1** [comment]
Thanks all for the consideration and help!

@augustjk 
I didn’t know that about esm, thanks for pointing that out!
