### ISSUE TITLE
[labs/virtualizer] Masonry: size and range bugs when the last item placed isn't the one extending the furthest

### ISSUE THREAD

**Issue by graynorton** [lit/lit#3815]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

When calculating virtualizer size and range, the masonry layout currently assumes that the item placed last is the one that extends furthest along the block axis. This is not always the case, which means that the virtualizer is sometimes not sized properly and the range is not always calculated correctly.

### Reproduction

Sizing issue: https://lit.dev/playground/#gist=ff60a155695034225bf49d2d9042e97a
Range issue: https://lit.dev/playground/#gist=d8e9639ad3e68cba0a928783594c1fbb

### Workaround

It's probably possible to engineer a hack to work around the sizing issue, but there is no obvious workaround for the range issue.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 2.0.0

### Browser/OS/Node environment

N/A

**Comment by graynorton** [comment]
An additional failure case was just reported. New repro is here:

https://lit.dev/playground/#gist=e7242c15fd81d6a881dd2297290f8255

**Comment by augustjk** [comment]
Fixed with https://github.com/lit/lit/pull/4355
