### ISSUE TITLE
[labs/eleventy-plugin-lit] Change eleventy-plugin-lit example HTML to show content if JS is disabled

### ISSUE THREAD

**Issue by alexgagnon** [lit/lit#3817]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Eleventy Plugin (@lit-labs/eleventy-plugin-lit)

### Description

The current example HTML default layout for @lit-labs/eleventy-plugin-lit has the following code:

```html
  <body dsd-pending>
    <script>
      if (HTMLTemplateElement.prototype.hasOwnProperty('shadowRoot')) {
        // This browser has native declarative shadow DOM support, so we can
        // allow painting immediately.
        document.body.removeAttribute('dsd-pending');
      }
    </script>

```

However when JS is disabled this means the body remains hidden. What about changing the example to the following?

```html
  <body>
    <script>
      if (!HTMLTemplateElement.prototype.hasOwnProperty('shadowRoot')) {
        // This browser does not have native declarative shadow DOM support, so we hide
        // the body until the template-shadowroot polyfill has executed
        document.body.setAttribute('dsd-pending');
      }
    </script>
```

That way at least some content will be displayed even when JS is disabled.

### Alternatives and Workarounds

Can just do it yourself in your own project.

**Comment by augustjk** [comment]
Somewhat related https://github.com/lit/lit/issues/2490

I think this is a good idea. It's only an example so it's lower in priority.

PRs welcome!

**Comment by augustjk** [comment]
@alexgagnon Thank you for the PR. I'm having second thoughts here.

For browsers that do support DSD and have JS disabled, I think this makes sense as you would get content. But I wonder what the experience for browsers that do not support DSD and also have JS disabled would be. It would have all the custom elements without shadowroots attached, so any light DOM children would be visible, unstyled, and not projected to slots. Is this acceptable?

I suppose ultimately this README is one example, and it would be up to the user to choose what outcome they want to optimize for.

**Comment by alexgagnon** [comment]
Agreed, the whole thing came up when I was playing around with it in Firefox and ended up with a blank page. I have no strong opinion either way, as you say it's just an example

**Comment by augustjk** [comment]
Still, thanks for bringing this up and hope I didn't make you waste too much time.
