### ISSUE TITLE
All decorators failing

### ISSUE THREAD

**Issue by Craig-Fisk** [lit/lit#3821]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I'm attempting to setup a new web component library project and it is falling over at the first hurdle. 

I've tried this inside an existing typescript project and in a standalone new repository and am getting the same results.

I'm trying to use some of the example code from the documentation website to set up a demo component:
```typescript
import { LitElement, css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('name-tag')
class NameTag extends LitElement {
  @property()
    name?: string;

  render() {
    return html`Hello I'm ${this.name}.`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'name-tag': NameTag
  }
}

```
and I am receiving errors in VS Code whilst editing for both the decorators:
```
Unable to resolve signature of class decorator when called as an expression.
  The runtime will invoke the decorator with 2 arguments, but the decorator expects 1.
```

I have tried the suggestions i've seen from a while ago to add the following property to `tsconfig` but that has made no difference.
```json
"useDefineForClassFields": false
```

### Reproduction

Package.json
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lit": "^2.7.2",
    "tslib": "^2.5.0",
    "typescript": "^5.0.4"
  }
}

```

tsconfig.json
```json
{
    "compilerOptions": {
        "useDefineForClassFields": false,
    }
}
```

component.ts
```typescript
import { LitElement, css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('name-tag')
class NameTag extends LitElement {
  @property()
    name?: string;

  render() {
    return html`Hello I'm ${this.name}.`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'name-tag': NameTag
  }
}

```

### Workaround

I have not found a workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing 2.7.2

### Browser/OS/Node environment

Node version 16.17.1
NPM version 8.15.0

VS Code
Version: 1.77.0 (Universal)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T09:57:11.797Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

**Comment by Craig-Fisk** [comment]
Solved my own issue, I was missing the following option in tsconfig:
```json
"experimentalDecorators": true
```

**Comment by rwalle** [comment]
I don't think it is the correct workaround or this should be closed -- if you look at recent updates regarding TypeScript v5, they are now supporting [a different decorator model](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#differences-with-experimental-legacy-decorators) by default which is not compatible with `experimentalDecorators`. The new model will be how decorators work going forward, which means that the source code of lit should be updated to accommodate this change.

**Comment by p-ob** [comment]
> I don't think it is the correct workaround or this should be closed -- if you look at recent updates regarding TypeScript v5, they are now supporting [a different decorator model](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#differences-with-experimental-legacy-decorators) by default which is not compatible with `experimentalDecorators`. The new model will be how decorators work going forward, which means that the source code of lit should be updated to accommodate this change.

I believe there's an issue to track this as they're waiting for browser vendors to ship the freshly standardized decorators proposal that TSv5 implemented.
