### ISSUE TITLE
[labs/ssr-react] Handling of children in props

### ISSUE THREAD

**Issue by augustjk** [lit/lit#3823]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

When monkey-patching `React.createElement` we assume proper usage of the function such that `children` are presented as extra argument(s) after the prop, rather than as a property within the props object. https://react.dev/reference/react/createElement#createelement

The original `createElement` behavior is to use `props.children` but override it with the extra arguments if present.
https://github.com/facebook/react/blob/v17.0.2/packages/react/src/ReactElement.js#L386

So in effect, providing `props.children` is actually valid unless there are extra arguments after props. Since during SSR we always create the extra arg for the template shadowroot, we end up swallowing any children prop that's provided.

This has been happening for any `@lit-labs/react` wrapped package, or `styled-components` usage, as these pass through children as `props.children`.

### Reproduction

See repro and description: https://github.com/lit/lit/issues/3418#issuecomment-1515939084

### Workaround

We'll need to check for the presence of props.children and carry it over.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.1.1

### Browser/OS/Node environment

N/A

**Comment by raoufswe** [comment]
Hi @augustjk, I'm not sure if the following is related, but I've just come across a rehydration miss match issue on Next.js when a component uses `<slot></slot>` and is wrapped by the React wrapper. 

I initially thought it was an issue with our setup, but I managed to reproduce it in [example/next](https://github.com/lit/lit/tree/main/examples/nextjs) as well by adding `<slot>`  to the `SimpleGreeter` component and then passing children to the react wrapper.
