### ISSUE TITLE
Cannot read properties of null (reading 'nodeType')

### ISSUE THREAD

**Issue by Flrande** [lit/lit#3839]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

We are developing a [rich text editor](https://github.com/toeverything/blocksuite) using Lit, which supports [AFFiNE](https://github.com/toeverything/AFFiNE). However, there is a probability that such an error will occur when updating the state with IME.

![image](https://user-images.githubusercontent.com/50035259/234173988-56121b42-4ec8-4cc6-b358-25200aae99f5.png)

https://user-images.githubusercontent.com/50035259/234176267-bae5f302-3665-4ec3-ab59-393b09f4289c.mp4

I'm not sure if something is missing in lit-html, like adding `parent !== null`.

https://github.com/lit/lit/blob/main/packages/lit-html/src/lit-html.ts#L1317-L1318

### Reproduction

You can test it in https://blocksuite-toeverything.vercel.app/?init=empty

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.6.1

### Browser/OS/Node environment

All environments will appear.

**Comment by Flrande** [comment]
I upgrade to 2.7 and it said that we can not set `textContent`. But as an editor we need to modify the Text Node directly under certain boundary conditions, is there an alternative way?

**Comment by Flrande** [comment]
The reason we want to modify the textContent directly is that in the case of IME, the browser will change the dom node directly, and this change will not be tracked by lit, even if I re-call the `requestUpdate` of the corresponding component to remove the characters added by IME.

**Comment by Flrande** [comment]
related to https://github.com/lit/lit/issues/3611

**Comment by Flrande** [comment]
When I cancel the IME with ESC there is a chance that the comment node will disappear and thus cause the rendering to fail, I am not sure what is happening, this works fine in the non-line-header case.

https://user-images.githubusercontent.com/50035259/234282496-86b0c778-abea-411b-aac2-1889e0af0025.mp4

**Comment by augustjk** [comment]
Hard to say exactly without seeing the code but it sounds like you may need some property property binding on `.innerText` (see https://lit.dev/docs/templates/expressions/#invalid-locations) possibly with the `live()` directive (https://lit.dev/docs/templates/directives/#live) if something else is modifying it.

**Comment by Flrande** [comment]
> It looks like you're trying to edit the DOM created by Lit - that's not supported. Editing the DOM can break the markers that Lit uses to track bindings.

I found that even though I didn't change the dom node directly, I still got the error.

**Comment by Flrande** [comment]
> I found that even though I didn't change the dom node directly, I still got the error.

https://user-images.githubusercontent.com/50035259/234437428-9e20a7cf-48f1-4826-8ef3-ed41df1fd30c.mp4
