### ISSUE TITLE
Scroll issue in Firefox with inner components and display:none CSS

### ISSUE THREAD

**Issue by jgreffe** [lit/lit#3867]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

With Firefox, using two divs, one displayed and the other one hidden through components, scroll is replicated through divs, which is unexpected.

### Reproduction

[lit playground reproduction](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgc3RhdGUsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQge3JhbmdlfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9yYW5nZS5qcyc7XG5pbXBvcnQge21hcH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvbWFwLmpzJztcblxuaW1wb3J0ICcuL215LXZpZXcuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgI2ZpcnN0IHtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogYmx1ZTtcbiAgICAgIH1cblxuICAgICAgI3NlY29uZCB7XG4gICAgICAgIGJhY2tncm91bmQtY29sb3I6IGdyZWVuO1xuICAgICAgfVxuICAgICBcbiAgICAgIC5jb250ZW50IHtcbiAgICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgICBoZWlnaHQ6IDIwMHB4O1xuICAgICAgICBvdmVyZmxvdy15OiBhdXRvO1xuICAgICAgfVxuXG4gICAgICAuaGlkZGVuIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgICB9XG4gICAgICBgO1xuICBcbiAgQHN0YXRlKCkgZGlzcGxheWVkID0gdHJ1ZTtcbiAgXG4gIHRvZ2dsZSgpIHtcbiAgICB0aGlzLmRpc3BsYXllZCA9ICF0aGlzLmRpc3BsYXllZDtcbiAgfTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxwPlxuICAgICAgICA8dWw-XG4gICAgICAgIDxsaT5zY3JvbGwgYm90aCBibHVlICYgb3JhbmdlIGRpdnMgdG8gYm90dG9tIGFuZCBjbGljayB0b2dnbGU8L2xpPlxuICAgICAgICA8bGk-aW4gQ2hyb21lLCBTYWZhcmkgJiBFZGdlXG4gICAgICAgICAgPHVsPlxuICAgICAgICAgICAgPGxpPmdyZWVuICYgcmVkIGRpdnMgYXJlIHN0aWxsIGF0IHRoZSB0b3A6IGV4cGVjdGVkPC9saT5cbiAgICAgICAgICA8L3VsPlxuICAgICAgICA8L2xpPlxuICAgICAgICA8bGk-aW4gRmlyZWZveDpcbiAgICAgICAgICA8dWw-XG4gICAgICAgICAgICA8bGk-Z3JlZW4gZGl2IGlzIGF0IHRoZSB0b3A6IGV4cGVjdGVkPC9saT5cbiAgICAgICAgICAgIDxsaT5yZWQgZGl2IGlzIGF0IHRoZSBib3R0b206IHVuZXhwZWN0ZWQ8L2xpPlxuICAgICAgICAgIDwvdWw-XG4gICAgICAgIDwvbGk-XG4gICAgICAgIDwvdWw-XG4gICAgICAgIDwvcD5cbiAgICAgICAgXG4gICAgICAgIDxkaXYgaWQ9XCJmaXJzdFwiIGNsYXNzPVwiY29udGVudCAke3RoaXMuZGlzcGxheWVkID8gJyc6ICdoaWRkZW4nfVwiPlxuICAgICAgICAgICAgJHttYXAocmFuZ2UoMjApLCAoaSkgPT4gaHRtbGA8cD50ZXN0ICR7aSArIDF9IGZpcnN0PC9wPmApfVxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBpZD1cInNlY29uZFwiIGNsYXNzPVwiY29udGVudCAke3RoaXMuZGlzcGxheWVkID8gJ2hpZGRlbic6ICcnfVwiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb250ZW50XCI-XG4gICAgICAgICAgICAke21hcChyYW5nZSgyMCksIChpKSA9PiBodG1sYDxwPnRlc3QgJHtpICsgMX0gc2Vjb25kPC9wPmApfVxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgXG4gICAgICAgIDxteS12aWV3IG5hbWU9XCJ0aGlyZFwiID9kaXNwbGF5ZWQ9JHt0aGlzLmRpc3BsYXllZH0-PC9teS12aWV3PlxuICAgICAgICA8bXktdmlldyBuYW1lPVwiZm91cnRoXCIgP2Rpc3BsYXllZD0keyF0aGlzLmRpc3BsYXllZH0-PC9teS12aWV3PlxuICAgICAgICBcbiAgICAgICAgXG4gICAgICAgIDxidXR0b24gaWQ9XCJ0b2dnbGVcIiBAY2xpY2s9JHt0aGlzLnRvZ2dsZX0-XG4gICAgICAgICB0b2dnbGVcbiAgICAgICAgPC9idXR0b24-ICAgICAgICBcbiAgICAgICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3NpbXBsZS1ncmVldGluZy5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX0seyJuYW1lIjoibXktdmlldy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgc3RhdGUsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQge3JhbmdlfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9yYW5nZS5qcyc7XG5pbXBvcnQge21hcH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvbWFwLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ215LXZpZXcnKVxuZXhwb3J0IGNsYXNzIE15VmlldyBleHRlbmRzIExpdEVsZW1lbnQge1xuXG5zdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgI3RoaXJkIHtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogb3JhbmdlO1xuICAgICAgfVxuXG4gICAgICAjZm91cnRoIHtcbiAgICAgICAgYmFja2dyb3VuZC1jb2xvcjogcmVkO1xuICAgICAgfVxuICAgIFxuICAgICAgI3RoaXJkLCAjZm91cnRoIHtcbiAgICAgICAgbWFyZ2luLXRvcDogMmVtO1xuICAgICAgfVxuXG4gICAgICAuY29udGVudCB7XG4gICAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgICAgb3ZlcmZsb3cteTogYXV0bztcbiAgICAgICAgaGVpZ2h0OiAyMDBweDtcbiAgICAgIH1cblxuICAgICAgLmhpZGRlbiB7XG4gICAgICAgIGRpc3BsYXk6IG5vbmU7XG4gICAgICAgfVxuICAgICAgYDtcbiAgQHByb3BlcnR5KHt0eXBlOiBTdHJpbmd9KSBuYW1lO1xuICBAcHJvcGVydHkoe3R5cGU6IEJvb2xlYW59KSBkaXNwbGF5ZWQ7XG5cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8ZGl2IGlkPVwiJHt0aGlzLm5hbWV9XCIgY2xhc3M9XCJjb250ZW50ICR7dGhpcy5kaXNwbGF5ZWQgPyAnJzogJ2hpZGRlbid9XCI-XG4gICAgICAgICAgICAke21hcChyYW5nZSgyMCksIChpKSA9PiBodG1sYDxwPnRlc3QgJHtpICsgMX0gJHt0aGlzLm5hbWV9PC9wPmApfVxuICAgICAgICA8L2Rpdj5cbiAgICAgIGA7XG4gIH1cbn0ifV0)

[JSFiddle with shadow root](https://jsfiddle.net/jgreffe/d2b49k6u/), reproduced also, so not related to lit.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

From playground

### Browser/OS/Node environment

Browser: Firefox 112.0.2
MacOS: Ventura 13.3.1

**Comment by justinfagnani** [comment]
Is this a Firefox bug?

**Comment by jgreffe** [comment]
It's tied to lit sub-components with Firefox. Using direct HTML works, please see playground.

**Comment by jgreffe** [comment]
Tried the same behavior with **vue**, see [this playground](https://play.vuejs.org/#eNrNVMGO0zAQ/ZXZ7GFB2rQrjiFbAScOcELilIsbTxNrXdtyJu1WUf6dsZ20BbUFISFRVe14xn7z4nkvQ/bRucWux6zIyrs8r8xn9Ah7hK61e6CWA7V1GjsCZ7tOrTVCbbfOGjQE+1bVLYi6RkcdCHDeOhBGgkcj0XegaFGZLyi8ga1lYLG2PZ0AeIOJTZpeSbyrTJ6vKlOZsqu9csQxN7ee4Ovhu8I9bLzdwsNimZaB90PYjq9xk8SN6DXBUBk461GkBEwgIR4fw68UJN68naseqWea04qrqnNaHFAWQL7HlB7j6crwt1weSfKCkG9JEPIKoLQ6/gOk31KqHSj5XGUb5TuqMqi16Dpe19YQc+RMMacGaJWUaAq4O1IYq2w1YznY5RvreacJt/fuiWsU5jMMYGAcIfYoly5RWXLvK2Q65PbyT9n8HZnU4zqbCec0mvAxYosMSa3yTG/OFkcGXDvGc31VTqqY4C9Dbmzvqb2Cebrva6AT9LonsgY+1FrVL+dk4PlsaHwVcxuyTaMnCZXLdHy6kCiVcnmmnyB/OugQLqaJzJLW1hfBdITvQ8Lu0G+03eeHAkRPNiZbVE1LBc/iyb1yhqW6SDNMKBO/AgzbI9XTg91H4ZwMALAW9UvjbW9kPvVe6z61nswwh/dpzrcPNx7RnJ9mC8UHzR6zk6PDm+jorEvODi+Zk6nDYAv4Rl6ZJrr6J+d+slajiDR/79pgjCI6I4D+Y5cOQ2gyjr9a4/+QQrTe7WlaL0xzWQzJZbePe5QXpTD+AOhFKW8=), and all works, even with firefox.

I think issue is with lit nested component and firefox. Not firefox itself (?)

**Comment by justinfagnani** [comment]
Did you also use shadow DOM with Vue?

**Comment by jgreffe** [comment]
Tried with a JSFiddle with shadow dom, and I can reproduce the issue without lit.
Opened this Mozilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1856571
