### ISSUE TITLE
[labs/ssr-react] Light DOM is stripped from SSR rendered React Wrappers in NextJS

### ISSUE THREAD

**Issue by kevin-coyle** [lit/lit#3876]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

Stackblitz Reference: https://stackblitz.com/edit/nextjs-goebkm?file=pages/index.js

We are having some trouble implementing SSR with NextJS and the React wrappers. When we use the components on their own we can see the SSR rendered component complete with declarative shadow dom and respective light dom. 

However, when we use the react wrapper we still get the server side rendered component but the light dom is stripped out.

I have added a stackblitz link which demonstrates this.

### Reproduction

Please take a look at this stackblitz link https://stackblitz.com/edit/nextjs-goebkm?file=pages/index.js

Then view source of the rendered output and you will see that the lightdom markup is present for the Lit only implementation but not present for the react implementation

### Workaround

I can not figure out a workaround for this other than to not use the react wrappers for SSR.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.7.3

### Browser/OS/Node environment

Browser: Chome 113
Node Version: 16+

**Comment by augustjk** [comment]
Thanks for the report! This is related to https://github.com/lit/lit/issues/3823.
The fix has just been released. Updating deps in the stackblitz example (I deleted `package-lock.json` and npm installed) fixes the issue.

**Comment by kevin-coyle** [comment]
Thanks you rock!
