### ISSUE TITLE
Docs "createRenderRoot" example doesn't work

### ISSUE THREAD

**Issue by miketests** [lit/lit#3881]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

There is a `Not Found` output in `createRenderRoot` example in the documentation:
 
https://lit.dev/docs/components/shadow-dom/#implementing-createrenderroot
https://lit.dev/playground/#sample=docs/components/shadowdom/renderroot

<img width="768" alt="lit-element-createRenderRoot-output-bug" src="https://user-images.githubusercontent.com/131380665/236423502-a0c94cf0-a2e7-47f1-b20c-95878b806236.png">

### Reproduction

Go to the links provided and see that there is incorrect output:

https://lit.dev/docs/components/shadow-dom/#implementing-createrenderroot
https://lit.dev/playground/#sample=docs/components/shadowdom/renderroot

<img width="768" alt="lit-element-createRenderRoot-output-bug" src="https://user-images.githubusercontent.com/131380665/236423502-a0c94cf0-a2e7-47f1-b20c-95878b806236.png">

### Workaround

No workaround found

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Latest

### Browser/OS/Node environment

Safari 15.6.1

**Comment by justinfagnani** [comment]
I think the playground service worker must be misbehaving. Can you shift-reload, or failing that, clear the service worker?This method should work: https://jun711.github.io/web/how-to-force-update-a-service-worker-on-chrome-firefox-and-safari/#safari
