### ISSUE TITLE
[labs] Import minify-html-literals into the monorepo

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#3900]
This utility is important to a lot of build chain setups. @asyncliz hasn't had much time to main these and they fit well with some of our developing tools like the CLI, template compiler, and analyzer.

There are two main packages:
- https://github.com/asyncLiz/minify-html-literals
- https://github.com/asyncLiz/parse-literals

We might want those brought in as a single package, or a common utility in the analyzer for parsing templates.

**Comment by augustjk** [comment]
Completed in https://github.com/lit/lit/pull/4044

**Comment by fernandopasik** [comment]
Any chance this will be published soon @bencbradshaw ?
