### ISSUE TITLE
Issue with uncaught exceptions thrown when a task function rejects/throws an error

### ISSUE THREAD

**Issue by rstoneIDBS** [lit/lit#3946]
### Which package(s) are affected?

Task (@lit-labs/task)

### Description

See this discord thread for a full description:
https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582
@justinfagnani mentioned towards the bottom that an issue was going to be raised but I couldn't find anything so am raising it now as I have just run into this problem and currently the only solution is a little ugly namely manually adding a do nothing catch to 'taskComplete' to stop the error propogating.

### Reproduction

See https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582

### Workaround

See https://discord.com/channels/1012791295170859069/1047015641225371718/threads/1075045145596137582

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.1.1

### Browser/OS/Node environment

N/A

**Comment by e111077** [comment]
Solution in the process of being submitted will not throw unless you access `Task.prototype.taskComplete` and do not add a `.catch()` to the end of that `taskComplete` promise.
