### ISSUE TITLE
Two new modules, one for template, one for variables

### ISSUE THREAD

**Issue by R3D-CODE** [lit/lit#3951]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

It would be better if Lit has two new modules, one for template, the other for variables

### Alternatives and Workarounds

1. In template module, everything related to template would be exist
Some parts from css from Reactive-Element, some html/svg parts from Lit-html, ... all would be moved into template
```ts
const HTML_STRING = 1;
const SVG_STRING = 2;
const CSS_STRING = 3;

export type StringType = typeof HTML_STRING | typeof SVG_STRING | typeof CSS_STRING;
```
2. In variables part, everything related to attributes and properties would be moved into this module
Some from Reactive-Element, some from  Lit-html, ...
Also, even sanitizer part from html
And would be great if you add more options to `PropertyDeclaration` too
```ts
export type AttributeConverter<Type = unknown, TypeHint = unknown> =
  | {
      toAttribute?(value: Type, type?: TypeHint): unknown;
      fromAttribute?(value: string | null, type?: TypeHint): Type;
    }
  | ((value: string | null, type?: TypeHint) => Type); 
 
export interface PropertyDeclaration<Type = unknown, TypeHint = unknown> {
  readonly name: PropertyKey;
  readonly type: TypeHint;
  readonly converter?: AttributeConverter<Type, TypeHint>;
  readonly state?: boolean | string;
  readonly attribute?: boolean | string;
  readonly default?:  boolean | string;
  readonly reflect?: boolean;
  readonly validate?: PropertyValidator<Type>;
  readonly sanitize?: PropertySanitizer<Type>;
  readonly serialize?: PropertySerializer<Type>;
  readonly deserialize?: PropertyDeserializer<Type>;
  hasChanged?(value: Type, oldValue: Type): boolean; 
  readonly noAccessor?: boolean; 
```
3. Some improvements in compiler would be great too
```ts
export const defaultConverter: AttributeConverter = {
  toAttribute(value: unknown, type?: unknown): string | null {

    let toValue: unknown = value;

    if (value === null || value === undefined ||  value === '') {
      return null;
    }

    switch (type) {
      case Boolean:
        toValue = value ? emptyStringForBooleanAttribute : null;
        break;
      case Number:
      case BigInt:
      case Symbol:
      case Function:
        toValue = value.toString();
        break;
      case Object:
      case Array:
      case Map:
      case Set:
        toValue = JSON.stringify(value);
        break;
      // case Date:
      //   toValue = (value as Date).toISOString();
      //   break;
      default:
        throw new Error(`Can not convert type "${type}" and value "${value}" to attribute`);
    }
    return String(toValue);
  },
  fromAttribute(value: string | null, type?: unknown): unknown {

    let fromValue: unknown = value;

    if (value === null || value === undefined ||  value === '') {
      return null;
    }
    switch (type) {
      case Boolean: 
      fromValue = value !== null;
      break;
      case Number:
        fromValue = Number(value);
        break;
      case Object:
      case Array:
      case Map:
      case Set:
        fromValue = JSON.stringify(value);
        break;
      // case Date:
      //   fromValue = new Date(value);
      //   break;
      default:
        throw new Error(`Can not convert type "${type}" and value "${value}" from attribute`);
    }
    return String(fromValue); 
  },
}
```

**Comment by R3D-CODE** [comment]
I know that your code is stable or is going to be stable, and you don't want change or move some parts of code to new modules
But I think, having separate modules `variable.ts` in `reactive-element` and `template.ts` in `lit-html` won't cause any conflicts, and even will help your packages be more clear, flexible, and modular

Based on my understanding variables(attributes/properties) play an important role in web development, and are really important in dependency tracking before and even after rendering and it'd be better, like css (`css-tag.ts) have their own place
Same for templates in  `lit-html` too

**Comment by VandeurenGlenn** [comment]
@R3D-CODE What is this "dependency tracking" you always talk about? We have package.json and the lock file etc for that, so wondering what you mean.

**Comment by R3D-CODE** [comment]
It's about monitor and react to changes, in "pre-rendering" and/or "post-rendering" stages
Everything is happening in your website is dependency

I mentioned this before:
> I read Preact Signal source
There saw a wrong comment, but they used it because it's easy for many to understand
https://github.com/preactjs/signals/blob/d38fd8acaf7c2817932c1a40da28fa1e80be3e2e/packages/core/src/index.ts#L16
We have dependency tracking, everything is dependency, two dependencies are:
> 1. Upstream dependencies or sources that Preact called them dependencies
> 2. Downstream dependencies or targets that Preact called them dependents
>
> So, the idea is clear, there're sources and targets

**Comment by R3D-CODE** [comment]
Are you familiar with "declaration merging"?
```ts
import { Part1 } from './Part1';
import { Part2 } from './Part2';

export class MyClass implements Part1, Part2 {}
```

**Comment by VandeurenGlenn** [comment]
> It's about monitor and react to changes, in "pre-rendering" and/or "post-rendering" stages Everything is happening in your website is dependency
> 
> I mentioned this before:
> 
> > I read Preact Signal source
> > There saw a wrong comment, but they used it because it's easy for many to understand
> > https://github.com/preactjs/signals/blob/d38fd8acaf7c2817932c1a40da28fa1e80be3e2e/packages/core/src/index.ts#L16
> > We have dependency tracking, everything is dependency, two dependencies are:
> > 
> > 1. Upstream dependencies or sources that Preact called them dependencies
> > 2. Downstream dependencies or targets that Preact called them dependents
> > 
> > So, the idea is clear, there're sources and targets

On a server or on a client ? Also splitting up is a good thing but if you overdo it that would have a negative impact

**Comment by VandeurenGlenn** [comment]
> Are you familiar with "declaration merging"?
> 
> ```ts
> import { Part1 } from './Part1';
> import { Part2 } from './Part2';
> 
> export class MyClass implements Part1, Part2 {}
> ```

What has that todo with this issue?

**Comment by R3D-CODE** [comment]
That way they can have modules that each module focuses at one aspect
`reactive-element.ts` can be divided to three main parts (as I did):
- `data.ts` that focuses on attributes and properties --> around 250 lines of code
- `css.ts` that focuses on css contents --> around 150 lines of code
- `reactive-element.ts` that focuses on initialization and methods/callbacks --> around 200 lines of code
