### ISSUE TITLE
[labs/virtualizer] Flakey virtualizer test

### ISSUE THREAD

**Issue by augustjk** [lit/lit#3970]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Example run:
https://github.com/lit/lit/actions/runs/5336743485/jobs/9671855750#step:8:218

cc @usergenic 

### Reproduction

n/a

### Workaround

n/a

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

latest

### Browser/OS/Node environment

in CI

**Comment by usergenic** [comment]
Should be fixed by #3973 in review
