### ISSUE TITLE
[labs/analyzer]: No source files found in package when tsconfig extends

### ISSUE THREAD

**Issue by bennypowers** [lit/lit#3999]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

Analyzer can't find source files when `extends` is used in tsconfig.

```
Analyzer error: No source files found in package.
original error
  Error: No source files found in package.
      at Analyzer.getPackage (file:///home/bennyp/Developer/patternfly/patternfly-elements/node_modules/@lit-labs/analyzer/lib/analyzer.js:39:19)
      at analyze (file:///home/bennyp/Developer/patternfly/patternfly-elements/tools/pfe-tools/cli/commands/analyze.js:9:28)
```

### Reproduction

Given https://github.com/patternfly/patternfly-elements/blob/367d186b15e2e92487bcf596364cfda06526411e/elements/tsconfig.json

and using this wrapper function:

```ts
async function analyze(argv: Opts) {
  const { packagePath } = argv;
  const path = packagePath instanceof URL ? fileURLToPath(packagePath) : join(process.cwd(), packagePath);
  const analyzer = createPackageAnalyzer(path as AbsolutePath);
  try {
    const p = analyzer.getPackage();
    console.log(p);
  } catch (e: any) {
    console.log(`Analyzer error: ${e.message}`);
    console.group(`original error`);
    console.error(e);
    console.groupEnd();
  }
}
```

and in the root of https://github.com/patternfly/patternfly-elements, running 

```js
await analyze({ packagePath: 'elements/tsconfig.json' });
```

### Workaround

replace the extends clause with the adjusted contents of tsconfig.settings.json. I will also need to replace `includes` with `files: []`, as the analyzer  **also does not pick up on files from `includes`**

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

0.8.0

### Browser/OS/Node environment

fedora 38

**Comment by justinfagnani** [comment]
I would have thought that using `ts.readConfigFile` and `ts.parseJsonConfigFileContent` [here](https://github.com/lit/lit/blob/main/packages/labs/analyzer/src/lib/analyze-package.ts#L42) would have read extended configs.

This is probably an easy fix for someone that knows the TS compiler API better than us, if anyone wants to help!

**Comment by bennypowers** [comment]
looks like they do that here https://github.com/microsoft/TypeScript/blob/9701f55f7217d7bd56d28e73b250444efcefa8dd/src/compiler/commandLineParser.ts#L3174

**Comment by bennypowers** [comment]
See also https://stackoverflow.com/questions/67956755/how-to-compile-tsconfig-json-into-a-config-object-using-typescript-api
