### ISSUE TITLE
Properties not converted to types when used via html component

### ISSUE THREAD

**Issue by garygreen** [lit/lit#4007]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When setting `type` on `properties` according to [the docs](https://lit.dev/docs/v1/components/properties/#property-options) it should convert the value to the given hinted type:

> A type hint for converting between properties and attributes. This hint is used by LitElement's default attribute converter, and is ignored if converter is set. If type is unspecified, behaves like type: String. See [Use LitElement's default attribute converter](https://lit.dev/docs/v1/components/properties/#conversion-type).

The default converter is described [here](https://lit.dev/docs/v1/components/properties/#conversion-type) and sets how the values are converted.

However, in the given demo you can see the type remains as string despite being set as various `type` - presumably this is because all HTML attribute values are technically strings.

I tested to see how [Vue handles this](https://play.vuejs.org/#eNp9Uk1PwkAQ/SuTjQmQkBLjDSuJXwc9qFGOe6CWARa7H9kPhDT9785uaeGgHpruzHtvdmbe1uzWmGwXkE1Z7korjAeHPpgZV0IabT3ca2lgZbWEQTaJQaQPuMonLZ+YFHiUpio8UgSQJ40K8oazS85medIRlE96Hhsz70qtVmKdbZ1W1EAdtZyVxBUV2lfjhVaOsykkJGJFVenv55TzNuC4y5cbLL9+yW/dPuY4e7Po0O6Qsx7zhV2jb+HHjxfc07kHpV6Gitj/gO/odBVijy3tLqgltX3GS90+pTUKtZ67x71H5bqhYqOR2SQ+Z7TWuKa/Rj+1e5VdJR1XDW2xs+Tk4Izb3r0alrgSKlXWCpWH5mhmdPE6MuOH+8QmbhGq9D/XDOvIAVCFxCkMHsi/B+HIx8Ng3CLGauNisykiZpBnEYA/GFK+BPmJ9ihJg6dT97eolmiHo5PQ0lO0ChanQgDzDcbyVAgEXXlRx9p6BX4jXEZAQ6n2omGXGjVdgUWauLuyGaWwf8ms+QH24AUb), and it also keeps the values as String, but does generate a warning to show the expected type was not found.

![image](https://github.com/lit/lit/assets/1702638/a6327660-515d-4af9-8d77-1abc7500035e)

Is this the expected behaviour for Lit? When should the converter actually get used to set the proper type?

### Reproduction

https://lit.dev/playground/#sample=examples%2Fproperties-has-changed&project=W3sibmFtZSI6InR5cGUtZGlzcGxheS5qcyIsImNvbnRlbnQiOiJpbXBvcnQge0xpdEVsZW1lbnQsIGh0bWx9IGZyb20gJ2xpdCc7XG5cbmNsYXNzIFR5cGVEaXNwbGF5IGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBwcm9wZXJ0aWVzID0ge1xuICAgIG51bTogTnVtYmVyLFxuICAgIGJvb2x0cnVlOiBCb29sZWFuLFxuICAgIGJvb2xmYWxzZTogQm9vbGVhbixcbiAgfTtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIG51bTogJHt0eXBlb2YgdGhpcy5udW19ICR7dGhpcy5udW19PGJyPlxuICAgICAgICBib29sdHJ1ZTogJHt0eXBlb2YgdGhpcy5ib29sdHJ1ZX0gJHt0aGlzLmJvb2x0cnVlfTxicj5cbiAgICAgICAgYm9vbGZhbHNlOiAke3R5cGVvZiB0aGlzLmJvb2xmYWxzZX0gJHt0aGlzLmJvb2xmYWxzZX08YnI-XG4gICAgIGA7XG4gIH1cbn1cbmN1c3RvbUVsZW1lbnRzLmRlZmluZSgndHlwZS1kaXNwbGF5JywgVHlwZURpc3BsYXkpO1xuIn0seyJuYW1lIjoibXktZWxlbWVudC5qcyIsImNvbnRlbnQiOiJpbXBvcnQge0xpdEVsZW1lbnQsIGh0bWx9IGZyb20gJ2xpdCc7XG5pbXBvcnQgJy4vdHlwZS1kaXNwbGF5LmpzJztcblxuY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDx0eXBlLWRpc3BsYXkgbnVtPVwiMVwiIGJvb2x0cnVlPVwidHJ1ZVwiIGJvb2xmYWxzZT1cImZhbHNlXCI-PC90eXBlLWRpc3BsYXk-XG4gICAgYDtcbiAgfVxufVxuY3VzdG9tRWxlbWVudHMuZGVmaW5lKCdteS1lbGVtZW50JywgTXlFbGVtZW50KTtcbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFkb2N0eXBlIGh0bWw-XG48aHRtbD5cbiAgPGhlYWQ-XG4gICAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9teS1lbGVtZW50LmpzXCI-PC9zY3JpcHQ-XG4gIDwvaGVhZD5cbiAgPGJvZHk-XG4gICAgPG15LWVsZW1lbnQ-PC9teS1lbGVtZW50PlxuICA8L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

### Workaround

Set the values manually when they change, not ideal

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.7.6

### Browser/OS/Node environment

Chrome: 114.0.5735.199

**Comment by VandeurenGlenn** [comment]
@garygreen 
You didn't set a type or provided a converter option
Setting a type will fix your issue
```js
static properties = {
    num: {type: Number},
    booltrue: { type: Boolean},
    boolfalse: { type: Boolean},
  };
```

**Comment by garygreen** [comment]
Thank you! Seems I made a whoopsie 😁

**Comment by VandeurenGlenn** [comment]
> Thank you! Seems I made a whoopsie 😁

Yw! Those happen! 🙈
