### ISSUE TITLE
[labs/ssr] Better errors on partIndex mismatch

### ISSUE THREAD

**Issue by augustjk** [lit/lit#4012]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr)

### Description

When hitting errors as reported in https://github.com/lit/lit/issues/3654 or https://github.com/lit/lit/issues/2441, it's hard to pinpoint where this happened just from the stack trace.

It would be good to also log the template to help locate what's causing this.

### Alternatives and Workarounds

Trial and error by rendering bits of template at a time.

**Comment by jimsimon** [comment]
I'm taking a stab at doing this. It looks pretty straightforward.
