### ISSUE TITLE
[labs/analyzer] Support for BYO TypeScript version

### ISSUE THREAD

**Issue by kevinpschaaf** [lit/lit#4018]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

The analyzer currently uses its own version of TypeScript (currently `4.7.4`). This is a problem when users are running the analyzer against a TS project that is being built against a different version of TS, since we currently stop analysis if there are semantic diagnostic errors (e.g. type errors), which often happens when running an older `tsc` against a codebase updated to a newer version of TS.

We should probably consider:
- Requiring that the `ts` module be passed into the `Analyzer` constructor rather than importing it directly. We could then consider having the CLI / `gen-manifest` support finding or pointing to a user-provided TS installation
- Update the analyzer to accept some number of different `ts` versions. e.g. build a union type of multiple versioned `ts` libs, and add the required duck-typing to choose correct API for where they vary. For example `node.decorators` for pre-4.8 vs. `ts.getDecorators(node)` for 4.8+
- Adding multiple builds / tests to the monorepo for building the analyzer and testing it against multiple versions

### Alternatives and Workarounds

Not possible today.

**Comment by jpzwarte** [comment]
Isn't this approach applicable to `@lit/localize-tools` and `@lit-labs/compiler` as well?
