### ISSUE TITLE
@lit-labs/ssr ReferenceError: __DENO_NODE_GLOBAL_THIS_0_46_0__

### ISSUE THREAD

**Issue by labidiaymen** [lit/lit#4034]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

![image](https://github.com/lit/lit/assets/3775924/2c30257f-9de9-4f37-81ac-f2424d3f056c)

### Reproduction

Create simple Deno fresh project and create a simple lit component

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@lit-labs/ssr-dom-shim/1.1.1

### Browser/OS/Node environment

Safari/MacOS

**Comment by justinfagnani** [comment]
I have no idea what `__DENO_NODE_GLOBAL_THIS_0_46_0__` is. It's not from our code base.

**Comment by augustjk** [comment]
Seems like a deno bug, supposedly should be fixed here? https://github.com/denoland/deno/pull/19307 and released yesterday https://github.com/denoland/deno/releases/tag/v1.35.2

**Comment by rictic** [comment]
We suspect this is fixed. Please reopen/refile if you're still seeing this!
