### ISSUE TITLE
With the starter kit, when you run the tests, it spams copies of source files in the project root directory

### ISSUE THREAD

**Issue by zeth** [lit/lit#4035]
### Which package(s) are affected?

Starter Kits (@lit/lit-starter-js / @lit/lit-starter-ts)

### Description

When I make a project with the starter kit, then run the unit tests, it fills the project root directory with source files in various stages of transpilation.

### Reproduction

Use the starter kit.
Run: npm test

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.2.4

### Browser/OS/Node environment

Node version: 9.6.3

**Comment by zeth** [comment]
It stopped, must have been a problem my end.

**Comment by zeth** [comment]
Closing.

**Comment by AndrewJakubowicz** [comment]
Thank you for filing an issue, and glad it resolved itself!
