### ISSUE TITLE
[labs/gen-wrapper-*] In Windows systems, the module path generated by the template wrapper is incorrect

### ISSUE THREAD

**Issue by zh-lx** [lit/lit#4051]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

In Windows systems, the module path generated by the template wrapper is incorrect.

In [labs/analyzer/src/lib/analyzer.ts](https://github.com/lit/lit/blob/main/packages/labs/analyzer/src/lib/analyzer.ts#L73-L82), we use `path.normalize` to adapt file paths to various operating systems:

<img width="645" alt="image" src="https://github.com/lit/lit/assets/73059627/f952e8d7-49d0-4574-9412-e42047c44ae7">

This value will be passed down and eventually used in [packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts](https://github.com/lit/lit/blob/main/packages/labs/gen-wrapper-vue/src/lib/wrapper-module-template-sfc.ts#L24-L34)

<img width="997" alt="image" src="https://github.com/lit/lit/assets/73059627/f7b61d90-05ca-42f4-8a9b-60c1678aa575">

It will cause the generated wrapper code to be incorrect in the Windows system:
![image](https://github.com/lit/lit/assets/73059627/32ec33c1-5c6b-4004-9080-3a1f8a4c7d09)

### Reproduction

execute `lit labs gen --framework=vue` in windows system.

### Workaround

We should replace `\` with `/` of module path when generating the wrapper code. I will solve this problem in #4052

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

The lasted version

### Browser/OS/Node environment

Node version: 18.12.0

**Comment by zlx1134558955** [comment]
I encountered the same problem. @justinfagnani I hope you can pay attention to and solve this problem, thanks!

**Comment by augustjk** [comment]
Thank you for the detailed report and opening a PR with the fix as well. We have tests that also run in Windows in CI which are not failing. Based on the screenshot, maybe it's due to having more subpath directories.

I'll have to try and reproduce this on a Windows machine.

**Comment by zh-lx** [comment]
> 

I'm willing to provide a example: https://github.com/zh-lx/lit-wrapper-demo.

Just clone the repository and execute `yarn gen-vue` or `yarn gen-react` in terminal. The incorrect code will be generated in `vue/src/ZhButton.vue` or `react/src/ZhButton.ts`.

**Comment by augustjk** [comment]
Thank you so much for providing a repro, and providing a fix @zh-lx!
