### ISSUE TITLE
Global CSS variables from :root not usable inside component

### ISSUE THREAD

**Issue by lp247-SAP** [lit/lit#4057]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

CSS variables defined outside of a component in :root of a global css file are not accessible from inside the component.
If I look up the css styles inside the dev tools the reference to the variable is greyed out.

It seems this is not a limitation of the shadow dom itself. See https://codepen.io/nolanlawson-the-selector/pen/eYdMOaE

### Reproduction

See lit.dev playground at https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgneC1yZXBybycpXG5leHBvcnQgY2xhc3MgWFJlcHJvIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiB2YXIoLS1teS1jb2xvcikgfWA7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYFxuICAgICAgPHA-VGhpcyB0ZXh0IHNob3VsZCBiZSByZWQ8L3A-XG4gICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3JlcHJvLmpzXCI-PC9zY3JpcHQ-XG4gIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBzcmM9XCIuL2luZGV4LmNzc1wiPlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx4LXJlcHJvPjwveC1yZXBybz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfSx7Im5hbWUiOiJpbmRleC5jc3MiLCJjb250ZW50IjoiOnJvb3Qge1xuICAtLW15LWNvbG9yOiByZWQ7XG59In1d

Note: The rendered text in the preview should be red but it is not as it is using a variable defined globally in :root. If I use "red" directly inside the components css it works.

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing lit.dev playground and in version 2.7.0 and 2.7.6

### Browser/OS/Node environment

Browser: Version 114.0.5735.198
OS: MacOS 13.4.1

**Comment by AndrewJakubowicz** [comment]
Thank you for the issue! The `link` tag uses the `href` attribute, while your repro has the `src` attribute.

In your example, `<link rel="stylesheet" src="./index.css">` should be `<link rel="stylesheet" href="./index.css">`. Then everything works as expected.

Please re-open if you're still encountering issues.

Fixed repro using `href`: https://lit.dev/playground/#gist=c9794687ab6b4f5a0e177e2bafa5b2a1
