### ISSUE TITLE
[labs/testing] Call site location by stack trace might not work in webkit

### ISSUE THREAD

**Issue by augustjk** [lit/lit#4067]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

Seeing failures in this workflow. https://github.com/lit/lit/actions/runs/5744321662/job/15570775282?pr=4062#step:8:506

This is due to webkit stack trace not including the `?wtr-session-id` querystring in the source file url, which we rely on here https://github.com/lit/lit/blob/51c431ee2a4c28a6e1a2fe6b0069ad24c7df0df3/packages/labs/testing/src/lib/fixtures/ssr-fixture.ts#L60-L62

Cause seems to be `playwright` version greater than 1.32. Unsure if it's playwright + webkit issue, or webkit straight up not including the querystring in stack.

Solution might be to find a different way to pinpoint the source file, maybe finding the first file that isn't an internal `@lit-labs/testing` file.

### Reproduction

TODO

### Workaround

Pin version of playwright.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

0.2.1

### Browser/OS/Node environment

.

**Comment by justinfagnani** [comment]
> or webkit straight up not including the querystring in stack

I don't think it's that the querystring isn't in the stack, I think it's that the stack frame that includes it is pushed out of the 10 frame window that's output in `error.stack`. Somehow there are more lines for the test framework in Webkit not.

**Comment by augustjk** [comment]
The behavior varied depending on the version of playwright. I've seen the mocha stacks, but also the correct lines without the querystrings that won't match the regex.
