### ISSUE TITLE
[labs/react] 2.0 custom event typing conflicts with common/global react events

### ISSUE THREAD

**Issue by hrmcdonald** [lit/lit#4093]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

In previous versions of `@lit-labs/react` events defined in the `createComponent` call always took precedence type-wise over React types.

This meant wherever we needed to override a global [React event prop](https://react.dev/reference/react-dom/components/common#common-props) we could and our `CustomEvent` typing would be what the user of the component sees. Something like

```typescript
export const ExampleInput = createComponent({
  tagName: 'my-example-input',
  elementClass: MyExampleInput,
  react: React,
  events: {
    onInput: 'onInput' as EventName<CustomEvent<TestInputEventDetail>>,
  },
});
```

would just work:

```tsx
const test = () => {
  return (
    <ExampleInput
      onInput={(e: CustomEvent<TestInputEventDetail>) => {
        console.log(e);
      }}
    />
  );
};
```

In `@lit-labs/react` these two types are now combined with an intersection which means users trying to handle our custom events are hit with a typescript error no matter what for any of the native bindings that we are attempting to override.

<img width="794" alt="image" src="https://github.com/lit/lit/assets/39349270/7aca61d4-5092-4710-b674-b5ff8ed888a4">

Previously this worked because the React wrapper component would set the native event listener for us, which would override the React synthetic event. Is that still happening here and this is just a typing issue, or are both firing somehow now?

### Reproduction

**Stackblitz recreation:** [https://stackblitz.com/edit/withastro-astro-7easvq?file=src%2Fcomponents%2FReactWrapper.tsx](https://stackblitz.com/edit/withastro-astro-7easvq?file=src%2Fcomponents%2FReactWrapper.tsx) (let `npm install` finish to see type error)

### Workaround

I could probably figure out a way to omit or override the provided type where these conflicts happen and instead, only export the CustomEvent handler function type, but it'd probably be nicer if we could tweak the internal typing to do this like it used to.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in `2.0.0`. Worked in `<= 1.2.0`

### Browser/OS/Node environment

Browser: N/A, Chrome
OS: MacOS, Liunux
Node: 18.16.0, 16.20.0
NPM: 9.5.1, 9.4.2

**Comment by augustjk** [comment]
> Previously this worked because the React wrapper component would set the native event listener for us, which would override the React synthetic event. Is that still happening here and this is just a typing issue, or are both firing somehow now?

There was only a type change so event listeners are still being added by the wrapper. I've identified the source of this regression and will do a fix to prefer the specified event handler type over React's built-in handler type.
