### ISSUE TITLE
other components instances is reset when adding an new element to parent

### ISSUE THREAD

**Issue by CypherPotato** [lit/lit#4122]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When I add an custom element made with lit using the following code:

```js
document.body.innerHTML += `<lit-test></lit-test>`
```

All others `<lit-test>` already present in the DOM is resetted.

[Working code example.](https://gist.github.com/CypherPotato/ade4575cce7394c96709b76a21d51243)

Is this behavior normal and expected? If so, how to prevent the states of existing components in the DOM from being reset when others are added?

### Reproduction

Reproduction:

https://lit.dev/playground/#gist=0184a9d58104c1b38c32f1504301c2f6

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@2 latest

### Browser/OS/Node environment

Chrome: 116.0.5845.96
MS Windows 11, build 22621.2134
No node or npm was used.

**Comment by augustjk** [comment]
That is how setting `.innerHTML`, even with `+=`, works. It basically wipes the content, and recreates it all. You want `.appendChild()`.

https://lit.dev/playground/#gist=5327e82db906acaf9b59664605344ec6

**Comment by CypherPotato** [comment]
@augustjk thank you so much, this fixed this issue.

> also i didn't know that calling `innerHTML +=` recreates the content.
