### ISSUE TITLE
[labs/virtualizer] Fixed-position virtualizer not refreshing items on scroll

### ISSUE THREAD

**Issue by cintaccs** [lit/lit#4125]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Works in 2.0.3 but since the virtualizer stops refreshing (i.e. stops adding new content / updating the list) when scrolling in a popup container.

It only seems to be an issue for virtualizer listings in "popups". I.e. only an issue when the container is fixed or absolute positioned or something like that.

2.0.3
<img width="290" alt="Screenshot 2023-08-22 at 12 27 20" src="https://github.com/lit/lit/assets/4300051/a062f5ed-05fb-4e6b-9646-e628bfbe3d0a">

2.0.6
<img width="305" alt="Screenshot 2023-08-22 at 12 27 42" src="https://github.com/lit/lit/assets/4300051/a71582eb-69ed-4435-a1be-28b7d4ad9c4c">

### Reproduction

I can't do this easily. It is deep in my application.

### Workaround

I haven't been able to find a workaround.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 2.0.4+ and not in 2.0.3

### Browser/OS/Node environment

Chrome Version 116.0.5845.97 (Official Build) (64-bit) on Windows.

**Comment by graynorton** [comment]
@cintaccs Just to confirm, you've verified that this regression first occurred specifically in `2.0.4`, correct? Knowing that should help narrow down potential causes.

**Comment by graynorton** [comment]
Here's a simple repro for this issue, BTW: https://lit.dev/playground/#gist=4662ccd73a8637399ef8cd0cd6213ca2

**Comment by cintaccs** [comment]
> @cintaccs Just to confirm, you've verified that this regression first occurred specifically in `2.0.4`, correct? Knowing that should help narrow down potential causes.
> 
> Edit: Looks almost certainly related to #3976, which landed in 2.0.4. At first glance, it appears that the logic to account for `position: fixed` elements is a bit too aggressive; it should only filter out ancestors of a `position: fixed` element, but currently it also filters out the element itself. Am testing a fix.

Yes correct!

**Comment by cintaccs** [comment]
@graynorton works very well! - thanks a lot!
