### ISSUE TITLE
[labs/context] infinite loop with v0.4.0 release

### ISSUE THREAD

**Issue by christophe-g** [lit/lit#4158]
### Which package(s) are affected?

Context (@lit-labs/context)

### Description

There are cases where @lit-labs/context creates an infinite loop. 

The crux of the issue is when new subscriptions are added (https://github.com/lit/lit/blob/170e91648472d21ecee3fca9ac7a0a52787b6e98/packages/labs/context/src/lib/value-notifier.ts#L68) while subscriptions are being looped (https://github.com/lit/lit/blob/170e91648472d21ecee3fca9ac7a0a52787b6e98/packages/labs/context/src/lib/controllers/context-provider.ts#L118)

This creates a situation where `for (const [callback, {consumerHost}] of this.subscriptions) {` never ends.

Making a shallow copy of `this.subscription` and then looping over it might solve the issue. 

### Reproduction

https://lit.dev/playground/#gist=fe54f4b5181c4c69bcfecd2a2475d561 will never render and eventually make browser process crash. 

### Workaround

Downgrade to v0.3.3

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 0.4.0 - working in 0.3.3 

### Browser/OS/Node environment

Chrome latest linux.

**Comment by rictic** [comment]
Can confirm, and repro.

I've reduced the repro down a bit more: https://lit.dev/playground/#gist=057e655ade9c47fd992892594046c40e

**Comment by rictic** [comment]
I've got a fix. However, providing the same context multiple times from a single host element – as your example does with `<simple-provider>` – seems bad. Which provider should consumers get? You end up with multiple sources of truth and it's a quirk of implementation which one they end up with.

**Comment by christophe-g** [comment]
Thanks a lot for this!

> I've got a fix. However, providing the same context multiple times from a single host element – as your example does with <simple-provider> – seems bad.

Fully agree and fully aware of this. Just wanted to have a case illustrating the issue before taking some leave; and did what I could given my time constraints ; )

**Comment by AndrewJakubowicz** [comment]
This has landed in [lit-labs/context@0.4.1](https://github.com/lit/lit/releases/tag/%40lit-labs%2Fcontext%400.4.1).
