### ISSUE TITLE
[labs/virtualizer] TypeError: Cannot destructure property 'scrollTop' of 'this._scrollerController' as it is null

### ISSUE THREAD

**Issue by steverep** [lit/lit#4182]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Reference issue: https://github.com/home-assistant/frontend/issues/17745

Getting errors below (`_scrollerController` is asserted as not null in the source code).  Regression probably occurred as of 2.0.6.

```
TypeError: Cannot destructure property 'scrollTop' of 'this._scrollerController' as it is null.
scrollTop (src/Virtualizer.ts:741:13)
_correctScrollError (src/Virtualizer.ts:546:9)
_finishDOMUpdate (src/Virtualizer.ts:538:9)
_updateDOM (src/Virtualizer.ts:603:11)
_handleLayoutMessage (src/Virtualizer.ts:441:43)
_hostSink (src/layouts/shared/BaseLayout.ts:478:9)
_sendStateChangedMessage (src/layouts/shared/BaseLayout.ts:364:9)
_reflow (src/layouts/flow.ts:491:10)
_reflow (src/layouts/shared/BaseLayout.ts:257:11)
reflowIfNeeded (src/Virtualizer.ts:563:20)

```

### Reproduction

We can reproduce in Home Assistant fairly easily - see https://github.com/home-assistant/frontend/issues/17745#issuecomment-1703767600.

I have not been able to isolate the cause just yet.

### Workaround

I have not found a workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Affects virtualizer >= 2.0.6

### Browser/OS/Node environment

Chrome or Firefox on any OS

**Comment by usergenic** [comment]
Thank you for the issue @steverep  -- I think the recent change in 2.0.6 overlooked the case of a null controller.  Hopefully this fix will be as easy as adding a check instead of an assertion.

**Comment by steverep** [comment]
> Thank you for the issue @steverep -- I think the recent change in 2.0.6 overlooked the case of a null controller. Hopefully this fix will be as easy as adding a check instead of an assertion.

I just submitted a PR to do exactly that.
