### ISSUE TITLE
Seems like setValue will prevent other lit-component update when property changed.

### ISSUE THREAD

**Issue by BugMaker-Huang** [lit/lit#4205]
### Which package(s) are affected?

React (@lit-labs/react)

### Description

Reproduction: https://lit.dev/playground/#sample=examples%2Freact-basics&project=W3sibmFtZSI6ImFwcC50c3giLCJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gJ2h0dHBzOi8vZXNtLnNoL3JlYWN0QDE4JztcbmltcG9ydCB7Y3JlYXRlUm9vdH0gZnJvbSAnaHR0cHM6Ly9lc20uc2gvcmVhY3QtZG9tQDE4L2NsaWVudCc7XG5pbXBvcnQge2NyZWF0ZUNvbXBvbmVudH0gZnJvbSAnQGxpdC1sYWJzL3JlYWN0JztcbmltcG9ydCB7RGVtb0dyZWV0aW5nIGFzIERlbW9HcmVldGluZ1dDfSBmcm9tICcuL2RlbW8tZ3JlZXRpbmcuanMnO1xuXG4vLyBDcmVhdGVzIGEgUmVhY3QgY29tcG9uZW50IGZyb20gYSBMaXQgY29tcG9uZW50XG5jb25zdCBEZW1vR3JlZXRpbmcgPSBjcmVhdGVDb21wb25lbnQoe1xuICByZWFjdDogUmVhY3QsXG4gIHRhZ05hbWU6ICdkZW1vLWdyZWV0aW5nJyxcbiAgZWxlbWVudENsYXNzOiBEZW1vR3JlZXRpbmdXQyxcbn0pO1xuXG5jb25zdCByb290ID0gY3JlYXRlUm9vdChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXBwJykhKTtcbiAgICAgICAgICAgICAgICAgICAgICAgIFxuY29uc3QgQXBwID0gKCkgPT4ge1xuICBjb25zdCBBcHBsZVJlZiA9IFJlYWN0LnVzZVJlZigpO1xuICBjb25zdCBbdmFsdWUsIHNldFZhbHVlXSA9IFJlYWN0LnVzZVN0YXRlKCdCZWFyJyk7XG4gIFxuICByZXR1cm4gKDw-XG4gICAgPERlbW9HcmVldGluZyB2YWx1ZT1cIkFwcGxlXCIgcmVmPXtBcHBsZVJlZn0gLz5cbiAgICA8RGVtb0dyZWV0aW5nIHZhbHVlPXt2YWx1ZX0gLz5cbiAgICAgIDxiciAvPlxuICAgIFNvIGNvbmZ1c2luZy4uLlxuICAgICAgPGJyIC8-XG4gICAgICBUaGUgZmlyc3QgRGVtb0dyZWV0aW5nIHdpbGwgbm90IGNoYW5nZSB3aGVuIGNsaWNrIHRoZSBmaXJzdCBidXR0b24gb25jZSwgYnV0IGNoYW5nZWQgd2hlbiBjbGljayB0d2ljZS4uLlxuICAgIDxidXR0b24gb25DbGljaz17KCkgPT4ge1xuICAgICAgICBBcHBsZVJlZi5jdXJyZW50LnZhbHVlID0gJ0NhbmR5JztcbiAgICAgICAgc2V0VmFsdWUoJ2RvY3RvcicpO1xuICAgICAgICB9fT4gc2V0VmFsdWUgPC9idXR0b24-XG4gICAgICBcbiAgICA8YnV0dG9uIG9uQ2xpY2s9eygpID0-IHtcbiAgICAgICAgQXBwbGVSZWYuY3VycmVudC52YWx1ZSA9ICdDYW5keSc7XG4vLyAgICAgICAgIHNldFZhbHVlKCdkb2N0b3InKTtcbiAgICAgICAgfX0-IEp1c3QgY2hhbmdlIHRoZSB2YWx1ZSA8L2J1dHRvbj5cbiAgICAgIDxiciAvPlxuICAgICBJZiB3ZSBkb24ndCB1c2Ugc2V0VmFsdWUsIGl0IHdpbGwgY2hhbmdlIGltbWVkaWF0ZWx5IGFzIHdlIHdhbnRlZC5cbiAgICA8Lz4pXG59XG5cbnJvb3QucmVuZGVyKDxBcHAgLz4pO1xuIn0seyJuYW1lIjoiZGVtby1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuLy8gQSBwbGFpbiBMaXQgY29tcG9uZW50IHdoaWNoIGNhbiBiZSB1c2VkIGluIGFueSBmcmFtZXdvcmtcbkBjdXN0b21FbGVtZW50KCdkZW1vLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBEZW1vR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICBwIHtcbiAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICAgIGJvcmRlcjogc29saWQgMXB4IGdyYXk7XG4gICAgICBiYWNrZ3JvdW5kOiB3aGl0ZTtcbiAgICAgIHBhZGRpbmc6IDAgMWVtO1xuICAgIH1cbiAgYDtcblxuICBAcHJvcGVydHkoKSB2YWx1ZSA9ICdTb21lYm9keSc7XG4gIEBwcm9wZXJ0eSgpIGRlZmF1bHQgPSAnZGVmYXVsdCc7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMudmFsdWV9ITwvcD5gO1xuICB9XG59XG5cbmRlY2xhcmUgZ2xvYmFsIHtcbiAgaW50ZXJmYWNlIEhUTUxFbGVtZW50VGFnTmFtZU1hcCB7XG4gICAgJ2RlbW8tZ3JlZXRpbmcnOiBEZW1vR3JlZXRpbmc7XG4gIH1cbn1cbiJ9LHsibmFtZSI6InJlYWN0LmQudHMiLCJjb250ZW50IjoiZGVjbGFyZSBtb2R1bGUgJ2h0dHBzOi8vZXNtLnNoL3JlYWN0QDE4JyB7XG4gIGV4cG9ydCBkZWZhdWx0IFJlYWN0O1xufVxuXG5kZWNsYXJlIG1vZHVsZSAnaHR0cHM6Ly9lc20uc2gvcmVhY3QtZG9tQDE4L2NsaWVudCcge1xuICBleHBvcnQgKiBmcm9tICdyZWFjdC1kb20vY2xpZW50Jztcbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFkb2N0eXBlIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9hcHAuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IGlkPVwiYXBwXCI-PC9kaXY-XG4gIDxwPkNoZWNrb3V0IG91ciA8YSBocmVmPVwiaHR0cHM6Ly9saXQuZGV2L2RvY3MvZnJhbWV3b3Jrcy9yZWFjdC9cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lciBub3JlZmVycmVyXCI-UmVhY3QgZnJhbWV3b3JrIGRvY3M8L2E-ITwvcD5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yXCIsXG4gICAgXCJAdHlwZXMvcmVhY3RcIjogXCIxOC4yLjdcIixcbiAgICBcIkB0eXBlcy9yZWFjdC1kb21cIjogXCJeMThcIixcbiAgICBcIkB0eXBlcy9yZWFjdC1kb20vY2xpZW50XCI6IFwiXjE4XCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

```javascript
import React from 'https://esm.sh/react@18';
import {createRoot} from 'https://esm.sh/react-dom@18/client';
import {createComponent} from '@lit-labs/react';
import {DemoGreeting as DemoGreetingWC} from './demo-greeting.js';

// Creates a React component from a Lit component
const DemoGreeting = createComponent({
  react: React,
  tagName: 'demo-greeting',
  elementClass: DemoGreetingWC,
});

const root = createRoot(document.getElementById('app')!);
                        
const App = () => {
  const AppleRef = React.useRef();
  const [value, setValue] = React.useState('Bear');
  
  return (<>
    <DemoGreeting value="Apple" ref={AppleRef} />
    <DemoGreeting value={value} />
      <br />
    So confusing...
      <br />
      The first DemoGreeting will not change when click the first button once, but changed when click twice...
    <button onClick={() => {
        AppleRef.current.value = 'Candy';
        setValue('doctor');
        }}> setValue </button>
      
    <button onClick={() => {
        AppleRef.current.value = 'Candy';
//         setValue('doctor');
        }}> Just change the value </button>
      <br />
     If we don't use setValue, it will change immediately as we wanted.
    </>)
}

root.render(<App />);


import {html, css, LitElement} from 'lit';
import {customElement, property} from 'lit/decorators.js';

// A plain Lit component which can be used in any framework
@customElement('demo-greeting')
export class DemoGreeting extends LitElement {
  static styles = css`
    p {
      display: inline-block;
      border: solid 1px gray;
      background: white;
      padding: 0 1em;
    }
  `;

  @property() value = 'Somebody';
  @property() default = 'default';

  render() {
    return html`<p>Hello, ${this.value}!</p>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-greeting': DemoGreeting;
  }
}

```

### Reproduction

https://lit.dev/playground/#sample=examples%2Freact-basics&project=W3sibmFtZSI6ImFwcC50c3giLCJjb250ZW50IjoiaW1wb3J0IFJlYWN0IGZyb20gJ2h0dHBzOi8vZXNtLnNoL3JlYWN0QDE4JztcbmltcG9ydCB7Y3JlYXRlUm9vdH0gZnJvbSAnaHR0cHM6Ly9lc20uc2gvcmVhY3QtZG9tQDE4L2NsaWVudCc7XG5pbXBvcnQge2NyZWF0ZUNvbXBvbmVudH0gZnJvbSAnQGxpdC1sYWJzL3JlYWN0JztcbmltcG9ydCB7RGVtb0dyZWV0aW5nIGFzIERlbW9HcmVldGluZ1dDfSBmcm9tICcuL2RlbW8tZ3JlZXRpbmcuanMnO1xuXG4vLyBDcmVhdGVzIGEgUmVhY3QgY29tcG9uZW50IGZyb20gYSBMaXQgY29tcG9uZW50XG5jb25zdCBEZW1vR3JlZXRpbmcgPSBjcmVhdGVDb21wb25lbnQoe1xuICByZWFjdDogUmVhY3QsXG4gIHRhZ05hbWU6ICdkZW1vLWdyZWV0aW5nJyxcbiAgZWxlbWVudENsYXNzOiBEZW1vR3JlZXRpbmdXQyxcbn0pO1xuXG5jb25zdCByb290ID0gY3JlYXRlUm9vdChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYXBwJykhKTtcbiAgICAgICAgICAgICAgICAgICAgICAgIFxuY29uc3QgQXBwID0gKCkgPT4ge1xuICBjb25zdCBBcHBsZVJlZiA9IFJlYWN0LnVzZVJlZigpO1xuICBjb25zdCBbdmFsdWUsIHNldFZhbHVlXSA9IFJlYWN0LnVzZVN0YXRlKCdCZWFyJyk7XG4gIFxuICByZXR1cm4gKDw-XG4gICAgPERlbW9HcmVldGluZyB2YWx1ZT1cIkFwcGxlXCIgcmVmPXtBcHBsZVJlZn0gLz5cbiAgICA8RGVtb0dyZWV0aW5nIHZhbHVlPXt2YWx1ZX0gLz5cbiAgICAgIDxiciAvPlxuICAgIFNvIGNvbmZ1c2luZy4uLlxuICAgICAgPGJyIC8-XG4gICAgICBUaGUgZmlyc3QgRGVtb0dyZWV0aW5nIHdpbGwgbm90IGNoYW5nZSB3aGVuIGNsaWNrIHRoZSBmaXJzdCBidXR0b24gb25jZSwgYnV0IGNoYW5nZWQgd2hlbiBjbGljayB0d2ljZS4uLlxuICAgIDxidXR0b24gb25DbGljaz17KCkgPT4ge1xuICAgICAgICBBcHBsZVJlZi5jdXJyZW50LnZhbHVlID0gJ0NhbmR5JztcbiAgICAgICAgc2V0VmFsdWUoJ2RvY3RvcicpO1xuICAgICAgICB9fT4gc2V0VmFsdWUgPC9idXR0b24-XG4gICAgICBcbiAgICA8YnV0dG9uIG9uQ2xpY2s9eygpID0-IHtcbiAgICAgICAgQXBwbGVSZWYuY3VycmVudC52YWx1ZSA9ICdDYW5keSc7XG4vLyAgICAgICAgIHNldFZhbHVlKCdkb2N0b3InKTtcbiAgICAgICAgfX0-IEp1c3QgY2hhbmdlIHRoZSB2YWx1ZSA8L2J1dHRvbj5cbiAgICAgIDxiciAvPlxuICAgICBJZiB3ZSBkb24ndCB1c2Ugc2V0VmFsdWUsIGl0IHdpbGwgY2hhbmdlIGltbWVkaWF0ZWx5IGFzIHdlIHdhbnRlZC5cbiAgICA8Lz4pXG59XG5cbnJvb3QucmVuZGVyKDxBcHAgLz4pO1xuIn0seyJuYW1lIjoiZGVtby1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuLy8gQSBwbGFpbiBMaXQgY29tcG9uZW50IHdoaWNoIGNhbiBiZSB1c2VkIGluIGFueSBmcmFtZXdvcmtcbkBjdXN0b21FbGVtZW50KCdkZW1vLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBEZW1vR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICBwIHtcbiAgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jaztcbiAgICAgIGJvcmRlcjogc29saWQgMXB4IGdyYXk7XG4gICAgICBiYWNrZ3JvdW5kOiB3aGl0ZTtcbiAgICAgIHBhZGRpbmc6IDAgMWVtO1xuICAgIH1cbiAgYDtcblxuICBAcHJvcGVydHkoKSB2YWx1ZSA9ICdTb21lYm9keSc7XG4gIEBwcm9wZXJ0eSgpIGRlZmF1bHQgPSAnZGVmYXVsdCc7XG5cbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBodG1sYDxwPkhlbGxvLCAke3RoaXMudmFsdWV9ITwvcD5gO1xuICB9XG59XG5cbmRlY2xhcmUgZ2xvYmFsIHtcbiAgaW50ZXJmYWNlIEhUTUxFbGVtZW50VGFnTmFtZU1hcCB7XG4gICAgJ2RlbW8tZ3JlZXRpbmcnOiBEZW1vR3JlZXRpbmc7XG4gIH1cbn1cbiJ9LHsibmFtZSI6InJlYWN0LmQudHMiLCJjb250ZW50IjoiZGVjbGFyZSBtb2R1bGUgJ2h0dHBzOi8vZXNtLnNoL3JlYWN0QDE4JyB7XG4gIGV4cG9ydCBkZWZhdWx0IFJlYWN0O1xufVxuXG5kZWNsYXJlIG1vZHVsZSAnaHR0cHM6Ly9lc20uc2gvcmVhY3QtZG9tQDE4L2NsaWVudCcge1xuICBleHBvcnQgKiBmcm9tICdyZWFjdC1kb20vY2xpZW50Jztcbn0iLCJoaWRkZW4iOnRydWV9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFkb2N0eXBlIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9hcHAuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IGlkPVwiYXBwXCI-PC9kaXY-XG4gIDxwPkNoZWNrb3V0IG91ciA8YSBocmVmPVwiaHR0cHM6Ly9saXQuZGV2L2RvY3MvZnJhbWV3b3Jrcy9yZWFjdC9cIiB0YXJnZXQ9XCJfYmxhbmtcIiByZWw9XCJub29wZW5lciBub3JlZmVycmVyXCI-UmVhY3QgZnJhbWV3b3JrIGRvY3M8L2E-ITwvcD5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yXCIsXG4gICAgXCJAdHlwZXMvcmVhY3RcIjogXCIxOC4yLjdcIixcbiAgICBcIkB0eXBlcy9yZWFjdC1kb21cIjogXCJeMThcIixcbiAgICBcIkB0eXBlcy9yZWFjdC1kb20vY2xpZW50XCI6IFwiXjE4XCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d

### Workaround

Not yet.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@lit-labs/react@2.0.3, lit 2.x, actually all latest, I reproduced it in lit playground.

### Browser/OS/Node environment

Chrome 116 and lit playground

**Comment by justinfagnani** [comment]
I think this is just standard React behavior, and a combination of having a JSX attribute on the component, setting a value outside of React's rendering with the ref, and causing a re-render with useState.

The first thing you have is:
```ts
    <DemoGreeting value="Apple" ref={AppleRef} />
```
Which tells React to set the value to "Apple"

Then the button performs:

```ts
        AppleRef.current.value = 'Candy';
        setValue('doctor');
```

which sets the value property of the element from _outside_ React's render loop, and then causes React to re-render because of the useState setter. When React re-renders it sets `value` to "Apple"` as it's told to by the JSX. This overwrites the "Candy" value.

The second time the button is clicked React doesn't perform a render because the value passed to `setValue()` hasn't change, so in that case the value set by the ref is not overwritten.

You can verify this behavior a few ways:

- Remove the `value="Apple"` attribute from the JSX, then "Candy" will appear on the first click.
- call `setValue()` with a different value each time, like appending a counter, then "Apple" will appear every time.

**Comment by BugMaker-Huang** [comment]
> I think this is just standard React behavior, and a combination of having a JSX attribute on the component, setting a value outside of React's rendering with the ref, and causing a re-render with useState.
> 
> The first thing you have is:
> 
> ```ts
>     <DemoGreeting value="Apple" ref={AppleRef} />
> ```
> 
> Which tells React to set the value to "Apple"
> 
> Then the button performs:
> 
> ```ts
>         AppleRef.current.value = 'Candy';
>         setValue('doctor');
> ```
> 
> which sets the value property of the element from _outside_ React's render loop, and then causes React to re-render because of the useState setter. When React re-renders it sets `value` to "Apple"` as it's told to by the JSX. This overwrites the "Candy" value.
> 
> The second time the button is clicked React doesn't perform a render because the value passed to `setValue()` hasn't change, so in that case the value set by the ref is not overwritten.
> 
> You can verify this behavior a few ways:
> 
> * Remove the `value="Apple"` attribute from the JSX, then "Candy" will appear on the first click.
> * call `setValue()` with a different value each time, like appending a counter, then "Apple" will appear every time.

Ahhh...I thing I understand! Apologize for my foolish question. Thanks♪(･ω･)ﾉ
