### ISSUE TITLE
[lit-html] Choose directive doesn't check types correctly

### ISSUE THREAD

**Issue by remziatay** [lit/lit#4220]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When I use `choose` directive like this, I would expect typescript to throw error since `'test'` and `'random'` can't be assigned to `CheckoutStep` type 

```ts
type CheckoutStep = 'register' | 'delivery' | 'payment';

function render(step: CheckoutStep) {
    return choose(step, [
        ['test', () => 1],
        ['random', () => 2],
        ['register', () => 3],
    ]);
}
```

### Reproduction

There should be a type error but there isn't: [Typescript gist](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuaW1wb3J0IHtjaG9vc2V9IGZyb20gJ2xpdC1odG1sL2RpcmVjdGl2ZXMvY2hvb3NlLmpzJztcblxudHlwZSBDaGVja291dFN0ZXAgPSAncmVnaXN0ZXInIHwgJ2RlbGl2ZXJ5JyB8ICdwYXltZW50JztcblxuQGN1c3RvbUVsZW1lbnQoJ3gtcmVwcm8nKVxuZXhwb3J0IGNsYXNzIFhSZXBybyBleHRlbmRzIExpdEVsZW1lbnQgeyAgXG4gIHJlbmRlclN0ZXAoc3RlcDogQ2hlY2tvdXRTdGVwKSB7XG4gICAgcmV0dXJuIGNob29zZShzdGVwLCBbXG4gICAgICAgIFsndGVzdCcsICgpID0-IDFdLFxuICAgICAgICBbJ3JhbmRvbScsICgpID0-IDJdLFxuICAgICAgICBbJ3JlZ2lzdGVyJywgKCkgPT4gM10sXG4gICAgXSk7XG4gIH1cblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIHRoaXMucmVuZGVyU3RlcCgncmVnaXN0ZXInKTtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3JlcHJvLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHgtcmVwcm8-PC94LXJlcHJvPlxuPC9ib2R5PlxuIn0seyJuYW1lIjoicGFja2FnZS5qc29uIiwiY29udGVudCI6IntcbiAgXCJkZXBlbmRlbmNpZXNcIjoge1xuICAgIFwibGl0XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJAbGl0L3JlYWN0aXZlLWVsZW1lbnRcIjogXCJeMS4wLjBcIixcbiAgICBcImxpdC1lbGVtZW50XCI6IFwiXjMuMC4wXCIsXG4gICAgXCJsaXQtaHRtbFwiOiBcIl4yLjAuMFwiXG4gIH1cbn0iLCJoaWRkZW4iOnRydWV9XQ)

### Workaround

It's seems like it's because `T` is inferred as `string` since it's used for both `value` and `cases` params
```ts
export declare const choose: <T, V>(value: T, cases: [T, () => V][]) => V;
```

It works as expected when I update the signature like this
```ts
export declare const choose: <T, V, K extends T>(value: T, cases: [K, () => V][]) => V;
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

This never worked

### Browser/OS/Node environment

OS: Windows 10
Node version: 18.12.1
npm version: 8.19.2

**Comment by augustjk** [comment]
Interesting! Yeah, looks like the type inference for `T` becomes broader so you'd need to manually provide the types like `choose<CheckoutStep, number>` to get it to type check in its current state.

The suggestion of adding the third type parameter extending `T` does indeed fix this. It would be good to make it default to `T` to make it non-breaking for anyone who actually did specify only 2 type arguments before like
```ts
export declare const choose: <T, V, K extends T = T>(value: T, cases: [K, () => V][]) => V;
```
