### ISSUE TITLE
[labs/ssr] svg templates are surrounded with empty <svg></svg> tags when rendered

### ISSUE THREAD

**Issue by pft** [lit/lit#4265]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

Any svg``-template is rendered wrapped in `<svg>...</svg>` when rendered with ssr.

This makes it impossible to create a valid svg, unless we do post-processing on the output.

### Reproduction

```
import { render } from "@lit-labs/ssr/lib/render-lit-html.js";
import { svg } from "lit";
import { Readable } from "stream";

const readable = Readable.from(
  render(svg`<svg xmlns="http://www.w3.org/2000/svg"
    height="229.6"
    width="300"
    viewBox="-16 0 250 229.6">${[
      svg`<path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path>`,
      svg`<path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path>`
    ]}</svg>`)
);

const chunks = [];

readable.on("readable", () => {
  let chunk;
  while (null !== (chunk = readable.read())) {
    chunks.push(chunk);
  }
});

readable.on("end", () => {
  const content = chunks.join("");
  console.log(content);
});

```

outputs

```
<!--lit-part h4LS1XLQZw0=--><svg><svg xmlns="http://www.w3.org/2000/svg"
    height="229.6"
    width="300"
    viewBox="-16 0 250 229.6"><!--lit-part--><!--lit-part XW/ddiU0ieA=--><svg><path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path></svg><!--/lit-part--><!--lit-part XW/ddiU0ieA=--><svg><path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path></svg><!--/lit-part--><!--/lit-part--></svg></svg><!--/lit-part-->
```

### Workaround

I could imagine post-processing by regexp or by creating an XML-document and doing structural post-processing on that, but have not implemented any such thing.

Another work-around might be to use lit html instead of svg (e.g. `import { html as svg } from lit`); but that means having to pass the lit tagged template function (i.e. html or svg) to my own template functions. Especially with nested templates this will get messy.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@lit-labs/ssr@3.1.7

### Browser/OS/Node environment

Browser: n/a
Node: v18.15.0
npm: 9.6.6

**Comment by justinfagnani** [comment]
`<svg>` is an HTML element, so if you want to use that in a template you need to use the `html` template tag.

The `svg` template tag is for SVG elements like `<g>` or `<path>`, which would be nested somewhere inside an `<svg>` HTML element, like so:

```ts
render(html`<svg xmlns="http://www.w3.org/2000/svg"
    height="229.6"
    width="300"
    viewBox="-16 0 250 229.6">${[
      svg`<path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path>`,
      svg`<path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path>`
    ]}</svg>`
```

**Comment by pft** [comment]
When using this suggestion,  you end up with

```html
<!--lit-part Nh7bUQPEJsY=--><svg
    xmlns="http://www.w3.org/2000/svg"
    height="229.6"
    width="300"
    viewBox="-16 0 250 229.6"
  >
    <!--lit-part--><!--lit-part XW/ddiU0ieA=--><svg><path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path></svg><!--/lit-part--><!--lit-part XW/ddiU0ieA=--><svg><path d="M116,33.9L116,38.06666666666667C116,42.23333333333333,116,50.56666666666666,116,58.9C116,67.23333333333333,116,75.56666666666668,116,79.73333333333333L116,83.9"></path></svg><!--/lit-part--><!--/lit-part-->
  </svg><!--/lit-part-->
```

The `<svg>` around `<svg xmlns="....">` is indeed gone, but note the spurious `<svg>` tags around the `<path>`s.

**Comment by sorvell** [comment]
When running @justinfagnani 's example in the browser, I believe we get expected output, where there's no nested `<svg>`. See [this example](https://lit.dev/playground/#gist=7423b8db12dd4b44e566ef1e8ed11d93).

Perhaps this issue is isolated to the SSR code. @augustjk maybe you could test that?

**Comment by pft** [comment]
Sorry if I hadn't made it more clear this issue was only about SSR. I indeed never encountered this problem in the browser.

**Comment by AndrewJakubowicz** [comment]
Thanks for filing this issue. It'll be fixed by https://github.com/lit/lit/pull/4298
