### ISSUE TITLE
Support for kebab-casing attributes by default

### ISSUE THREAD

**Issue by bahrus** [lit/lit#4271]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I strongly believe it would be much safer to hyphenate our attributes, especially for lengthy multi word attributes.  One prominent group of developers reported that one of their components broke with the introduction of popovertarget (I believe).  I could see how that would happen if I defined a property with name popoverTarget, and just went with the default setting.

This opinion may differ from the philosophy of the lit team, which is fine, but it is something that does hold me back from wanting to use lit, frankly.

I propose a class decorator be supported (if that even makes sense), where we can specify to do this by default.  Or some other approach, but definitely something so I don't have to remember to do it for every property I define.

### Alternatives and Workarounds

Defining the attribute name for every property.

**Comment by justinfagnani** [comment]
We do the most unopinionated thing we can and just pass the property name to observed attributes. Anything more complicated will end up having edge cases around where hyphens are inserted, requires more code, and requires that code readers understand our attribute making rules.

For the core Lit library we decided to do the simplest thing possible.

You can write your own decorator that applies naming rules you choose. It should be fairly easy to wrap `@property` and pass a new attribute make to it.

**Comment by justinfagnani** [comment]
Also I should note that this would be a breaking change, so it would need an RFC.

**Comment by bahrus** [comment]
Ok, thanks for the explanation.

**Comment by bahrus** [comment]
Hi @justinfagnani, I accept your argument, and have closed the issue, and appreciate your advice on how to implement.

But as someone who is attempting to build a web component library that could be used by others, where I've always planned to support this, and as someone who has been doing this for years (and I think an earlier Polymer version supported this as well, so I don't doubt you encountered some issues that caused later versions and lit to change course) without incident, could you kindly provide some specific examples of edge cases you have encountered?

Examples of what appear to me to be predictable algorithms are [found here](https://stackoverflow.com/questions/63116039/camelcase-to-kebab-case#:~:text=The%20function%20below%20supports%20converting%20both%20camelCase%20and,return%20str.replace%20%28%2F%20%28%5Ba-z%5D%29%20%28%5BA-Z%5D%29%2Fg%2C%20%22%241-%242%22%29.toLowerCase%20%28%29%3B%20%7D), for example.  Where would they produce unexpected results?

**Comment by bahrus** [comment]
Found this duplicate where edge cases are listed.  

https://github.com/lit/lit/issues/240

I still think that given that we now seem to have evidence of a production break, lit would be well advised to provide the option.  The edge cases listed there seem minor to me compared to the risks.  The breakage that happened happened to a loyal user who took it all in stride, but as lit's use spreads and becomes used in "legacy" applications, with no active development, I think it could raise enough ire that the concerns listed in the link above will seem rather trite compared to the consequences of the breakage.  I hope I'm wrong.
