### ISSUE TITLE
Cannot generate module for lit-html@3.0.0/lit-html.js

### ISSUE THREAD

**Issue by iMiMx** [lit/lit#4281]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Unsure if this is the right place or not, feel free to close if not.

Using a Homeassistant card, that references:

https://unpkg.com/lit-html@3.0.0/lit-html.js?module=

The above fails to load with the below error:

```
Cannot generate module for lit-html@3.0.0/lit-html.js
SyntaxError: unknown: Support for the experimental syntax 'logicalAssignment' isn't currently enabled (6:2831):
```

Consequently the card does not then load.  I appreciate unpkg says 'module' is very experimental.

### Reproduction

Presumably https://unpkg.com/lit-html@3.0.0/lit-html.js?module= should generate a module, not an error?

I see there was an update published on npm 6-7 hours ago.

```
lit-html
TypeScript icon, indicating that this package has built-in type declarations
3.0.0 • Public • Published 6 hours ago
```

### Workaround

Rolled back to an earlier version of the Homeassistant card, that does not reference the above impacted resource.

2.8.0 of lit-html does appear to work with 'module' without any errors thrown:

https://unpkg.com/lit-html@2.8.0/lit-html.js?module=

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing on 3.0

### Browser/OS/Node environment

Impacts all browsers, apps tested.

**Comment by iMiMx** [comment]
I believe it came from 'latest'

```
} from "https://unpkg.com/lit-element@3.0.1/lit-element.js?module";
import {unsafeHTML} from 'https://unpkg.com/lit-html@latest/directives/unsafe-html.js?module';
```

https://github.com/Olen/lovelace-flower-card/blob/master/flower-card.js

I worked around it by specifying 2.8.0 instead for now.

**Comment by justinfagnani** [comment]
There's this existing bug with unpkg: https://github.com/mjackson/unpkg/issues/351
