### ISSUE TITLE
The JSDoc for the `@provide` decorator is wrong

### ISSUE THREAD

**Issue by zaunt** [lit/lit#4292]
### Which package(s) are affected?

Context (@lit/context)

### Description

The JSDoc for the `@provide` decorator seems to have been copied from other decorators and insufficiently edited. Problems include:

- it says it's a "property decorator that adds a ContextConsumer controller," when it should say it adds a `ContextProvider` controller.
- it says it "will try and retrieve a value" but it *provides* a value
- it mentions a parameter `multiple` which doesn't exist on the function
- it has an irrelevant link to the Mozilla documentation for `querySelector`
- the code sample imports the `consume` decorator but not the `provide` decorator, and it has a method that *uses* the logger instead of providing it

### Reproduction

N/A

### Workaround

N/A

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0

### Browser/OS/Node environment

N/A

**Comment by AndrewJakubowicz** [comment]
Thanks for filing an issue. This should be resolved by https://github.com/lit/lit/pull/4286

**Comment by zaunt** [comment]
Excellent. Thanks!
