### ISSUE TITLE
@lit-labs/solid-signals

### ISSUE THREAD

**Issue by birkskyum** [lit/lit#4308]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

With Lit 3.0 shipped @lit-labs/preact-signals , but I'd like to use [SolidJS](https://solidjs.com/) signals instead, and I noticed this sentence in the Lit 3 announcement:

> "rather than build our own signals package or pick just one that we endorse, we plan on offering integration packages to be able to use various signal libraries with Lit."

### Alternatives and Workarounds

I don't have a good workaround.

**Comment by paglobal** [comment]
You could actually implement directives, mixins and a even new html tag function to support that. Have a look at the preact-signals package code 👉️ https://github.com/lit/lit/tree/main/packages/labs/preact-signals.
It's actually quite intuitive if you already understand directives, mixins and tag functions to a certain extent.

**Comment by justinfagnani** [comment]
This should be an RRFC or RFC

**Comment by paglobal** [comment]
> You could actually implement directives, mixins and a even new html tag function to support that. Have a look at the preact-signals package code 👉️ https://github.com/lit/lit/tree/main/packages/labs/preact-signals. It's actually quite intuitive if you already understand directives, mixins and tag functions to a certain extent.

@birkskyum you could reach out on the discord server though. great place to get help regarding the implementation. i'm also on there and happy to help out in any way I can.

**Comment by birkskyum** [comment]
Okay, I'll take a stab at hooking it up.
