### ISSUE TITLE
Syntax Error on Unpkg.com for 3.0.0

### ISSUE THREAD

**Issue by aphex** [lit/lit#4316]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

The module version of lit-html 3.0.0 is broken on unpkg.com. Not sure how all this comes together but just noticed this today when messing with an older codepen pointing at latest `lit-html`

Visit https://unpkg.com/lit-html@3.0.0?module and you will see

`SyntaxError: unknown: Support for the experimental syntax 'logicalAssignment' isn't currently enabled (6:2831):`

### Reproduction

Visit https://unpkg.com/lit-html@3.0.0?module or https://unpkg.com/lit-html@3.0.0/lit-html.js?module and you will see

`SyntaxError: unknown: Support for the experimental syntax 'logicalAssignment' isn't currently enabled (6:2831):`

### Workaround

Force the version back to 2.8.0

https://unpkg.com/lit-html@2.8.0/lit-html.js?module

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

3.0.0

### Browser/OS/Node environment

All browsers and envs

**Comment by thepassle** [comment]
This is an issue with unpkg, not lit. Please create an issue here instead: https://github.com/mjackson/unpkg

**Comment by augustjk** [comment]
Relevant unpkg issues:
https://github.com/mjackson/unpkg/issues/351
https://github.com/mjackson/unpkg/issues/372

https://esm.sh/ and https://esm.run/ (jsdelivr) are alternative CDNs that work with lit@3

**Comment by augustjk** [comment]
Closing as it is an unpkg issue that is out of our hands and we won't be changing our emit target level.
