### ISSUE TITLE
[labs/virtualizer] offsetParent issue report – virtualizer not working

### ISSUE THREAD

**Issue by AndrewJakubowicz** [lit/lit#4346]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

User reported that virtualizer stopped working after the introduction of: https://github.com/lit/lit/commit/f84963d80f890f6ddaa46720622dcc366663cb6a#diff-1e2b7f3328e9761f16f9252acbf58364a193256cd562b17c47522317f8520b22R556-R564

Report states that after this change, Virtualizer stopped working within a `position: fixed;` container (within a `mwc-dialog` specifically).
Theory is that `offsetParent` is not precise enough to check whether an element is displayed or not.

### Reproduction

Repro: https://lit.dev/playground/#gist=a7c2a4f12422be727d0a6464482f8e0a

It looks like `offsetParent` with fixed element within shadowDOM doesn't work. In the repro, virtualizer works if the fixed element is in the light DOM.

### Workaround

A possible workaround is to use [the offsetParent](https://github.com/josepharhar/offsetparent-polyfills/blob/main/offsetParent-polyfill.js) polyfill.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Introduced in https://github.com/lit/lit/commit/f84963d80f890f6ddaa46720622dcc366663cb6a

### Browser/OS/Node environment

No repro yet.

**Comment by graynorton** [comment]
@AndrewJakubowicz I think the recent change would indeed probably cause a virtualizer not to render if the virtualizer host node itself is `position: fixed`. It should still work fine if the virtualizer simply has a `position: fixed` ancestor. Maybe you can confirm with the user who reported the issue?

We might need to handle the `position: fixed` host node as a special case.

**Comment by AndrewJakubowicz** [comment]
Repro: https://lit.dev/playground/#gist=c5092116336fc50d238753e27ef7aff0
Expected to see the numbers 1,2,3,4 in the dialog.

**Comment by graynorton** [comment]
It appears this is due to a feature of Shadow DOM that prevents`<slottedElement>.offsetParent` from returning a node that is part of the same shadow tree as the slot.

Background:

https://github.com/WICG/webcomponents/issues/497
https://github.com/w3c/csswg-drafts/issues/159
https://bugs.chromium.org/p/chromium/issues/detail?id=1331803#c9

**Comment by graynorton** [comment]
I can take a crack at fixing this later this week. Will that work out OK, timing-wise, @AndrewJakubowicz?

**Comment by graynorton** [comment]
Quick update: I've identified and made a fix and am working to prepare a PR. I am adding a handful of new tests, which may take a bit more time to complete; I expect to submit the PR early next week.

**Comment by AndrewJakubowicz** [comment]
Thank you so much!!!
