### ISSUE TITLE
11ty plugin unavailable via npm in browser or via cli (Cloudflare error)

### ISSUE THREAD

**Issue by ctorgalson** [lit/lit#4347]
### Which package(s) are affected?

Eleventy Plugin (@lit-labs/eleventy-plugin-lit)

### Description

(Sorry if this is not _your_ issue and it actually belongs to npmjs.com/Cloudflare. I thought as project owners you might be able to trigger a rebuild etc).

When using `npm i @lit-labs/eleventy-plugin-lit`, I'm consistently getting this result in the terminal (logfile):

```
error 500 Internal Server Error - GET https://registry.npmjs.org/@lit-labs%2feleventy-plugin-lit - KV GET failed: 401 Unauthorized
```

I tried to get a little more info and it looks like a Cloudflare issue:

```
❱ http --headers https://registry.npmjs.org/@lit-labs%2feleventy-plugin-lit
HTTP/1.1 500 Internal Server Error
CF-RAY: 81e64c5b98f63a68-FRA
Connection: keep-alive
Content-Length: 43
Content-Type: application/json
Date: Mon, 30 Oct 2023 20:09:51 GMT
Server: cloudflare
Vary: Accept-Encoding
```

At the moment, I get essentially the same result on npmjs.com:

![image](https://github.com/lit/lit/assets/1063424/0fb7f2d0-0b20-430c-8290-a32f931e5a98)

### Reproduction

Either of these currently results in an error (in an npm log for the first, and directly to stdout for the second):
   
    # Try to install the package.
    npm i @lit-labs/eleventy-plugin-lit

    # Try to get a bit of diagnostic info using httpie.
    http --headers https://registry.npmjs.org/@lit-labs%2feleventy-plugin-lit

### Workaround

I have not found a workaround. Possibly it will work itself out while I'm asleep :)

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0.1

### Browser/OS/Node environment

Browser: any
OS: Ubuntu 20.04 / Android 13 / ChromeOS Beta 119.*
Node version: v20.9.0
npm version: v10.1.0

**Comment by augustjk** [comment]
I tried it just now and both https://www.npmjs.com/package/@lit-labs/eleventy-plugin-lit and `npm i @lit-labs/eleventy-plugin-lit` is working fine for me in California, US.

So it seems like an issue with your region or VPN you might be going through?

I don't know of a way for us to force a new npm publish or anything like that.

**Comment by ctorgalson** [comment]
I'm in France but also tested from a server in Germany. Just tried Canada via VPN, and I see what you see. 

As I said, maybe it'll resolve while I sleep :)
