### ISSUE TITLE
[context] Global Context

### ISSUE THREAD

**Issue by autopulated** [lit/lit#4361]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Context (@lit/context)

### Description

It seems like it would be quite straightforward to extend the Context API so that a truly global context provider can be set up on document.

Something like this:
```js
class AppComponent1 extends LitElement {
    // note use of 'document' instead of 'this'
    _userProvider = new ContextProvider(document, userContext); 
    // or perhaps a new class:
    _userProvider = new GlobalContextProvider(document, userContext); 
}
```

And then components can consume a global context value in exactly the same way as a normal one:
```js
class AppComponent2 extends LitElement {
    static properties = {
        user: {}
    }
    _userConsumer = new ContextConsumer(this, userContext, value => {
        this._user = value;
    }, true);
}
```

My reasoning for this is that I have a largely static page, with different `LitElement` components in different areas. For example a navigation bar (which needs to know whether the user is logged in or not to show login/logout buttons), and a small section of interactive content further down the page, which depends on the login.

It doesn't really make sense to turn the whole largely static page into a `LitElement`, but it would be nice to have a standard way to share some context between all components on the page. Since context is identified by the identity of the context object, there doesn't seem to be any danger of breaking the isolation between separate components that do not know about the context, and this should be completely backwards compatible with the existing context API.

### Alternatives and Workarounds

It's possible to do this outside of Lit, but would be much neater to re-use the internal `ValueNotifier` class, or just modify the existing `ContextProvider` class to accept the document, and it seems like something that would be generally useful.

If this is something which would be welcome, then I'm happy to have a stab at implementing it.

(I don't think this is a substantial change, but correct me if I'm wrong)

**Comment by augustjk** [comment]
I can envision this being a possibility but I would discourage attaching the provider to the `document` from within another component like shown.

I think it could be more like the `ContextRoot` https://github.com/lit/lit/tree/main/packages/context#late-upgraded-context-providers that attaches a provider to a DOM node like `document.body`.

The only lifecycle that `ContextProvider` uses is `hostConnected` so perhaps it can be more generalized so that the provider can be added to any `HTMLElement` and the readiness can be manually signaled.

**Comment by sorvell** [comment]
This does seem valuable and could perhaps piggyback on `ContextRoot`, but it is pretty simple to do with `ContextProvider` with one little hack to add `addController` to the host element (and this could easily just be optional):

```js
// hack `addController` onto host
document.addController = () => {};
const provider = new ContextProvider(document, context, nextValue());
// doesn't need to be called in this case.
provider.hostConnected();
```

https://lit.dev/playground/#gist=049135c4376d76e12bc9ff28c8ccf628

**Comment by augustjk** [comment]
Agree. I tried the same hack with no-op `addController`. 😁
Updating the host type on `ContextProvider` and optionally calling `addController()`, and documenting this use case seems like an easy way to support this. Manually calling `hostConnected()` would only be needed if this is imperatively being added to an element that's a child of another provider, or if there's concern that this will be added after a consumer's already registered and you need to tap into `ContextRoot`.
