### ISSUE TITLE
my-element.js 404 in starter-kit

### ISSUE THREAD

**Issue by goodcodedev** [lit/lit#4368]
### Which package(s) are affected?

Starter Kits (@lit/lit-starter-js / @lit/lit-starter-ts)

### Description

I went from https://lit.dev/docs/tools/starter-kits/ to https://github.com/lit/lit-element-starter-ts

### Reproduction

```bash
git clone https://github.com/lit/lit-element-starter-ts
cd lit-element-starter-ts
npm i
npm serve
```

Open http://localhost:8000/
Click `component demo` link
404 on my-element.js

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0.2

### Browser/OS/Node environment

Ubuntu wsl2
npm 9.8.0

**Comment by goodcodedev** [comment]
I needed to `npm run build` before/`npm run build:watch` in another tab..
I will leave it here if you want to consider documentation improvements.
The `npm run build` command did give an error: `src/test/my-element_test.ts:10:9 - error TS2724: '"lit"' has no exported member named 'UncompiledTemplateResult'. Did you mean 'CompiledTemplateResult'?`

**Comment by AndrewJakubowicz** [comment]
Thank you for filing this issue. The error `error TS2724: '"lit"' has no exported member named 'UncompiledTemplateResult'` has uncovered version skew between the starter kits and the main repo.

Making a PR to fix now.

**Comment by augustjk** [comment]
Closing as fixed. Thanks for the report!
