### ISSUE TITLE
playwright github action doesn't work

### ISSUE THREAD

**Issue by urswilke** [lit/lit#4384]
### Which package(s) are affected?

Starter Kits (@lit/lit-starter-js / @lit/lit-starter-ts)

### Description

I tried to add the [playwright github actions workflow](https://playwright.dev/docs/next/ci-intro#setting-up-github-actions) to a [repo](https://github.com/urswilke/lit_gha) created with https://github.com/lit/lit-element-starter-js.

The tests work on my local machine, but on the github action they [fail](https://github.com/urswilke/lit_gha/actions/runs/6823799755/job/18558414384).

### Reproduction

Steps to reproduce:
```
git clone https://github.com/urswilke/lit_gha
cd lit_gha/
npm ci
```
Now create a new empty public github repository

```
git remote rm origin
git remote add origin <your repository url.git>
git branch -M main
git push -u origin main
```

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in lit@3.0.2

### Browser/OS/Node environment

Browser: Chromium Version 119.0.6045.9 (Developer Build) (64-bit)
OS: Arch Linux, Kernel version: Linux 6.5.6-arch2-1
Node version: 20.8.0
npm version: 10.2.0

**Comment by augustjk** [comment]
The test command in the action is not the same as that of the repo
https://github.com/urswilke/lit_gha/blob/54f24eb9d22e3556821c4dcdcc84e1bb2b6ab27f/.github/workflows/playwright.yml#L21
replacing that with `npm test` should work.

**Comment by urswilke** [comment]
thanks! 
it [works](https://github.com/urswilke/lit_gha/actions/runs/6831181617/job/18580307360) now
