### ISSUE TITLE
[labs/nextjs] Support Next.js 14

### ISSUE THREAD

**Issue by augustjk** [lit/lit#4410]
### Which package(s) are affected?

Other/unknown (please mention in description)

### Description

The plugin still should work with the Page router even in Next.js 14.

We could include it in our peer dependency sem ver to allow installs. We should still clearly document limitation with App router.

**Comment by foadtkf** [comment]
what about the app router?
![image](https://github.com/lit/lit/assets/67990762/555b390d-9d0a-4ed4-b79e-ed46b169f41d)

**Comment by augustjk** [comment]
@foadtkf support for app router is tracked in a separate issue https://github.com/lit/lit/issues/3657

**Comment by augustjk** [comment]
Supporting v14 seems a bit more complicated as they're now bundling `react/jsx-dev-runtime` and `react/jsx-runtime` rather than it being external for us to use the normal module replacement plugin. See https://github.com/vercel/next.js/discussions/46470#discussioncomment-8375627 and https://github.com/vercel/next.js/pull/55362

We may need to make users specify `jsxImportSource` instead and also forego with wrapping the webpack externals config. This means we no longer have the ability to touch any jsx-runtime imports within node_modules code, e.g. npm installed react components that use bare Lit components within them. This was considered a pretty niche use case to support but nonetheless disappointing to have to give up.

Monkey-patching of `React.createElement` still seems to work.

**Comment by augustjk** [comment]
Found a way to monkey-patch everything without resorting to module replacement in above linked PR.
