### ISSUE TITLE
[ssr] invalid locations error when using server only templates

### ISSUE THREAD

**Issue by thescientist13** [lit/lit#4417]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

Per [this thread](https://github.com/lit/lit/issues/2441) on use cases for Lit SSR, the takeaway was that a special server only template function has now been made available that would relax some of the restrictions on the client side version of `html`, thus allowing something like [this](https://github.com/lit/lit/issues/2441#issuecomment-1816903951) to be server rendered now
```js
import {render, html} from '@lit-labs/ssr';

const template = ({ title, lang }) => html`
  <!DOCTYPE html>
  <html lang="${lang}">
    <head>
      <!-- Works within a server only template -->
      <title>${title}</title>
    </head>
    <body>
      <p>${title}</p>
    </body>
  </html>
`;
```

However, based on my experiments
```js
import { render, html } from '@lit-labs/ssr';
import { collectResult } from '@lit-labs/ssr/lib/render-result.js'

const template = ({ title, lang }) => html`
  <!DOCTYPE html>
  <html lang="${lang}">
    <head>
      <!-- Works within a server only template -->
      <title>${title}</title>
    </head>
    <body>
      <p>${title}</p>
    </body>
  </html>
`;

const ssrResult = render(template({ title: 'My Website', lang: 'en'}));
const ssrContent = await collectResult(ssrResult);

console.log({ ssrContent });
```

doing this will result in an [invalid locations error](https://lit.dev/docs/templates/expressions/#invalid-locations)
```sh
file:///Users/owenbuckley/Workspace/github/lit-v3-ssr-demo/node_modules/@lit-labs/ssr/lib/render-value.js:605
        throw new Error(errorMsg);
              ^
Error:
    Unexpected final partIndex: 2 !== 3 while processing the following template:


  <!DOCTYPE html>
  <html lang="${...}">
    <head>
      <!-- Works within a server only template -->
      <title>${...}</title>
    </head>
    <body>
      <p>${...}</p>
    </body>
  </html>


    This could be because you're attempting to render an expression in an invalid location. See
    https://lit.dev/docs/templates/expressions/#invalid-locations for more information about invalid expression
    locations.
```

### Reproduction

I have a repro repo setup here you can check out
https://github.com/thescientist13/lit-v3-ssr-demo/tree/master#document-%EF%B8%8F

Just clone, run `npm ci` and then run `npm run demo:document`.  The relevant code is in _document.js_

### Workaround

not really a work around, but It should be noted if I remove the `lang=${...}` from the template, the error goes away.
```sh
{
  ssrContent: '\n' +
    '  <!DOCTYPE html>\n' +
    '  <html>\n' +
    '    <head>\n' +
    '      <!-- Works within a server only template -->\n' +
    '      <title>My Website</title>\n' +
    '    </head>\n' +
    '    <body>\n' +
    '      <p>My Website</p>\n' +
    '    </body>\n' +
    '  </html>\n'
}
```

Not sure if I am doing something wrong?  In the repro repo I conducted another experiment to SSR a [greeting component](https://github.com/thescientist13/lit-v3-ssr-demo/tree/master#greeting-) and that all seemed to go fine, so at least I'm doing _something_ right _somewhere_ 😅 

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@lit-labs/ssr: ^3.2.0,  lit: ^3.1.0

### Browser/OS/Node environment

macOS: 14.0
Node: 18.12.1
npm: 8.19.2

**Comment by AndrewJakubowicz** [comment]
You are not doing something wrong, this is a real bug. Thank you for the report!
The bug is that `<html lang="${lang}">` currently doesn't get handled correctly, and the `lang` attribute is skipped. This then results in a part mismatch error being thrown.


It'll be fixed with https://github.com/lit/lit/issues/4417
