### ISSUE TITLE
Expressions in rendering custom element attributes should be evaluated before rendering custom element

### ISSUE THREAD

**Issue by vvaradarajan** [lit/lit#4423]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

In the lit release 3.0.1, if a lit-element is rendered (from another lit-element) like:
`html **backtick** <div id="sizer" style="height:80%;width:80%;border:1px solid red;margin-bottom:20px;">
      <child-comp id="${chartId}" name="${chartId}"></child-comp>
      </div>**backtick**`
The **attributes id and name are not passed** as attribues during the construction/first rendering of the child-comp.

Howerver **if we explicitly specify the values like**:
`html **backtick**<div id="sizer" style="height:80%;width:80%;border:1px solid red;margin-bottom:20px;">
      <chart-comp id="nice-chart" name="nice-chart"></chart-comp>
      </div>**backtick**`
it works fine. The attributes id and name are passed as attributes and available to the constructor/first rendering of the child-comp.

This behaviour is probably due to 'late' evaluation of expressions in the Template and may be there for efficiency. The attributes do get eventually passed causing re-rendering of the child comp. The code to handle this is awkward and requires checking if the attributes did get passed in the render function. It also disturbs the utility of the 'firstUpdated' callback.

The feature request is to evaluate the template expressions and pass them as attributes to the constructor of the child component.

### Alternatives and Workarounds

The alternative is the way it works now. Declare attributes as properties in order to receive an callback, when the template expressions are eventually evaluated, and modify(re-construct) the child-comp in the 'updated' callback.  The original construction of the child-comp without the attributes is to be explicitly ignored  in the child-comp during the render (and also firstUpdated) functions.

**Comment by augustjk** [comment]
Perhaps I'm misunderstanding but I'm not sure that's actually the case. Might you have a reproduction?

Whether it's a literal attribute or a bound expression, the value is available for the child's first render, and making it an expression does not cause a re-render.
https://lit.dev/playground/#gist=179db88317a7576aea3024756e190005

If you're talking about having it available at the `constructor`, that's not possible to do as the constructor is where the default is set, which subsequently can get overridden with any provided value.

So if you want access to those values before the first render, you can do it before the return of the `render()` or in `willUpdate()` and check for `this.hasUpdated` which will be `false` before the very first render and true afterwards so you can skip.

**Comment by vvaradarajan** [comment]
Thank you for the quick response.  Here are the files showing the issue (I used javascript, did not use properties=>prefer not to use properties as my values do no change, and constructor attributes are easier to read(?)). I modifled the code in your playground link to show the issue here:

**Comment by vvaradarajan** [comment]
Thank you for the explanation and suggestions. And also the example in the playground. 

Explanation of why this is a problem (i.e. as I perceive): The object paradigm of defining attributes in the constructor is clearer and easier. A corollary issue is establishing a pointer back to the parent lit-element. 

In Python we can just pass a pointer to the parent as a constructor parameter to the child. 

Here I am passing a string key in the attribute to the custom tag. The parent then locates its children in its shadow dom and identifies itself as the parent to each of the children by calling a method on each child.  The situation is that the parent component has many children of the same type (i.e. the same tag), and each child is unique to the parent, due to the value of its attribute key).

I found this to be the simpler than others I encountered in googling like:
The procedures of establishing parent-child connections using bubbling events - involves learning and process bloat, and complex debugging.  I also avoid using properties, and explicitly use requestUpdate for clarity.

The workaround is/was suggested by A. Kim => grab the attributes in the first render.  As the attributes are available here, this works. In the parent component wait for the updateComplete of each child (ensuring first render was completed), before calling methods on the child.
Please feel free to suggest better workarounds or design. Thank you.
Also the issue can be closed, as it may not pertain to Lit.

**Comment by sorvell** [comment]
Glad you got it working.

> Please feel free to suggest better workarounds or design.

It depends on how generic of a solution you want or how coupled the relationship can be. The events technique relies only on the built in platform event system and is therefore very generic, and admittedly can be cumbersome at times.

Regarding a more targeted/coupled approach, here's a slightly simpler setup if the child is rendered within the shadowRoot of the parent you want to connect with:

```js
// in the child
// assuming you want to registry only specific elements in the parent's shadow subtree.
firstUpdated() {
  const parent = this.getRootNode().host;
  // record the children or whatever...
  parent.registryImportantElement?.(this);
}

// in the parent
// note, assumes new children are not dynamically rendered; if so, use `updated`.
async firstUpdated() { 
  await new Promise(requestAnimationFrame) // ensures the entire subtree has exhaustively rendered
  // do some setup or whatever
  this.setupImportantElemnts()
}
```

**Comment by vvaradarajan** [comment]
Using getRootNode().host and child setup during registry with parent works well.

**Comment by augustjk** [comment]
Thanks for the update! I'll close this issue as it won't be a feature add to Lit but feel free to report any other updates issues if you find them.

**Comment by vvaradarajan** [comment]
Found that there is another solution, that seems simpler and works here:
[https://stackoverflow.com/questions/59666518/dynamic-tags-for-lit-html-not-possible](https://stackoverflow.com/questions/59666518/dynamic-tags-for-lit-html-not-possible)

in #9 by GH61
