### ISSUE TITLE
[labs/virtualizer] support directory is not included into the npm package

### ISSUE THREAD

**Issue by pdesoyres-cc** [lit/lit#4426]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

Not sure this should be considered as a `bug`.

A section in `README.md` file explains how to deal with  `"ResizeObserver loop limit exceeded" errors`.

But the files under `support` directory are not included into the npm package.

### Reproduction

Steps to reproduce:

* add `"@lit-labs/virtualizer": "2.0.11"` dependency to a package.json
* run `npm install`
* try to import utility file as stated in the `README.md`: `import {setupIgnoreWindowResizeObserverLoopErrors} from '@lit-labs/virtualizer/support/resize-observer-errors.js';`

The import cannot be resolved.

### Workaround

None

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

2.0.11

### Browser/OS/Node environment

Any

**Comment by augustjk** [comment]
Thanks for the report and the fix PR!
