### ISSUE TITLE
Unexptected token '{'

### ISSUE THREAD

**Issue by matthme** [lit/lit#4433]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

After switching from vite 2 to vite 3 I get the following error in my console in an electron project:
```
Unexptected token '{'
```
And it originates from the following part of the code in my bundle:
```
`lit$${(Math.random() + "" + "").slice(9)}$` [... more stuff]
```
Which in the browser actually gets loaded as
```
`lit${(Math.random() + "").slice(9)}<!DOCTYPE html>
```
So for some reason, the second template literal disappears and things break.

The same code works fine when it's being loaded in a tauri project (using webkit on Linux).

### Reproduction

I have not been able to reproduce it outside of my project so far. [This](https://github.com/matthme/launcher-electron/blob/we/utils/applet-iframe/src/index.ts) is the file where that leads to the issue (bundled with vite).

### Workaround

I have not found any workaround yet.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in 0.3.2, working in 0.2.x

### Browser/OS/Node environment

Browser: Chrome/114.0.5735.289 (Electron/25.9.7)
yarn: 1.22.19
node: 18.15.0
OS: Linux (Ubuntu 22.04)

**Comment by matthme** [comment]
In case someone else hits the issue, it was caused by injecting the lit code into the index.html and apparently javascript is funny enough to deal like this in its replace method:
![image](https://github.com/lit/lit/assets/36768177/8f0e01c8-7c47-4c27-b814-8758040680c1)
Seems to be an unfortunate conflict with lit's creation of that character combination...

**Comment by matthme** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_the_replacement

**Comment by augustjk** [comment]
Very interesting, and unfortunate behavior. I guess electron is doing some string replacement on the HTML with source code inlined? Thanks for adding this info for future readers!
