### ISSUE TITLE
@lit/react package is not setting properties passed to the component during Vitest tests

### ISSUE THREAD

**Issue by tylerbmyers** [lit/lit#4446]
### Which package(s) are affected?

React (@lit/react)

### Description

When running tests in Vitest and using any version of @lit/react or @lit-labs/react versions 2 and up, any lit element wrapped with `createComponent` is not setting the properties of the web component that are passed as props.

This works fine in a real browser using Vite, and seems to be only an issue in the tests. The other thing that is interesting is that if I copy and paste the `create-component.ts` file into my project and import it directly, it works just fine, so my guess is that something with the minified file is not compatible with Vitest for some reason.

### Reproduction

I have created [this](https://github.com/tylerbmyers/lit-react-vitest-issue) repo with a simple Lit web component to reproduce the issue. In `App.test.tsx` you will see the component that is created using the `@lit/react` package is not setting the `name` property, but the component created using the direct import of `create-component.ts` is setting the `name` property.

### Workaround

My current workaround is to use `@lit-labs/react` version 1 as this works fine with Vitest.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing any version of @lit/react or @lit-labs/react versions 2 and up

### Browser/OS/Node environment

Node version: 20.10.0

**Comment by augustjk** [comment]
From the fact that local copy of `create-component.ts` working, the likely culprit is that the Vitest build is using the "node" export condition when resolving the import while building the test file which removes the `useLayoutEffect()` that's responsible for updating the property here: https://github.com/lit/lit/blob/a365002dedb560cc0f1c68a74ea6817aebc4f971/packages/react/src/create-component.ts#L270-L297

There might be some configuration changes that can be done to make sure it uses the default browser build, but I haven't closely looked into how or if that plays nice with jsdom/happydom. It looks like Vitest also has an experimental mode to run tests in the browser with webdriverio and maybe that'll bring in browser builds too.

**Comment by augustjk** [comment]
The whole point of using export condition is that it the end-user should not have to worry about where they're importing from when you're writing code that's meant to work in both SSR and in browsers.

This is unfortunately another downside/limitation of trying to test browser code in Node.

According to Vitest docs, having `environment: 'jsdom'` should automatically use the "web" transform mode. But it seems it's still using nodejs resolution for the initial entry into the external dependency which starts of picking the wrong entrypoint (the node export condition in our case).

Some configs I tried below:

```js
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    pool: 'vmThreads',
    deps: {
      web: {
        transformGlobPattern: /@lit\/react\//,
      },
      // optimizer overrides the transform above
      optimizer: {
        web: {
          enabled: true,
          include: ['@lit/react'],
          esbuildOptions: {
            platform: 'browser',
          },
        },
      },
    },
  },
});
```
The `deps.web.transformGlobPattern` is used to transform matching package with Vite, and transforming in web mode should resolve any imports within it to the default browser build.

Or the `deps.optimizer.web` would bundle the dep with esbuild where it can do so with platform set to browser.

Unfortunately, in both of these cases, it seems like it runs the transform/bundling after it has resolved to the node export condition. This would work if the wrapped component was its own external package then `@lit/react` would be a transitive dependency so transforming with vite/esbuild with above config would pull in the correct browser build.

However, when `@lit/react` is a direct dependency, I can't find a way to force it to resolve to the browser build. This feels like a gap in Vitest's capability where it should be able resolving dependencies with its own module resolution when running in "web" mode rather than using node module resolution.

**Comment by tylerbmyers** [comment]
I created an issue in the Vitest repo to further this discussion.

**Comment by tylerbmyers** [comment]
They closed the issue saying it is the intended behavior but their provided [solution](https://github.com/vitest-dev/vitest/issues/4757#issuecomment-1858137328) does not seem to work.

**Comment by tylerbmyers** [comment]
> They closed the issue saying it is the intended behavior but their provided [solution](https://github.com/vitest-dev/vitest/issues/4757#issuecomment-1858137328) does not seem to work.

I do believe this would work if the export conditions were updated like this:
`".": {
      "types": "./development/index.d.ts",
      "node": {
        "development": "./node/development/index.js",
        "default": "./node/index.js"
      },
      "development": "./development/index.js",
      "browser": "./index.js",
      "default": "./index.js"
    },`

This could still accomplish the task of for the majority of use cases not needing to worry about whether you are in node or the browser but allow a workaround for test runners that are in node to resolve the package correctly.

This would also help in Jest as it already default to a condition of `browser` (https://jestjs.io/docs/configuration#testenvironmentoptions-object)

**Comment by tylerbmyers** [comment]
> > They closed the issue saying it is the intended behavior but their provided [solution](https://github.com/vitest-dev/vitest/issues/4757#issuecomment-1858137328) does not seem to work.
> 
> I do believe this would work if the export conditions were updated like this: `".": { "types": "./development/index.d.ts", "node": { "development": "./node/development/index.js", "default": "./node/index.js" }, "browser": "./index.js", "development": "./development/index.js", "default": "./index.js" },`
> 
> This could still accomplish the task of for the majority of use cases not needing to worry about whether you are in node or the browser but allow a workaround for test runners that are in node to resolve the package correctly.
> 
> This would also help in Jest as it already default to a condition of `browser` (https://jestjs.io/docs/configuration#testenvironmentoptions-object).
> 
> I understand some work with the rollup config would need to be done to make this work, but I am not sure of another way around this and as running React unit tests using either Jest/Vitest is still the predominant way of testing React, it seems like something will need to be done or this package will not be useful for a lot of teams.
> 
> EDIT: I messed around with this a bit locally and I am still not seeing it resolve correctly even providing this config. Looks like the `resolves` just adds the option of `broswer` to exist and does not override it, so vitest is still passing the condition of `node`. I don't know how you'd solve that without having an explicit export path for `browser`. Any ideas?
> 
> Edit 2: I can confirm that this exports configuration does work. Still have yet to figure out a way to how to override the `node` condition with `browser` successfully.
> 
> ```js
> "exports": {
>     ".": {
>       "types": "./development/index.d.ts",
>       "node": {
>         "development": "./node/development/index.js",
>         "default": "./node/index.js"
>       },
>       "browser": "./index.js",
>       "development": "./development/index.js",
>       "default": "./index.js"
>     },
>     "./browser" : "./index.js",
>     "./use-controller.js": {
>       "types": "./development/use-controller.d.ts",
>       "node": {
>         "development": "./node/development/use-controller.js",
>         "default": "./node/use-controller.js"
>       },
>       "development": "./development/use-controller.js",
>       "default": "./use-controller.js"
>     }
>   },
> ```

I looked into this even more and it seems that this would work:
```js
"exports": {
    ".": {
      "types": "./development/index.d.ts",
      "browser": "./index.js",
      "node": {
        "development": "./node/development/index.js",
        "default": "./node/index.js"
      },
      "development": "./development/index.js",
      "default": "./index.js"
    },
    "./use-controller.js": {
      "types": "./development/use-controller.d.ts",
      "node": {
        "development": "./node/development/use-controller.js",
        "default": "./node/use-controller.js"
      },
      "development": "./development/use-controller.js",
      "default": "./use-controller.js"
    }
  },
```

According to the docs here `https://nodejs.org/api/packages.html#conditional-exports`, the node condition will always be added no matter what for a node environment, but that key order matters. So if you move the `browser` condition above the `node` condition and manually resolve it in vitest like this it will work:
```js
export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
  },
  resolve: {
    conditions: ["browser"],
  },
});
```

I'm happy to open a PR if that seems like a good solution to this issue.

**Comment by augustjk** [comment]
Hmm... yes, an extra `"browser"` key above `"node"` seems like an okay compromise to me. Thank you for doing the research!
However, I would like to get thoughts from other maintainers too and whether we want to apply this for all of our packages rather than just `@lit/react`. I'll bring this up in our next eng meeting which unfortunately will be after the holidays in the first week of January.

**Comment by augustjk** [comment]
We discussed this morning and will work on adding the "browser" condition placed above in priority to all of our packages that also have a "node" condition.

e.g. for `lit-html`
```json
".": {
      "types": "./development/lit-html.d.ts",
      "browser": {
        "development": "./development/lit-html.js",
        "default": "./lit-html.js"
      },
      "node": {
        "development": "./node/development/lit-html.js",
        "default": "./node/lit-html.js"
      },
      "development": "./development/lit-html.js",
      "default": "./lit-html.js"
    },

```

This does add a lot of extra conditions in these packages, and some of our packages have a lot of exports explicitly listed. I think we should also take this opportunity to explore using `*` to simplify our package exports list as described in https://nodejs.org/api/packages.html#subpath-patterns
This should make the size of `package.json` smaller and reduce duplication and room for error.
