### ISSUE TITLE
Cannot render dynamic comment

### ISSUE THREAD

**Issue by tstewart-klaudhaus** [lit/lit#4449]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I'm trying to render comments with interpolated data into my output HTML in order to support a testing framework.

If the HTML to be rendered contains a comment with dynamic content (i.e. data etc. in ${}), the dynamic portion is replaced with a lit internal identifier instead of the data value.

### Reproduction

I added a comment with dynamic content to the default repro code:

https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgneC1yZXBybycpXG5leHBvcnQgY2xhc3MgWFJlcHJvIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIEBwcm9wZXJ0eSgpXG4gIF9udW1DbGlja3MgPSAwO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDwhLS0gdGVzdCAke3RoaXMuX251bUNsaWNrc30gLS0-XG4gICAgICA8cD5DbGlja2luZyB0aGUgYnV0dG9uIGJlbG93IGlzIGV4cGVjdGVkIHRvIHVwZGF0ZSB0aGUgdGV4dCwgYnV0IGl0IGRvZXNuJ3Q6PC9wPlxuICAgICAgPGJ1dHRvbiBAY2xpY2s9JHt0aGlzLl9vbkNsaWNrQnV0dG9ufT5DbGljayBtZTwvYnV0dG9uPlxuICAgICAgPHA-WW91IGhhdmUgY2xpY2tlZCAke3RoaXMuX251bUNsaWNrc30gdGltZXM8L3A-XG4gICAgYDtcbiAgfVxuICBcbiAgX29uQ2xpY2tCdXR0b24oKSB7XG4gICAgLy8gQSB0eXBvIGZvciBidWcgZGVtb25zdHJhdGlvbiBwdXJwb3Nlcy4gVGhlIGxlYWRpbmcgXyBpcyBtaXNzaW5nLlxuICAgIHRoaXMubnVtQ2xpY2tzKys7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9yZXByby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx4LXJlcHJvPjwveC1yZXBybz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4yLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjEuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl4zLjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMi4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0

The comment is like this:

`<!-- test ${this._numClicks} -->`

But if you inspect the result, you can see that the comment does not contain the intended data but instead looks something like:

`<!-- test lit$306548989$ -->`

### Workaround

I hav not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 2.8.0 and 3.1.0

### Browser/OS/Node environment

Chrome: 119.0.6045.199
MacOS: 13.1

**Comment by augustjk** [comment]
We don't support dynamic

**Comment by tstewart-klaudhaus** [comment]
Thanks @augustjk, I hadn't noticed that section of the doc, but it makes sense to me now why it works that way. Your workaround will work for me in this case.
