### ISSUE TITLE
Lit stripping @property custom properties from CSS?

### ISSUE THREAD

**Issue by adrianbruntonsagecom** [lit/lit#4454]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When I add the CSS `@property` to a lit component, it appears to be completely stripping it out.
https://developer.mozilla.org/en-US/docs/Web/CSS/@property

I'm assuming there is perhaps some sanitisation that happens, and since `@property` conflicts with the lit property decorator, this may be the cause?

### Reproduction

See [this link](https://lit.dev/playground/#sample=examples%2Fdirective-class-map&project=W3sibmFtZSI6Im15LWVsZW1lbnQudHMiLCJjb250ZW50IjoiaW1wb3J0IHtMaXRFbGVtZW50LCBodG1sLCBjc3N9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQge2NsYXNzTWFwfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9jbGFzcy1tYXAuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnbXktZWxlbWVudCcpXG5leHBvcnQgY2xhc3MgTXlFbGVtZW50IGV4dGVuZHMgTGl0RWxlbWVudCB7XG5cbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICAgIEBwcm9wZXJ0eSAtLWEge1xuICAgICAgICBpbml0aWFsLXZhbHVlOiAwZGVnO1xuICAgICAgICBpbmhlcml0czogZmFsc2U7XG4gICAgICAgIHN5bnRheDogXCI8YW5nbGU-XCI7XG4gICAgICB9XG4gICAgICAuY2hhcmdlciB7XG4gICAgICAgIGhlaWdodDogNDB2bWluO1xuICAgICAgICB3aWR0aDogNDB2bWluO1xuICAgICAgICBib3JkZXItcmFkaXVzOiA1MCU7XG4gICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICAgICAgYmFja2dyb3VuZDogIzQwNDA0MDtcbiAgICAgIH1cbiAgICAgIC5jaGFyZ2VyOmJlZm9yZSB7XG4gICAgICAgIGFuaW1hdGlvbjogbG9hZCAycyBpbmZpbml0ZSBlYXNlLWluLW91dCBmb3J3YXJkcztcbiAgICAgICAgY29udGVudDogXCJcIjtcbiAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgICB0b3A6IC0ydm1pbjtcbiAgICAgICAgcmlnaHQ6IC0ydm1pbjtcbiAgICAgICAgbGVmdDogLTJ2bWluO1xuICAgICAgICBib3R0b206IC0ydm1pbjtcbiAgICAgICAgYmFja2dyb3VuZDogY29uaWMtZ3JhZGllbnQocmVkIHZhcigtLWEpLCB0cmFuc3BhcmVudCBjYWxjKHZhcigtLWEpKSk7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6IDUwJTtcbiAgICAgICAgei1pbmRleDogLTE7XG4gICAgICB9XG4gICAgICBAa2V5ZnJhbWVzIGxvYWQge1xuICAgICAgICAwJSxcbiAgICAgICAgMTAlIHtcbiAgICAgICAgICAtLWE6IDBkZWc7XG4gICAgICAgIH1cbiAgICAgICAgMTAwJSB7XG4gICAgICAgICAgLS1hOiAzNjBkZWc7XG4gICAgICAgIH1cbiAgICAgIH1cbiAgYDtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIEZyb20gbGl0IGNvbXBvbmVudDpcbiAgICAgIDxkaXYgY2xhc3M9XCJjaGFyZ2VyXCI-PC9kaXY-XG4gICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8c3R5bGU-XG4gIGJvZHkgeyBmb250LWZhbWlseTogc2Fucy1zZXJpZjsgfSAgXG4gIFxuICAgICAgICBAcHJvcGVydHkgLS1hLWh0bWwge1xuICAgICAgICBpbml0aWFsLXZhbHVlOiAwZGVnO1xuICAgICAgICBpbmhlcml0czogZmFsc2U7XG4gICAgICAgIHN5bnRheDogXCI8YW5nbGU-XCI7XG4gICAgICB9XG4gICAgICAuaHRtbCB7XG4gICAgICAgIGhlaWdodDogNDB2bWluO1xuICAgICAgICB3aWR0aDogNDB2bWluO1xuICAgICAgICBib3JkZXItcmFkaXVzOiA1MCU7XG4gICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcbiAgICAgICAgYmFja2dyb3VuZDogIzQwNDA0MDtcbiAgICAgIH1cbiAgICAgIC5odG1sOmJlZm9yZSB7XG4gICAgICAgIGFuaW1hdGlvbjogaHRtbC1sb2FkIDJzIGluZmluaXRlIGVhc2UtaW4tb3V0IGZvcndhcmRzO1xuICAgICAgICBjb250ZW50OiBcIlwiO1xuICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgIHRvcDogLTJ2bWluO1xuICAgICAgICByaWdodDogLTJ2bWluO1xuICAgICAgICBsZWZ0OiAtMnZtaW47XG4gICAgICAgIGJvdHRvbTogLTJ2bWluO1xuICAgICAgICBiYWNrZ3JvdW5kOiBjb25pYy1ncmFkaWVudChyZWQgdmFyKC0tYS1odG1sKSwgdHJhbnNwYXJlbnQgY2FsYyh2YXIoLS1hLWh0bWwpKSk7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6IDUwJTtcbiAgICAgICAgei1pbmRleDogLTE7XG4gICAgICB9XG4gICAgICBAa2V5ZnJhbWVzIGh0bWwtbG9hZCB7XG4gICAgICAgIDAlLFxuICAgICAgICAxMCUge1xuICAgICAgICAgIC0tYS1odG1sOiAwZGVnO1xuICAgICAgICB9XG4gICAgICAgIDEwMCUge1xuICAgICAgICAgIC0tYS1odG1sOiAzNjBkZWc7XG4gICAgICAgIH1cbiAgICAgIH1cbjwvc3R5bGU-XG5cbjxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vbXktZWxlbWVudC5qc1wiPjwvc2NyaXB0PlxuXG48bXktZWxlbWVudD48L215LWVsZW1lbnQ-XG5cbkZyb20gaHRtbFxuPGRpdiBjbGFzcz1cImh0bWxcIj48L2Rpdj4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) for a reproduction. In it, there are two versions of what should be the same thing. The first is completely driven by the lit component however the `@property --a` portion appears to be missing (or at least non-functional). The second example is the same thing with different names driven outside of the lit component.

The issue therefore is the lit component appears to be stripping out and over-sanitising the CSS styles provided.

### Workaround

The workaround appears to be to add the `@property` syntaxes in global CSS outside of any lit component encapsulation. in my example, that would be this portion. It would then function as intended:
```css
      @property --a {
        initial-value: 0deg;
        inherits: false;
        syntax: "<angle>";
      }
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.1.0

### Browser/OS/Node environment

Replicated on https://lit.dev/playground

**Comment by sorvell** [comment]
This is not a Lit issue. Unfortunately, there's currently no platform support for `@property` in styles applied to shadow roots. You'll need to apply the `@property` to the document. 

You can do this pretty simply from within the element ([example](https://lit.dev/playground/#gist=1fe581ba6126728b8bfcd2dbdefdd724)), however:

```js
static {
    document.adoptedStyleSheets.push(css`
      @property --a { /* ... */ }`.styleSheet);
```

This just shows Lit isn't doing anything to remove the `@property` style; it's taken from the example posted above:

![Screenshot 2023-12-13 at 8 07 24 AM](https://github.com/lit/lit/assets/78891/45194bb4-dbd2-474d-8ff5-49b7aafc1a5a)

**Comment by justinfagnani** [comment]
We should make sure to link to (and star and comment on!) the browser bugs causing this: https://bugs.chromium.org/p/chromium/issues/detail?id=1457892&q=%40property%20shadow%20root&can=2
