### ISSUE TITLE
@lit/context is not SSR safe

### ISSUE THREAD

**Issue by matthewp** [lit/lit#4457]
### Which package(s) are affected?

Context (@lit/context), SSR (@lit-labs/ssr)

### Description

`@lit/context` attaches listeners in the constructor, see here: https://github.com/lit/lit/blob/25fbfba9c0f1b97d720a981831c59c08472ba6ee/packages/context/src/lib/controllers/context-provider.ts#L89

The SSR shim does not shim `addEventListener`, therefore it throws when the constructor is called.

The constructor is called here: https://github.com/lit/lit/blob/25fbfba9c0f1b97d720a981831c59c08472ba6ee/packages/labs/ssr/src/lib/lit-element-renderer.ts#L35

### Reproduction

https://stackblitz.com/edit/withastro-astro-gxjipq?file=src%2Fcomponents%2FmyChild.ts

1. Receives error `this.host.addEventListener is not a function`.
2. Should not have an error.

### Workaround

Not using context in an SSR app.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.2.0

### Browser/OS/Node environment

OS: Stackblitz
Node version: unknown

**Comment by augustjk** [comment]
Related https://github.com/lit/lit/issues/3301

**Comment by augustjk** [comment]
Closing in favor of issue mentioned above.
