### ISSUE TITLE
[labs/ssr-dom-shim] Implement toggleAttribute

### ISSUE THREAD

**Issue by Lattyware** [lit/lit#4468]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

SSR (@lit-labs/ssr), Other/unknown (please mention in description)

### Description

Currently the DOM shim doesn't implement [`toggleAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute), which specifically is breaking [Material Web components](https://github.com/material-components/material-web/tree/main) (specifically at least the checkbox and radio buttons) when trying to render them with SSR, as [they use it](https://github.com/material-components/material-web/blob/main/labs/behaviors/form-associated.ts#L241), getting `TypeError: this.toggleAttribute is not a function` and blowing up on the render.

This function seems to be a reasonable one to include in the shim given the other attribute methods currently implemented, and it can be easily implemented in terms of the others, so it feels like a small change (unless I'm missing something).

### Alternatives and Workarounds

My current work around for this is injecting a polyfill into the shim, i.e:

```ts
function toggleAttribute(
  this: Element,
  name: string,
  force?: boolean | undefined,
): boolean {
  switch (force) {
    case true: {
      this.setAttribute(name, "");
      return true;
    }
    case false: {
      this.removeAttribute(name);
      return false;
    }
    default:
      return toggleAttribute.bind(this)(name, !this.hasAttribute(name));
  }
}

class PatchedLitElementRenderer extends LitElementRenderer {
  constructor(tagName: string) {
    super(tagName);
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    if (this.element.toggleAttribute === undefined) {
      this.element.toggleAttribute = toggleAttribute;
    }
  }
}

// ...

render(template, {
    elementRenderers: [PatchedLitElementRenderer],
})
```

**Comment by augustjk** [comment]
Thanks for the report! I agree it seems reasonable to include that for the `Element` shim.
