### ISSUE TITLE
[react] reusal of react component instances across render cycles by react leads to properties not being updated correctly

### ISSUE THREAD

**Issue by mikonse** [lit/lit#4497]
### Which package(s) are affected?

React (@lit/react)

### Description

Let's assume a simple lit component with a disabled flag and a label `<my-input label="label" disabled></my-input>` and a minimal react wrapper created using `@lit/react` called `MyInput`.

Consider the following react code snippet from a simple react component:

```tsx
if (somecondition) {
  return <MyInput label="foo" disabled={true} />
}

return <MyInput label="bar" />
```

If our the component containing the above code is rendered across two render cycles, `somecondition` being true in the first cycle, false in the second, something interesting happens.
After the second render cycle the DOM will contain 

```html
<my-input label="bar" disabled=""></my-input>
```

This is obviously unexpected as from looking at the react code we'd expect the input to not be disabled at all.

The reason for this weird behavior lies (to some extent) in the way how react reuses component instances.
In the second render cycle react determines that it already rendered an instance of `MyInput` as the first element to be returned from our component in the first render cycle. It simply decides to reuse the instance of `MyInput` from the first cycle and just pass the new props ` { label: "bar" }`.
Since react reuses the component instance, the underlying lit component is also the same with `disabled = true` set in the first render cycle.

`@lit/react`, however, only updates component properties which are explicitly set in the props object passed to a component by react. See https://github.com/lit/lit/blob/546d75d9e26f4aefa3bf91d114a70a3c3fb05da2/packages/react/src/create-component.ts#L277-L285

Since the props object does not contain `disabled` as it has not been set explicitly on the second render of `MyInput`, the update is not propagated to the lit component by `@lit/react` leading to the value from the previous render cycle being set.

### Reproduction

[interactive example](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzeCIsImNvbnRlbnQiOiJpbXBvcnQgUmVhY3QgZnJvbSAnaHR0cHM6Ly9lc20uc2gvcmVhY3RAMTgnO1xuaW1wb3J0IHtjcmVhdGVSb290fSBmcm9tICdodHRwczovL2VzbS5zaC9yZWFjdC1kb21AMTgvY2xpZW50JztcbmltcG9ydCB7Y3JlYXRlQ29tcG9uZW50fSBmcm9tICdAbGl0L3JlYWN0JztcbmltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnbXktaW5wdXQnKVxuZXhwb3J0IGNsYXNzIE15SW5wdXRMaXQgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgQHByb3BlcnR5KClcbiAgZGlzYWJsZWQgPSBmYWxzZTtcbiAgXG4gIEBwcm9wZXJ0eSgpXG4gIGxhYmVsID0gXCJcIjtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICA8cD4ke3RoaXMubGFiZWx9PC9wPlxuICAgICAgPGlucHV0IGRpc2FibGVkPSR7dGhpcy5kaXNhYmxlZH0gLz5cbiAgICAgIDxwPmRpc2FibGVkID0gJHt0aGlzLmRpc2FibGVkfTwvcD5cbiAgICBgO1xuICB9XG59XG5cbmNvbnN0IE15SW5wdXQgPSBjcmVhdGVDb21wb25lbnQoe1xuICByZWFjdDogUmVhY3QsXG4gIHRhZ05hbWU6ICdteS1pbnB1dCcsXG4gIGVsZW1lbnRDbGFzczogTXlJbnB1dExpdCxcbn0pO1xuXG5jb25zdCBBcHAgPSAoKSA9PiB7XG4gIGNvbnN0IFtzdGF0ZSwgc2V0U3RhdGVdID0gUmVhY3QudXNlU3RhdGUodHJ1ZSk7XG4gIFxuICBSZWFjdC51c2VFZmZlY3QoKCkgPT4ge1xuICAgIHNldFN0YXRlKGZhbHNlKTtcbiAgfSwgW3NldFN0YXRlXSk7XG4gIFxuICBpZiAoc3RhdGUpIHtcbiAgICByZXR1cm4gPE15SW5wdXQgbGFiZWw9XCJmb29cIiBkaXNhYmxlZD17dHJ1ZX0gLz4gXG4gIH1cbiAgcmV0dXJuIDxNeUlucHV0IGxhYmVsPVwiYmFyXCIgLz5cbn1cblxuY29uc3Qgcm9vdCA9IGNyZWF0ZVJvb3QoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FwcCcpISk7XG5yb290LnJlbmRlcig8QXBwIC8-KTsifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vcmVwcm8uanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8ZGl2IGlkPVwiYXBwXCI-PC9kaXY-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

There are multiple possible workarounds:

- pass different `key` properties to the react components. This will prevent react from reusing the component instance and circumvent the issue completely (preferred)
- explicitly pass the optional properties which have this problem and set them to `undefined` (very ugly and error prone)

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

all versions of @lit/react and @lit-labs/react

### Browser/OS/Node environment

Independent of used browser

**Comment by augustjk** [comment]
Thank you for the report. The observation makes sense as well as the workarounds proposed. I'd say adding different `key` props for each of the JSX being conditionally rendered is the best course of action. This would be necessary even with vanilla React components for certain things like uncontrolled value properties if you want that to clear when switching to the other condition.

For the `disabled` thing in particular, that is related to https://github.com/lit/lit/issues/4227
We currently don't, but we could try and keep track of the previously provided JSX props and detect whether it has been omitted in an update to try and "unset". The question is what the value should be though. `undefined` might be reasonable for many use cases but React users might expect a revert to some default value which we also don't have.

**Comment by augustjk** [comment]
The team discussed this a bit more and agree unsetting something like `disabled` shouldn't require passing in `undefined`. Handling "unset" props that are missing compared to a previous render should be done by the wrapper.
