### ISSUE TITLE
Houdini transition animation on CSS custom properties are not playing

### ISSUE THREAD

**Issue by YannDuv** [lit/lit#4499]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I tried to make the demo from [Una Kravets article to animate a background with gradiant](https://web.dev/articles/at-property). It works by using transition on [CSS Properties and Values API](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Properties_and_Values_API).
I successfully made it work on simple HTML+CSS. Then I made it work with shadowDOM in a vanilla Custom Elements but I can't make it work with Lit.

I am sorry, but I am clueless on the reasons that can lead to this issue 😞.

### Reproduction

On modern Chrome, when mouse is over the colored block, [the gradiant background](https://lit.dev/playground/#project=W3sibmFtZSI6InJlcHJvLnRzIiwiY29udGVudCI6ImltcG9ydCB7aHRtbCwgY3NzLCBMaXRFbGVtZW50fSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgneC1ob3VkaW5pJylcbmV4cG9ydCBjbGFzcyBYUmVwcm8gZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgIDpob3N0IHtcbiAgICAgIC0tY29sb3IxOiBwaW5rO1xuICAgICAgLS1jb2xvcjI6IG9yYW5nZTtcbiAgICB9XG5cbiAgICBAc3VwcG9ydHMgKGJhY2tncm91bmQ6IHBhaW50KGhvdWRpbmkpKSB7XG4gICAgICBAcHJvcGVydHkgLS1ncmFkUG9pbnQge1xuICAgICAgICBzeW50YXg6IFwiPHBlcmNlbnRhZ2U-XCI7XG4gICAgICAgIGluaGVyaXRzOiBmYWxzZTtcbiAgICAgICAgaW5pdGlhbC12YWx1ZTogNDAlO1xuICAgICAgfVxuICAgIH1cblxuICAgIC5wb3N0IHtcbiAgICAgIC0tZ3JhZFBvaW50OiA0MCU7XG4gICAgICB3aWR0aDogMzgwcHg7XG4gICAgICBwYWRkaW5nOiAycmVtO1xuICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudChcbiAgICAgICAgdmFyKC0tY29sb3IxKSB2YXIoLS1ncmFkUG9pbnQpLFxuICAgICAgICB2YXIoLS1jb2xvcjIpIGNhbGModmFyKC0tZ3JhZFBvaW50KSArIDIwJSlcbiAgICAgICk7XG4gICAgICB0cmFuc2l0aW9uOiAtLWdyYWRQb2ludCAwLjVzLCBmaWx0ZXIgMC44cztcbiAgICB9XG5cbiAgICBAc3VwcG9ydHMgKGJhY2tncm91bmQ6IHBhaW50KGhvdWRpbmkpKSB7XG4gICAgICAucG9zdDpob3ZlcixcbiAgICAgIC5wb3N0OmZvY3VzIHtcbiAgICAgICAgLS1ncmFkUG9pbnQ6IDEwMCU7XG4gICAgICB9XG4gICAgfVxuXG4gICAgI2NvbnRhaW5lciB7XG4gICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgZGlzcGxheTogZmxleDtcbiAgICAgIGJhY2tncm91bmQ6IHdoaXRlO1xuICAgIH1cbiAgYDtcblxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgIDxhIGNsYXNzPVwicG9zdFwiPlxuICAgICAgPGRpdiBpZD1cImNvbnRhaW5lclwiPlxuICAgICAgICA8aDI-VGhpcyBEZW1vIFJlcXVpcmVzIENocm9tZSA4NSs8L2gyPlxuICAgICAgPC9kaXY-XG4gICAgPC9hPmA7XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9yZXByby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDx4LWhvdWRpbmk-PC94LWhvdWRpbmk-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMi4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4xLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeMy4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjIuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) should transition.

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 3.1.0

### Browser/OS/Node environment

Brower: Chrome 116.0.5845.110 ; OS: Macos 13.6.2 ; node: 18.15.0 ; npm: 9.6.4

**Comment by justinfagnani** [comment]
Do you have a link to the vanilla web components implementation?

Lit doesn't do anything with CSS except add it to the shadow root with adoptedStyleSheets. It should be exactly the same.

**Comment by justinfagnani** [comment]
It works if you put the `@property` declaration in the main document. Is this what you did with the vanilla implementation?

**Comment by YannDuv** [comment]
Indead, I had a duplicate of my styles on the main document for the custom elements (unintedend) and that is why it worked.

Thanks a lot for finding the right ticket for me 😊 
I can close this one.

**Comment by YannDuv** [comment]
Indead, I had a duplicate of my styles on the main document for the custom elements (unintedend) and that is why it worked.

Thanks a lot for finding the right ticket for me 😊
I can close this one.

**Comment by YannDuv** [comment]
A not so ugly workaround for me was to use the javascript API:
```js
if (window.CSS.registerProperty) {
  window.CSS.registerProperty({
    inherits: true,
    initialValue: '0turn',
    name: '--_stepper-progress',
    syntax: '<angle>',
  })
}
```
💡 If you use it, prefix it with your library name to prevent collision on custom property variable.
❓I don't know if registering the same property more than once is an issue.

**Comment by justinfagnani** [comment]
@YannDuv would you mind posting that workaround to the Chrome bug? It might help people and the activity will show that this is effecting real developers.
