### ISSUE TITLE
[labs/ssr] 3.2.0 to 3.2.1 breaks `<td colspan=${'foo')>` in server html template

### ISSUE THREAD

**Issue by JulianCataldo** [lit/lit#4513]
### Which package(s) are affected?

SSR (@lit-labs/ssr)

### Description

Updating from 3.2.0 to 3.2.1 breaks `td` `colspan` binding.

### Reproduction

Repro:

```ts
import { html, render } from '@lit-labs/ssr';
import { collectResultSync } from '@lit-labs/ssr/lib/render-result.js';

const test = html` <td colspan=${2}>test</td> `;

console.log(collectResultSync(render(test)));
```

Error:

```
error: 
    Unexpected final partIndex: 0 !== 1 while processing the following template:

     <td colspan=${...}>test</td> 
```

### Workaround

none

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

3.2.0 to 3.2.1 

### Browser/OS/Node environment

node 1.0.25
bun v20.11.0

**Comment by augustjk** [comment]
Thank you for reporting. I can confirm this is indeed a regression introduced by https://github.com/lit/lit/pull/4421

It seems `parse` from `parse5` swallows bare `<td>` tags so we lose all attribute bindings.
https://astexplorer.net/#/gist/161a7023b229715f0ba3f23f09a14fe4/fc8a336ba1088b61ae4b427027b7cf72de29f426

We tried to test for these https://github.com/lit/lit/blob/273ad4e23b8ec97f1a5015dbf398104f535f9c34/packages/labs/ssr/src/test/test-files/render-test-module.ts#L338 but failed to do so with attribute bindings.

I think we need to reconsider using `parse` over `parseFragment`.

**Comment by thescientist13** [comment]
I wonder if the issue, at least from my understanding of the parse docs, is that if your string contains:
- an `<html>` tag (a "complete") document, you would need to use [`parse`](https://parse5.js.org/functions/parse5.parse.html) 
- for anything else, you would want to use [`parseFragment`](https://parse5.js.org/functions/parse5.parseFragment.html)

So perhaps [the detection](https://github.com/lit/lit/pull/4421/files#diff-993b92b15e276bc22253e71a6283fda6fe62ccf8a3d3846276e73808765b2eb1R315) needs to be something like this instead?
```js
const ast = (html.indexOf('html') >= 0 ? parse : parseFragment)(String(html), {
  sourceCodeLocationInfo: true,
});
```

I could be totally way off here, so YMMV.  😅

**Comment by justinfagnani** [comment]
I'm not sure we want to use `parse()` for anything, because we rely on the order of expressions matching the JS template literal, and `parse()` can move things around enough to break that.

I think we need to find a way to make `<html>` work with `parseFragment()`.
