### ISSUE TITLE
[labs/testing] Use `setHTMLUnsafe()` for parsing declarative shadow DOM

### ISSUE THREAD

**Issue by augustjk** [lit/lit#4539]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

`@lit-labs/testing` uses `DOMParser.parseFromString()` with the `includeShadowRoots: true` option which is non-spec behavior that only works in Chrome.

https://github.com/lit/lit/blob/d68f5c705484b9f6ea1f553d4851a9aa6a440db0/packages/labs/testing/src/lib/fixtures/ssr-fixture.ts#L80-L96

The correct way to parse declarative shadow DOM would be to use `setHTMLUnsafe()` or `parseHTMLUnsafe()` https://github.com/whatwg/html/pull/9538

Also noticing that the feature detection here we're using the old `HTMLTemplateElement.prototype.shadowRoot` rather than `shadowRootMode` for the feature detection which should be updated.

As of writing, DSD and unsafe HTML methods are in Firefox shipped behind a flag and to be generally available next major version, and in Safari tech preview.

### Alternatives and Workarounds

n/a

**Comment by TechQuery** [comment]
@augustjk @justinfagnani I have published [a polyfill for the final version of this proposal][1], which has been used for **VDOM/JSX to HTML** generation: EasyWebApp/DOM-Renderer#5

[1]: https://github.com/EasyWebApp/declarative-shadow-dom-polyfill
