### ISSUE TITLE
`@lit/react` binds event callback prop as instance property, overriding the element's class method

### ISSUE THREAD

**Issue by stefanpearson** [lit/lit#4569]
### Which package(s) are affected?

React (@lit/react)

### Description

This one gave me such a headache, it took me ages to figure out what was happening here!

Initially, I thought this was some synthetic event pain, but discovered that when wrapping an element in the React component factory, **it seems the _react_ prop is overriding the actual class method**. In my case, an `onInput` prop is overriding the internal `onInput` class method.

React app:
```ts
import { createComponent } from "@lit/react";

const SearchField = createComponent({
  tagName: SearchFieldElement.tagName,
  elementClass: SearchFieldElement,
  react: React,
  events: {
    onInput: "input"
  }
});

const MyComponent = () => {
  const onSearchInput = useCallback(
    (event: React.FormEvent<SearchFieldElement>) => {
      // this is binding straight to the Lit render template!
    },
    []
  );

  return (
    <SearchField onInput={onSearchInput} />
  )
};
```
SearchField class:
```ts
class SearchField extends LitElement {
  static tagName = 'my-search-input' as const;

  protected onInput(event: InputEvent) {
    // This is overridden by the onSearchInput prop reference 
  }

  render() {
    return html`
      <input @input=${this.onInput} />
    `
  }
}
```

### Reproduction

See code example, I can create a sandbox if necessary

### Workaround

Rename the internal class method name 🤷

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

"@lit/react": "1.0.3", "lit": "3.1.2"

### Browser/OS/Node environment

Seems to be all browsers

**Comment by augustjk** [comment]
Thank you for the report!
This specifically happens when the React component is re-rendered but given the same value to the mapped event handler prop as you do by using `useCallback()`.

I found the source of the bug here https://github.com/lit/lit/blob/1b00c07a58707f45ad066809cd79f878fc3590d2/packages/react/src/create-component.ts#L168-L171
We are not early returning if a re-render happens with the same reference on the event binding, which ends up setting it on the instance. I'll have a fix up soon.

As an aside, I still like prefixing internal methods with `_` if not using private fields with `#` which makes it so it wouldn't be overridden. Also `on` prefixing is often used for public interfaces so I like prefixing internal ones with `handle`, like `handleInput` rather than `onInput`.

**Comment by stefanpearson** [comment]
FYI @augustjk, I've changed all internal private callbacks to be prefixed with `_`. However, it makes me nervous that, unless specified in the `events` map, any innocent internal handler (e.g. `onKeyDown`) could simply be overridden by a React prop. As TS didn't catch this issue, I ended up having to create a global test that checks an instance whether it has any 'reserved' prop names, which all seems a bit brittle.

```ts
/* Taken from DOMAttributes type in React */
export const REACT_EVENT_CALLBACK_NAMES = [
  "onCopy",
  "onCopyCapture",
  "onCut",
  "onCutCapture",
  "onPaste",
  // etc
] as const;

export const runReactSanitizeCheck = (Element: CustomElementConstructor) => {
  /**
   * When using `@lit/react`'s `createComponent` to create a React component, it unfortunately
   * just assigns any property that is part of React's props interface. This means that when
   * a consumer uses a React component like `<BdsElement onClick={} />`, the `onClick` property
   * will be set on the instance, and override any prototype property.
   *
   * This can be problematic and can lead to obscure issues that are difficult to track down,
   * without any TypeScript errors, or runtime errors. It will simply override the private handler
   * and lead to unexpected runtime behavior.
   *
   * Until React really fixes its interface with custom elements (React 19 may solve this?),
   * or `@lit/react` ensures this does not happen, we have to forbid any keys on an element's
   * prototype that could conflict with these React event callback names.
   */
  it("it does not use any prototype properties that could be overridden by React", () => {
    const elementInstance = new Element();

    REACT_EVENT_CALLBACK_NAMES.forEach((callbackName) => {
      assert.isUndefined(
        (elementInstance as any)[callbackName],
        `Element should not use ${callbackName} as a prototype property, to avoid being overridden by React props.`
      );
    });
  });
};
```
Is this a case of a gotcha to look out for, or could `@lit/react` make an effort to guard this, as it currently does with `ref`/`children`/`className` etc?

**Comment by augustjk** [comment]
Ah, that's a valid point. I can indeed confirm that "internal" methods named that way does prevent those React built-in event handlers from working. I think this warrants a separate issue and discussion. I made one here https://github.com/lit/lit/issues/4585

**Comment by vmizg** [comment]
@augustjk it's nice to see this finally being fixed.

It's funny, I actually raised this point in #3471, but the team thought it was working as expected before.
