### ISSUE TITLE
[lit] Repeat Directive not working as intended when sorting elements

### ISSUE THREAD

**Issue by ryker002** [lit/lit#4602]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When using sortableJS, in the onEnd function I am changing the order of table columns

```

onEnd: (event: Sortable.SortableEvent) => {
            const { oldIndex, newIndex } = event;
            if(oldIndex && newIndex && oldIndex !== newIndex) {
              if (this.sortableColumns) {
                const order = this.sortableColumns.toArray();
                const newColumns = order.map((id) => this.columns.find((column) => column.key === id)).filter(item => item !== undefined);
                if(newColumns.length === this.columns.length) {
                  this.columns = newColumns as Column[];
                  this.requestUpdate()
                  this.requestUpdateVirtualList();
                };
              }
            }
          }

# Rendering Columns

         ${repeat(
          this.columns,
          (column) => column.key,
          (column, index) => {
            return html`
            <th data-id=${column.key} data-index=${index}>
            <div class="reorder-handle"><svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M3 15h18v-2H3v2zm0 4h18v-2H3v2zm0-8h18V9H3v2zm0-6v2h18V5H3z"/></svg></div>
            ${column.label}
            </th>
          `;
          }
        )}
```
 
         
The returned data shows correctly when changed but the repeat directive does not re-render the columns correctly, even if a console log within the repeat directive shows the correct column that is supposed to be applied.
         
         

### Reproduction

https://stackblitz.com/edit/vitejs-vite-q5djd6?file=src%2Fmy-element.ts

Move `First Name` to `Gender`

Notice the stringified columns show the order correctly but the DOM Structure is incorrect

### Workaround

Changing the onEnd function where we change the this.columns property to this fixes the issue
```
if (newColumns.length === this.columns.length) {
              this.columns = [];
              this.updateComplete.then(() => {
                this.columns = newColumns as Column[];
              });
            }
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.0.0

### Browser/OS/Node environment

Browser: Arc, Based on Chromium version 122.0.6261.112 (Official Build) (arm64)
OS: Mac 14.2.1

**Comment by justinfagnani** [comment]
In general, DOM created by Lit has to be managed by Lit. So you can't reorder the DOM created by `repeat()` directly - you need to update the data provided to repeat and let it reorder.

**Comment by augustjk** [comment]
Sortable mutates the DOM without knowledge of Lit so the Lit marker nodes become out of sync with the list.
There's a longer discussion of it in Discord: https://discord.com/channels/1012791295170859069/1169918375481315388/1169918375481315388

From that thread, here's an example by @sorvell that attempts to keep the moved nodes in sync. https://lit.dev/playground/#gist=242f45fd2dbe21ecb6902f144686aae8

**Comment by ryker002** [comment]
As per mention from @augustjk and known sortable ticket: [sortable ticket](https://github.com/SortableJS/Sortable/issues/2089#issuecomment-1902094024) closing this
