### ISSUE TITLE
Iterative slots only projecting the first slot

### ISSUE THREAD

**Issue by Arthurdw** [lit/lit#4617]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When using a slot in an iterator only the first slot gets projected, all other slot values default.

### Reproduction

[Lit Playground - non functioning demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNsb3RzLWRlbW8udHMiLCJjb250ZW50IjoiaW1wb3J0IHtodG1sLCBjc3MsIExpdEVsZW1lbnR9IGZyb20gJ2xpdCc7XG5pbXBvcnQge2N1c3RvbUVsZW1lbnQsIHByb3BlcnR5fSBmcm9tICdsaXQvZGVjb3JhdG9ycy5qcyc7XG5pbXBvcnQge3JhbmdlfSBmcm9tICdsaXQvZGlyZWN0aXZlcy9yYW5nZS5qcyc7XG5pbXBvcnQge21hcH0gZnJvbSAnbGl0L2RpcmVjdGl2ZXMvbWFwLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3Nsb3RzLWl0ZXJhdG9yJylcbmV4cG9ydCBjbGFzcyBTbG90c0l0ZXJhdG9yIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgICAgPHA-T25seSB0aGUgZmlyc3QgaXRlcmF0aW9uIGl0cyBzbG90IGdldHMgcHJvcGVybHkgcmVuZGVyZWQgOig8L3A-XG4gICAgICAgICR7bWFwKHJhbmdlKDUpLCAoKSA9PiBodG1sYFxuICAgICAgICAgIDxzbG90PlxuICAgICAgICAgICAgPHA-Tm8gc2xvdCBjb250ZW50IHJlY2VpdmVkIDooPC9wPlxuICAgICAgICAgIDwvc2xvdD5cbiAgICAgICAgIGApfVxuICAgIGA7XG4gIH1cbn1cblxuQGN1c3RvbUVsZW1lbnQoJ3Nsb3RzLWRlbW8nKVxuZXhwb3J0IGNsYXNzIFNsb3RzRGVtbyBleHRlbmRzIExpdEVsZW1lbnQge1xuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgXG4gICAgICAgIDxzbG90cy1pdGVyYXRvcj5cbiAgICAgICAgICA8cD5IZWxsbyB0aGVyZSBzbG90IGNvbnRlbnQ8L3A-XG4gICAgICAgIDwvc2xvdHMtaXRlcmF0b3I-XG4gICAgYDtcbiAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL3Nsb3RzLWRlbW8uanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2xvdHMtZGVtbz48L3Nsb3RzLWRlbW8-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)
[Vue Playground - expected behavior](https://play.vuejs.org/#eNp9UstOwzAQ/JWVLwWpTQ7AJYRKgCpRDgXRHn2Jkm3rNrEt2wmpqv47a4e+KOotnpmdjD27Zc9aR02NLGGpzY3QDiy6Wg+5FJVWxsG0VM6OHZrMKQNzoyroRbH16ED8wt6h98hlGnceNE0Hh5UuM4d0AkjPfAJEoB6+YVkqcEs0CN4UciUdSpfGPgNJ4r+DaXxizPrMWRqZi0W0skrSPbZ+jLNcVVqUaD60E0pazhIIjOcy+uf3e8CcqbG/x/Ml5ut/8JVtPcbZp0GLpkHODpzLzAJdR4+mE2zp+0BWqqhLUl8hv9CqsvYZO9lLLQuKfaILacehDSEXMztq6YHs/lI+qFfugp4zquL1ytWPce+i+zDH5Y5e8bLQi5W41q4ezpbCQqHQgjZKoyk3YFAWaIDyh2otJLeHWkPXzWCuzBNnomhBSHjgDJI1bjqEs+OWTNTZcpBzjqLBApKb46J4xcV+7H4AmaD5jg==)

### Workaround

I have not found a workaround

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.1.2

### Browser/OS/Node environment

Google Chrome: 123.0.6312.106 (Official Build) (64-bit) (cohort: Stable)
Node: v20.11.1

> I believe this issue affects all browsers *(not tested)*

**Comment by justinfagnani** [comment]
This is how slots work. You're making a bunch of slots with the same name (no name in this case). When content is projected into the slots, it choose the first slot with the matching name.

If you want to project content into multiple slots, the slots need unique names and you need different content to put into each slot, by name. The content is not cloned into a slot, but just rendered ("projected") there, so content cannot be projected into multiple slots at once.

Here's your demo changed with content projected into each slot: https://lit.dev/playground/#gist=2f1f2ce9f3efa0462cf14f589526d899

**Comment by Arthurdw** [comment]
First of all, thanks for the quick reply; I really appreciate it.

> If you want to project content into multiple slots, the slots need unique names and you need different content to put into each slot, by name. The content is not cloned into a slot, but just rendered ("projected") there, so content cannot be projected into multiple slots at once.

This then makes the functionality that eg for a grid where a "grid" component does the header layout processing and then iterates over all records allowing the "caller" to dynamically define the layout for each record without having to create a record for each one?

**Comment by augustjk** [comment]
To achieve a single content filling in multiple "slots", you can do something like a render prop.

Here's a roughly modified version of the example https://lit.dev/playground/#gist=ab808bca7f6563d76ffeff7f841f492e

Though I would not really call it `renderSlot` and give it a better name since that is not the behavior of platform `<slot>` elements.

Caveat is this is assuming all components are using Lit and you have to be careful with styling because the template will be rendered in the shadowroot of the component that it got passed to, not where it was passed from.

**Comment by Arthurdw** [comment]
> To achieve a single content filling in multiple "slots", you can do ...

Thanks, this is indeed the behavior I was looking for.
