### ISSUE TITLE
CSS Variables defined in by `:root` selector in styles of a lit component are not available to other rules

### ISSUE THREAD

**Issue by Mehuge** [lit/lit#4649]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

CSS Variables defined in by `:root` selector in styles of a lit component are not available to other rules

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

### Reproduction

Hello World example 

https://lit.dev/playground/#gist=db5c5d93afd354654b45d844570e572a

```javascript
import {html, css, LitElement} from 'lit';
export class HelloWorld extends LitElement {
  static get styles() {
    return css`
      :root { --blue: blue; }                                               /* change to :host and will work */
      p { background-color: var(--blue) }
    `;
  }
  render() {
    return html`
      <p>This text should have a blue background</p>
    `;
  }
}
customElements.define('hello-world', HelloWorld);
```

### Workaround

Change `:root` to `:host` or `*` and the variables work.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.3.3

### Browser/OS/Node environment

Chrome Version 124.0.6367.203 (Official Build) (64-bit)
Windows 11

**Comment by justinfagnani** [comment]
`:root` only matches the `<html>` element that's at the root of a document. It doesn't match anything in a shadow root. You want `:host`. See https://developer.mozilla.org/en-US/docs/Web/CSS/:root

**Comment by Mehuge** [comment]
Thanks, makes sense now.
Closing
