### ISSUE TITLE
Import loop in @lit/localize

### ISSUE THREAD

**Issue by codingjoe** [lit/lit#4655]
### Which package(s) are affected?

Localize (@lit/localize)

### Description

Hi there 👋,

Thanks for all the wonderful work! I noticed a little something:

`lit-localize.js` and `init/*.js` have an import loop.

There is already a comment to drop the lines:
https://github.com/lit/lit/blob/abf30b3e895ea5d833f6d9559612e2b1ba47580d/packages/localize/src/lit-localize.ts#L15C1-L22C37

However, the comment is only regarding the bundle size, not the import loop.

### Reproduction

I noticed this while using a post-processors, that traverses imports. It's much too complicated to set up, but you can simply check the imports manual and verify the issue:
https://github.com/search?q=repo%3Alit%2Flit+import+%7B_installMsgImplementation%7D+from+%27..%2Flit-localize.js%27%3B&type=code

### Workaround

I used esbuild to bundled it. Most bundlers will ignore the loop.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

latest

### Browser/OS/Node environment

OS independent issue.

### Potential solutions

1. Remove the code, that's marked for deprecation (clean, but risky).
2. Move the `_installMsgImplementation` into a separate file (safe).

**Comment by justinfagnani** [comment]
What's the problem being cause by the import cycle?

**Comment by codingjoe** [comment]
> What's the problem being cause by the import cycle?

Django can't process the package. It has built in static file collection, including caching. This requires resolving dependencies and assign filenames to them hash-based version postfixes (cache busters). Django ships with cycle detection, it's impossible to resolve the problem.

That behavior is very much required, especially with in browser ESM loading. We actually serve Lit as ESM in the browser. It's been wonderful, except for translations.

**Comment by augustjk** [comment]
Solution 2 seems like a quick and easy fix – it's an internal function anyway – and we can punt the removal of re-exports to a later breaking change.

**Comment by augustjk** [comment]
Thank you that would be amazing!

**Comment by codingjoe** [comment]
Sure, I think, I did everything I was supposed to according to the contributing guide, don't hesitate to amend my patch.
