### ISSUE TITLE
[LitElement]: Autofocus does not work as expected with LitElement

### ISSUE THREAD

**Issue by KonnorRogers** [lit/lit#4662]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When I use the `autofocus` attribute on a Lit custom element, it does not autofocus the element.

The autofocus attribute does work however when used with a "vanilla" web component.

### Reproduction

Unfortunately, because most online playgrounds use `<iframe>` you can't really recreate it there. But if you make a `index.html` locally, add the following HTML, then you can reproduce:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
  </head>
  <body>
    <input>
    <my-input autofocus></my-input>

    <script type="module">
      import {LitElement, html} from 'https://cdn.jsdelivr.net/gh/lit/dist@3/core/lit-core.min.js';
      customElements.define("my-input", class extends LitElement {
        static formAssociated = true
        static shadowRootOptions = {...LitElement.shadowRootOptions, delegatesFocus: true }

        constructor () {
          super()
          this.internals = this.attachInternals()
        }

        render () {
          return html`<input>`
        }
      })

      // This works.
      // customElements.define("my-input", class extends HTMLElement {
      //   static formAssociated = true
      //   constructor () {
      //     super()
      //     this.internals = this.attachInternals()
      //     this.attachShadow({ mode: "open", delegatesFocus: true })
      //   }

      //   connectedCallback () {
      //     this.shadowRoot.innerHTML = `<input>`
      //   }
      // })
    </script>
  </body>
</html>

```

### Workaround

I guess you could do `.focus()` if the element is visible, and not contained in a `popover` or `dialog`, and the element is not currently focused in the `firstUpdated` callback

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.x

### Browser/OS/Node environment

Browsers tested:

Chrome 125 ✅
Firefox 126.0.1 ❌
Safari 17.4.1  ❌

**Comment by sorvell** [comment]
The input will be rendered asynchronously, and this may be a problem. To debug, try:

```ts
conectedCallback() {
  super.connectedCallback();
  this.performUpdate();
}
```

**Comment by justinfagnani** [comment]
Oh... I misread the example. It doesn't create the shadow root in connected, it renders. Yeah, that could be it.

**Comment by KonnorRogers** [comment]
On second look...it seems I can get this to reliably fail just by adding an import into the `<script type="module">`...I think this may be worth filing as a browser bug.

**Comment by sorvell** [comment]
[This example](https://lit.dev/playground/#gist=24a2cede667679dfaa42d0f0e6c97c06) seems to work for me consistently. It uses the `blocking="render"` attribute on the script tag to avoid timing issues.

Here is the [spec for autofocus](https://html.spec.whatwg.org/multipage/interaction.html#the-autofocus-attribute). It just says "as soon as the page is loaded" and while that's not explained, it may refer to the readyState transitioning from `loading` to `interactive`.

**Comment by KonnorRogers** [comment]
Thanks all for the help! Closing as this is not a Lit issue!
