### ISSUE TITLE
Legacy decorators result in field shadowing error despite "useDefineForClassFields: false"

### ISSUE THREAD

**Issue by tpluscode** [lit/lit#4678]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I followed the [Avoiding issues with class fields when declaring properties](https://lit.dev/docs/components/properties/#avoiding-issues-with-class-fields) section to address the errors from lit I started getting recently

### Reproduction

Check out `no-accessor` branch of https://github.com/tminuscode/wtr-decorators/

```
npm i
npm test
```

### Workaround

Adding `accessor` keywords work but bug https://github.com/modernweb-dev/web/issues/2757 prevents me from going there and I do not want to compile first to run tests

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

3.1.4

### Browser/OS/Node environment

macOS 14
node 18.19.0 and 20.11.1
npm 10.2.3
Browser irrelevant?

**Comment by justinfagnani** [comment]
The repo appears to be using standard decorators, not experimental decorators.

If experimental decorators don't work, it's some sort of configuration or tooling problem. Can you run a regular class with a plain field through this setup and see if the class field is using assignment or `defineProperty()`?

**Comment by tpluscode** [comment]
> The repo appears to be using standard decorators, not experimental decorators.

Experimental decorators are set up on the [`no-accessor` branch](https://github.com/tminuscode/wtr-decorators/tree/no-accessor)

> If experimental decorators don't work, it's some sort of configuration or tooling problem.

`wtr` build with `esbuild` on the fly and I do expect an issue there somewhere. Here's the output of `tsc`

```js
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
import { html, css, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';
let SimpleGreeting = class SimpleGreeting extends LitElement {
    constructor() {
        super(...arguments);
        this.name = "Sombeody";
    }
    static { this.styles = css `p { color: blue }`; }
    render() {
        return html `<p>Hello, ${this.name}!</p>`;
    }
};
__decorate([
    property({ type: String })
], SimpleGreeting.prototype, "name", void 0);
SimpleGreeting = __decorate([
    customElement('simple-greeting')
], SimpleGreeting);
export { SimpleGreeting };
let ElaborateGreeting = class ElaborateGreeting extends SimpleGreeting {
    constructor() {
        super(...arguments);
        this.salutation = "Mr.";
    }
    render() {
        return html `<p>Hello, ${this.salutation} ${this.name}!</p>`;
    }
};
__decorate([
    property({ type: String })
], ElaborateGreeting.prototype, "salutation", void 0);
ElaborateGreeting = __decorate([
    customElement('elaborate-greeting')
], ElaborateGreeting);
export { ElaborateGreeting };
```

And here's what `wtr` serves

```js
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __decorateClass = (decorators, target, key, kind) => {
  var result = kind > 1 ? void 0 : kind ? __getOwnPropDesc(target, key) : target;
  for (var i = decorators.length - 1, decorator; i >= 0; i--)
    if (decorator = decorators[i])
      result = (kind ? decorator(target, key, result) : decorator(result)) || result;
  if (kind && result)
    __defProp(target, key, result);
  return result;
};
import { html, css, LitElement } from "./node_modules/lit/index.js";
import { customElement, property } from "./node_modules/lit/decorators.js";
export let SimpleGreeting = class extends LitElement {
  static styles = css`p { color: blue }`;
  name = "Sombeody";
  render() {
    return html`<p>Hello, ${this.name}!</p>`;
  }
};
__decorateClass([
  property({ type: String })
], SimpleGreeting.prototype, "name", 2);
SimpleGreeting = __decorateClass([
  customElement("simple-greeting")
], SimpleGreeting);
export let ElaborateGreeting = class extends SimpleGreeting {
  salutation = "Mr.";
  render() {
    return html`<p>Hello, ${this.salutation} ${this.name}!</p>`;
  }
};
__decorateClass([
  property({ type: String })
], ElaborateGreeting.prototype, "salutation", 2);
ElaborateGreeting = __decorateClass([
  customElement("elaborate-greeting")
], ElaborateGreeting);
```

> Can you run a regular class with a plain field through this setup and see if the class field is using assignment or `defineProperty()`?

I'm sorry, I don't understand. So avoid using the decorator altogether?

**Comment by augustjk** [comment]
`esbuild` doesn't automatically pickup your `tsconfig.json` file.
In your WTR config file do
```
  plugins: [
    esbuildPlugin({ ts: true, tsconfig: 'tsconfig.json' })
  ],
```
to specify the `tsconfig.json` file and it should apply the correct compiler options for using experimental decorators.

**Comment by tpluscode** [comment]
Riight, thank you @augustjk. That fixes experimental decorators!
