### ISSUE TITLE
Add a decorator that checks if the element was already registered before defining it

### ISSUE THREAD

**Issue by aryelu** [lit/lit#4680]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

Hello, I've used the lit component library and stumbled on an issue where my module has run multiple times. This results in the following error:
```
'CustomElementRegistry': the name "button1" has already been used with this registry.
```

I've resolved it by checking `customElements` first and removing the decorator. I would like to propose a decorator which is doing the same. I would love to make the PR if you think it is OK from your side

### Alternatives and Workarounds
```
if (!customElements.get('button1')) {
  customElements.define('button1', Button1);
}
```

**Comment by augustjk** [comment]
https://github.com/lit/lit/pull/4461 would address this.

Related issue: https://github.com/lit/lit/issues/4455

**Comment by justinfagnani** [comment]
@kadoshms yeah, manual registration, or making your own decorator is recommended for now. The `@customElement` decorator is quite simple - it just calls `customElements.define()`.

One of the benefits of registering yourself is that you can define the behavior you want when there is conflict. For instance, you may have a scheme to check for compatibility and not raise an error.

**Comment by justinfagnani** [comment]
I think we can dedupe this with https://github.com/lit/lit/issues/4455 though, so closing.
