### ISSUE TITLE
[labs/gen-vue-wrapper] Stop renaming output files

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#4686]
### Should this be an RFC?

- [X] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

We currently generate a script that renames the files output by the vue-tsc compiler to remove the `.vue` part of the extension. This doesn't appear to be idiomatic. Packages that published compiled Vue components to npm use the default output filenames.

For example, `@mcler/v-calendar`, published components like Calendar.vue.js: https://unpkg.com/browse/@mcler/v-calendar@1.0.4/dist/es/components/Calendar/

One motivation for renaming the script is that the output files changed with a Vue update, and the rename script doesn't work well enough for the tests. Removing the script simplifies things and is more resilient to future changes.

### Alternatives and Workarounds

You can remove the rename script.

**Comment by Githubant123** [comment]
hello
