### ISSUE TITLE
:user-invalid pseudoclass not recognized

### ISSUE THREAD

**Issue by Didel** [lit/lit#4748]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

When using the (relatively new) [`:user-invalid` (link to MDN)](https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid) pseudoclass in lit-CSS, it looks like this is not supported and/or properly typed. When using it inside a regular `<style>` -tag (so without using Lit) in the same editor (VSCode), it is supported and recognized properly. This is not the case when using it inside Lit CSS.

### Reproduction

Apply the following style in a lit-component that renders a `<input required />` element (note the `required` attribute) :

```
static styles = [
    css`
      input:user-invalid {
        border-color: red;
      }
    `,
];
```

The red border should **not** apply initially after rendering. Then, apply focus to the input field, without entering a value. Then, when giving focus to another element, the red border should be applied.

### Workaround

I have manually worked around this problem by using other classes.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in Lit 3.2.0

### Browser/OS/Node environment

Tested in both Edge 128 and Chrome 128.

**Comment by justinfagnani** [comment]
Lit doesn't do anything with the styles - they're attached to your component as-is. So there's nothing for us to do to support new CSS features.

I made [an example](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudH0gZnJvbSAnbGl0JztcbmltcG9ydCB7Y3VzdG9tRWxlbWVudCwgcHJvcGVydHl9IGZyb20gJ2xpdC9kZWNvcmF0b3JzLmpzJztcblxuQGN1c3RvbUVsZW1lbnQoJ3NpbXBsZS1ncmVldGluZycpXG5leHBvcnQgY2xhc3MgU2ltcGxlR3JlZXRpbmcgZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgc3RhdGljIHN0eWxlcyA9IGNzc2BcbiAgICBpbnB1dDp1c2VyLWludmFsaWQge1xuICAgICAgYm9yZGVyLWNvbG9yOiByZWQ7XG4gICAgfVxuICBgO1xuXG4gIEBwcm9wZXJ0eSgpXG4gIG5hbWUgPSAnU29tZWJvZHknO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBJbiBMaXQ6IDxpbnB1dCB0eXBlPVwiZW1haWxcIiByZXF1aXJlZD5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG4gIDxzdHlsZT5cbiAgICBpbnB1dDp1c2VyLWludmFsaWQge1xuICAgICAgYm9yZGVyLWNvbG9yOiByZWQ7XG4gICAgfVxuICA8L3N0eWxlPlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxkaXY-XG4gICAgPGZvcm0-XG4gICAgSW4gSFRNTDogPGlucHV0IHR5cGU9XCJlbWFpbFwiIHJlcXVpcmVkPlxuICAgIDwvZm9ybT5cbiAgPC9kaXY-XG4gIDxzaW1wbGUtZ3JlZXRpbmcgbmFtZT1cIldvcmxkXCI-PC9zaW1wbGUtZ3JlZXRpbmc-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d) in the lit.dev playground that shows it working for me.

**Comment by justinfagnani** [comment]
Closing this one, since Lit doesn't modify styles. It's likely a browser support issue.
