### ISSUE TITLE
[lit-html] optional expression not working after lit@3 update

### ISSUE THREAD

**Issue by chrisatipoque** [lit/lit#4750]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

After the update from lit@2.8 to lit@3.2 we got some errors in our e2e tests. We discovered that the optional expression in lit-html had some issues. So following lit code

```html
<button ?data-foo=${false}>my button</button>
```
creates following DOM node

```html
<button data-foo>my button</button>
```

After a deep dive in lit-html we discovered a change from `setAttribute`/`removeAttribute` to `toggleAttribute`.  And the return value was not a boolean instead it of undefined. We are using the [soped-custom-element-registry@0.0.6](https://github.com/webcomponents/polyfills/tree/master/packages/scoped-custom-element-registry) package which patches the `toggleAttribute`. This was the reason for the clinch. After updating to the newest verion (0.0.9) of this package all works fine. The patch for `toggleAttribute` was released in 0.0.8.

This ticket can be closed but we want to inform all users which may have the same issues because it was a very long evaluation process.

### Reproduction

could not reproduce it on stackblitz, but the description includes the possible solution.

### Workaround

install @webcomponents/soped-custom-element-registry >= 0.0.8

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failed with lit >= 3

### Browser/OS/Node environment

@webcomponents/soped-custom-element-registry < 0.0.8

**Comment by justinfagnani** [comment]
Thanks for digging into the root cause. Hopefully people find this and upgrade if they hit a similar problem.
