### ISSUE TITLE
[labs/virtualizer] Incompatible with display table-row-group

### ISSUE THREAD

**Issue by lou-lan** [lit/lit#4764]
### Which package(s) are affected?

Virtualizer (@lit-labs/virtualizer)

### Description

```
<tbody style="display: table-row-group">
    ${virtualize({ scroller: true, items: this.contacts, renderItem: (i: any) => html`
        <tr>
        ${Object.keys(i).map(key => html`<td>${i[key]}</td>`)}
        </tr>`
    })}
</tbody>
```

In the context, I want to use `labs/virtualize` to implement a table that supports virtual scrolling and column resizing.

If I specify `display: table-row-group`, virtual scrolling does not work well. If I do not specify `display: table-row-group`, the default is `display: block`, which causes the column widths to be inconsistent with the table header.

### Reproduction

* [lit dev playground](https://lit.dev/playground/#project=W3sibmFtZSI6Imxpc3QtZGVtby50cyIsImNvbnRlbnQiOiJpbXBvcnQge2NzcywgaHRtbCwgTGl0RWxlbWVudH0gZnJvbSBcImxpdFwiO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBwcm9wZXJ0eX0gZnJvbSBcImxpdC9kZWNvcmF0b3JzLmpzXCI7XG5pbXBvcnQgXCJAbGl0LWxhYnMvdmlydHVhbGl6ZXJcIjtcbmltcG9ydCB7IHZpcnR1YWxpemUgfSBmcm9tICdAbGl0LWxhYnMvdmlydHVhbGl6ZXIvdmlydHVhbGl6ZS5qcyc7XG5cbkBjdXN0b21FbGVtZW50KFwibGlzdC1kZW1vXCIpXG5leHBvcnQgY2xhc3MgTGlzdERlbW8gZXh0ZW5kcyBMaXRFbGVtZW50IHtcbiAgICBzdGF0aWMgc3R5bGVzID0gY3NzYFxuICAgICAgICA6aG9zdCB7XG4gICAgICAgICAgICBkaXNwbGF5OiBibG9jaztcbiAgICAgICAgICAgIHdpZHRoOiAxMDAlO1xuICAgICAgICB9XG4gICAgICAgIC5saXN0IHtcbiAgICAgICAgICAgIGhlaWdodDogNDAwcHg7XG4gICAgICAgICAgICB3aWR0aDogMTAwJTtcbiAgICAgICAgICAgIGRpc3BsYXk6IHRhYmxlO1xuICAgICAgICB9XG4gICAgICAgIC5saXN0IHRyIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IHRhYmxlLXJvdztcbiAgICAgICAgICAgIHdpZHRoOiAxMDAlO1xuICAgICAgICB9XG4gICAgICAgIHRhYmxlIHtcbiAgICAgICAgICAgIGRpc3BsYXk6IHRhYmxlO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgIH1cbiAgICAgICAgdGJvZHkge1xuICAgICAgICAgICAgZGlzcGxheTogdGFibGUtcm93LWdyb3VwO1xuICAgICAgICAgICAgd2lkdGg6IDEwMCU7XG4gICAgICAgIH1cbiAgICAgICAgXG4gICAgICAgIGxpdC12aXJ0dWFsaXplciB7XG4gICAgICAgICAgICB3aWR0aDogMTAwJSAhaW1wb3J0YW50O1xuICAgICAgICB9XG4gICAgYFxuXG4gICAgQHByb3BlcnR5KHsgdHlwZTogQXJyYXkgfSkgY29sdW1ucyA9IFtcbiAgICAgICAgeyBpZDogJ2NpdHknLCB0aXRsZTogJ0NpdHknLCB3aWR0aFdlaWdodGluZzogNTB9LFxuICAgICAgICB7IGlkOiAnY291bnRyeScsIHRpdGxlOiAnQ291bnRyeScsIHdpZHRoV2VpZ2h0aW5nOiA1MH0sXG4gICAgXTtcblxuICAgIEBwcm9wZXJ0eSh7IHR5cGU6IEFycmF5IH0pIGNvbnRhY3RzID0gQXJyYXkuZnJvbSh7IGxlbmd0aDogMTAwMCB9LCAoXywgaSkgPT4gKHtcbiAgICAgICAgbmFtZTogYENvbnRhY3QgJHtpICsgMX1gLFxuICAgICAgICBwaG9uZTogYDEyMy00NTYtNzgke1N0cmluZyhpKS5wYWRTdGFydCgyLCAnMCcpfWBcbiAgICB9KSk7XG5cblxuICAgIGNvbm5lY3RlZENhbGxiYWNrKCkge1xuICAgICAgICBzdXBlci5jb25uZWN0ZWRDYWxsYmFjaygpO1xuICAgIH1cblxuICAgIGRpc2Nvbm5lY3RlZENhbGxiYWNrKCkge1xuICAgICAgICBzdXBlci5kaXNjb25uZWN0ZWRDYWxsYmFjaygpO1xuICAgIH1cblxuICAgIHJlbmRlcigpIHtcbiAgICAgICAgcmV0dXJuIGh0bWxgXG4gICAgICAgICAgICA8dGFibGU-XG4gICAgICAgICAgICAgICAgPGNvbGdyb3VwPlxuICAgICAgICAgICAgICAgICAgICA8Y29sIHN0eWxlPVwid2lkdGg6IDMwMHB4XCI-XG4gICAgICAgICAgICAgICAgICAgIDxjb2wgc3R5bGU9XCJ3aWR0aDogMzAwcHhcIj5cbiAgICAgICAgICAgICAgICA8L2NvbGdyb3VwPlxuICAgICAgICAgICAgICAgIDx0aGVhZD5cbiAgICAgICAgICAgICAgICAgICAgPHRyPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRoPk5hbWU8L3RoPlxuICAgICAgICAgICAgICAgICAgICAgICAgPHRoPlBob25lPC90aD5cbiAgICAgICAgICAgICAgICAgICAgPC90cj5cbiAgICAgICAgICAgICAgICA8L3RoZWFkPlxuICAgICAgICAgICAgICAgIDx0Ym9keSBzdHlsZT1cImRpc3BsYXk6IHRhYmxlLXJvdy1ncm91cFwiPlxuICAgICAgICAgICAgICAgICAgICAke3ZpcnR1YWxpemUoeyBzY3JvbGxlcjogdHJ1ZSwgaXRlbXM6IHRoaXMuY29udGFjdHMsIHJlbmRlckl0ZW06IChpOiBhbnkpID0-IGh0bWxgXG4gICAgICAgICAgICAgICAgICAgICAgICA8dHI-XG4gICAgICAgICAgICAgICAgICAgICAgICAke09iamVjdC5rZXlzKGkpLm1hcChrZXkgPT4gaHRtbGA8dGQ-JHtpW2tleV19PC90ZD5gKX1cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvdHI-YFxuICAgICAgICAgICAgICAgICAgICB9KX1cbiAgICAgICAgICAgICAgICA8L3Rib2R5PlxuICAgICAgICAgICAgPC90YWJsZT5cbiAgICAgICAgYDtcbiAgICB9XG59XG5cblxuZGVjbGFyZSBnbG9iYWwge1xuICAgIGludGVyZmFjZSBIVE1MRWxlbWVudFRhZ05hbWVNYXAge1xuICAgICAgICAnbGlzdC1kZW1vJzogTGlzdERlbW87XG4gICAgfVxufVxuIn0seyJuYW1lIjoiaW5kZXguaHRtbCIsImNvbnRlbnQiOiI8IURPQ1RZUEUgaHRtbD5cbjxoZWFkPlxuICA8c2NyaXB0IHR5cGU9XCJtb2R1bGVcIiBzcmM9XCIuL2xpc3QtZGVtby5qc1wiPjwvc2NyaXB0PlxuPC9oZWFkPlxuPGJvZHk-XG4gIDxsaXN0LWRlbW8-PC9saXN0LWRlbW8-XG48L2JvZHk-XG4ifSx7Im5hbWUiOiJwYWNrYWdlLmpzb24iLCJjb250ZW50Ijoie1xuICBcImRlcGVuZGVuY2llc1wiOiB7XG4gICAgXCJsaXRcIjogXCJeMy4wLjBcIixcbiAgICBcIkBsaXQvcmVhY3RpdmUtZWxlbWVudFwiOiBcIl4yLjAuMFwiLFxuICAgIFwibGl0LWVsZW1lbnRcIjogXCJeNC4wLjBcIixcbiAgICBcImxpdC1odG1sXCI6IFwiXjMuMC4wXCJcbiAgfVxufSIsImhpZGRlbiI6dHJ1ZX1d)

### Workaround

I don't know how to work this.

### Is this a regression?

No.

### Affected versions

* lit 3.1.4
* lit-labs/virtualizer ^2.0.14

### Browser/OS/Node environment

OS: macOS 14.5 
Chrome: 128.0.6613.138

**Comment by graynorton** [comment]
This is a known limitation: virtualizer uses absolute positioning to lay out its children and manually sets the size of its container element, but the browser's native table-layout styles don't play nicely with this approach.

It's possible to work around this by overriding the `display` property on the various table elements and relying on some means other than `<colgroup>` to size your columns.

Here is a modified version of your playground example that shows one possible approach (in this case, using the `:nth-of-type()` pseudo-class to control column sizing:

https://lit.dev/playground/#gist=ea97053f65a8ec8a593ae33e04abdd6e

You may need to experiment and adapt to suit your specific needs.
