### ISSUE TITLE
PropertyValues type error with lifecycle method and property declared with @state()

### ISSUE THREAD

**Issue by jrunning** [lit/lit#4766]
### Which package(s) are affected?

Lit Core (lit / lit-html / lit-element / reactive-element)

### Description

I'm using `willUpdate` to watch for changes on a property I've declared with the `@state()` decorator. This works great. However, I'd also like `willUpdate`'s `changedProps` parameter to be strongly typed, so I've used the `PropertyValues<this>` type:

```js
@state()
private secret: string = 'xyzzy';
  
willUpdate(changedProps: PropertyValues<this>) {
  if (changedProps.has('secret')) {
    console.log('secret changed');
  }
}
```

This leads to a type error on the string `'secret'`:

> Argument of type `"secret"` is not assignable to parameter of type `keyof SimpleGreeting`.

This seems incorrect, since `'secret'` is an expected key of `changedProps`.

If this is the intended behavior, is there another way I can get the correct type information here?

### Reproduction

[lit.dev Playground reproduction](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIExpdEVsZW1lbnQsIFByb3BlcnR5VmFsdWVzfSBmcm9tICdsaXQnO1xuaW1wb3J0IHtjdXN0b21FbGVtZW50LCBzdGF0ZX0gZnJvbSAnbGl0L2RlY29yYXRvcnMuanMnO1xuXG5AY3VzdG9tRWxlbWVudCgnc2ltcGxlLWdyZWV0aW5nJylcbmV4cG9ydCBjbGFzcyBTaW1wbGVHcmVldGluZyBleHRlbmRzIExpdEVsZW1lbnQge1xuICBAc3RhdGUoKVxuICBwcml2YXRlIHNlY3JldDogc3RyaW5nID0gJ3h5enp5JztcbiAgXG4gIHdpbGxVcGRhdGUoY2hhbmdlZFByb3BzOiBQcm9wZXJ0eVZhbHVlczx0aGlzPikge1xuICAgIGlmIChjaGFuZ2VkUHJvcHMuaGFzKCdzZWNyZXQnKSkge1xuICAgICAgY29uc29sZS5sb2coJ3NlY3JldCBjaGFuZ2VkJyk7XG4gICAgfVxuICB9XG4gIFxuICByZW5kZXIoKSB7XG4gICAgcmV0dXJuIGh0bWxgPHA-SGVsbG8sICR7dGhpcy5zZWNyZXR9ITwvcD5gO1xuICB9XG59XG4ifSx7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhRE9DVFlQRSBodG1sPlxuPGhlYWQ-XG4gIDxzY3JpcHQgdHlwZT1cIm1vZHVsZVwiIHNyYz1cIi4vc2ltcGxlLWdyZWV0aW5nLmpzXCI-PC9zY3JpcHQ-XG48L2hlYWQ-XG48Ym9keT5cbiAgPHNpbXBsZS1ncmVldGluZyBuYW1lPVwiV29ybGRcIj48L3NpbXBsZS1ncmVldGluZz5cbjwvYm9keT5cbiJ9LHsibmFtZSI6InBhY2thZ2UuanNvbiIsImNvbnRlbnQiOiJ7XG4gIFwiZGVwZW5kZW5jaWVzXCI6IHtcbiAgICBcImxpdFwiOiBcIl4zLjAuMFwiLFxuICAgIFwiQGxpdC9yZWFjdGl2ZS1lbGVtZW50XCI6IFwiXjIuMC4wXCIsXG4gICAgXCJsaXQtZWxlbWVudFwiOiBcIl40LjAuMFwiLFxuICAgIFwibGl0LWh0bWxcIjogXCJeMy4wLjBcIlxuICB9XG59IiwiaGlkZGVuIjp0cnVlfV0)

### Workaround

Using `PropertyValues` instead of `PropertyValues<this>` removes the error but also removes much of its utility.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

Failing in 3.2.0

### Browser/OS/Node environment

Browser: Chrome 127
OS: macOS Sonoma 14.6.1
Node: 22.8.0
npm: 10.8.2
TypeScript version: 5.5.4

**Comment by justinfagnani** [comment]
TypeScript doesn't include protected or private fields in the `this` type. The only way to get them would be to define a new type with the private fields added in:

```ts
interface MyElementInternal extends MyElement {
  secret: string;
}

class MyElement extends LitElement {
  willUpdate(changeProperties: PropertyValues<MyElementInternal>) { ... }
}
```

There's nothing we can really do about this, since TypeScript doesn't include any way to extract the private interface.

**Comment by jrunning** [comment]
Oh, I see. I thought the problem was with using `@state()` instead of `@property()`, but instead it's the use of `private`. Thanks for the clarification.
