### ISSUE TITLE
[react] Broken SSR compat without global HTMLElement shim

### ISSUE THREAD

**Issue by augustjk** [lit/lit#4771]
### Which package(s) are affected?

React (@lit/react)

### Description

The package includes a reference to a global `HTMLElement` here: https://github.com/lit/lit/blob/42260c2d3bb179756e109616338936de2a589801/packages/react/src/create-component.ts#L187

We already have a node build for `@lit/react` so we should make the node build not break by either removing the reference or bringing in a shim like we do for `@lit/reactive-element`.

Thanks to @hrmcdonald for finding the root cause.

### Reproduction

.

### Workaround

Include snippet below to entrypoint before any component is loaded.
```js
import {HTMLElement} from '@lit-labs/ssr-dom-shim';
globalThis.HTMLElement ??= HTMLElement;
```

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

.

### Browser/OS/Node environment

.

**Comment by hrmcdonald** [comment]
I'd bet this is the same issue: https://github.com/lit/lit/issues/3407
