### ISSUE TITLE
IntersectionController not initialized in node environments

### ISSUE THREAD

**Issue by lennartbuit** [lit/lit#4804]
### Which package(s) are affected?

Observers (@lit-labs/observers)

### Description

In upgrading @lit-labs/observers, we had a test failing that has an intersection controller. The code we were testing looks a bit like this:

```ts
@customElement("my-element")
export class MyElement extends LitElement {
  #myController = new IntersectionController(...);

  firstUpdated() {
    this.#myController.observe(...);
  }
}
```

Now, we test this with JSDOM, that happens to run in a node environment. This causes `isServer` to be true, and since https://github.com/lit/lit/pull/4591 there is short circuit behaviour in the constructors of the controllers exported in the observers package. This short circuiting prevents construction of this `IntersectionController` which makes the call in `firstUpdated` fail (cannot call `observe` on `undefined`). Thats an issue in JSDOM because it does execute the components lifecycle.

I was a bit surprised, I personally expected that it would be stubbed with no-ops in node environments, which also would have gone over well in my JSDOM tests. Instead, construction is prevented, causing calls to error.

### Reproduction

I am having a hard time producing a solid reproduction for this. I hope my description above is sufficient but let me know :).

### Workaround

We worked around this by adding `resolve: { conditions: ["browser"] }` to our vitest config.

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in (@lit-labs/observers) 2.0.4, worked in 2.0.2

### Browser/OS/Node environment

Node: v20.18.0

**Comment by augustjk** [comment]
I think the workaround you mention is a viable solution here. Testing with JSDOM in a Node environment rather than a real browser inherently comes with their pitfalls with this being one of them.

Our solutions for SSR support in other packages including the core `lit-html` and `LitElement` have all involved using export conditions targeting the "node" environment which the `isServer` check is based on. We'll likely continue to lean on that so if you want to test as if you're in the browser, I would recommend keeping the "browser" condition for the module resolution settings.

**Comment by lennartbuit** [comment]
Thanks. One thing I wonder, the SSR codepath prevents construction of these controllers. So calling any method on them gets you an error. I guess that surprised me at first, although there is also something to say for erroring, as these methods are not going to do something in SSR environments. What do you think?

**Comment by lennartbuit** [comment]
I was talking about SSR environments. Your explanation makes sense to me, I was just wondering if we could do more for users who accidentally use one of these controllers in an SSR environment and get strange "cannot read property `observe` of `undefined`" type errors (because the `IntersectionController` was not constructed). But yeah, you are right, thats never going to be complete anyway.

Thanks, I guess we can close this :).
