### ISSUE TITLE
[labs/nextjs] Add support for Next.js 15

### ISSUE THREAD

**Issue by Shellishack** [lit/lit#4812]
### Should this be an RFC?

- [x] This is not a substantial change

### Which package is this a feature request for?

Other/unknown (please mention in description)

### Description

Next.js 15 was just released (https://nextjs.org/blog/next-15). I was curious enough to try lit on Next.js 15, but it gave me dependency resolution error on @lit-labs/nextjs. 
```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: test@0.1.0
npm error Found: next@15.0.1
npm error node_modules/next
npm error   next@"15.0.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer next@"13 || 14" from @lit-labs/nextjs@0.2.0
npm error node_modules/@lit-labs/nextjs
npm error   @lit-labs/nextjs@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```
I was able to get it running for a very basic use case via bypassing dependency checking. Are there anything released from Next.js 15 could potentially break the @lit-labs/nextjs packages? 

Below is how I used the @lit-labs/nextjs package in a Next.js 15 app (app router).
**Steps:**
1. Install app router Nextjs like normal. Add `--legacy-peer-deps` to bypass warnings when installing @lit-labs/nextjs.
```
npx create-next-app@latest test
cd test
npm i lit @lit/react
npm i @lit-labs/nextjs --legacy-peer-deps
```

2. Configure next.config.ts
```
import type { NextConfig } from "next";
import withLitSSR from "@lit-labs/nextjs";

const nextConfig: NextConfig = {
  /* config options here */
  reactStrictMode: true,
};

export default withLitSSR({
  addDeclarativeShadowDomPolyfill: true,
})(nextConfig);
```

3. Add web component in page.tsx
```
"use client";

import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import { createComponent } from "@lit/react";
import React from "react";

@customElement("my-element")
export class MyElement extends LitElement {
  render() {
    return html` <div>Hello from my Lit Element!</div> `;
  }
}

const HelloComponent = createComponent({
  tagName: "my-element",
  elementClass: MyElement,
  react: React,
});

export default function Home() {
  return (
    <HelloComponent/>
  );
}
```

4. Run `npm run dev` and web component is displayed.

**Potential issues:**
- Turbopack seems not working after configuring lit SSR in step 2.
- No other notable issues found for now

### Alternatives and Workarounds

Use `--legacy-peer-deps` to bypass warning during installation.

**Comment by augustjk** [comment]
Nothing in the release blog stands out as something that would break the plugin. It would be good to expand the peer dep range and also add v15 to https://github.com/lit/lit/tree/main/examples so we it gets tested too. Unsure if we need to do both page router and app router at this point though.

**Comment by JamesIves** [comment]
[I've put together a pull request](https://github.com/lit/lit/pull/4815) for this here as this was blocking my teams upgrade path. Would appreciate some eyes!

**Comment by AlexanderShabalinMaersk** [comment]
any news in here? Can that PR be merged?

**Comment by JamesIves** [comment]
@augustjk Is there a schedule for the next labs release where this will be included?
