### ISSUE TITLE
[Lit/Task]: Improve type-checking by using `const`

### ISSUE THREAD

**Issue by maxpatiiuk** [lit/lit#4829]
### Should this be an RFC?

- [x] This is not a substantial change

### Which package is this a feature request for?

Task (@lit/task)

### Description

TypeScript 5.0 [added the `const` modifier for type variables](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters).

It can be adapted in`@lit/task` like so:

```diff
export class Task<
-  T extends ReadonlyArray<unknown> = ReadonlyArray<unknown>,
+  const T extends ReadonlyArray<unknown> = ReadonlyArray<unknown>,
-  R = unknown,
+  const R = unknown,
 > {
```

The advantage of this is that argument types and return types would be inferred better by TypeScript. Example:

```tsx
// Before this was inferred as Task<(string | undefined)[], string[]>
// With addition of "const" it would be Task<readonly [string | undefined], readonly [string]> - a much more accurate type
  _dataTask = new Task(
    this,
    async ([name]) => {
      if (name === undefined) {
        return "";
      }

      const response = await fetch(`example.com/${name}`);
      return [await response.text()];
    },
    () => [this.name],
  );
```

### Alternatives and Workarounds

If `const` is not included in the `@lit/tasks` typings, it can be manually included in the component source code:

```diff
-    () => [this.name],
+    () => [this.name] as const,
```

however, not every TypeScript user would be aware of this, so some might get frustrated by bad type checking experience when using Lit Task

**Comment by maxpatiiuk** [comment]
I would be happy to open a PR for this if the team is ok with the change.

The `const` syntax was added in TypeScript 5.0 (released 1.5 years ago - March 16, 2023)

**Comment by augustjk** [comment]
Oooh very nice! I think this would be a welcome addition. We already have a dependency on TS 5.0 due to decorator types, so users need to `skipLibCheck` if on lower versions, though that technically could be fixed by vending our own types for it, whereas we can't do that for the `const` syntax. So committing to this would mean we'd be giving up on https://github.com/lit/lit/issues/4283

@justinfagnani what do you think?

**Comment by rictic** [comment]
I'm in favor. We already require 5.0, skipLibCheck is a thing, and TypeScript type issues are morally lint warnings not compiler errors.

**Comment by justinfagnani** [comment]
SGTM
