### ISSUE TITLE
Jest Test Cases Fail After Updating from lit-labs/react v1.1.1 to lit-react: Getting only the default values

### ISSUE THREAD

**Issue by arunks5** [lit/lit#4830]
### Which package(s) are affected?

React (@lit/react)

### Description

I am updating from lit-labs/react v1.1.1 to lit-react in my project. All my test cases work fine with lit-labs/react v1.1.1, but the same test cases are failing with lit-react and the latest lit-labs/react versions. In the latest lit/react, only the default values are getting reflected in firstUpdated. The values passed from app side is not getting reflected.

### Reproduction

https://github.com/arunks5/my-next-app

Issue Description:
Even though I have set name={'people'} on the Button component, it is not respecting that value when using lit/react. However, the same test case works fine with lit-labs/react

The test file is in path : org\apps\org\src\app\Button.test.tsx

### Workaround

I don't have any workaround

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Affected versions

Failing in lit/react, worked in lit-labs/react

### Browser/OS/Node environment

Node Version:v21.7.0

**Comment by augustjk** [comment]
The likely reason for this is that the node build of `@lit/react` is being imported where `useLayoutEffect`s are removed.
I don't know if jest provides a way to configure this but you want to target either the "default" or the "browser" export of the package. https://github.com/lit/lit/blob/1eb179f69d663440fd2ebd3589b6f2808d87494f/packages/react/package.json#L22

Conditional exports are explained here: https://nodejs.org/api/packages.html#conditional-exports
If jest doesn't give you a way to configure the condition to resolve, you might be able to use the environment variable `NODE_OPTIONS=--conditions=browser` to do so.

**Comment by arunks5** [comment]
Thanks @augustjk for the suggestion. We can use [testEnvironmentOptions]https://jestjs.io/docs/configuration#testenvironmentoptions-object) config from Jest as below,
`testEnvironmentOptions: {
    NODE_OPTIONS: '--conditions=browser'
  }`

This works. 
Thanks again.

**Comment by augustjk** [comment]
Nice! From the Jest doc you linked, looks like it might also be possible to do
```js
  testEnvironmentOptions: {
    customExportConditions: ['browser'],
  },
```
maybe you meant that and just had a copy-paste error.

In any case, thanks for reporting back! Closing issue as solved. Feel free to bring up any other issues you see.
