### ISSUE TITLE
Previous value checks could use SameValue

### ISSUE THREAD

**Issue by mikesamuel** [lit/lit#787]
If `NaN` ends up as a part value, it might cause spurious re-renders when `===` is used to check the new value against the previous value since `NaN !== NaN`.

This pattern may occur several places in directive code:

https://github.com/Polymer/lit-html/blob/539a70ebd11992237236ffee3c0aafc31524ab15/src/directives/guard.ts#L63

https://github.com/Polymer/lit-html/blob/539a70ebd11992237236ffee3c0aafc31524ab15/src/directives/unsafe-html.ts#L44-L45

https://github.com/Polymer/lit-html/blob/539a70ebd11992237236ffee3c0aafc31524ab15/src/directives/repeat.ts#L362-L363

Ideally, primitive values would compare as per the [*SameValue*](https://www.ecma-international.org/ecma-262/#sec-samevalue) abstract operator.

*SameValue* treats IEEE754 -0 and +0 as distinct unlike JS where `0 === -0` which may or may not be desirable for lit-html directives.

**Comment by justinfagnani** [comment]
The concrete change would be to use `Object.is()`.

Given that `===` treats `NaN`s as different, and `Object.is()` treats `-0` and `+0` as different, I'm not sure that `Object.is()` is that much better. `Object.is()` also requires an additional polyfill on IE11.

**Comment by sorvell** [comment]
Closing since ReactiveElement's exported `notEqual` does handle NaN checking. The newer `Object.is` does as well and can be used for this also.
