### ISSUE TITLE
[lit-html] Gesture system support / declarative synthetic event generators

### ISSUE THREAD

**Issue by justinfagnani** [lit/lit#957]
We'd like it to be easier to integrate gesture systems into lit-html templates.

Many gesture libraries work on a similar overall structure, where they listen to several native events, and synthesize their own events for the gesture, once the gesture is recognized. These events aren't always DOM Events, but they're similar in spirit.

For example, Hammer.js:

```js
const el = document.querySelector('#el');
const hammer = new Hammer(el);
const onPan = (e) => {
  //
});
hammer.on('press', onPan);
```

The `onPan` function passed to `on()` receives a Hammer Event object.

We already have a nice way to listen to arbitrary DOM Events. So if Hammer worked slightly differently and instead of accepting listeners via the `on()` method, it just fired DOM Events, we could write something like this:

```js
html`<div @pan=${onPan}`></div>`
```

THis is nice, but we would still need a way to attach the gesture recognizer to the element - in Hammer, what the `new Hammer(el)` and `hammer.on('pan', ...)` calls do.

We could do this now with a directive:

```js
import {hammer} from 'hammer-lit';

// ...

html`<div @pan=${hammer(onPan)}`></div>`
```

Where the `hammer` directive gets the name of the event, constructs a `Hammer` object if necessary, and registers the Hammer listener.

This isn't so bad, and we should consider that we could just document this approach and implement a few adapter directives for gesture libraries. But ideally we'd do this without any extra ceremony at the event listener binding site. These synthetic events should have a similar DX as native events.

So another option is to use `RenderOptions` to allow gesture systems to hook event listeners across a whole render tree. A custom element base-class like LitElement could wire this together, much like it does for `eventTarget`:

```js
import {pan} from 'hammer-lit';

class MyElement extends LitElement {
  static gestures = {
    pan
  };

  render() {
    <div @pan=${this._onPan}></div>
  }

  _onPan(e) {
    // ...
  }
}
```

Here the `hammer-lit` module would adapt the APIs. The `pan` gesture hook would be called only when listeners are attached for the `pan` event, so there's no cost if the hook isn't used. The hook would do whatever setup is necessary to attach the gesture library's native event listeners, and would fire a DOM Event matching the gesture name.

This is obviously more general than just gestures, and would amount to a kind of render-root-scoped implicit directive. Is that a good thing? Render-root-scoped behavior might be tricky when composing templates from multiple sources, as the behavior of the template changes based on where it's rendered. We could also consider an approach where the hooks are registered with the template tag, and so are scoped to the template that uses them...

**Comment by justinfagnani** [comment]
cc @straversi @azakus

**Comment by ARuzek** [comment]
Thank you so much for the clear documentation above demonstrating current capabilities. I'm interested in adding gesture support to my components soon. Any updates on this proposed enhancement? Otherwise, I guess I can start implementing hammer like in the first example.

**Comment by justinfagnani** [comment]
This should be an RFC, and with element directives and reactive controllers, probably doesn't need to have built-in support in LitElement or lit-html. We could do a labs package.
